### ISSUE TITLE
[BUG] Failed to submit sell orders to bittrex

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#1025]
**Describe the bug**

User getting an error in Pure Market Making + Bittrex. There's an issue creating a sell order

**Error**
```
Traceback (most recent call last):
  File "hummingbot/market/bittrex/bittrex_market.pyx", line 890, in hummingbot.market.bittrex.bittrex_market.BittrexMarket.execute_sell
    order_result = await self.place_order(order_id,
  File "hummingbot/market/bittrex/bittrex_market.pyx", line 745, in place_order
    api_response = await self._api_request("POST", path_url=path_url, body=body)
  File "hummingbot/market/bittrex/bittrex_market.pyx", line 1039, in _api_request
    async with client.request(http_method,
  File "hummingbot/market/bittrex/bittrex_market.pyx", line 1047, in hummingbot.market.bittrex.bittrex_market.BittrexMarket._api_request
    raise IOError(f"Error fetching response from {http_method}-{url}. HTTP Status Code {response.status}: "
OSError: Error fetching response from POST-https://api.bittrex.com/v3/o	rders. HTTP Status Code 400: {'code': 'DUST_TRADE_DISALLOWED_MIN_VALUE'}
2019-11-04 08:29:52,121 - 4672 - hummingbot.market.bittrex.bittrex_market - WARNING - Failed to submit sell order to Bittrex. Check API key and network connection.
2019-11-04 08:29:53,001 - 4672 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (GBYTE-BTC) Creating limit ask orders at (Size, Price): ['0.11449512 GBYTE, 0.0025181 BTC'] [clock=2019-11-04 08:29:53+00:00]
2019-11-04 08:29:53,129 - 4672 - hummingbot.market.bittrex.bittrex_market - NETWORK - Error submitting sell LIMIT order to Bittrex for 0.11449512 GBYTE-BTC 0.00251810.
```
**Screenshots**
![bitt](https://user-images.githubusercontent.com/27669951/68113678-481e4580-ff2f-11e9-9139-98ae8845d61b.jpg)

**Release version**
``ver-0.17.1``

**Attachments**
[logs_conf_pure_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/3803496/logs_conf_pure_market_making_strategy_0.log)
[conf_pure_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/3803519/conf_pure_market_making_strategy_0.txt)

**Optional: your discord username:** vik

**Comment by CrimsonJacket** [comment]
@znerol19619 The amount you're trading is below the trading amount allowed by Bittrex as stated in their Trading Rule. 
> The trade you submitted is below the minimum allowed trade amount.  Your quantity * price must be greater than .0005 BTC.  Please increase your amount or price in order to place this order.

Increasing the `order_amount` in the strategy configs will do the trick.
