### ISSUE TITLE
[BUG] Cannot create orders for pairs with very low price in Bittrex

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1032]
**Describe the bug**

This was reported by a user trading FXC-BTC. Getting the following errors in logs.

```
2019-11-05 11:30:02,983 - 15812 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (FXC-BTC) Creating limit bid orders at (Size, Price): ['1794.70736022 FXC, 3.1E-7 BTC'] [clock=2019-11-05 03:30:03+00:00]
2019-11-05 11:30:04,080 - 15812 - hummingbot.market.bittrex.bittrex_market - NETWORK - Error submitting buy LIMIT order to Bittrex for 1794.70736022 FXC-BTC 3.1E-7.
Traceback (most recent call last):
  File "hummingbot\market\bittrex\bittrex_market.pyx", line 741, in hummingbot.market.bittrex.bittrex_market.BittrexMarket.execute_buy
  File "hummingbot\market\bittrex\bittrex_market.pyx", line 702, in place_order
  File "hummingbot\market\bittrex\bittrex_market.pyx", line 996, in _api_request
  File "hummingbot\market\bittrex\bittrex_market.pyx", line 1004, in hummingbot.market.bittrex.bittrex_market.BittrexMarket._api_request
OSError: Error fetching response from POST-https://api.bittrex.com/v3/orders. HTTP Status Code 400: {'code': 'BAD_REQUEST', 'detail': 'Refer to the data field for specific field validation failures or extra fields in the body that were rejected.', 'data': {'newOrder.limit': ['Error converting value "3.1E-7" to type \'System.Nullable`1[System.Decimal]\'. Path \'limit\', line 1, position 102.']}}
2019-11-05 11:30:04,082 - 15812 - hummingbot.market.bittrex.bittrex_market - WARNING - Failed to submit buy order to Bittrex. Check API key and network connection.
```

Used the same configs on two different pairs and it worked fine. Probably when the trading pair's price is too low it results to this error. Current price of FXC-BTC is 0.00000030

```
Error submitting buy LIMIT order to Bittrex for 1794.70736022 FXC-BTC 3.1E-7
```

```
Error converting value "3.1E-7" to type \'System.Nullable`1[System.Decimal]
```

**Screenshots**

<img width="947" alt="putty_g70dNvJi6l" src="https://user-images.githubusercontent.com/50150287/68180586-3e4c1f00-ffcf-11e9-83c5-2608c680ae1e.png">

**Release version**

Tried on two different machine setup

| Branch | Version | Installation Type | Environment |
| --- | --- | --- | --- |
| Latest | 0.18.0 | Binary | Windows |
| Latest | 0.18.0 | Docker | Linux Cloud Server |

**Attachments**

[bittrex_fxc-btc.log](https://github.com/CoinAlpha/hummingbot/files/3807353/bittrex_fxc-btc.log)
[bittrex_fxc-btc.txt](https://github.com/CoinAlpha/hummingbot/files/3807354/bittrex_fxc-btc.txt)

**Username:** cody
**ETH address:** ---

**Comment by dennisocana** [comment]
Tested in `fix/market-base-handle-normalize-price` branch and confirmed working.

<img width="947" alt="ubuntu1804_LvwLHBTCtN" src="https://user-images.githubusercontent.com/50150287/68460247-48298880-0242-11ea-981a-a40fa6793124.png">
<img width="683" alt="ubuntu1804_vrGAxvfuBQ" src="https://user-images.githubusercontent.com/50150287/68460249-4a8be280-0242-11ea-9c45-27bd8e51885b.png">

**Comment by dennisocana** [comment]
Confirmed fix by https://github.com/CoinAlpha/hummingbot/pull/1050
