### ISSUE TITLE
[BUG] Error submitting orders in Radar Relay

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1087]
**Describe the bug**

Just updated to latest version 0.19.0 and getting errors when trying to submit orders.

```
2019-11-19 11:08:22,256 - 10 - hummingbot.market.radar_relay.radar_relay_order_book_tracker - ERROR - Unknown error. Retrying after 5 seconds.
Traceback (most recent call last):
  File "/hummingbot/core/data_type/order_book_tracker.py", line 210, in _order_book_snapshot_router
    trading_pair: str = ob_message.trading_pair
  File "/hummingbot/core/data_type/order_book_message.py", line 304, in trading_pair
    return self.content["symbol"]
KeyError: 'symbol'
```
```
2019-11-19 11:08:26,002 - 10 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Error submitting buy order to Radar Relay for 5.8204439 ZRX-WETH.
Traceback (most recent call last):
  File "radar_relay_market.pyx", line 755, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket.execute_trade
  File "radar_relay_market.pyx", line 681, in submit_limit_order
ValueError: Unknown format code 'f' for object of type 'str'
```

**Screenshots**

<img width="947" alt="MaYpmghBxn" src="https://user-images.githubusercontent.com/50150287/69142193-42188f00-0b01-11ea-83dc-58732c2314f6.png">

**Release version**

```
"branch": "master",
"commit": "6c2abea0e2d05ea883190d40d6dbbcf06265535f",
"date": "2019-11-19T00:06:27Z",
```
```
"branch": "development",
"commit": "20e11541cd5ba7e1d15367c0daff55b0a572c4d4",
"date": "2019-11-19T01:49:00Z",
```

**Attachments**

[conf_radar_relay_zrx-weth.txt](https://github.com/CoinAlpha/hummingbot/files/3863446/conf_radar_relay_zrx-weth.txt)
[radar_relay_zrx-weth.log](https://github.com/CoinAlpha/hummingbot/files/3863447/radar_relay_zrx-weth.log)

**Comment by martinkou** [comment]
Fixed with #1089
