### ISSUE TITLE
[BUG] DDEX : Errno Request to https://api.ddex.io/v3/fees has failed

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1090]
**Describe the bug**

Errors when starting Hummingbot on DDEX.
```
2019-11-20 04:11:40,138 - 10 - hummingbot.market.ddex.ddex_market - NETWORK - Unexpected error while fetching account and status updates.
Traceback (most recent call last):
  File "ddex_market.pyx", line 225, in hummingbot.market.ddex.ddex_market.DDEXMarket._status_polling_loop
  File "/hummingbot/core/utils/async_utils.py", line 19, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "ddex_market.pyx", line 535, in _update_trade_fees
  File "ddex_market.pyx", line 497, in _api_request
  File "ddex_market.pyx", line 504, in hummingbot.market.ddex.ddex_market.DDEXMarket._api_request
OSError: [Errno Request to https://api.ddex.io/v3/fees has failed] {'status': 1002, 'desc': 'Unsupport market.', 'tmplate': 'unsupport_market', 'vals': ''}
2019-11-20 04:11:40,138 - 10 - hummingbot.market.ddex.ddex_market - WARNING - Failed to fetch account updates on DDEX. Check network connection.
```

**Screenshots**

<img width="947" alt="putty_lI6BlvlQgn" src="https://user-images.githubusercontent.com/50150287/69208812-fb25aa80-0b8f-11ea-936d-f75aebe33143.png">

**Release version**

```
"branch": "development",
"commit": "8ecf6db6bc10def4b625efcedce0c80812f82033",
"date": "2019-11-20T00:24:12Z",
```

**Attachments**

[ddex_zrx-weth.log](https://github.com/CoinAlpha/hummingbot/files/3867300/ddex_zrx-weth.log)
[conf_ddex_zrx-weth.txt](https://github.com/CoinAlpha/hummingbot/files/3867304/conf_ddex_zrx-weth.txt)

**Comment by martinkou** [comment]
Fixed with #1097.
