### ISSUE TITLE
[BUG] Issues with orders getting filled in Coinbase Pro

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1142]
**Describe the bug**

TradeFill table in local database shows 2 orders only.

![image](https://user-images.githubusercontent.com/50150287/69867643-5d924f80-12e2-11ea-87ec-f294a0c6ef25.png)

------------------------------------------------
buy-LINK-ETH-1574982362002163

```
2019-11-28 23:06:02,435 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Created OrderType.LIMIT buy order buy-LINK-ETH-1574982362002163 for 1.00000000 LINK-ETH.
2019-11-28 23:06:02,446 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"type": "OrderType.LIMIT", "trading_pair": "LINK-ETH", "amount": "1.00000000", "price": "0.01479348", "order_id": "buy-LINK-ETH-1574982362002163", "event_name": "BuyOrderCreatedEvent", "event_source": "coinbase_pro", "ts": 1574982362.0}

2019-11-28 23:06:02,523 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Filled 3.00000000 out of 1.00000000 of the limit buy order buy-LINK-ETH-1574982362002163
2019-11-28 23:06:02,524 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (LINK-ETH) Maker buy order of 3.00000000 LINK filled. [clock=2019-11-28 23:06:02+00:00]
2019-11-28 23:06:02,536 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "buy-LINK-ETH-1574982362002163", "trading_pair": "LINK-ETH", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "0.01479348", "amount": "3.00000000", "trade_fee": ["0.0015", []], "exchange_trade_id": "67ae8ceb-bb52-4227-93f4-a2a567809ad7", "event_name": "OrderFilledEvent", "event_source": "coinbase_pro", "ts": 1574982362.0}

2019-11-28 23:06:42,001 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (LINK-ETH) Cancelling the limit order buy-LINK-ETH-1574982362002163. [clock=2019-11-28 23:06:42+00:00]
2019-11-28 23:06:42,108 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Successfully cancelled order buy-LINK-ETH-1574982362002163.
2019-11-28 23:06:42,116 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "buy-LINK-ETH-1574982362002163", "event_name": "OrderCancelledEvent", "event_source": "coinbase_pro", "ts": 1574982402.0}
```

- It says the order amount is 1 and the filled amount is 3
- Order was filled and then cancelled

------------------------------------------------
buy-LINK-ETH-1574983059001435

```
2019-11-28 23:17:39,430 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Created OrderType.LIMIT buy order buy-LINK-ETH-1574983059001435 for 1.00000000 LINK-ETH.
2019-11-28 23:17:39,442 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"type": "OrderType.LIMIT", "trading_pair": "LINK-ETH", "amount": "1.00000000", "price": "0.01477142", "order_id": "buy-LINK-ETH-1574983059001435", "event_name": "BuyOrderCreatedEvent", "event_source": "coinbase_pro", "ts": 1574983059.0}
2019-11-28 23:17:39,504 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Filled 3.00000000 out of 1.00000000 of the limit buy order buy-LINK-ETH-1574983059001435
2019-11-28 23:17:39,505 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (LINK-ETH) Maker buy order of 3.00000000 LINK filled. [clock=2019-11-28 23:17:39+00:00]
2019-11-28 23:17:39,517 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "buy-LINK-ETH-1574983059001435", "trading_pair": "LINK-ETH", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "0.01477142", "amount": "3.00000000", "trade_fee": ["0.0015", []], "exchange_trade_id": "c845aebd-ff53-4ca0-a228-f23385b26609", "event_name": "OrderFilledEvent", "event_source": "coinbase_pro", "ts": 1574983059.0}

2019-11-28 23:18:19,001 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (LINK-ETH) Cancelling the limit order buy-LINK-ETH-1574983059001435. [clock=2019-11-28 23:18:19+00:00]
2019-11-28 23:18:19,073 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Successfully cancelled order buy-LINK-ETH-1574983059001435.
2019-11-28 23:18:19,085 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "buy-LINK-ETH-1574983059001435", "event_name": "OrderCancelledEvent", "event_source": "coinbase_pro", "ts": 1574983099.0}
```

- Both orders above are filled in Hummingbot but are not in Coinbase Pro order history and generated report.

![image](https://user-images.githubusercontent.com/50150287/69868264-35a3eb80-12e4-11ea-9742-81298453671d.png)

------------------------------------------------

This issue below is the same as https://github.com/CoinAlpha/hummingbot/issues/1138

- This buy error below was "filled" first before it was created. Also, it keeps getting an unexpected error while processing events 106, 107, 200, 201.
- After comparing the events related to these errors, found out that error 107 is when an order is trying to get filled, error 106 is when the order is being cancelled, 200 and 201 when the order is created (both have the same trace dump).
- There are 100+ more "filled order" events like this in the logs.

```
2019-11-28 23:23:48,440 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Filled 3.00000000 out of 1.00000000 of the limit buy order buy-LINK-ETH-1574983428002189
2019-11-28 23:23:48,440 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (LINK-ETH) Maker buy order of 3.00000000 LINK filled. [clock=2019-11-28 23:23:48+00:00]
2019-11-28 23:23:48,446 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - ERROR - Unexpected error while processing event 107.
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: TradeFill.exchange_trade_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
  File "/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/hummingbot/market/markets_recorder.py", line 234, in _did_fill_order
    self.save_market_states(self._config_file_path, market, no_commit=True)
  File "/hummingbot/market/markets_recorder.py", line 129, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market)
  File "/hummingbot/market/markets_recorder.py", line 157, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3250, in one_or_none
    ret = list(self)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3322, in __iter__
    self.session._autoflush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1587, in _autoflush
    util.raise_from_cause(e)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2458, in flush
    self._flush(objects)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2596, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2556, in _flush
    flush_context.execute()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: TradeFill.exchange_trade_id
[SQL: INSERT INTO "TradeFill" (config_file_path, strategy, market, symbol, base_asset, quote_asset, timestamp, order_id, trade_type, order_type, price, amount, trade_fee, exchange_trade_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('pmm_cbp_link-eth.yml', 'pure_market_making', 'coinbase_pro', 'LINK-ETH', 'LINK', 'ETH', 1574983428441, 'buy-LINK-ETH-1574983428002189', 'BUY', 'LIMIT', 0.01475706, 3.0, '{"percent": 0.0015, "flat_fees": []}', None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
```
```
2019-11-28 23:23:48,456 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "buy-LINK-ETH-1574983428002189", "trading_pair": "LINK-ETH", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "0.01475706", "amount": "3.00000000", "trade_fee": ["0.0015", []], "exchange_trade_id": null, "event_name": "OrderFilledEvent", "event_source": "coinbase_pro", "ts": 1574983428.0}
2019-11-28 23:23:48,526 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Created OrderType.LIMIT buy order buy-LINK-ETH-1574983428002189 for 1.00000000 LINK-ETH.
2019-11-28 23:23:48,528 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - ERROR - Unexpected error while processing event 200.
Traceback (most recent call last):
  File "pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
  File "/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/hummingbot/market/markets_recorder.py", line 190, in _did_create_order
    self.save_market_states(self._config_file_path, market, no_commit=True)
  File "/hummingbot/market/markets_recorder.py", line 129, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market)
  File "/hummingbot/market/markets_recorder.py", line 157, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3250, in one_or_none
    ret = list(self)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3322, in __iter__
    self.session._autoflush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2458, in flush
    self._flush(objects)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2551, in _flush
    subtransactions=True
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 937, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 315, in _begin
    self._assert_active()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: TradeFill.exchange_trade_id
[SQL: INSERT INTO "TradeFill" (config_file_path, strategy, market, symbol, base_asset, quote_asset, timestamp, order_id, trade_type, order_type, price, amount, trade_fee, exchange_trade_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('pmm_cbp_link-eth.yml', 'pure_market_making', 'coinbase_pro', 'LINK-ETH', 'LINK', 'ETH', 1574983428441, 'buy-LINK-ETH-1574983428002189', 'BUY', 'LIMIT', 0.01475706, 3.0, '{"percent": 0.0015, "flat_fees": []}', None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
```
```
2019-11-28 23:23:48,529 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"type": "OrderType.LIMIT", "trading_pair": "LINK-ETH", "amount": "1.00000000", "price": "0.01475706", "order_id": "buy-LINK-ETH-1574983428002189", "event_name": "BuyOrderCreatedEvent", "event_source": "coinbase_pro", "ts": 1574983428.0}
2019-11-28 23:24:28,001 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (LINK-ETH) Cancelling the limit order buy-LINK-ETH-1574983428002189. [clock=2019-11-28 23:24:28+00:00]
2019-11-28 23:24:28,097 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - ERROR - Unexpected error while processing event 106.
Traceback (most recent call last):
  File "pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
  File "/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/hummingbot/market/markets_recorder.py", line 271, in _did_cancel_order
    self._update_order_status(event_tag, market, evt)
  File "/hummingbot/market/markets_recorder.py", line 253, in _update_order_status
    order_record: Optional[Order] = session.query(Order).filter(Order.id == order_id).one_or_none()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3250, in one_or_none
    ret = list(self)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3322, in __iter__
    self.session._autoflush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2458, in flush
    self._flush(objects)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2551, in _flush
    subtransactions=True
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 937, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 315, in _begin
    self._assert_active()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: TradeFill.exchange_trade_id
[SQL: INSERT INTO "TradeFill" (config_file_path, strategy, market, symbol, base_asset, quote_asset, timestamp, order_id, trade_type, order_type, price, amount, trade_fee, exchange_trade_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('pmm_cbp_link-eth.yml', 'pure_market_making', 'coinbase_pro', 'LINK-ETH', 'LINK', 'ETH', 1574983428441, 'buy-LINK-ETH-1574983428002189', 'BUY', 'LIMIT', 0.01475706, 3.0, '{"percent": 0.0015, "flat_fees": []}', None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
```
```
2019-11-28 23:24:28,098 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "buy-LINK-ETH-1574983428002276", "event_name": "OrderCancelledEvent", "event_source": "coinbase_pro", "ts": 1574983468.0}
2019-11-28 23:24:28,099 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Successfully cancelled order buy-LINK-ETH-1574983428002189.
2019-11-28 23:24:29,348 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - ERROR - Unexpected error while processing event 201.
Traceback (most recent call last):
  File "pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
  File "/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/hummingbot/market/markets_recorder.py", line 190, in _did_create_order
    self.save_market_states(self._config_file_path, market, no_commit=True)
  File "/hummingbot/market/markets_recorder.py", line 129, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market)
  File "/hummingbot/market/markets_recorder.py", line 157, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3250, in one_or_none
    ret = list(self)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3322, in __iter__
    self.session._autoflush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2458, in flush
    self._flush(objects)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2551, in _flush
    subtransactions=True
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 937, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 315, in _begin
    self._assert_active()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) NOT NULL constraint failed: TradeFill.exchange_trade_id
[SQL: INSERT INTO "TradeFill" (config_file_path, strategy, market, symbol, base_asset, quote_asset, timestamp, order_id, trade_type, order_type, price, amount, trade_fee, exchange_trade_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('pmm_cbp_link-eth.yml', 'pure_market_making', 'coinbase_pro', 'LINK-ETH', 'LINK', 'ETH', 1574983428441, 'buy-LINK-ETH-1574983428002189', 'BUY', 'LIMIT', 0.01475706, 3.0, '{"percent": 0.0015, "flat_fees": []}', None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Release version**

```
"branch": "master",
"commit": "a7544f028b6d8a16a363058ea5f9968dd98dc589",
"date": "2019-11-26T22:34:43Z",
```

**Attachments**

[config_logs_trades.zip](https://github.com/CoinAlpha/hummingbot/files/3905104/config_logs_trades.zip)

**Comment by BUDDHA-TONY** [comment]
Tested this with the latest dev image with the PR `fix/cb_pro_trade_fill_bug` was not getting the error anymore.

![git1142](https://user-images.githubusercontent.com/55869559/70584475-46b1fe00-1bfc-11ea-947c-be29770f2779.png)

**Comment by veecos2** [comment]
As Dennis mentioned that this is similar to https://github.com/CoinAlpha/hummingbot/issues/1138 and its closed, closing this issue
