### ISSUE TITLE
[BUG] Error parsing trading_pair BTCRUB in Binance

### ISSUE THREAD

**Issue by BUDDHA-TONY** [CoinAlpha/hummingbot#1184]
**Describe the bug**
Binance added a new token pair causing the error,  strategy will not initialize.

**Steps To Reproduce**
1.Create New Strategy , Enter the token trading pair you would like to trade on binance (e.g. ZRX-ETH) >   
>> BTC-RUB
2. Finish intial configuration , Enter Start / Status 
3. Error will show

**Screenshots**

Test 1 : Paper-trade mode on
![image](https://user-images.githubusercontent.com/55869559/70589759-83392600-1c0b-11ea-9cf0-cbdeae1bd11d.png)

Test 2 : Paper-trade mode off / Not enough balance

![image](https://user-images.githubusercontent.com/55869559/70589735-6e5c9280-1c0b-11ea-8b77-5eecfa661685.png)

**Release version**
V-0.20.0

**Attachments**

```
2019-12-11 03:06:38,748 - 10 - hummingbot.data_feed.coin_gecko_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-11 03:06:38,782 - 10 - hummingbot.data_feed.coin_cap_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-11 03:14:53,063 - 10 - root - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "/hummingbot/client/command/stop_command.py", line 32, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
ValueError: list.remove(x): x not in list
```

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Lars l Support 
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by BUDDHA-TONY** [comment]
Tested with paper-trade mode on/off confirm [FIX]
