### ISSUE TITLE
[BUG] "Minimum order not met" error  on IDEX even if the minimum order placed was met

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1215]
**Describe the bug**
// User ran a Arbitrage strategy between IDEX and Liquid. Order was filled on the LIQUID side but the IDEX gives an error of the followig
```
HTTP status is 400 - {'error': 'Minimum trade amount not met. Please try a larger total amount (met 0% percent of minimum).'}

The order  size  of 1673.6 he placed was above the minimum order that the Idex exchange requires.
```
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ..

```
#####################################
###   Arbitrage strategy config   ###
#####################################

template_version: 2

# The following configuations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: liquid
secondary_market: idex
primary_market_trading_pair: CEL-ETH
secondary_market_trading_pair: CEL-ETH

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.03

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters


```

2. Run the bot
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

The screenshot below shows that the order was placed but when the exchange attempts to fill the order, it errors out on the IDEX.
![image](https://user-images.githubusercontent.com/53868268/71170334-07516600-2229-11ea-9c7a-f52bf9901011.png)

Logs shows the following
```
2019-12-18 11:33:18,531 - 10 - hummingbot.market.idex.idex_market - NETWORK - Error submitting buy order to IDEX for 1673.60 ETH_CEL.
Traceback (most recent call last):
  File "idex_market.pyx", line 764, in hummingbot.market.idex.idex_market.IDEXMarket.execute_buy
  File "idex_market.pyx", line 672, in post_market_order
  File "idex_market.pyx", line 456, in _sequential_api_request
  File "idex_market.pyx", line 466, in hummingbot.market.idex.idex_market.IDEXMarket._sequential_api_request
  File "/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "idex_market.pyx", line 430, in _api_request
  File "idex_market.pyx", line 439, in hummingbot.market.idex.idex_market.IDEXMarket._api_request
OSError: Error fetching data from https://api.idex.market/trade. HTTP status is 400 - {'error': 'Minimum trade amount not met. Please try a larger total amount (met 0% percent of minimum).'}
2019-12-18 11:33:18,532 - 10 - hummingbot.market.idex.idex_market - WARNING - Failed to submit buy order to IDEX: Error fetching data from https://api.idex.market/trade. HTTP status is 400 - {'error': 'Minimum trade amount not met. Please try a larger total amount (met 0% percent of minimum).'}
2019-12-18 11:33:18,533 - 10 - hummingbot.strategy.arbitrage.arbitrage - INFO - Market order failed on idex: buy-ETH_CEL-1576668798012366 [clock=2019-12-18 11:33:18+00:00]
```

**Release version**
0.20.0

**Attachments**
Log file
[logs_conf_arbitrage_strategy.log](https://github.com/CoinAlpha/hummingbot/files/3983362/logs_conf_arbitrage_strategy.log)

Strategy file
[conf_arbitrage_strategy.txt](https://github.com/CoinAlpha/hummingbot/files/3983367/conf_arbitrage_strategy.txt)

**Optional: your discord username:** deimos#1453
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by rennel-tabing** [comment]
User run  the strategy at a different time slot yesterday and had the same error.

Idex support team also confirms that the order met their requirements.
![image](https://user-images.githubusercontent.com/53868268/71170868-58158e80-222a-11ea-8fb9-9ae22a3ee30f.png)

**Comment by dennisocana** [comment]
This and https://github.com/CoinAlpha/hummingbot/issues/855 might be related.

**Comment by Deimoos** [comment]
Hi @dennisocana did you get any workaround this issue ? Thanks

**Comment by yzhang1994** [comment]
The IDEX connector is deprecated - we will no longer support IDEX-related issues. Closing this issue for now.
