### ISSUE TITLE
[BUG] Failing to initialize discovery strategy with bamboo relay

### ISSUE THREAD

**Issue by BUDDHA-TONY** [CoinAlpha/hummingbot#1220]
**Describe the bug**
// Fail to initialize discovery strategy with bamboo relay

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create new discovery strategy, choose exchange bamboo relay pair with any other exchange 
2. Start the bot error will show
...

**Screenshots**

![image](https://user-images.githubusercontent.com/55869559/71221811-eb24f600-2308-11ea-94f3-15c2c7d1f15d.png)

**Release version**
0.21.0

```
2019-12-20 01:02:42,577 - 10 - hummingbot.data_feed.coin_gecko_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-20 01:02:43,355 - 10 - hummingbot.data_feed.coin_cap_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-20 01:02:56,988 - 10 - hummingbot.client.hummingbot_application - ERROR - Error parsing trading_pair on bamboo_relay: H-C-WETH
Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 80, in filter_trading_pair_by_single_token
    base_token, quote_token = MARKET_CLASSES[market_name].split_trading_pair(t)
ValueError: too many values to unpack (expected 2)
2019-12-20 01:02:56,995 - 10 - hummingbot.client.hummingbot_application - ERROR - Error initializing strategy.
Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 118, in start
    self._initialize_markets(market_names)
  File "/hummingbot/client/hummingbot_application.py", line 364, in _initialize_markets
    raise ValueError(f"Market name {market_name} is invalid.")
ValueError: Market name bamboo_relay is invalid.
```

                "branch": "development",
                "commit": "851a01be8d24d5e588f359134bc65acee9879e5d",
                "date": "2019-12-20T00:10:49Z",

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Lars l Support
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by BUDDHA-TONY** [comment]
tagging @Arctek

**Comment by BUDDHA-TONY** [comment]
https://github.com/CoinAlpha/hummingbot/issues/1219

**Comment by BUDDHA-TONY** [comment]
Pure Market Making Strategy Testing with Bamboo-Relay

![image](https://user-images.githubusercontent.com/55869559/71222465-a0f14400-230b-11ea-9872-8005b9ff5de1.png)

**Comment by Arctek** [comment]
First issue was a problem on my side, one of the tokens had a hyphen in its name.
I've renamed it for now and will have to see about a different fix for it in the long term - but discovery works again.

Ok so in the second case it's complaining about the kill switch setting:
`self._kill_switch_rate: Decimal = Decimal(global_config_map.get("kill_switch_rate").value)`
`TypeError: conversion from NoneType to Decimal is not supported`

Is `kill_switch_rate` set to a value in your global config file?

This is probably an issue which will affect any strategy though that uses the kill switch.

**Comment by BUDDHA-TONY** [comment]
I checked on my side and its set to `false` 

![image](https://user-images.githubusercontent.com/55869559/71224039-35f63c00-2310-11ea-893d-3b69394376d3.png)

**Comment by PtrckM** [comment]
![image](https://user-images.githubusercontent.com/54516858/71223698-d1d37800-230f-11ea-9840-a8b3f3c6926e.png)

no problem at all when using https://docs.hummingbot.io/operation/client/#trading-strategy-autostart
shows profitability at the end.

the error shows as well on other connectors like binance, ddex and coinbase 

![image](https://user-images.githubusercontent.com/54516858/71223844-fd566280-230f-11ea-9dcf-15a774e8894f.png)

![image](https://user-images.githubusercontent.com/54516858/71224083-43abc180-2310-11ea-907e-5aff98402584.png)


but when using autostart trading works no problem.

![image](https://user-images.githubusercontent.com/54516858/71224126-53c3a100-2310-11ea-8a55-31072a5f3467.png)

**Comment by PtrckM** [comment]
```
2019-12-26 01:03:02,489 - 10 - hummingbot.data_feed.coin_gecko_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-26 01:03:02,889 - 10 - hummingbot.data_feed.coin_cap_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-26 01:03:17,832 - 10 - hummingbot.client.hummingbot_application - ERROR - Error initializing strategy.
Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 118, in start
    self._initialize_markets(market_names)
  File "/hummingbot/client/hummingbot_application.py", line 364, in _initialize_markets
    raise ValueError(f"Market name {market_name} is invalid.")
ValueError: Market name bamboo_relay is invalid.
2019-12-26 01:03:17,838 - 10 - hummingbot.client.hummingbot_application - ERROR - 'NoneType' object has no attribute 'restore_market_states'
Traceback (most recent call last):
  File "/hummingbot/client/command/start_command.py", line 99, in start_market_making
    self.markets_recorder.restore_market_states(config_path, market)
AttributeError: 'NoneType' object has no attribute 'restore_market_states'

```

                "branch": "development",
                "commit": "b41ddec4430d335ef5b1510f49c73fac6c394fdf",
                "date": "2019-12-24T23:13:31Z",

**Comment by BUDDHA-TONY** [comment]
Confirm Discovery Strategy is initializing with Bamboo-Relay. Tested.
