### ISSUE TITLE
[BUG] Liquid unable to start and/or unable to show profitability on discovery

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1231]
Liquid unable to start and/or unable to show profitability if able to start.

- Tested in 2 VM's in all pair exchanges below:

liquid - radar_relay = wont start Market name radar_relay is invalid. - able to start using [autostart trading ](https://docs.hummingbot.io/operation/client/#trading-strategy-autostart)but still unable to show profitability
liquid - ddex = wont start Market name ddex is invalid. - able to start using [autostart trading](https://docs.hummingbot.io/operation/client/#trading-strategy-autostart) but still unable to show profitability
liquid - idex = unable show profitability
liquid - binance = unable to show profitability
liquid - bittrex = unable to show profitability
liquid - bamboo = wont start Market name bamboo_relay is invalid. - able to start using [autostart trading](https://docs.hummingbot.io/operation/client/#trading-strategy-autostart) but still unable to show profitability
liquid - coinbase = unable to show profitability
liquid - dolomite = wont start Market name dolomite is invalid. - able to start using [autostart trading](https://docs.hummingbot.io/operation/client/#trading-strategy-autostart) but still unable to show profitability
liquid - bitcoin_com = unable to show profitability

```
2019-12-21 03:07:02,305 - 11 - hummingbot.data_feed.coin_gecko_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-21 03:07:02,594 - 11 - hummingbot.data_feed.coin_cap_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-21 03:07:17,649 - 11 - hummingbot.client.hummingbot_application - ERROR - Error initializing strategy.
Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 118, in start
    self._initialize_markets(market_names)
  File "/hummingbot/client/hummingbot_application.py", line 364, in _initialize_markets
    raise ValueError(f"Market name {market_name} is invalid.")
ValueError: Market name bamboo_relay is invalid.
2019-12-21 03:07:17,653 - 11 - hummingbot.client.hummingbot_application - ERROR - 'NoneType' object has no attribute 'restore_market_states'
Traceback (most recent call last):
  File "/hummingbot/client/command/start_command.py", line 99, in start_market_making
    self.markets_recorder.restore_market_states(config_path, market)
AttributeError: 'NoneType' object has no attribute 'restore_market_states'
```

![image](https://user-images.githubusercontent.com/54516858/71302551-3e6d7600-23e7-11ea-8b5a-76570568a098.png)
![image](https://user-images.githubusercontent.com/54516858/71302555-4b8a6500-23e7-11ea-8727-76ea1077dbb6.png)
![image](https://user-images.githubusercontent.com/54516858/71302561-5d6c0800-23e7-11ea-877d-ad28917c039e.png)
![image](https://user-images.githubusercontent.com/54516858/71302563-63fa7f80-23e7-11ea-9ff2-b4887e081711.png)
![image](https://user-images.githubusercontent.com/54516858/71302582-b20f8300-23e7-11ea-956a-924c86fe7bc2.png)

- Configs

```
#####################################
###   Discovery strategy config   ###
#####################################

template_version: 2

# The following configuations are only required for the discovery strategy

# Exchange and token parameters
primary_market: liquid
secondary_market: bitcoin_com
target_trading_pair_1: []
target_trading_pair_2: []

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
target_profitability: 0.0
target_amount: .inf

# Tokens that the bot assumes are equivalent
equivalent_tokens:
- - USDT
  - USDC
  - USDS
  - DAI
  - PAX
  - TUSD
  - USD
- - ETH
  - WETH
- - BTC
  - WBTC

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/discovery/
```

- Release version

                "branch": "development",
                "commit": "5a94dbb9d8876dd0ab2f5d166dd90193e0a25e72",
                "date": "2019-12-21T00:32:40Z",

- Attachments

[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/3991024/logs_conf_discovery_strategy_0.log)
[logs_conf_discovery_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/3991025/logs_conf_discovery_strategy_1.log)
[logs_conf_discovery_strategy_2.log](https://github.com/CoinAlpha/hummingbot/files/3991026/logs_conf_discovery_strategy_2.log)
[logs_liq_bn.log](https://github.com/CoinAlpha/hummingbot/files/3991027/logs_liq_bn.log)
[logs_liq_br.log](https://github.com/CoinAlpha/hummingbot/files/3991028/logs_liq_br.log)
[logs_liq_btx.log](https://github.com/CoinAlpha/hummingbot/files/3991029/logs_liq_btx.log)

**Comment by CrimsonJacket** [comment]
I did some initial investigation, this seems to be related to #1234

**Comment by BUDDHA-TONY** [comment]
Tested With the PR https://github.com/CoinAlpha/hummingbot/pull/1242 [CONFIRM FIX] was able to initialized & show profitability 

![image](https://user-images.githubusercontent.com/55869559/71495723-639c3180-288a-11ea-8cb2-a119e0d30434.png)

![image](https://user-images.githubusercontent.com/55869559/71495746-76af0180-288a-11ea-91f6-988b96773635.png)

**Comment by PtrckM** [comment]
confirmed fix

![image](https://user-images.githubusercontent.com/54516858/71499547-ee395c80-289b-11ea-83e3-9d09c8d9e5a7.png)

[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4004041/logs_conf_discovery_strategy_0.log)
[discovery_strategy_output_2019-12-26-22-26-35.txt](https://github.com/CoinAlpha/hummingbot/files/4004043/discovery_strategy_output_2019-12-26-22-26-35.txt)

but i found this error messages on the logs

```
2019-12-26 22:21:58,021 - 4012 - hummingbot.market.liquid.liquid_order_book_tracker - ERROR - Unknown error. Retrying after 5 seconds.
Traceback (most recent call last):
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-CNY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patz/hummingbot/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 169, in get_trading_pairs
    for trading_pair in self._trading_pairs
  File "/home/patz/hummingbot/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 169, in <dictcomp>
    for trading_pair in self._trading_pairs
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 988, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-CNY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patz/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 153, in _refresh_tracking_loop
    await self._refresh_tracking_tasks()
  File "/home/patz/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 129, in _refresh_tracking_tasks
    available_pairs: Dict[str, OrderBookTrackerEntry] = await self.data_source.get_tracking_pairs()
  File "/home/patz/hummingbot/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 215, in get_tracking_pairs
    trading_pairs: List[str] = await self.get_trading_pairs()
  File "/home/patz/hummingbot/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 176, in get_trading_pairs
    app_warning_msg=f"Error getting active exchange information. Check network connection."
  File "/home/patz/hummingbot/hummingbot/logger/logger.py", line 35, in network
    self.log(NETWORK, log_msg, *args, **kwargs)
  File "/home/patz/miniconda3/envs/hummingbot/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'exe_info'
```
