### ISSUE TITLE
[BUG] Liquid Connector not working due to missing pair ETH-USDC

### ISSUE THREAD

**Issue by marten42** [CoinAlpha/hummingbot#1234]
I was using the new connector to Liquid for 2 days. Since today it thorws unexpected error, seems due to the fact that ETH-USDC is not listed any more on liquid:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 159, in get_trading_pairs
    active_markets_df: pd.DataFrame = await self.get_active_exchange_markets()
  File "/hummingbot/core/utils/init.py", line 15, in memoize
    cache[key] = await fn(*args, **kwargs)
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 73, in get_active_exchange_markets
    eth_price: float = float(all_markets_df.loc['ETH-USDC'].last_traded_price)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1500, in getitem
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-USDC'

**Comment by marten42** [comment]
![Unbenannt2](https://user-images.githubusercontent.com/22445447/71359561-1a4b9980-258d-11ea-9790-9c533dcb2d9d.JPG)

**Comment by rennel-tabing** [comment]
Checked Liquid.com and I was able to confirm that the pair ETH-USDC is not an existing pair on that exchange.

@marten42 Please provide the following
1) Hummingbot version

2) Deployment environment (local/cloud, which cloud provider, which operating system, docker or from source)

3) **Screenshot**: In the hummingbot client, run the `status` command and take a screenshot that includes the full Terminal/Bash window. Make sure to include both the left pane and the right log pane of Hummingbot.

4) **Strategy config file**: This is the file with the parameters associated with your strategy. It does not contain API keys, wallet private keys, or other confidential data. It is located in the `conf/` folder. For example, if you have configured a pure market making strategy for the first time, the file's default name is `conf_pure_market_making_0.yml`

5) **Log file**: This is the file that contains a detailed log output and error stack trace. It is located in the `logs/` folder. If you are sending logs related to your most recent Hummingbot session, sort the folder for the most recently updated file. It should have a name similar to `hummingbot_logs_2019-07-31-19-51-36.log`

**Comment by marten42** [comment]
Hi, thanks for being so fast. Please find the requested infos as follows:

1. most recent hummingbot version form yesterday (0.2) - this first version including the liquid connector

2. desktop env with win10 - dockerized hummingbot

3 find attached

4 find attached

5 find attached

As the connector is just 5 days old - iassume somewhere inside the reference to  ETH-USDC is "hradcoded" and now fails as Liquid removed that trading pair last night.

**Comment by marten42** [comment]
![3screenshot](https://user-images.githubusercontent.com/22445447/71371768-8c82a500-25b2-11ea-9855-87e4b975af57.JPG)
[4_config.txt](https://github.com/CoinAlpha/hummingbot/files/3995753/4_config.txt)
[5_logs.txt](https://github.com/CoinAlpha/hummingbot/files/3995754/5_logs.txt)

**Comment by rennel-tabing** [comment]
User @deimos#1453 saw a hard code on the connector. 
Here is the link https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/market/liquid/liquid_api_order_book_data_source.py

![image](https://user-images.githubusercontent.com/53868268/71383132-f0a06b80-25a8-11ea-9b81-b460810cb250.png)

**Comment by Deimoos** [comment]
Hello,

As Liquid delisted the ETH-USDC pair permanently (see https://help.liquid.com/en/articles/3545212-trading-pair-delisting-december-2019),

changing the code to ETH-USD instead of ETH-USDC worked on my side in the liquid_api_order_book_data_source.py file. 

It is a quick and simple fix to use ETH-USD instead of ETH-USDC.
Hope this helps.

**Comment by PtrckM** [comment]
fix confirmed @Deimoos

**Comment by dennisocana** [comment]
Confirmed fix #1242 in development branch and will be in tomorrow's release.
