### ISSUE TITLE
[BUG] Liquid shows KeyError: 'ETH-CNY' on logs.

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1251]
**Describe the bug**
Liquid produces error in logs **KeyError: 'ETH-CNY'** aside from this bot run smoothly and produce profitability. 

tested on other exchange pair confirms that this came with liquid: 
liquid - bittrex = KeyError: 'ETH-CNY
liquid - binance = KeyError: 'ETH-CNY
liquid - coinbase = KeyError: 'ETH-CNY

```
2019-12-28 02:09:10,993 - 10 - hummingbot.market.liquid.liquid_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-CNY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 169, in get_trading_pairs
    for trading_pair in self._trading_pairs
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 169, in <dictcomp>
    for trading_pair in self._trading_pairs
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 988, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-CNY'
```

- CONFIG
![image](https://user-images.githubusercontent.com/54516858/71537815-60717600-295c-11ea-97a5-29486fb666b2.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/71537792-0ffa1880-295c-11ea-9d47-f5d07f46fb4a.png)

**Release version**
```
                "branch": "development",
                "commit": "7fa2cc1b6de3b5ee7147b63afdb27b25d4e8a4de",
                "date": "2019-12-27T21:34:54Z",
```

**Attachments**
- LOGS
[logs_conf_discovery_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/4006621/logs_conf_discovery_strategy_1.log)

- CSV
[discovery_strategy_output_2019-12-28-02-13-43.txt](https://github.com/CoinAlpha/hummingbot/files/4006622/discovery_strategy_output_2019-12-28-02-13-43.txt)

**Comment by CrimsonJacket** [comment]
Is the `ETH-CNY` trading pair active on Liquid? I am not seeing any orders. 
https://app.liquid.com/exchange/ETHCNY

**Comment by BUDDHA-TONY** [comment]
Was able to reproduce the behavior using discovery strategy liquid-bitcoin default parameters

```
Traceback (most recent call last):
  File "/home/tony/miniconda3/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-CNY'
```

**Comment by znerol19619** [comment]
Just run some test on latest development release using the same config and haven't found any errors on log file

**version**
```
                "branch": "development",
                "commit": "38ceaf9995d7a37c49c4734b0c95e0e27f2a9632",
                "date": "2019-12-29T15:16:11Z",
```

**attachement**
[logs_conf_discovery_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/4009469/logs_conf_discovery_strategy_1.log)

**Comment by PtrckM** [comment]
tested on both release 0.21.0 and dev-0.22.0

error on logs still exist.

```
2019-12-31 01:18:31,162 - 10 - hummingbot.data_feed.coin_gecko_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-31 01:18:31,993 - 10 - hummingbot.data_feed.coin_cap_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-31 01:18:33,652 - 10 - hummingbot.market.bitcoin_com.bitcoin_com_market - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-31 01:18:33,740 - 10 - hummingbot.market.liquid.liquid_market - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-12-31 01:18:34,003 - 10 - hummingbot.strategy.discovery.discovery - INFO - Waiting to finish fetching trading pair from bitcoin_com. [clock=2019-12-31 01:18:34+00:00]
2019-12-31 01:18:34,587 - 10 - hummingbot.market.liquid.liquid_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-CNY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 169, in get_trading_pairs
    for trading_pair in self._trading_pairs
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 169, in <dictcomp>
    for trading_pair in self._trading_pairs
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 988, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 141, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ETH-CNY'
```

```
                "branch": "master",
                "commit": "a8070e3369d9273ddb29e7d9e505987ad8fa1b46",
                "date": "2019-12-30T21:27:45Z",
```

```
                "branch": "development",
                "commit": "1f3a126b0e29cb4aa7e6aacb398cdb8311ee233a",
                "date": "2019-12-30T21:54:40Z",
```

**Comment by dennisocana** [comment]
Confirmed fix by https://github.com/CoinAlpha/hummingbot/pull/1300
