### ISSUE TITLE
[BUG] Liquid WebSocket connection errors

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1266]
**Describe the bug**

Getting WebSocket connection errors with Liquid connector using any strategies. Despite the errors, Hummingbot continues to behave as expected (creating and canceling orders). Haven't checked yet what happens when a trade is executed.

```
2020-01-02 03:11:45,514 - 10 - hummingbot.market.liquid.liquid_api_user_stream_data_source - ERROR - Unexpected error with Liquid WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'quoted_currency'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/market/liquid/liquid_api_user_stream_data_source.py", line 73, in listen_for_user_stream
    for trading_pair in self._trading_pairs
  File "/hummingbot/market/liquid/liquid_api_user_stream_data_source.py", line 73, in <listcomp>
    for trading_pair in self._trading_pairs
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1017, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 1913, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexing.py", line 137, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/generic.py", line 3585, in xs
    loc = self.index.get_loc(key)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2658, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'quoted_currency'
```
<img width="947" alt="6K5l4163cI" src="https://user-images.githubusercontent.com/50150287/71653171-f7c43800-2d65-11ea-9bd0-90c43f23b235.png">

**Release version**

This happens in both master branch `0.21.0` and development branch `dev-0.22.0`.

```
"branch": "master",
"commit": "a8070e3369d9273ddb29e7d9e505987ad8fa1b46",
"date": "2019-12-30T21:27:45Z",
```

```
"branch": "development",
"commit": "7f73abc040c894e6e87fdd887b5bc508bd6a910b",
"date": "2020-01-01T04:58:19Z",
```

**Attachments**

[liquid_websocket_errors.log](https://github.com/CoinAlpha/hummingbot/files/4014984/liquid_websocket_errors.log)

**Comment by dennisocana** [comment]
Fixed by #1270 in development branch and will be in the upcoming version 0.22.0 release.
