### ISSUE TITLE
[BUG] Paper trade on Dolomite unable to initialized.

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1272]
**Describe the bug**
When Paper trade enabled on Dolomite ARB, PMM and XEMM strategy unable to initialized.

**Steps To Reproduce**
Using default values.

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/71707368-49cb9300-2e24-11ea-88f4-17fad40cf739.png)

![image](https://user-images.githubusercontent.com/54516858/71707375-58b24580-2e24-11ea-8776-64ff580b7656.png)

![image](https://user-images.githubusercontent.com/54516858/71707378-610a8080-2e24-11ea-82d9-a4f148389d62.png)

**Release version**
```
                "branch": "development",
                "commit": "cae487e7b06cec45e588b0190517a8debbf6dacc",
                "date": "2020-01-03T01:08:34Z",
```

**Attachments**
- Configs
[conf_cross_exchange_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/4018121/conf_cross_exchange_market_making_strategy_0.txt)
[conf_pure_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/4018122/conf_pure_market_making_strategy_0.txt)
[conf_arbitrage_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/4018123/conf_arbitrage_strategy_0.txt)

- LOGS
[logs_conf_cross_exchange_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4018118/logs_conf_cross_exchange_market_making_strategy_0.log)
[logs_conf_pure_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4018119/logs_conf_pure_market_making_strategy_0.log)
[logs_conf_arbitrage_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4018120/logs_conf_arbitrage_strategy_0.log)

- Some of the errors on logs

```
Traceback (most recent call last):
  File "/hummingbot/market/dolomite/dolomite_api_order_book_data_source.py", line 128, in get_tracking_pairs
    snapshot: Dict[str, any] = await self.get_snapshot(client, trading_pair)
  File "/hummingbot/market/dolomite/dolomite_api_order_book_data_source.py", line 110, in get_snapshot
    async with client.get(f"{self.REST_URL}{SNAPSHOT_URL}".replace(":trading_pair", trading_pair)) as response:
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 473, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 285, in __init__
    self.update_host(url)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 339, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /v1/orders/markets/WETH-DAI/depth/unmerged
2020-01-03 04:16:37,075 - 10 - hummingbot.market.ddex.ddex_api_order_book_data_source - INFO - Initialized order book for ZRX-WETH. 1/1 completed.
2020-01-03 04:16:38,378 - 10 - hummingbot.market.ddex.ddex_order_book_tracker - INFO - Started order book tracking for ZRX-WETH.
2020-01-03 04:16:42,223 - 10 - hummingbot.market.dolomite.dolomite_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/uri.py", line 44, in parse_uri
    assert uri.scheme in ['ws', 'wss']
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hummingbot/market/dolomite/dolomite_api_order_book_data_source.py", line 194, in listen_for_order_book_snapshots
    async with websockets.connect(self.WS_URL) as ws:
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/client.py", line 345, in __init__
    wsuri = parse_uri(uri)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/uri.py", line 49, in parse_uri
    raise InvalidURI("{} isn't a valid URI".format(uri)) from exc
websockets.exceptions.InvalidURI: ParseResult(scheme='', netloc='', path='', params='', query='', fragment='') isn't a valid URI
```

**Comment by Hashira-Lars** [comment]
Tested with a different token pair and config settings and was able to reproduce this behavior.

                "branch": "development",
                "commit": "54a4441558d868f0466ccbea62ce8989caba61f2",
                "date": "2020-01-04T06:43:32Z",

also im wandering does this error happen because of the quote asset `weth` where in the main exchange it uses `eth` 

![image](https://user-images.githubusercontent.com/55869559/71763733-30a50e00-2f1a-11ea-825c-b257a249d4ef.png)

**Comment by yzhang1994** [comment]
@coreycaplan3
