### ISSUE TITLE
[BUG] Binance PMM Error fetching Binance market snapshot HTTP status is 418

### ISSUE THREAD

**Issue by sweetpotatoz** [CoinAlpha/hummingbot#1278]
**Describe the bug**

Errors for PMM XZCBTC in Binance 

```
2020-01-04 03:52:35,610 - 10 - hummingbot.market.binance.binance_api_order_book_data_source - ERROR - Error getting snapshot for XZCBTC. 
Traceback (most recent call last):
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 144, in get_tracking_pairs
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair, 1000)
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 125, in get_snapshot
    raise IOError(f"Error fetching Binance market snapshot for {trading_pair}. "
OSError: Error fetching Binance market snapshot for XZCBTC. HTTP status is 418.

```

Errors for PMM XZCBNB in Binance 
```
2020-01-04 04:00:00,507 - 10 - hummingbot.market.binance.binance_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 233, in listen_for_order_book_snapshots
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair)
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 125, in get_snapshot
    raise IOError(f"Error fetching Binance market snapshot for {trading_pair}. "
OSError: Error fetching Binance market snapshot for XZCBNB. HTTP status is 418.
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

I have tried to re-create a new PMM strategy file for XZCBNB, still producing the same error.
I have attached the PMM strategy for XZCBTC below.
Suspected Binance exchange issue?  since both XZCBTC and XZCBNB bots are affected.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.21.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[PMM_Binance_XZCBTC.txt](https://github.com/CoinAlpha/hummingbot/files/4021531/PMM_Binance_XZCBTC.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by sweetpotatoz** [comment]
![image](https://user-images.githubusercontent.com/1692346/71763249-b625bf80-2f14-11ea-957a-0c711379bc4b.png)

After running a while, we will run into this issue.  Stop, some orders will not be cancelled, then failed to start.  We have to manually removed the orders.  Then we can start again.

**Comment by sweetpotatoz** [comment]
![image](https://user-images.githubusercontent.com/1692346/71764666-b9757700-2f25-11ea-8ce3-d6e64da7c080.png)
getting this issue now

**Comment by dennisocana** [comment]
Currently looking into this issue. I'm not sure if this is related, but I'm getting an error with `fetch_binance_trading_pairs` at the start. I find it odd because I'm using Liquid connector.

```
2020-01-05 04:17:36,319 - 10 - root - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "/hummingbot/core/utils/trading_pair_fetcher.py", line 312, in fetch_all
    binance_trading_pairs = await self.fetch_binance_trading_pairs()
  File "/hummingbot/core/utils/trading_pair_fetcher.py", line 55, in fetch_binance_trading_pairs
    async with client.get(BINANCE_ENDPOINT, timeout=API_CALL_TIMEOUT) as response:
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

**Comment by dennisocana** [comment]
@sweetpotatoz there was a recent PR merged to fix the bug related to Binance trading pair fetcher. Can you check if this is still happening on the most recent development image?

**Comment by sweetpotatoz** [comment]
still getting the same error, after running dev-0.22 for a day.  it started yesterday well.

**Comment by dennisocana** [comment]
@sweetpotatoz as per Binance API docs here https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#http-return-codes:

- HTTP 418 return code is used when an IP has been auto-banned for continuing to send requests after receiving 429 codes.
- HTTP 429 return code is used when breaking a request rate limit.

Make sure you're not running more than one instance of Hummingbot on Binance in the same server especially if you are on multiple order mode.

**Comment by dennisocana** [comment]
This is similar to issue https://github.com/CoinAlpha/hummingbot/issues/1247.

**Comment by sweetpotatoz** [comment]
running one instance on Binance in the same server, and have not seen the same issue happen again.  thanks
