### ISSUE TITLE
[BUG] Error running performance analysis

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1289]
**Describe the bug**

Getting error when running `history` command in development.

<img width="947" alt="putty_unW3YJsr1J" src="https://user-images.githubusercontent.com/50150287/71873662-b3b4a700-315a-11ea-8b8d-9db5f407d019.png">

```
2020-01-07 06:00:08,132 - 10 - root - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "/hummingbot/core/utils/trading_pair_fetcher.py", line 323, in fetch_all
    radar_relay_trading_pairs = await self.fetch_radar_relay_trading_pairs()
  File "/hummingbot/core/utils/trading_pair_fetcher.py", line 117, in fetch_radar_relay_trading_pairs
    async with client.get(f"{RADAR_RELAY_ENDPOINT}?perPage=100&page={page_count}", timeout=API_CALL_TIMEOUT) \
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

2020-01-07 06:00:09,844 - 10 - hummingbot.client.hummingbot_application - ERROR - Unexpected error running performance analysis.
Traceback (most recent call last):
  File "/hummingbot/client/command/history_command.py", line 131, in trade_performance_report
    inventory_df: pd.DataFrame = self.balance_comparison_data_frame(market_trading_pair_stats)
  File "/hummingbot/client/command/history_command.py", line 68, in balance_comparison_data_frame
    starting_balance = self.starting_balances.get(asset).get(market.name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Release version**

Confirmed this doesn't affect the master branch and happens on development only.
```
"branch": "development",
"commit": "0c016de5c986878879d01e9cca3c36966f494740",
"date": "2020-01-07T00:50:50Z",
```

**Attachments**

[logs_conf_pure_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4029207/logs_conf_pure_market_making_strategy_0.log)

**Comment by veecos2** [comment]
@dennisocana : The radar relay trading pair issue is already fixed with the PR I raised yesterday.

**Comment by yzhang1994** [comment]
@Nullably Please take a look at this issue when you have time. Should be an easy fix

**Comment by dennisocana** [comment]
@Nullably confirmed that this is no longer an issue in the most recent development docker image.
