### ISSUE TITLE
[BUG] Error when entering default value for expiration_second

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1301]
**Describe the bug**
- When the question `How long should your limit orders remain valid until they expire are replaced? (Minimum / Default is 130 sec)` appears, press `Enter`
- Instead of Hummingbot placing the default value, the unknown error will appear and set expiration_seconds to `None`

Additional detail:
- Bot will run if you will manually enter a value for the expiration_second.
- Tested other strategies and other markets and it appears that this is within Bamboo_relay using Pure market making strategy only.

**Steps To Reproduce**
1. Create a PMM strategy using Bamboo_relay
2. Fill in required details
3. When the question `How long should your limit orders remain valid until they expire are replaced? (Minimum / Default is 130 sec)` appears, press `Enter`
4. Unknown error will immediately appear on the log pane, `list configs` and check `expiration_second,` 
```
2020-01-09 20:55:30,802 - 10 - hummingbot.client.hummingbot_application - ERROR - Unknown error while writing config. could not convert string to float:
Traceback (most recent call last):
  File "/hummingbot/client/command/config_command.py", line 369, in _config_loop
    await self._inner_config_loop(keys)
  File "/hummingbot/client/command/config_command.py", line 357, in _inner_config_loop
    await self._inner_config_loop(self._get_empty_configs())
  File "/hummingbot/client/command/config_command.py", line 352, in _inner_config_loop
    value = await self.prompt_single_variable(cv, requirement_overwrite=False)
  File "/hummingbot/client/command/config_command.py", line 310, in prompt_single_variable
    if not cvar.validate(val):
  File "/hummingbot/client/config/config_var.py", line 43, in validate
    valid = self._validator(value)
  File "/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 66, in <lambda>
    validator=lambda input: float(input) >= 130.0),
ValueError: could not convert string to float:
```

**Screenshots**
![Bamboo](https://user-images.githubusercontent.com/57189990/72166433-2e541f80-3404-11ea-8371-02092f17b89e.PNG)
![Bamboo1](https://user-images.githubusercontent.com/57189990/72166437-301de300-3404-11ea-9ad6-8f242689bb7b.PNG)

**Release version**
Note: Issue is within development branch only
```
branch: "development",
commit: "2a85c61416c588e5a1070f5fdabc2a47841ddd3a",
date": "2020-01-10T01:52:36Z",
```

**Attachments**
[Bamboo_log_hummingbot.txt](https://github.com/CoinAlpha/hummingbot/files/4046441/Bamboo_log_hummingbot.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Hashira-Lars** [comment]
Confirm Fix Tested with PR #1288 merged in development

![image](https://user-images.githubusercontent.com/55869559/72233269-3f1db480-3601-11ea-89b3-34d5bb376ddf.png)

**Comment by Hashira-Lars** [comment]
However i reproduce the error by entering a value equivalent to 1 year , 1 month & 1 week 

![image](https://user-images.githubusercontent.com/55869559/72233745-1ba83900-3604-11ea-9ff6-2130b3a5800e.png)

2020-01-13 12:47:25,271 - 4939 - hummingbot.client.hummingbot_application - ERROR - Unknown error while writing config. could not convert string to float: '31,556,952'
Traceback (most recent call last):
  File "/home/tony/hummingbot/hummingbot/client/command/config_command.py", line 394, in _config_single_key
    value = await self.prompt_single_variable(cv, requirement_overwrite=True)
  File "/home/tony/hummingbot/hummingbot/client/command/config_command.py", line 317, in prompt_single_variable
    val = await self.prompt_single_variable(cvar, requirement_overwrite)
  File "/home/tony/hummingbot/hummingbot/client/command/config_command.py", line 310, in prompt_single_variable
    if not cvar.validate(val):
  File "/home/tony/hummingbot/hummingbot/client/config/config_var.py", line 43, in validate
    valid = self._validator(value)
  File "/home/tony/hummingbot/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 66, in <lambda>
    validator=lambda input: float(input) >= 130.0),
ValueError: could not convert string to float: '31,556,952'

2020-01-13 12:50:06,366 - 4939 - hummingbot.client.hummingbot_application - ERROR - Unknown error while writing config. could not convert string to float: '2,629,746'
Traceback (most recent call last):
  File "/home/tony/hummingbot/hummingbot/client/command/config_command.py", line 394, in _config_single_key
    value = await self.prompt_single_variable(cv, requirement_overwrite=True)
  File "/home/tony/hummingbot/hummingbot/client/command/config_command.py", line 310, in prompt_single_variable
    if not cvar.validate(val):
  File "/home/tony/hummingbot/hummingbot/client/config/config_var.py", line 43, in validate
    valid = self._validator(value)
  File "/home/tony/hummingbot/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 66, in <lambda>
    validator=lambda input: float(input) >= 130.0),
ValueError: could not convert string to float: '2,629,746'

2020-01-13 12:52:26,957 - 4939 - hummingbot.client.hummingbot_application - ERROR - Unknown error while writing config. could not convert string to float: '604,800'
Traceback (most recent call last):
  File "/home/tony/hummingbot/hummingbot/client/command/config_command.py", line 394, in _config_single_key
    value = await self.prompt_single_variable(cv, requirement_overwrite=True)
  File "/home/tony/hummingbot/hummingbot/client/command/config_command.py", line 310, in prompt_single_variable
    if not cvar.validate(val):
  File "/home/tony/hummingbot/hummingbot/client/config/config_var.py", line 43, in validate
    valid = self._validator(value)
  File "/home/tony/hummingbot/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 66, in <lambda>
    validator=lambda input: float(input) >= 130.0),
ValueError: could not convert string to float: '604,800'

**Comment by chowryan** [comment]
https://github.com/CoinAlpha/hummingbot/pull/1307
