### ISSUE TITLE
[BUG] Intermittent index errors with pure market making

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#1317]
**Describe the bug**

Pure Market Making strategy intermittently throwing index error messages.
Errors persist after exiting and restarting the bot. It also stopped creating new orders.

So far we've only seen this error in Binance and not on other exchanges. Will update this post when we run into this on other connectors

```
2020-01-15 08:34:37,002 - 10 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 323, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 342, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_filter_orders_proposal_for_takers
IndexError: list index out of range
```
**Screenshots**

![pmm-index-error](https://user-images.githubusercontent.com/27669951/72420913-7b484500-37ba-11ea-8561-301321349cca.png)
![Screenshot from 2020-01-15 17-22-09](https://user-images.githubusercontent.com/27669951/72421518-9e272900-37bb-11ea-9437-c48cab4e7264.png)

**Release version**
***
                "branch": "master",
                "commit": "03aaa8d2000c48f988d94a873d7e65b4714a65b9",
                "date": "2020-01-13T20:02:43Z",

***

**Attachments**
[logs_conf_pmm_bnb-usdt.log](https://github.com/CoinAlpha/hummingbot/files/4064035/logs_conf_pmm_bnb-usdt.log)

**Comment by Nullably** [comment]
I have submitted a PR to fix this.

**Comment by znerol19619** [comment]
Error is Confirmed fix. Haven't got any error on my bot running for 2 days.

I will now close this issue. 

**Release Version**

***
                "branch": "development",
                "commit": "2cd17177ea7cb71e31173c7aebd4b6e24867af86",
                "date": "2020-01-17T02:37:48Z",

***
