### ISSUE TITLE
[BUG] Hummingbot's balance doesn't match with Bittrex

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#1322]
**Describe the bug**
There are cases where Hummingbot cannot create orders because of INSUFFICIENT_FUNDS error. I have confirmed that I have enough balance in my wallet to create orders. I notice that the balance showing in Hummingbot does not match the actual balance in the exchange.

**Screenshots**
![btrrx-hb-bal](https://user-images.githubusercontent.com/27669951/72515269-971b1c00-388a-11ea-9e48-2978819385d2.png)
![btrrx-bal](https://user-images.githubusercontent.com/27669951/72515274-98e4df80-388a-11ea-8360-c389b24ebcac.png)

**Error**
```
2020-01-15 12:12:23,552 - 10 - hummingbot.market.bittrex.bittrex_market - NETWORK - Error submitting buy LIMIT order to Bittrex for 5.21814510 XZC-BTC 0.00063389.
Traceback (most recent call last):
  File "bittrex_market.pyx", line 779, in hummingbot.market.bittrex.bittrex_market.BittrexMarket.execute_buy
  File "bittrex_market.pyx", line 739, in place_order
  File "bittrex_market.pyx", line 1034, in _api_request
  File "bittrex_market.pyx", line 1042, in hummingbot.market.bittrex.bittrex_market.BittrexMarket._api_request
OSError: Error fetching response from POST-https://api.bittrex.com/v3/orders. HTTP Status Code 409: {'code': 'INSUFFICIENT_FUNDS'}
```

**Release version**
```
                "branch": "development",
                "commit": "b90b47fe923d0a02b08adab44df39ba27b97ce5a",
                "date": "2020-01-14T20:18:49Z",

```

**Attachments**
[logs_pmm_btx_xzc-btc.log](https://github.com/CoinAlpha/hummingbot/files/4070521/logs_pmm_btx_xzc-btc.log)
[pmm_btx_xzc-btc.txt](https://github.com/CoinAlpha/hummingbot/files/4070530/pmm_btx_xzc-btc.txt)

**Comment by dennisocana** [comment]
This is resolved in version 0.26.0

![image](https://user-images.githubusercontent.com/50150287/80559717-11724500-8a11-11ea-8c39-50f8cf945f62.png) 
![image](https://user-images.githubusercontent.com/50150287/80559748-264ed880-8a11-11ea-8749-8f03ddee828d.png)
