### ISSUE TITLE
[BUG] Cannot start Hummingbot on KuCoin connector

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1339]
**Describe the bug**

Hummingbot won't start or initialize due to an error.

```
2020-01-23 03:15:22,098 - 10 - root - ERROR - Unhandled error in background task: Error fetching data from https://openapi-sandbox.kucoin.com/api/v1/accounts. HTTP status is 401.
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "network_iterator.pyx", line 107, in _check_network_loop
  File "kucoin_market.pyx", line 221, in start_network
  File "kucoin_market.pyx", line 296, in _update_account_id
  File "kucoin_market.pyx", line 288, in _api_request
OSError: Error fetching data from https://openapi-sandbox.kucoin.com/api/v1/accounts. HTTP status is 401.
```

I made sure I entered the correct API key, secret key and API passphrase. I also confirmed that my API has "General" and "Trade" permissions enabled.

<img width="947" alt="putty_D8nLyfeEKk" src="https://user-images.githubusercontent.com/50150287/72965419-36925e80-3df7-11ea-87a5-4d48bd05435a.png">

**Release version**

```
"branch": "development",
"commit": "8554c75cc7bf9ca984ec522b00d77b6cf774c028",
"date": "2020-01-23T00:28:23Z",
```

**Attachments**

[logs_pmm_kucoin_kcs-usdt.log](https://github.com/CoinAlpha/hummingbot/files/4101847/logs_pmm_kucoin_kcs-usdt.log)

**Comment by vic-en** [comment]
The issue is from line 64 of kucoin_market.pyx. It should be ` KUCOIN_ROOT_API = "https://api.kucoin.com" `

**Comment by dennisocana** [comment]
This specific issue is fixed on development branch. Strategy has started but new bug discovered https://github.com/CoinAlpha/hummingbot/issues/1349 when trying to create orders.
