### ISSUE TITLE
[BUG] Order stuck in Hummingbot but none in Bittrex

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#1340]
**Describe the bug**

Failed to cancel an order that was successfully created. Order stuck in Hummingbot client that is not showing in Bittrex.

**Error**
```
2020-01-23 02:57:23,470 - 10 - hummingbot.market.bittrex.bittrex_market - WARNING - Failed to cancel the order buy-XZC-BTC-1579689313002040 on Bittrex. Check API key and network connection.
2020-01-23 02:59:58,886 - 10 - hummingbot.market.bittrex.bittrex_market - NETWORK - Failed to cancel order buy-XZC-BTC-1579689313002040: Error fetching response from DELETE-https://api.bittrex.com/v3/orders/9af764c8-d67f-4ae3-b6ce-4d6153f21fa1. HTTP Status Code 400: {'code': 'INVALID_ORDER'}.
Traceback (most recent call last):
  File "bittrex_market.pyx", line 957, in hummingbot.market.bittrex.bittrex_market.BittrexMarket.execute_cancel
  File "bittrex_market.pyx", line 1034, in _api_request
  File "bittrex_market.pyx", line 1042, in hummingbot.market.bittrex.bittrex_market.BittrexMarket._api_request
OSError: Error fetching response from DELETE-https://api.bittrex.com/v3/orders/9af764c8-d67f-4ae3-b6ce-4d6153f21fa1. HTTP Status Code 400: {'code': 'INVALID_ORDER'}
```

**Screenshots**
<img width="619" alt="bittrex_open_orders" src="https://user-images.githubusercontent.com/27669951/72968370-495c6180-3dfe-11ea-8c84-f3b51099eec8.png">
<img width="947" alt="hummingbot_status" src="https://user-images.githubusercontent.com/27669951/72968372-4a8d8e80-3dfe-11ea-98cd-d3d89ade309b.png">

[logs_pmm_btx_xzc-btc.log](https://github.com/CoinAlpha/hummingbot/files/4102065/logs_pmm_btx_xzc-btc.log)

**Release version**
```
                "branch": "development",
                "commit": "8554c75cc7bf9ca984ec522b00d77b6cf774c028",
                "date": "2020-01-23T00:28:23Z",

```

**Attachments**
[logs_pmm_btx_xzc-btc.log](https://github.com/CoinAlpha/hummingbot/files/4102065/logs_pmm_btx_xzc-btc.log)
[pmm_btx_xzc-btc.txt](https://github.com/CoinAlpha/hummingbot/files/4102066/pmm_btx_xzc-btc.txt)

**Comment by dennisocana** [comment]
Ran into this same bug but getting an HTTP status code 409 instead of code 400.

[logs_pmm_btx_xzc-btc.log](https://github.com/CoinAlpha/hummingbot/files/4284806/logs_pmm_btx_xzc-btc.log)

```
2020-03-03 07:09:48,334 - 10 - hummingbot.market.bittrex.bittrex_market - NETWORK - Failed to cancel order sell-XZC-BTC-1583219328002866: Error fetching response from DELETE-https://api.bittrex.com/v3/orders/a9ff7a2c-7265-4b06-8874-4cb6621c7a4b. HTTP Status Code 409: {'code': 'ORDER_NOT_OPEN'}.
Traceback (most recent call last):
  File "bittrex_market.pyx", line 962, in hummingbot.market.bittrex.bittrex_market.BittrexMarket.execute_cancel
  File "bittrex_market.pyx", line 1039, in _api_request
  File "bittrex_market.pyx", line 1047, in hummingbot.market.bittrex.bittrex_market.BittrexMarket._api_request
OSError: Error fetching response from DELETE-https://api.bittrex.com/v3/orders/a9ff7a2c-7265-4b06-8874-4cb6621c7a4b. HTTP Status Code 409: {'code': 'ORDER_NOT_OPEN'}
2020-03-03 07:09:48,335 - 10 - hummingbot.market.bittrex.bittrex_market - WARNING - Failed to cancel the order sell-XZC-BTC-1583219328002866 on Bittrex. Check API key and network connection.
```

The order is stuck in the HB client and cannot be cancelled because it doesn't exist in the exchange.

<img width="947" alt="putty_EEMvSTgFr1" src="https://user-images.githubusercontent.com/50150287/75840423-21511c80-5e06-11ea-9baa-099039f64bd0.png"> <img width="225" alt="putty_2V6MmSoovs" src="https://user-images.githubusercontent.com/50150287/75840431-24e4a380-5e06-11ea-81bc-e010ada4e5d0.png"> <img width="613" alt="chrome_Hs2kB6nefc" src="https://user-images.githubusercontent.com/50150287/75840434-2615d080-5e06-11ea-94d0-5252b631046f.png">

**Comment by Pascal66** [comment]
Same for me all the night 
![image](https://user-images.githubusercontent.com/3041616/81528654-7f960080-935d-11ea-8a08-dadd32a7ba41.png)

**Comment by PtrckM** [comment]
- a user experience as well that an order got filled on hummingbot but none on bittrex, appears also on his bot `history` but none on bittrex

- users conf and logs
[logs_cgld_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/4672174/logs_cgld_pure_mm_1.log)
[cgld_pure_mm_1.txt](https://github.com/CoinAlpha/hummingbot/files/4672175/cgld_pure_mm_1.txt)

**Comment by dennisocana** [comment]
Haven't ran into this same error for a month, closing this PR for now. Linked PR has additional debugging message in logs in case this happens again in the future.
