### ISSUE TITLE
[BUG] Cannot create orders on KuCoin

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1349]
**Describe the bug**

No orders are created in KuCoin connector and getting these errors.

<img width="947" alt="putty_B2whAsgKew" src="https://user-images.githubusercontent.com/50150287/73115778-b9d1c280-3f65-11ea-90ac-456c696d4fdc.png">

```
2020-01-25 03:21:41,001 - 16468 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Unknown error while generating order proposals.
Traceback (most recent call last):
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 311, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
    orders_proposal = self.c_get_orders_proposal_for_market_info(
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 566, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_get_orders_proposal_for_market_info
    sizing_proposal = self._sizing_delegate.c_get_order_size_proposal(self,
  File "hummingbot/strategy/pure_market_making/constant_size_sizing_delegate.pyx", line 84, in hummingbot.strategy.pure_market_making.constant_size_sizing_delegate.ConstantSizeSizingDelegate.c_get_order_size_proposal
    required_quote_asset_balance = pricing_proposal.buy_order_prices[0] * (1 + buy_fees.percent) * quantized_bid_order_size
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

2020-01-25 03:21:41,001 - 16468 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 319, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
    filtered_proposal = self._filter_delegate.c_filter_orders_proposal(self,
  File "hummingbot/strategy/pure_market_making/pass_through_filter_delegate.pyx", line 22, in hummingbot.strategy.pure_market_making.pass_through_filter_delegate.PassThroughFilterDelegate.c_filter_orders_proposal
    int64_t actions = orders_proposal.actions
AttributeError: 'NoneType' object has no attribute 'actions'
```

**Steps To Reproduce**

Run a pure market making strategy on KuCoin connector with all the default values on basic configuration mode.

**Release version**

Environment: AWS Linux cloud server
Operating system: Ubuntu 18.04 LTS
Version: dev-0.23.0 pulled latest commit

```
(base) ubuntu@ip-172-31-5-146:~/hummingbot$ git pull origin development
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 2), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/CoinAlpha/hummingbot
 * branch              development -> FETCH_HEAD
   8554c75c..6d9f2a24  development -> origin/development
Updating 8554c75c..6d9f2a24
Fast-forward
 hummingbot/market/kucoin/kucoin_market.pyx | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Attachments**

[logs_conf_pure_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4111592/logs_conf_pure_market_making_strategy_0.log)

**Comment by Nullably** [comment]
I have suggested a solution to vic-en as he's already been looking into this. Basically, the return value from `c_get_fee` of the kucoin connector needs to be `Decimal`.

**Comment by dennisocana** [comment]
Confirmed fix by https://github.com/CoinAlpha/hummingbot/pull/1374
