### ISSUE TITLE
[BUG] exchange.bitcoin.com XZC/BCH not running anymore - ERROR - Unexpected error running clock tick.

### ISSUE THREAD

**Issue by sweetpotatoz** [CoinAlpha/hummingbot#1351]
**Describe the bug**
// A clear and concise description of what the bug is.

The same bot with the same version was running ok.
But recently, the bot is running, but it cannot place any orders.

```
2020-01-26 01:51:34,002 - 10 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 323, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 348, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_filter_orders_proposal_for_takers
IndexError: list index out of range
2020-01-26 01:51:35,004 - 10 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 323, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 348, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_filter_orders_proposal_for_takers
IndexError: list index out of range
2020-01-26 01:51:36,003 - 10 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 323, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 348, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_filter_orders_proposal_for_takers
IndexError: list index out of range
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

[xzcbch.txt](https://github.com/CoinAlpha/hummingbot/files/4113094/xzcbch.txt)

**Screenshots**
// If applicable, add screenshots to help explain your problem.
stop, exit the bot then start again.  same error

![image](https://user-images.githubusercontent.com/1692346/73129568-417d0700-4022-11ea-9b66-9b10e42b7f1d.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.22.0 

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by dennisocana** [comment]
This is the same as https://github.com/CoinAlpha/hummingbot/issues/1317 which is fixed in the development branch.

**Comment by PtrckM** [comment]
confirmed fix on development, tested on paper trade

![image](https://user-images.githubusercontent.com/54516858/73132450-4a87cb80-4056-11ea-9a73-e7b8a252c9d4.png)

```
                "branch": "development",
                "commit": "6b0909012ced929f0c5d94159a546e275ec88fc3",
                "date": "2020-01-26T05:22:37Z",
```
