### ISSUE TITLE
[BUG]PMM Exchange Price Feed Error

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1423]
**Describe the bug**
Bot running pure_market_making strategy on DEX market failed to start due to unable to get price feed from CEX market. Same result if market making on CEX and using DEX as price feed.

```
2020-02-15 07:07:44,897 - 13376 - hummingbot.market.kucoin.kucoin_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "hummingbot\market\kucoin\kucoin_api_order_book_data_source.py", line 280, in listen_for_order_book_snapshots
  File "hummingbot\market\kucoin\kucoin_order_book.pyx", line 41, in hummingbot.market.kucoin.kucoin_order_book.KucoinOrderBook.snapshot_message_from_exchange
KeyError: 'data'
```
```
2020-02-15 07:16:39,885 - 16580 - hummingbot.market.huobi.huobi_api_order_book_data_source - ERROR - Error getting snapshot for zrxweth. 
Traceback (most recent call last):
  File "hummingbot\market\huobi\huobi_api_order_book_data_source.py", line 137, in get_tracking_pairs
  File "hummingbot\market\huobi\huobi_order_book.pyx", line 42, in hummingbot.market.huobi.huobi_order_book.HuobiOrderBook.snapshot_message_from_exchange
KeyError: 'tick'
```

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Establish a bot using Pure_market_making_strategy
2. Use a DEX market (Bamboo_Relay)
3. Used the default parameter for other parameters
4. Enable the use of external price feed
6. Select Exchange and use a CEX market (KuCoin)
7. Start bot

Note: if CEX is used as a market, external price exchange should be DEX
...
**Screenshots**
![SNX-WETH bamboo - price feed KuCoin](https://user-images.githubusercontent.com/57189990/74576524-1d2f9d00-4fc6-11ea-8a9f-5b30a1e617b1.PNG)

**Release version**
Master (0.23.0) and Development branch  (0.24.0)
Tested on: Windows Binary installer and Docker (Linux)

**Attachments**
[PMM_config.txt](https://github.com/CoinAlpha/hummingbot/files/4207400/PMM_config.txt)
[logs_conf_pure_market_making_strategy_3.log](https://github.com/CoinAlpha/hummingbot/files/4207401/logs_conf_pure_market_making_strategy_3.log)
[PMM_config.txt](https://github.com/CoinAlpha/hummingbot/files/4207411/PMM_config.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Clint-G13** [comment]
@Nullably , Sir can you check this as well, thanks.

**Comment by Hashira-Lars** [comment]
Tested using the same configs & tried with other token pair have reproduce the error causing the bot to fail to start. 

SNX-WETH / Bamboo-Relay / External_pricing = Exchange (kucoin)
![image](https://user-images.githubusercontent.com/55869559/74586179-10d82e00-5020-11ea-90cd-2c61d069e3a7.png)

```
Traceback (most recent call last):
  File "/home/tony/hummingbot/hummingbot/market/kucoin/kucoin_api_order_book_data_source.py", line 148, in get_tracking_pairs
    metadata={"symbol": trading_pair}
  File "hummingbot/market/kucoin/kucoin_order_book.pyx", line 41, in hummingbot.market.kucoin.kucoin_order_book.KucoinOrderBook.snapshot_message_from_exchange
    "update_id": int(msg["data"]["sequence"]),
KeyError: 'data'
2020-02-15 18:10:53,596 - 615 - hummingbot.market.kucoin.kucoin_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/home/tony/hummingbot/hummingbot/market/kucoin/kucoin_api_order_book_data_source.py", line 280, in listen_for_order_book_snapshots
    metadata={"symbol": trading_pair}
  File "hummingbot/market/kucoin/kucoin_order_book.pyx", line 41, in hummingbot.market.kucoin.kucoin_order_book.KucoinOrderBook.snapshot_message_from_exchange
    "update_id": int(msg["data"]["sequence"]),
KeyError: 'data'
```

ZRX-WETH / Bamboo-Relay / External_pricing = Exchange (kucoin)
![image](https://user-images.githubusercontent.com/55869559/74586200-3ebd7280-5020-11ea-91cc-bba1b180b2c0.png)

```
2020-02-15 18:20:03,557 - 1466 - hummingbot.market.kucoin.kucoin_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/home/tony/hummingbot/hummingbot/market/kucoin/kucoin_api_order_book_data_source.py", line 280, in listen_for_order_book_snapshots
    metadata={"symbol": trading_pair}
  File "hummingbot/market/kucoin/kucoin_order_book.pyx", line 41, in hummingbot.market.kucoin.kucoin_order_book.KucoinOrderBook.snapshot_message_from_exchange
    "update_id": int(msg["data"]["sequence"]),
KeyError: 'data'
2020-02-15 18:20:03,591 - 1466 - hummingbot.market.kucoin.kucoin_api_order_book_data_source - ERROR - Error getting snapshot for ZRX-WETH.
Traceback (most recent call last):
  File "/home/tony/hummingbot/hummingbot/market/kucoin/kucoin_api_order_book_data_source.py", line 148, in get_tracking_pairs
    metadata={"symbol": trading_pair}
  File "hummingbot/market/kucoin/kucoin_order_book.pyx", line 41, in hummingbot.market.kucoin.kucoin_order_book.KucoinOrderBook.snapshot_message_from_exchange
    "update_id": int(msg["data"]["sequence"]),
KeyError: 'data'
```

**Comment by Clint-G13** [comment]
Retest using different token pair and confirmed fix.
![Price feed new1](https://user-images.githubusercontent.com/57189990/75488567-8e6e4780-59eb-11ea-8462-a6396d2b6be2.PNG)
![Price feed new](https://user-images.githubusercontent.com/57189990/75488573-91693800-59eb-11ea-9e92-132b57d493df.PNG)
