### ISSUE TITLE
[BUG] Bittrex websocket connection time-outs

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1426]
**Describe the bug**

Intermittently getting errors in Bittrex that sometimes lasts to almost 1 day duration. This stops the bot from behaving normally as expected.

```
2020-02-12 20:00:17,554 - 10 - hummingbot.market.bittrex.bittrex_api_order_book_data_source - WARNING - Message recv() timed out. Going to reconnect...
2020-02-12 20:00:17,555 - 10 - hummingbot.market.bittrex.bittrex_api_order_book_data_source - INFO - Reinitializing websocket connection...
2020-02-12 20:00:17,555 - 10 - hummingbot.market.bittrex.bittrex_api_order_book_data_source - INFO - Subscribed to BTC-XZC deltas
2020-02-12 20:00:17,555 - 10 - hummingbot.market.bittrex.bittrex_api_order_book_data_source - INFO - Query BTC-XZC snapshot.
2020-02-12 20:00:34,507 - 10 - hummingbot.market.bittrex.bittrex_api_user_stream_data_source - WARNING - Message recv() timed out. Reconnecting to Bittrex SignalR WebSocket... 
2020-02-12 20:00:34,508 - 10 - hummingbot.market.bittrex.bittrex_api_user_stream_data_source - INFO - Invoked GetAuthContext
```

```
2020-02-13 06:50:45,933 - 10 - hummingbot.market.bittrex.bittrex_market - NETWORK - Unexpected error while polling updates.
Traceback (most recent call last):
  File "bittrex_market.pyx", line 610, in hummingbot.market.bittrex.bittrex_market.BittrexMarket._status_polling_loop
  File "/hummingbot/core/utils/async_utils.py", line 19, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "bittrex_market.pyx", line 208, in _update_balances
  File "bittrex_market.pyx", line 1039, in _api_request
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
2020-02-13 06:50:45,953 - 10 - hummingbot.market.bittrex.bittrex_market - WARNING - Could not fetch updates from Bittrex. Check API key and network connection.
```

**Steps To Reproduce**

Run a normal pure market making bot.

**Release version**

dev-0.24.0

```
"branch": "development",
"commit": "ac812edb117f260d48828fcc3daacfd54cf04d84",
"date": "2020-02-12T01:30:21Z",
```

Haven't tried if this also happens in master branch as I am using this bot for another test case.

**Attachments**

[bittrex_websocket.log](https://github.com/CoinAlpha/hummingbot/files/4210161/bittrex_websocket.log)
[conf_bittrex_websocket.txt](https://github.com/CoinAlpha/hummingbot/files/4210164/conf_bittrex_websocket.txt)

**Comment by finer9** [comment]
@mifeng thank you for prioritizing this bug, it is affecting me almost daily.

**Comment by dennisocana** [comment]
Haven't ran into this same error for a month, closing this PR for now. Linked PR has additional debugging message in logs in case this happens again in the future.
