### ISSUE TITLE
[BUG] Binance Invalid API-key, IP, or permissions for action

### ISSUE THREAD

**Issue by sweetpotatoz** [CoinAlpha/hummingbot#1431]
**Describe the bug**
// A clear and concise description of what the bug is.

we were using the same api key, same ip address.  it was able to run smoothly previously.
not sure why we have withdraw exception, as the bot should not perform any withdrawal exchange

```
2020-02-18 05:47:58,759 - 10 - hummingbot.market.binance.binance_market - NETWORK - Unexpected error while fetching trading rules.
Traceback (most recent call last):
  File "binance_market.pyx", line 753, in hummingbot.market.binance.binance_market.BinanceMarket._trading_rules_polling_loop
  File "/hummingbot/core/utils/async_utils.py", line 19, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "binance_market.pyx", line 330, in _update_trade_fees
  File "binance_market.pyx", line 320, in hummingbot.market.binance.binance_market.BinanceMarket._update_trade_fees
  File "binance_market.pyx", line 278, in query_api
  File "/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/opt/conda/envs/hummingbot/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 1795, in get_trade_fee
    raise BinanceWithdrawException(res['msg'])
binance.exceptions.BinanceWithdrawException: BinanceWithdrawException: Invalid API-key, IP, or permissions for action.
2020-02-18 05:47:58,759 - 10 - hummingbot.market.binance.binance_market - WARNING - Could not fetch new trading rules from Binance. Check network connection.
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
version 0.23.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
Log Files
[xzcbnb.tar.gz](https://github.com/CoinAlpha/hummingbot/files/4218512/xzcbnb.tar.gz)

Strategy File (rename to .yml)
[xzcbnb.txt](https://github.com/CoinAlpha/hummingbot/files/4218515/xzcbnb.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by rennel-tabing** [comment]
This issue could be related to https://github.com/freqtrade/freqtrade/issues/2480

**Comment by dennisocana** [comment]
Possible causes of this error are restricted IP, incorrect API key, and trading permissions. Please make sure to check the following:

1. External IP address of your VPS instance matches the trusted IPs of your API key
2. You have entered the correct API key in Hummingbot
3. Set the correct trading permissions (read-only, enable trading)
