### ISSUE TITLE
[BUG] Cannot create orders on DEXs with Windows binary version

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1505]
**Describe the bug**
Unable to place order using Bamboo_relay or Radar_relay on Windows Binary 0.24.0 and 0.24.1

**Steps To Reproduce**

Create/import a conf strategy (pmm or xemm)
Select decentralized exchanges (Bamboo Relay or Radar Relay)
select token pair
select default configurations
Start the bot
...

**Screenshots**
Using PMM on bamboo_relay
![image](https://user-images.githubusercontent.com/54516858/76175733-e0338080-61e8-11ea-9dad-656c020b246b.png)
![image](https://user-images.githubusercontent.com/54516858/76175738-e32e7100-61e8-11ea-9304-b7cf4c6cde9c.png)
Using XEMM on bamboo_relay
![image](https://user-images.githubusercontent.com/54516858/76175742-e9245200-61e8-11ea-906c-03dc56a6556a.png)
![image](https://user-images.githubusercontent.com/54516858/76175748-ed506f80-61e8-11ea-8b86-3e1ef881256c.png)
Using PMM on radar_relay
![image](https://user-images.githubusercontent.com/54516858/76176238-cdba4680-61ea-11ea-9649-43ff0013bc30.png)
![image](https://user-images.githubusercontent.com/54516858/76176132-761bdb00-61ea-11ea-88f9-ed3bf35cc182.png)

**Release version**
Windows Binary both **0.24.0** and **0.24.1**

**Attachments**

Strategy Config
[pmm_br_weth-usdc.txt](https://github.com/CoinAlpha/hummingbot/files/4304255/pmm_br_weth-usdc.txt)
[xemm_br-bn_weth-usdc.txt](https://github.com/CoinAlpha/hummingbot/files/4304256/xemm_br-bn_weth-usdc.txt)

Logs
[logs_xemm_br-bn_weth-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4304261/logs_xemm_br-bn_weth-usdc.log)
[logs_pmm_br_weth-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4304262/logs_pmm_br_weth-usdc.log)
[logs_pmm_rr_weth-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4304302/logs_pmm_rr_weth-usdc.log)

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 1405, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.execute_trade
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 1230, in submit_limit_order
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 975, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.get_zero_ex_signature
  File "hummingbot\wallet\ethereum\zero_ex\zero_ex_custom_utils_v3.py", line 278, in fix_signature
  File "hummingbot\wallet\ethereum\zero_ex\zero_ex_custom_utils_v3.py", line 204, in is_valid_signature
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 137, in chain_to_addresses
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 123, in chain_to_addresses
  File "site-packages\pkg_resources\__init__.py", line 1157, in resource_string
  File "site-packages\pkg_resources\__init__.py", line 1401, in get_resource_string
  File "site-packages\pkg_resources\__init__.py", line 1560, in _get
  File "c:\users\yzhang1994\anaconda3\envs\hummingbot\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 475, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Hummingbot\\zero_ex\\contract_addresses\\addresses.json'
2020-03-09 09:18:42,303 - 348 - hummingbot.market.bamboo_relay.bamboo_relay_market - WARNING - Failed to submit limit buy order to Bamboo Relay. Check Ethereum wallet and network connection.
2020-03-09 09:18:42,312 - 348 - hummingbot.market.bamboo_relay.bamboo_relay_market - NETWORK - Error submitting limit sell order to Bamboo Relay for 0.035998939 WETH-USDC.
Traceback (most recent call last):
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 120, in chain_to_addresses
KeyError: '1'
```

**Workaround:**
Use docker build or source build (master/dev)
![image](https://user-images.githubusercontent.com/54516858/76175776-17a22d00-61e9-11ea-8336-8afc6746d654.png)
![image](https://user-images.githubusercontent.com/54516858/76175784-1d980e00-61e9-11ea-8765-b88f28597eef.png)

**Comment by znerol19619** [comment]
I tried running XEMM and PMM using radar relay, and got a different behavior instead.  I'm using latest development release.

Orders that are created in hummingbot client are not reflecting on Radar Relay

**XEMM - Radar Relay / Coinbase Pro**
![Screenshot from 2020-03-10 18-14-30](https://user-images.githubusercontent.com/27669951/76304936-3266c580-62ff-11ea-835f-b696888ded5b.png)
![Screenshot from 2020-03-10 18-14-21](https://user-images.githubusercontent.com/27669951/76304951-3abf0080-62ff-11ea-8b20-bf3345beca06.png)

**Error in XEMM**
I get this error in logs, it seems that this occur when bot is trying to cancel orders that aren't existing in radar relay. 

```
2020-03-10 10:15:50,727 - 10 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: ('Web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).', '0xa258b39954cef5cb142fd567a46cddb31a670124')
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 7, in safe_wrapper
    return await c
  File "radar_relay_market.pyx", line 877, in cancel_order
  File "/hummingbot/wallet/ethereum/zero_ex/zero_ex_exchange_v3.py", line 118, in cancel_order
    tx_hash: str = self._wallet.execute_transaction(self._contract.functions.cancelOrder(order_tuple))
  File "web3_wallet.pyx", line 173, in hummingbot.wallet.ethereum.web3_wallet.Web3Wallet.execute_transaction
  File "/hummingbot/wallet/ethereum/web3_wallet_backend.py", line 503, in execute_transaction
    transaction: Dict[str, Any] = contract_function.buildTransaction(transaction_args)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/web3/contract.py", line 1018, in buildTransaction
    return build_transaction_for_function(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/web3/contract.py", line 1573, in build_transaction_for_function
    prepared_transaction = prepare_transaction(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/contracts.py", line 226, in prepare_transaction
    prepared_transaction['data'] = encode_transaction_data(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/contracts.py", line 255, in encode_transaction_data
    return add_0x_prefix(encode_abi(web3, fn_abi, fn_arguments, fn_selector))
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/contracts.py", line 178, in encode_abi
    normalized_arguments = map_abi_data(
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/abi.py", line 788, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 669, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 644, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/abi.py", line 822, in data_tree_map
```
**PMM - Radar Relay**
![Screenshot from 2020-03-10 18-40-58](https://user-images.githubusercontent.com/27669951/76305233-bb7dfc80-62ff-11ea-90aa-0f9df8e3bc15.png)
![Screenshot from 2020-03-10 18-34-52](https://user-images.githubusercontent.com/27669951/76305220-b4ef8500-62ff-11ea-9699-ec26250b6f25.png)

**Error in PMM**
```
2020-03-10 10:41:39,251 - 10 - hummingbot.wallet.ethereum.watcher.new_blocks_watcher - NETWORK - Timed out fetching new block.
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/wallet/ethereum/watcher/new_blocks_watcher.py", line 110, in fetch_new_blocks_loop
    incoming_block: AttributeDict = await self.call_async(
  File "/hummingbot/wallet/ethereum/watcher/base_watcher.py", line 26, in call_async
    return await AsyncCallScheduler.shared_instance().call_async(func, *args, **kwargs)
  File "/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
```

**Attached files**
[logs_conf_cross_exchange_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4311891/logs_conf_cross_exchange_market_making_strategy_0.log)
[logs_conf_pure_market_making_strategy_2.log](https://github.com/CoinAlpha/hummingbot/files/4311892/logs_conf_pure_market_making_strategy_2.log)

**Comment by PtrckM** [comment]
Problem still persist on 0.25.0

**Comment by PtrckM** [comment]
Problem still persist on 0.26.0

**Comment by rennel-tabing** [comment]
Same error reported by use: Lumpy on his Mac machine on version 0.26.0 on Bamboo relay and Bittrex
![image](https://user-images.githubusercontent.com/53868268/81822625-5d3ce800-9501-11ea-8a1f-3b3c2b2cd70d.png)

I

**Comment by PtrckM** [comment]
on version 0.28.1
![image](https://user-images.githubusercontent.com/54516858/86528033-fd4a3880-bed6-11ea-871a-49a7d6289212.png)

```
2020-07-05 15:40:58,295 - 6400 - hummingbot.market.radar_relay.radar_relay_market - WARNING - Failed to submit buy order to Radar Relay. Check Ethereum wallet and network connection.
2020-07-05 15:41:16,692 - 6400 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2020-07-05 15:43:36,462 - 10892 - hummingbot.notifier.telegram_notifier - INFO - Telegram is listening...
2020-07-05 15:43:37,235 - 10892 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2020-07-05 15:43:50,622 - 10892 - hummingbot.wallet.ethereum.web3_wallet - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-07-05 15:43:58,466 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_market - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-07-05 15:43:58,871 - 10892 - hummingbot.wallet.ethereum.web3_wallet_backend - INFO - Approval already exists for Dai Stablecoin from wallet address 0xD7940bddEbb5697ffD8b3BD7296c2832C295E132.
2020-07-05 15:43:58,872 - 10892 - hummingbot.wallet.ethereum.web3_wallet_backend - INFO - Approval already exists for Wrapped Ether from wallet address 0xD7940bddEbb5697ffD8b3BD7296c2832C295E132.
2020-07-05 15:43:59,426 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_api_order_book_data_source - INFO - Bamboo Relay API MOTD: Welcome to the Bamboo Relay REST API.
2020-07-05 15:43:59,426 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_api_order_book_data_source - INFO - Announcement: Tip: Market makers should set up a 0x Staking Pool to collect Protocol Fees to maximize your returns. See https://0x.org/docs/guides/zrx-portal-faq for details.
2020-07-05 15:43:59,595 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_api_order_book_data_source - INFO - Initialized order book for WETH-DAI. 1/1 completed.
2020-07-05 15:44:00,499 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_order_book_tracker - INFO - Started order book tracking for WETH-DAI.
2020-07-05 15:44:02,003 - 10892 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (WETH-DAI) Creating 1 bid orders at (Size, Price): ['0.005 WETH, 222.86419 DAI']
2020-07-05 15:44:02,005 - 10892 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (WETH-DAI) Creating 1 ask orders at (Size, Price): ['0.005 WETH, 226.00628 DAI']
2020-07-05 15:44:02,022 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_market - NETWORK - Error submitting limit buy order to Bamboo Relay for 0.0050000000 WETH-DAI.
Traceback (most recent call last):
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 120, in chain_to_addresses
KeyError: '1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 1416, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.execute_trade
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 1241, in submit_limit_order
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 981, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.get_zero_ex_signature
  File "hummingbot\wallet\ethereum\zero_ex\zero_ex_custom_utils_v3.py", line 277, in fix_signature
  File "hummingbot\wallet\ethereum\zero_ex\zero_ex_custom_utils_v3.py", line 202, in is_valid_signature
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 137, in chain_to_addresses
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 123, in chain_to_addresses
  File "site-packages\pkg_resources\__init__.py", line 1157, in resource_string
  File "site-packages\pkg_resources\__init__.py", line 1402, in get_resource_string
  File "site-packages\pkg_resources\__init__.py", line 1570, in _get
  File "c:\users\martin_kou\anaconda3\envs\hummingbot\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 471, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Hummingbot\\zero_ex\\contract_addresses\\addresses.json'
2020-07-05 15:44:02,026 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_market - WARNING - Failed to submit limit buy order to Bamboo Relay. Check Ethereum wallet and network connection.
2020-07-05 15:44:02,041 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_market - NETWORK - Error submitting limit sell order to Bamboo Relay for 0.0050000000 WETH-DAI.
Traceback (most recent call last):
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 120, in chain_to_addresses
KeyError: '1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 1416, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.execute_trade
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 1241, in submit_limit_order
  File "hummingbot\market\bamboo_relay\bamboo_relay_market.pyx", line 981, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.get_zero_ex_signature
  File "hummingbot\wallet\ethereum\zero_ex\zero_ex_custom_utils_v3.py", line 277, in fix_signature
  File "hummingbot\wallet\ethereum\zero_ex\zero_ex_custom_utils_v3.py", line 202, in is_valid_signature
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 137, in chain_to_addresses
  File "site-packages\zero_ex\contract_addresses\__init__.py", line 123, in chain_to_addresses
  File "site-packages\pkg_resources\__init__.py", line 1157, in resource_string
  File "site-packages\pkg_resources\__init__.py", line 1402, in get_resource_string
  File "site-packages\pkg_resources\__init__.py", line 1570, in _get
  File "c:\users\martin_kou\anaconda3\envs\hummingbot\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 471, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Hummingbot\\zero_ex\\contract_addresses\\addresses.json'
2020-07-05 15:44:02,045 - 10892 - hummingbot.market.bamboo_relay.bamboo_relay_market - WARNING - Failed to submit limit sell order to Bamboo Relay. Check Ethereum wallet and network connection.
```

**Comment by dennisocana** [comment]
Closing w.r.t. issue 2050
