### ISSUE TITLE
[BUG] Discovery / Kucoin Unable to Show Profitability

### ISSUE THREAD

**Issue by Hashira-Lars** [CoinAlpha/hummingbot#1506]
**Describe the bug**
 Any Exchange pair with Kucoin will fail to show profitability running Discovery Strategy.

**Steps To Reproduce**
1. Create discovery strategy
2. select either primary or secondary market Exchange "Kucoin"
3. finish config walk through default all
4. run and wait to finish
5. fail to show profitability / Flooded Message with " Waiting to fetch trading pair"

**Screenshots**
![image](https://user-images.githubusercontent.com/55869559/76182533-2ea04980-6200-11ea-8551-38b61b8aa60a.png)

**Release version**
0.24.1 / 0.25.0

**Attachments**
[logs_conf_discovery_strategy_4.log](https://github.com/CoinAlpha/hummingbot/files/4304630/logs_conf_discovery_strategy_4.log)

Sample Error

```
2020-03-09 11:09:04,588 - 5548 - hummingbot.strategy.discovery.discovery - NETWORK - Could not fetch market info for DiscoveryMarketPair(kucoin, binance)
Traceback (most recent call last):
  File "hummingbot\core\utils\__init__.py", line 13, in memoize
  File "site-packages\cachetools\ttl.py", line 191, in pop
  File "site-packages\cachetools\abc.py", line 39, in pop
KeyError: "((<class 'hummingbot.market.kucoin.kucoin_api_order_book_data_source.KucoinAPIOrderBookDataSource'>,), {})"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'symbol'
```

**Optional: your discord username:** Lars l Support
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by vic-en** [comment]
https://github.com/CoinAlpha/hummingbot/pull/1554

**Comment by Hashira-Lars** [comment]
I'm testing this out on latest dev image source/wsl/local will update findings later.

**Comment by Hashira-Lars** [comment]
- Kucoin-binance = ok
- Kucoin-bittrex = failing on bittrex side (Snapshot query timeout --retrying=loop)
- Kucoin-huobi = ok
- Kucoin-liquid = ok
- Kucoin-bamboo = ok (paper-trade = on / issue with wallet) github issue #1504
- Kucoin-radar = ok (paper-trade = on / issue with wallet) github issue #1504
- Kucoin-coinbase = ok
- Kucoin-dolomite = skip
- Kucoin-bitcoin = skip

Confirm Fix - closing github issue
