### ISSUE TITLE
[BUG] Bittrex connector not working

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1534]
**Describe the bug**

Bittrex market fails to initialize.

<img width="947" alt="putty_2Pc1D5rg1Q" src="https://user-images.githubusercontent.com/50150287/76852962-686bf280-6887-11ea-87e3-134d2add9086.png">
<img width="947" alt="putty_UxMnMVJRSX" src="https://user-images.githubusercontent.com/50150287/76852992-73268780-6887-11ea-9e46-a07ae9685d61.png">

Unit tests also not working - stuck with a blinking cursor. And below are the results when running command `python test_bittrex_market.py`.

```
INFO:hummingbot.market.bittrex.bittrex_market:Network status has changed to NetworkStatus.CONNECTED. Starting networking...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Subscribed to USDT-ETH deltas
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot.
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433241]. 1/20
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshots.[Scheduled]
INFO:hummingbot.market.bittrex.bittrex_api_user_stream_data_source:Invoked GetAuthContext
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433252]. 2/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433262]. 3/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433273]. 4/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433283]. 5/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433294]. 6/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433304]. 7/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433315]. 8/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433325]. 9/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433336]. 10/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433346]. 11/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433357]. 12/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433367]. 13/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433378]. 14/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433388]. 15/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433399]. 16/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433409]. 17/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433420]. 18/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433430]. 19/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
INFO:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Query USDT-ETH snapshot[1584433441]. 20/20
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Snapshot query timed out. Retrying...
/home/dennis/miniconda3/envs/hummingbot/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/home/dennis/miniconda3/envs/hummingbot/lib/python3.6/site-packages/dateparser/utils/strptime.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/dennis/miniconda3/envs/hummingbot/lib/python3.6/site-packages/dateparser/utils/strptime.py:26: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/dennis/miniconda3/envs/hummingbot/lib/python3.6/_strptime.py' mode='r' encoding='utf-8'>
  'strptime_patched', *imp.find_module('_strptime')
/home/dennis/miniconda3/envs/hummingbot/lib/python3.6/site-packages/dateparser/utils/strptime.py:30: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/dennis/miniconda3/envs/hummingbot/lib/python3.6/_strptime.py' mode='r' encoding='utf-8'>
  'calendar_patched', *imp.find_module('_strptime')
NETWORK:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Max retries met fetching snapshot for ETH-USDT.
Traceback (most recent call last):
  File "/home/dennis/hummingbot/hummingbot/market/bittrex/bittrex_api_order_book_data_source.py", line 227, in get_tracking_pairs
    snapshot: OrderBookMessage = await self.get_snapshot(temp_trading_pair)
  File "/home/dennis/hummingbot/hummingbot/market/bittrex/bittrex_api_order_book_data_source.py", line 211, in get_snapshot
    raise IOError
OSError
WARNING:hummingbot.market.bittrex.bittrex_api_order_book_data_source:Error getting snapshot for ETH-USDT. Check network connection.
```

**Release version**

Version : `dev-0.25.0`

```
"branch": "development",
"commit": "100e415f00d9f3f1f91d8627f94b757dbd819a83",
"date": "2020-03-17T05:31:09Z",
```

**Attachments**

[bittrex_config.txt](https://github.com/CoinAlpha/hummingbot/files/4343222/bittrex_config.txt)
[bittrex_not_working.log](https://github.com/CoinAlpha/hummingbot/files/4343219/bittrex_not_working.log)
[python_test_bittrex_market.log](https://github.com/CoinAlpha/hummingbot/files/4343245/python_test_bittrex_market.log)

**Comment by znerol19619** [comment]
I tested this, and it seems to work now. 
![Screenshot from 2020-04-01 18-06-43](https://user-images.githubusercontent.com/27669951/78125468-a8180a00-7443-11ea-83f1-0c5241f4a071.png)

**Version**
```
                "branch": "development",
                "commit": "f7b120d730e6e43e7996dccbe1254e119c020f17",
                "date": "2020-03-27T05:55:08Z",

```

**Comment by rennel-tabing** [comment]
Similar issue reported by user on this redditt post
https://www.reddit.com/r/Hummingbot/comments/fsw0l4/discovery_snapshot_query_time_out/
I was able to replicate the error using a discovery strategy on version 0.25.0

On version dev-0.26.0
```
 "branch": "development",
                "commit": "b421c3181589a27f6a938bd133f2d373dbad1a84",
                "date": "2020-04-01T02:55:07Z",

```
discovery mode I am getting this errors
![image](https://user-images.githubusercontent.com/53868268/78139573-bc81e580-73f6-11ea-8da7-43b699ad27f5.png)

I also noticed that the token scan never progresses and will always show 1/20

![image](https://user-images.githubusercontent.com/53868268/78139815-12568d80-73f7-11ea-9599-14611fd060b6.png)

**Comment by Dante2333** [comment]
Can confirm, suffering same error trying to run bittrex ARK-BTC

**Comment by PtrckM** [comment]
test on source build dev-0.26.0

![image](https://user-images.githubusercontent.com/54516858/79076474-0212ac80-7d2d-11ea-8914-b32b750e7b5d.png)
