### ISSUE TITLE
problem in compiling hummingbot 0.5.0 and dev-0.6.0 in windows bash (WSL)

### ISSUE THREAD

**Issue by Steve1943** [CoinAlpha/hummingbot#155]
**Describe the bug**
problem in compiling hummingbot v5 in windows bash

**Steps To Reproduce**
download current master to github local repository c/users/steven/github 
in WLS bash   cd /c/users/steven/github  &&  sudo cp -r * ~/hummingbot
cd ~/hummingbot && conda deactivate && ./uninstall && ./install && conda activate hummingbot && ./compile

**Screenshots**
Error compiling Cython file:
------------------------------------------------------------
...

from wings.event_listener cimport EventListener

er_logger = None

cdef class EventReporter(EventListener):
    ^
------------------------------------------------------------

hummingbot/wings/event_reporter.pyx:9:5: Base type does not match previous declaration
Traceback (most recent call last):
  File "setup.py", line 126, in <module>
    main()
  File "setup.py", line 115, in main
    ], language="c++", language_level=3),
  File "/home/steven/anaconda3/envs/hummingbot/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "/home/steven/anaconda3/envs/hummingbot/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: hummingbot/wings/event_reporter.pyx

**Release version**
5.0 (on WSL Ubuntu 18.04) where Github clone executed in Windows10(HE)

replicates also in dev-0.6.0 (on WSL Ubuntu 18.04) where Github clone executed in Windows10(HE)

does NOT replicate on 5.0 or dev-0.6.0 (on VirtualBox Ubuntu 18.04) where the Github clone was executed  in Linux.

Conclusion - fault likely derives from transfer of files from Windows (native)  to Windows WSL (linux).
Possibly a permissions issue - or maybe EOL symbol translation?

**Comment by Steve1943** [comment]
Attached is bash log confirming problem on latest dev-0.6.0 at 20190502 T 11:30GMT
[WSL_bash_log_Dev-060._install_20190502.txt](https://github.com/CoinAlpha/hummingbot/files/3137790/WSL_bash_log_Dev-060._install_20190502.txt)

**Comment by Steve1943** [comment]
I'm a habitual "Git Desktop" user in Windows and thus unfamiliar with Git's command line syntax.  

Because Windows WSL is CLI only, I was attempting to use Git's desktop GUI in windows and then transfer the downloaded hummingbot clone into the window's bash workspace.  This led to complications from newline symbol incompatability (CRLF vs LF only in unix).  

This is not really your problem, so I am closing the bug report with the advice to other Windows users that conflating Windows native GUI tools with WSL is better avoided.  This is certainly my experience with both Anaconda and Git.  

The Windows user new to hummingbot must choose between learning to run linux via a terminal only in WSL, or running a full linux GUI in VirtualBox.

However, I do recommend that some simple bash cribs for Git are added to the hummingbot install and operating instructions for WSL.  Just enough to install and configure Git; and then to install/upgrade hummingbot via the Git CLI. 

New WSL users might also find the following useful as a aide memoire:
https://www.howtogeek.com/412055/37-important-linux-commands-you-should-know/
