### ISSUE TITLE
[BUG] Liquid market unit test failed

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1574]
**Describe the bug**

Error with `test_deposit_info (test.integration.test_liquid_market.LiquidMarketUnitTest)`

```
Traceback (most recent call last):
  File "/home/dennis/hummingbot/test/integration/test_liquid_market.py", line 332, in test_deposit_info
    [deposit_info] = self.run_parallel(
TypeError: cannot unpack non-iterable NoneType object
-------------------- >> begin captured logging << --------------------
aiohttp.access: INFO: 127.0.0.1 [31/Mar/2020:00:25:46 +0000] "GET /api.liquid.com/crypto_accounts HTTP/1.1" 200 477 "-" "Python/3.8 aiohttp/3.6.2"
hummingbot.core.utils.async_utils: DEBUG: Unhandled error in background task: Expected unicode, got tuple
Traceback (most recent call last):
  File "/home/dennis/hummingbot/hummingbot/core/utils/async_utils.py", line 20, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "hummingbot/market/liquid/liquid_market.pyx", line 1222, in get_deposit_info
  File "hummingbot/market/liquid/liquid_market.pyx", line 1215, in get_deposit_address
TypeError: Expected unicode, got tuple
hummingbot.core.utils.async_utils: ERROR: Unhandled error in background task: Expected unicode, got tuple
Traceback (most recent call last):
  File "/home/dennis/hummingbot/hummingbot/core/utils/async_utils.py", line 7, in safe_wrapper
    return await c
  File "/home/dennis/hummingbot/hummingbot/core/utils/async_utils.py", line 20, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "hummingbot/market/liquid/liquid_market.pyx", line 1222, in get_deposit_info
  File "hummingbot/market/liquid/liquid_market.pyx", line 1215, in get_deposit_address
TypeError: Expected unicode, got tuple
```

[test_liquid_market.log](https://github.com/CoinAlpha/hummingbot/files/4412566/test_liquid_market.log)

**Release version**

`dev-0.26.0`

**Comment by kmcgowan2000** [comment]
all deposit/withdrawal methods will be removed from our connectors and base classes as per clubhouse story #8521. I think @Nullably will be doing that
