### ISSUE TITLE
[BUG] ValueError: invalid literal for int() with base 10 on paper trade mode

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1599]
**Describe the bug**
DEX market (Bamboo relay and Radar relay) throws unhandled error upon checking status when running a pure_market_making_strategy or cross_exchange_market_making_strategy in paper_trade
```
2020-03-27 01:18:15,024 - 1611 - hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - (BAT-WETH) Creating limit ask order for 75.0000000 BAT at 0.0011189 $
2020-03-27 01:18:16,597 - 1611 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: invalid literal for int() with base 10: 'WETH/916fb71e8c6d4f84388700e4b2'
Traceback (most recent call last):
  File "/home/patrick/miniconda3/envs/hummingbot/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/patrick/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 652, in read_from_input
    self.key_processor.process_keys()
  File "/home/patrick/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 274, in process_keys
    self._process_coroutine.send(key_press)
  File "/home/patrick/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 186, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "/home/patrick/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 329, in _call_handler
    handler.call(event)
  File "/home/patrick/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 101, in call
    self.handler(event)
  File "/home/patrick/hummingbot/hummingbot/client/ui/keybindings.py", line 34, in status
    hb.status()
  File "/home/patrick/hummingbot/hummingbot/client/command/status_command.py", line 129, in status
    self._notify(self.strategy.format_status() + "\n")
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 199, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.Cross$
    df = LimitOrder.to_pandas(limit_orders)
  File "hummingbot/core/data_type/limit_order.pyx", line 30, in hummingbot.core.data_type.limit_order.LimitOrder.to_pandas
    pd.Timestamp(int(time.time()) - int(order.client_order_id.split("-")[-1])/1e6,
ValueError: invalid literal for int() with base 10: 'WETH/916fb71e8c6d4f84388700e4b2'

```
**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Open Hummingbot and set paper_trade On
2. Create a pure_market_making_strategy or cross_exchange_market_making _strategy
3. Use either Bamboo relay or Radar relay
4.  Use either the default parameter or set the desired parameter
5. Start bot, an error will occur after that, however, will give you a report that an order will be place
6.  Press `Ctrl + S` or enter `status` command to check status, another error will appear(unhandled error in prompt_toolkit)

**Screenshots**
Pure market making:
![Radar_paper_trade](https://user-images.githubusercontent.com/57189990/78735902-71c81680-797e-11ea-8612-430fd9a04bfb.png)

Cross exchange market making
![Untitled](https://user-images.githubusercontent.com/57189990/78735915-78ef2480-797e-11ea-824d-ad27da1bbd5a.png)

**Release version**
0.25.0 and 0.26.0

**Attachments**

[logs_conf_pure_market_making_strategy_5.log](https://github.com/CoinAlpha/hummingbot/files/4447799/logs_conf_pure_market_making_strategy_5.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by rennel-tabing** [comment]
I did configure the bot with its parameter and enabled paper trade mode after. My test enviroment was  able to reproduce the same error on version 0.26.0 
```
                "branch": "development",
                "commit": "0b5341395791ce9e1e488e738b93c3ae8d19c59a",
                "date": "2020-04-08T03:03:58Z",
```

**Comment by Clint-G13** [comment]
Similar behavior happens when doing paper trade with fiat pairs. Tested with Coinbase and Liquid.

```
2020-04-09 14:49:07,309 - 1808 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: invalid literal for int() with base 10: 'EUR/50e67573eb1443602f1aefbaa0'
Traceback (most recent call last):
  File "/home/clint_g/miniconda3/envs/hummingbot/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/clint_g/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 652, in read_from_input
    self.key_processor.process_keys()
  File "/home/clint_g/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 274, in process_keys
    self._process_coroutine.send(key_press)
  File "/home/clint_g/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 186, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "/home/clint_g/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 329, in _call_handler
    handler.call(event)
  File "/home/clint_g/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 101, in call
    self.handler(event)
  File "/home/clint_g/hummingbot/hummingbot/client/ui/keybindings.py", line 34, in status
    hb.status()
  File "/home/clint_g/hummingbot/hummingbot/client/command/status_command.py", line 129, in status
    self._notify(self.strategy.format_status() + "\n")
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 286, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.format_status
    df = LimitOrder.to_pandas(active_orders, mid_price, self._hanging_order_ids)
  File "hummingbot/core/data_type/limit_order.pyx", line 30, in hummingbot.core.data_type.limit_order.LimitOrder.to_pandas
    pd.Timestamp(int(time.time()) - int(order.client_order_id.split("-")[-1])/1e6,
ValueError: invalid literal for int() with base 10: 'EUR/50e67573eb1443602f1aefbaa0'
```

**Comment by kmcgowan2000** [comment]
this is already fixed, logic now checks for "//" and marks paper trade orders as age "n/a" instead of trying to process them as if they have a timestamp in the client_order_id
