### ISSUE TITLE
[BUG] Occasional unexpected error when setting tight order spread.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1633]
**Describe the bug**
An unexpected error reported after running pure mm strategy on tight order spread.

**Steps To Reproduce**
- set up a pure mm bot on tight order spread, e.g.  0.01% or 0.001% on either bid or ask spread on ETH-USDC or any pairs that are high price and has high trading volume.
- run the strategy and wait for the error to occur, note this doesn't happen all the time (only occasionally)
- the error is easier to reproduce when setting ask spread than bid spread.

Here is error message in the log file
```
2020-04-18 16:49:16,282 - 7041 - hummingbot.market.binance.binance_market - INFO - The market sell order sell-ETHUSDC-1587199756004378 has completed according to user stream.
2020-04-18 16:49:16,282 - 7041 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ETHUSDC) Maker sell order sell-ETHUSDC-1587199756004378 (0.10000000 ETH @ 173.37000000 USDC) has been completely filled. [clock=2020-04-18 08:49:16+00:00]
2020-04-18 16:49:16,284 - 7041 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1587199756.0, "order_id": "sell-ETHUSDC-1587199756004378", "base_asset": "ETH", "quote_asset": "USDC", "fee_asset": "USDC", "base_asset_amount": "0.10000000", "quote_asset_amount": "17.3370000000000000", "fee_amount": "0.01733700", "order_type": "OrderType.LIMIT", "event_name": "SellOrderCompletedEvent", "event_source": "binance"}
2020-04-18 16:49:16,706 - 7041 - hummingbot.market.binance.binance_market - INFO - The market sell order sell-ETHUSDC-1587199698003430 has completed according to order status API.
2020-04-18 16:49:16,706 - 7041 - hummingbot.market.binance.binance_market - ERROR - Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
    self._owner.c_did_complete_sell_order(arg)
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 824, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
    MarketBase maker_market = market_info.market
AttributeError: 'NoneType' object has no attribute 'market'
2020-04-18 16:49:16,715 - 7041 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1587199756.0, "order_id": "sell-ETHUSDC-1587199698003430", "base_asset": "ETH", "quote_asset": "USDC", "fee_asset": "USDC", "base_asset_amount": "0.10000000", "quote_asset_amount": "17.33600000", "fee_amount": "0.03467200", "order_type": "OrderType.LIMIT", "event_name": "SellOrderCompletedEvent", "event_source": "binance"}
2020-04-18 16:49:17,208 - 7041 - hummingbot.market.binance.binance_market - INFO - Created OrderType.LIMIT buy order buy-ETHUSDC-1587199756004034 for 0.10000000 ETHUSDC.
2020-04-18 16:49:17,214 - 7041 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1587199757.0, "type": "OrderType.LIMIT", "trading_pair": "ETHUSDC", "amount": "0.10000000", "price": "156.03000000", "order_id": "buy-ETHUSDC-1587199756004034", "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}
2020-04-18 16:49:17,712 - 7041 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1587199757.0, "type": "OrderType.LIMIT", "trading_pair": "ETHUSDC", "amount": "0.10000000", "price": "173.37000000", "order_id": "sell-ETHUSDC-1587199756004378", "event_name": "SellOrderCreatedEvent", "event_source": "binance"}
2020-04-18 16:49:26,863 - 7041 - hummingbot.market.binance.binance_market - INFO - Successfully cancelled order buy-ETHUSDC-1587199756004034.
2020-04-18 16:49:26,874 - 7041 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1587199766.0, "order_id": "buy-ETHUSDC-1587199756004034", "event_name": "OrderCancelledEvent", "event_source": "binance"}
```

**Release version**
dev-0.26.0

**Comment by Nullably** [comment]
I did initial investigation. As you can see from the log file, the binance websocket sometimes reports order filled before the order api result is returned when the order is matched right or very soon after submission. So the order does not yet get tracked, the tracker has no such order hence it returns None.

The reason sell orders are easier to reproduce in this case is because we round the price down when calculating the order price.

To fix this is a bit tricky, we could start tracking the order as soon as we create it internally - this is very likely a substantial change at the core of order processing in both strategies and connectors base classes. We could also try to replay the websocket messages in the case no tracked record found, though this might create other unintended consequences. 

The other quicker solution is to use a new Binance order type - LIMIT_MAKER. This will only fix the issue above for Binance (not sure if the error also happens on other connectors).
