### ISSUE TITLE
[BUG] Unable to run status command in several connectors while paper trading

### ISSUE THREAD

**Issue by devoger** [CoinAlpha/hummingbot#1666]
**Describe the bug**
// A clear and concise description of what the bug is.

Running the status command in Kucoin will result to an error:
```
2020-04-26 06:32:59,539 - 10 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: invalid literal for int() with base 10: 'fbfe839831934d6c'
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Setup a pure market making 
2. Set paper trade on
3. Disable Inventory Skew and Hanging Orders
4. 1% ask/bid spread
5. Start the strategy 
6. Run status command

Configuration
![Screen Shot 2020-04-26 at 14 43 08](https://user-images.githubusercontent.com/8411294/80300133-902a7080-87cc-11ea-924d-3e96b6a13d2d.png)

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
Running status command will result to an error;
```
2020-04-26 06:32:59,539 - 10 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: invalid literal for int() with base 10: 'fbfe839831934d6c'
```

![Screen Shot 2020-04-26 at 14 36 06](https://user-images.githubusercontent.com/8411294/80299988-70df1380-87cb-11ea-901f-cd4ae0a4d797.png)
```
########################################################
###       Pure market making strategy config         ###
########################################################

template_version: 12
strategy: pure_market_making

# Exchange and token parameters.
exchange: kucoin

# Token trading pair for the exchange, e.g. BTC-USDT
market: ETH-USDT

# How far away from mid price to place the bid order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_spread is 1.
# Your bid is placed at 99.
bid_spread: 1.0

# How far away from mid price to place the ask order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_spread is 1.
# Your bid is placed at 101.
ask_spread: 1.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 60.0

# Size of your bid and ask order.
order_amount: 1.0

# Whether to enable Inventory skew feature (true/false).
inventory_skew_enabled: false

# Target base asset inventory percentage target to be maintained (for Inventory skew feature).
inventory_target_base_pct:

# The range around the inventory target base percent to maintain, expressed in multiples of total order size (for
# inventory skew feature).
inventory_range_multiplier: 1.0

# Ox ONLY - Sets the expiration of limit orders. Minimum is 130 seconds.
order_expiration_time: 130.0

# Number of levels of orders to place on each side of the order book.
order_levels: 1

# Increment size of consecutive orders after the first order (if order_levels > 1).
order_level_amount: 0

# Order price space between orders (if order_levels > 1).
order_level_spread: 1.0

# How long to wait before placing the next order in case your order gets filled.
filled_order_delay: 60

# Whether to stop cancellations of orders on the other side (of the order book),
# when one side is filled (hanging orders feature) (true/false).
hanging_orders_enabled: false

# Spread (from mid price, in percentage) hanging orders will be canceled (Enter 1 to indicate 1%)
hanging_orders_cancel_pct: 10.0

# Whether to enable order optimization mode (true/false).
order_optimization_enabled: false

# The depth in base asset amount to be used for finding top bid and ask (for order optimization mode).
order_optimization_depth: 0

# Whether to enable adding transaction costs to order price calculation (true/false).
add_transaction_costs: false

# Whether to use external pricing source for the mid price (true/false).
price_source_enabled: false

# The type of external pricing source (exchange/custom_api).
price_source_type:

# An external exchange name (for external exchange pricing source).
price_source_exchange:

# A trading pair for the external exchange, e.g. BTC-USDT (for external exchange pricing source).
price_source_market:

# An external api that returns price (for external custom_api pricing source).
price_source_custom:

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters
```

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

0.26.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/4534769/logs_conf_pure_mm_1.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by PtrckM** [comment]
test on Binary Installer, docker build and source build.
```
2020-04-26 18:06:13,442 - 10072 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-04-26 18:06:13,445 - 10072 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
TypeError: object NoneType can't be used in 'await' expression
2020-04-26 18:06:14,289 - 10072 - hummingbot.market.kucoin.kucoin_api_order_book_data_source - INFO - Initialized order book for ETH-USDT. 1/1 completed.
2020-04-26 18:06:14,689 - 10072 - hummingbot.market.kucoin.kucoin_order_book_tracker - INFO - Started order book tracking for ETH-USDT.
2020-04-26 18:06:15,004 - 10072 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ETH-USDT) Creating limit bid orders at (Size, Price): ['1 ETH, 193.946 USDT'] [clock=2020-04-26 10:06:15+00:00]
2020-04-26 18:06:15,041 - 10072 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ETH-USDT) Creating limit ask orders at (Size, Price): ['1 ETH, 197.864 USDT'] [clock=2020-04-26 10:06:15+00:00]
2020-04-26 18:06:18,803 - 10072 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: invalid literal for int() with base 10: '501d90bad371e4cb'
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\status_command.py", line 109, in status_check_all
  File "hummingbot\client\command\status_command.py", line 73, in strategy_status
  File "hummingbot\strategy\pure_market_making\pure_market_making_v2.pyx", line 366, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.format_status
  File "hummingbot\strategy\pure_market_making\pure_market_making_v2.pyx", line 322, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.active_orders_df
ValueError: invalid literal for int() with base 10: '501d90bad371e4cb'

```

**Comment by Clint-G13** [comment]
Tested this issue and it appears that `status` issue occurs on paper trade only, the issue occurs as well without providing any error.

**Comment by PtrckM** [comment]
Happens on other connectors too like Liquid, Coinbase_pro and Bittrex both strategies PMM and XEMM unable to run status command happens only when Papertrade is enabled

**Comment by PtrckM** [comment]
Confirmed fix by the PR

![image](https://user-images.githubusercontent.com/54516858/81275004-a9140b00-9083-11ea-83ea-baf36e4d6122.png)
