### ISSUE TITLE
[BUG][<class 'decimal.DivisionUndefined'>] arbitrage Windows

### ISSUE THREAD

**Issue by nextpuma** [CoinAlpha/hummingbot#1670]
**Describe the bug**
arbitrage on same exchange doesn't work. returns the error
2020-04-26 15:59:18,009 - 14388 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\core\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 172, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 346, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 364, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair_inner
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 469, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_find_best_profitable_amount
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]

**Steps To Reproduce**
#My config:
strategy: arbitrage
primary_market: binance
secondary_market: binance
primary_market_trading_pair: ETH-BUSD
secondary_market_trading_pair: ETH-USDT
min_profitability: 0.3

**Release version**
0.26.0

**Comment by PtrckM** [comment]
I cannot replicate this, tested on Docker Build, Source Build and Binary Install(Windows) all works fine. Can you attached your logs here?

- Paper trade enabled
![image](https://user-images.githubusercontent.com/54516858/80313604-7580e780-881e-11ea-9f42-c1fff3e75d0a.png)
- Live
![image](https://user-images.githubusercontent.com/54516858/80313649-c55fae80-881e-11ea-96ee-5cb05c2d8ccd.png)

```
2020-04-27 00:30:15,823 - 5924 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-04-27 00:30:15,825 - 5924 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
TypeError: object NoneType can't be used in 'await' expression
2020-04-27 00:30:16,023 - 5924 - hummingbot.strategy.arbitrage.arbitrage - WARNING - Markets are not ready. No arbitrage trading is permitted.
2020-04-27 00:30:16,109 - 5924 - hummingbot.market.binance.binance_api_order_book_data_source - INFO - Initialized order book for ETHBUSD. 1/2 completed.
2020-04-27 00:30:17,407 - 5924 - hummingbot.market.binance.binance_api_order_book_data_source - INFO - Initialized order book for ETHUSDT. 2/2 completed.
2020-04-27 00:30:18,403 - 5924 - hummingbot.market.binance.binance_order_book_tracker - INFO - Started order book tracking for ETHBUSD.
2020-04-27 00:30:18,404 - 5924 - hummingbot.market.binance.binance_order_book_tracker - INFO - Started order book tracking for ETHUSDT.
2020-04-27 00:30:18,993 - 5924 - hummingbot.strategy.arbitrage.arbitrage - INFO - Markets are ready. Trading started.
```

**Comment by nextpuma** [comment]
Sure
I'm using windows client. didn't try paper.

[logs_conf_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/4536102/logs_conf_arb_1.log)

**Comment by rennel-tabing** [comment]
I tried the strategy on my bot and did not encounter any error using a live trade.

![image](https://user-images.githubusercontent.com/53868268/80364421-e393d180-8853-11ea-9842-023f6410a735.png)

I saw a similar bug report but that has already been resolved.
https://github.com/CoinAlpha/hummingbot/issues/401

Can you try this steps on your Windows machine?
https://blog.tradedash.io/2018/03/16/how-to-sync-your-computers-clock-with-binance/

**Comment by nextpuma** [comment]
Tried with time.nist.gov and time.windows.com. tried in different computers and networks but the problem dint go away.
is there a way to check my latency to binance?

regards

**Comment by nextpuma** [comment]
hmm, i tried in a google cloud instance. i made a simples test
Balance avaiable:
23 BUSD
23 USDT
0.3 ETH

strategy: arbitrage
primary_market: binance
secondary_market: binance
primary_market_trading_pair: ETH-BUSD 
secondary_market_trading_pair: ETH-USDT
min_profitability: 0.03

if i test this with paper_trading it will run until i get low usdt as expected
but if i try the same live  i will get the same error : hummingbot.core.clock - ERROR - Unexpected error running clock tick.

the only divergence on this test is the amount of BUSD ON BINANCE

**Comment by Clint-G13** [comment]
Similar reported behavior #1358, and I was able to encounter the issue. However, after a few attempts to reproduce the error, my bot suddenly stops getting the error.
Initial attempt:
![Capture1](https://user-images.githubusercontent.com/57189990/80672983-a85a0280-8ae0-11ea-9f2d-95f43c53132f.PNG)
Second attempt using different min_profitability value, the error didn't occur.
![Capture](https://user-images.githubusercontent.com/57189990/80673054-db03fb00-8ae0-11ea-8bd8-eb11c27e87d6.PNG)

**Comment by mifeng** [comment]
Closing in favor of newer ticket #1358
