### ISSUE TITLE
[BUG] Import | Unhandled error in background : [Errno 21] Is a directory: 'conf/'

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1674]
**Describe the bug**

When you enter import in Hummingbot client and then press `Enter` without choosing a strategy file, an error will occur and won't allow you to import any strategy. On the previous version (0.25.0), we have a validator for blank input which seems to be not included in the new import command.

Error using docker build or source build:
```
2020-04-25 05:04:21,441 - 10 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [Errno 21] Is a directory: 'conf/'
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/hummingbot/client/command/import_command.py", line 32, in import_config_file
    file_name = await self.prompt_a_file_name()
  File "/hummingbot/client/command/import_command.py", line 50, in prompt_a_file_name
    err_msg = validate_strategy_file(file_path)
  File "/hummingbot/client/config/config_helpers.py", line 209, in validate_strategy_file
    strategy = strategy_name_from_file(file_path)
  File "/hummingbot/client/config/config_helpers.py", line 200, in strategy_name_from_file
    with open(file_path) as stream:
IsADirectoryError: [Errno 21] Is a directory: 'conf/'
```
Error using binary version:
```
2020-04-28 10:37:39,969 - 12228 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [Errno 13] Permission denied: 'conf/'
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\import_command.py", line 32, in import_config_file
  File "hummingbot\client\command\import_command.py", line 50, in prompt_a_file_name
  File "hummingbot\client\config\config_helpers.py", line 209, in validate_strategy_file
  File "hummingbot\client\config\config_helpers.py", line 200, in strategy_name_from_file
PermissionError: [Errno 13] Permission denied: 'conf/'
```

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Open Hummingbot client
2. Input `import` command
3. Press `enter` and an error will be given on the log pane.
4. Once the error occurs, try importing saved strategy file and the bot will do nothing.

**Screenshots**
![import issue](https://user-images.githubusercontent.com/57189990/80442317-372f1980-893f-11ea-867f-e4d222c06c15.PNG)
![import1](https://user-images.githubusercontent.com/57189990/80442325-38f8dd00-893f-11ea-940e-1567264a9df1.png)

**Release version**
0.26.0 and 0.27.0

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/4543131/logs_hummingbot.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Clint-G13** [comment]
Confirm fix on dev brach
