### ISSUE TITLE
Dolomite connector not working

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1687]
**Describe the bug**
Unable to start bot when using Dolimite Connector

**Steps To Reproduce**
create strategy as PMM
set spread 
set order min

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/80864989-eb6ece00-8cb8-11ea-882f-f386a132bc5f.png)

```
2020-05-02 21:05:46,697 - 2744 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Error formatting market stats.
Traceback (most recent call last):
  File "hummingbot\strategy\strategy_base.pyx", line 165, in hummingbot.strategy.strategy_base.StrategyBase.market_status_data_frame
  File "hummingbot\market\market_base.pyx", line 316, in hummingbot.market.market_base.MarketBase.get_price
  File "hummingbot\market\dolomite\dolomite_market.pyx", line 484, in hummingbot.market.dolomite.dolomite_market.DolomiteMarket.c_get_price
  File "hummingbot\market\dolomite\dolomite_market.pyx", line 197, in hummingbot.market.dolomite.dolomite_market.DolomiteMarket.c_get_order_book
ValueError: No order book exists for 'WETH-DAI'.
```

**Release version**
0.26.0 / Docker Build, Source Build and Binary Installer

**Attachments**
[pmm_dolomite.txt](https://github.com/CoinAlpha/hummingbot/files/4567749/pmm_dolomite.txt)
[logs_pmm_dolomite.log](https://github.com/CoinAlpha/hummingbot/files/4567750/logs_pmm_dolomite.log)

**Comment by dennisocana** [comment]
We will deprecate / remove this connector from the codebase during a maintenance release.
