### ISSUE TITLE
[BUG] No valid Kraken pairs in Cross-Exchange Market Making

### ISSUE THREAD

**Issue by babygiraffe05** [CoinAlpha/hummingbot#1693]
**Describe the bug**
When setting up Cross-Exchange market making using the "create" command and selecting Kraken for the taker exchange, there are no valid entries for the token trading pair on the taker exchange.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see screenshot in the section below):
1. Run "create" command to start configuration of a new cross-exchange market-making bot.
2. What is your market making strategy? Select "cross_exchange_market_making"
3. Enter your maker exchange name >>> (I entered coinbase_pro in the screenshot)
4. Enter your taker exchange name >>> kraken
5. Enter the token trading pair you would like to trade on maker market: coinbase_pro (e.g., ETH-USDC) >>> BTC-USD
6. Enter the token trading pair you would like to trade on taker market: kraken (e.g., XETH-USDC) >>>

There is no valid input for this. I've tried both entering the first letter and the tab-autocomplete drop down methods, and the bot won't accept any entries. At this point, the bot is essentially stuck, unable to complete the initial configuration.

**Screenshots**

![Screen Shot 2020-05-04 at 9 17 32 AM](https://user-images.githubusercontent.com/48837995/80989530-e9585c80-8de9-11ea-9cc4-2cb8317687a8.png)

**Release version**
Version 0.26.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

Cannot produce a config file, since the bug prevents its creation.

**Comment by Clint-G13** [comment]
Test concern and I was able to reproduce the behavior, autocomplete isn't working for Kraken as well. Traceback error:
```
2020-05-05 07:39:33,234 - 1817 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: argument of type 'OSError' is not iterable
Traceback (most recent call last):
  File "/home/clint_g/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/clint_g/hummingbot/hummingbot/client/command/create_command.py", line 60, in prompt_for_configuration
    await self.prompt_a_config(config)
  File "/home/clint_g/hummingbot/hummingbot/client/command/create_command.py", line 91, in prompt_a_config
    err_msg = config.validate(input_value)
  File "/home/clint_g/hummingbot/hummingbot/client/config/config_var.py", line 55, in validate
    err_msg = self._validator(value)
  File "/home/clint_g/hummingbot/hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making_config_map.py", line 42, in validate_taker_market_trading_pair
    return validate_market_trading_pair(taker_market, value)
  File "/home/clint_g/hummingbot/hummingbot/client/config/config_validators.py", line 49, in validate_market_trading_pair
    if value not in trading_pair_fetcher.trading_pairs.get(market):
TypeError: argument of type 'OSError' is not iterable
```
![Kraken](https://user-images.githubusercontent.com/57189990/81023777-06516600-8ea4-11ea-8205-b08ffb32e470.PNG)

**Comment by Clint-G13** [comment]
Test PR #1730 using arbitrage, cross exchange market making, and pure market making and confirmed the issue with autocomplete is fixed.
![kraken fetcher](https://user-images.githubusercontent.com/57189990/81765814-5fa24080-9507-11ea-904c-df84c8ce9779.PNG)
