### ISSUE TITLE
[BUG] Kraken history command error on BTC pairs

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1780]
Getting `Error running performance analysis` when running `history` command after executing trades on a BTC pair.

<img width="947" alt="putty_hs18YXAbl1" src="https://user-images.githubusercontent.com/50150287/82292683-e65e8e00-99dd-11ea-967d-2d7e1084062e.png">

Traceback does not always appear in logs. This is the log file of the bot above that has no error in logs - 
[without_errors.log](https://github.com/CoinAlpha/hummingbot/files/4648604/without_errors.log)

The other bot I was running on Kraken has the same issue but the log file contains the traceback - 
[with_errors.log](https://github.com/CoinAlpha/hummingbot/files/4648609/with_errors.log)

```
2020-05-19 04:46:34,557 - 10 - hummingbot.client.hummingbot_application - ERROR - Unexpected error running performance analysis.
Traceback (most recent call last):
  File "/hummingbot/client/command/history_command.py", line 119, in trade_performance_report
    trade_performance_stats, market_trading_pair_stats = self._calculate_trade_performance()
  File "/hummingbot/client/command/history_command.py", line 91, in _calculate_trade_performance
    trade_performance_stats, market_trading_pair_stats = performance_analysis.calculate_trade_performance(
  File "/hummingbot/client/performance_analysis.py", line 244, in calculate_trade_performance
    stats["delta_percentage"] = ((stats["acquired"] / stats["spent"]) - Decimal("1")) * Decimal("100")
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>
```

Error is not present on **ETH-USDT** pair.

<img width="947" alt="putty_akjiwCPDWp" src="https://user-images.githubusercontent.com/50150287/82292951-540aba00-99de-11ea-8149-f3d9b1c6befc.png">

**Version** : latest 0.27.0
**Environment** : Docker in AWS EC2 instance

**Comment by mifeng** [comment]
@kmcgowan2000 is this bug fixed now?

**Comment by kmcgowan2000** [comment]
@mifeng not yet, prioritising backend but will be fixed this week

**Comment by dennisocana** [comment]
I'm getting this error again after executing some trades on BTC-USDT pair.

```
2020-07-16 07:11:31,502 - 1 - hummingbot.core.utils.kill_switch - ERROR - Error calculating profitability: [<class 'decimal.DivisionByZero'>]
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/kill_switch.py", line 38, in check_profitability_loop
    self._hummingbot_application.calculate_profitability() / Decimal("100")
  File "/home/hummingbot/hummingbot/client/command/history_command.py", line 111, in calculate_profitability
    trade_performance_stats, _ = self._calculate_trade_performance()
  File "/home/hummingbot/hummingbot/client/command/history_command.py", line 93, in _calculate_trade_performance
    trade_performance_stats, market_trading_pair_stats = calculate_trade_performance(
  File "/home/hummingbot/hummingbot/client/performance_analysis.py", line 153, in calculate_trade_performance
    stats["delta_percentage"] = ((stats["acquired"] / stats["spent"]) - Decimal("1")) * Decimal("100")
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

<img width="947" alt="putty_2RracTsgAO" src="https://user-images.githubusercontent.com/50150287/87665078-e938ed80-c798-11ea-982d-faa9d96dceec.png">

[logs_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4931116/logs_kraken_btc-usdc.log)
