### ISSUE TITLE
Kraken - Strategy fails to start on BTC quote pairs

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1781]
Unable to start pure market making strategy using Kraken connector on BTC quote pairs. Tried on other pairs like ETH-USDC, BTC-USDC, ETH-EUR and are working fine.

1. Create a pure market making strategy config file with Kraken
2. Set `market` to any pair with BTC quote e.g. ETH-BTC, XRP-BTC
3. Run `start` command to get the error

```
2020-05-19 06:45:45,332 - 10 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/hummingbot/strategy/pure_market_making/start.py", line 86, in start
    maker_assets: Tuple[str, str] = self._initialize_market_assets(exchange, [trading_pair])[0]
  File "/hummingbot/client/hummingbot_application.py", line 197, in _initialize_market_assets
    market_trading_pairs: List[Tuple[str, str]] = [market_class.split_trading_pair(trading_pair) for trading_pair in trading_pairs]
  File "/hummingbot/client/hummingbot_application.py", line 197, in <listcomp>
    market_trading_pairs: List[Tuple[str, str]] = [market_class.split_trading_pair(trading_pair) for trading_pair in trading_pairs]
  File "kraken_market.pyx", line 195, in hummingbot.market.kraken.kraken_market.KrakenMarket.split_trading_pair
AttributeError: 'NoneType' object has no attribute 'split'
```

<img width="947" alt="putty_cjx2UxePjH" src="https://user-images.githubusercontent.com/50150287/82295963-178d8d00-99e3-11ea-91e3-debc8909e0de.png">

**NOTE** : The screenshot shows paper trade but this also happens in live trade.

Log file - [eth-btc_error.log](https://github.com/CoinAlpha/hummingbot/files/4648794/eth-btc_error.log)

**Version** : Latest 0.27.0
**Environment** : Docker on AWS EC2 instance

**Comment by RC-13** [comment]
Re-opening ticket, user Tomma100 reported the issue for ETH-BTC market pair failing to connect to exchange after initializing and getting `Unexpected error running clock tick`. Confirmed that it happens to other markets as well using BTC quote ( test done on ETH-BTC, XRP-BTC, LTC-BTC and DOGE-BTC), it seems that bot is failing to get the price for the trading pair however some market pair works ( tested on ALGO-BTC and BAT-BTC).
```
2021-01-22 09:08:20,001 - 7383 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 651, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    proposal =self.c_create_base_proposal()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 703, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
    price = self.get_price() * (Decimal("1") - self._bid_spread - (level * self._order_level_spread))
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 357, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
    price = price_provider.get_price_by_type(self._price_type)
  File "/home/clint_g/hummingbot/hummingbot/strategy/market_trading_pair_tuple.py", line 40, in get_price_by_type
    return self.market.get_price_by_type(self.trading_pair, price_type)
  File "hummingbot/connector/exchange_base.pyx", line 277, in hummingbot.connector.exchange_base.ExchangeBase.get_price_by_type
    return (self.c_get_price(trading_pair, True) + self.c_get_price(trading_pair, False)) / Decimal("2")
  File "hummingbot/connector/exchange_base.pyx", line 108, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
    return self.c_quantize_order_price(trading_pair, top_price)
  File "hummingbot/connector/connector_base.pyx", line 376, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
    price_quantum = self.c_get_order_price_quantum(trading_pair, price)
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 1016, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange.c_get_order_price_quantum
    TradingRule trading_rule = self._trading_rules[trading_pair]
KeyError: 'ETH-BTC'
```
![image](https://user-images.githubusercontent.com/57189990/105432474-a9e0e180-5c92-11eb-99d4-e21a6eb6aadc.png)

```
Branch: Latest (v0.35)
Environment: Binary (0.33.1 to 0.35), Docker, and Source
```

**Comment by lamtha** [comment]
It's moved to ETH/XBT:
```'XETHXXBT': {'altname': 'ETHXBT', 'wsname': 'ETH/XBT', 'aclass_base': 'currency', 'base': 'XETH', 'aclass_quote': 'currency', 'quote': 'XXBT' .... ```

**Comment by lamtha** [comment]
@keithbaum I took a crack at this and wanted to check this was the right direction before going further.
I took a slightly different approach than the string based matching/parsing for the trading pairs and instead stored the exchange base and quote on a KrakenTradingPair subclass. LMK if this is a good direction and I'll finish up.
I've had it up and running and worked in the most part for all the pairs mentioned above.
https://github.com/CoinAlpha/hummingbot/compare/development...lamtha:fix/kraken_trading_pairs?expand=1

**Comment by sidmontanez** [comment]
User strattonakmontclown also reported an issue regarding the error logs while running XDG-BTC Pair under Pi4. I tried replicating it on Docker ver 0.36.0 and Binary 0.35.0 and I'm also receiving the same error logs. 
![KrakenXDGError](https://user-images.githubusercontent.com/78310937/108600558-bf047980-73d2-11eb-92a2-9b2fd9f0fbf2.JPG)

**Comment by keithbaum** [comment]
I like the way you encapsulated Kraken special behavior in a separate object @lamtha but unfortunately this not only affects the trading rules but also the trading_pairs, which affect how the balance is added up (specially if multiple exchanges are involved, i.e. Liquidity Mining strategy) and also the list of pairs when creating a new strategy. I'm currently working in an approach to adapt the Kraken trading pairs list to the "canonical" trading pairs list, which in this case will be Binance
