### ISSUE TITLE
[BUG] Binance arbitrage not placing orders c_find_best_profitable_amount decimal.InvalidOperation

### ISSUE THREAD

**Issue by pacovi** [CoinAlpha/hummingbot#1787]
**Describe the bug**

When min_profitability is reached (as exposed by the status command), hummingbot tries to place a SELL order in Binance. The sell order is seen in the history but it never comes through Binance itself due to an exception happening within the c_tick function as shown in the trace below:
```
2020-05-16 10:55:14,002 - 10 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "arbitrage.pyx", line 172, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
  File "arbitrage.pyx", line 344, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
  File "arbitrage.pyx", line 364, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair_inner
  File "arbitrage.pyx", line 469, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_find_best_profitable_amount
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]
```

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file as shown below. Also reproducible other combinations:
   - Changing order of exchanges
	- Disabling / enabling Telegram (is the only general config changed from defaults)
	- Changing API key in Binance
	- Issuing spot order on Binance to see if it "clears" something up (some kind of queue?)
	- Try other currency-pairs (e.g. USD-BTC), not working
	- Try different profitability levels (e.g. 0.5, 0.6)
```
#####################################
###   Arbitrage strategy config   ###
#####################################
template_version: 3
strategy: arbitrage
# The following configuations are only required for the
# arbitrage strategy
# Exchange and token parameters
primary_market: coinbase_pro
secondary_market: binance
primary_market_trading_pair: BTC-EUR
secondary_market_trading_pair: BTC-EUR
# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 0.3
```

2. Start the bot using this command: import <config_file>, then start.
3. Check that you have ENOUGH balance in both exchanges to make trades, so that you don't get the low balance warning.
4. Check status for profitability values e.g.:
	-   Profitability:
```
    take bid on coinbase_pro, take ask on binance: -0.5975 %
    take ask on coinbase_pro, take bid on binance: 0.5925 %
```
5. If  profitabililty > min_profitability, an order will be attempted as shown in the history, but it won't go through unless profitability is greater than ~1% (estimation, see history logs below).
6. Status shows that no changes are actually made in the balances, but history command shows that they're tried but not effective
```
Recent trades:
       symbol   price   amount order_type  side   market            timestamp  fee_percent flat_fee / gas
    0  BTCEUR 8829.26 0.005663     market  sell  binance  2020-05-20 09:10:14        0.001           None
    1  BTCEUR 8829.26 0.003398     market  sell  binance  2020-05-20 09:10:14        0.001           None
    2  BTCEUR 8828.77 0.004939     market  sell  binance  2020-05-20 09:10:14        0.001           None
	
Inventory:
             Market Asset  Starting   Current Net Delta Trade Delta
    0  coinbase_pro   BTC    0.A    0.A    0.0000      0.0000
    1  coinbase_pro   EUR    B      B      0.0000      0.0000
    2       binance   BTC    0.C    0.C    0.0000     -0.0140
    3       binance   EUR    D      D      0.0000    123.4836
```
7. Log window shows the errors below.
![image](https://user-images.githubusercontent.com/6522045/82434691-87f3e700-9a93-11ea-9865-917815b784e1.png)

8. Logfile shows the error as shown in the description.
```
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]
2020-05-16 10:55:13,001 - 10 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "arbitrage.pyx", line 172, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
  File "arbitrage.pyx", line 344, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
  File "arbitrage.pyx", line 364, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair_inner
  File "arbitrage.pyx", line 469, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_find_best_profitable_amount
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]
```
(updated 21 May 2020)
When profitability is roughly above 1%, it seems like the orders do go through, no error is shown in the logs for those situations!
This is the history output from when orders started to go through, I added the column "MATCH" to reflect those that seem matched between the two exchanges. In the end, looking at the balances those "unmatched" created the error and hence, they didn't even go through in Binance, so the balance does not reflect those "history" lines.
```
         symbol   price   amount order_type  side        market            timestamp  fee_percent flat_fee / gas	MATCH
    0    BTCEUR 8829.26 0.005663     market  sell       binance  2020-05-20 09:10:14        0.001           None	
    1    BTCEUR 8829.26 0.003398     market  sell       binance  2020-05-20 09:10:14        0.001           None
    2    BTCEUR 8828.77 0.004939     market  sell       binance  2020-05-20 09:10:14        0.001           None	
    3    BTCEUR 8829.26 0.005663     market  sell       binance  2020-05-20 12:13:06        0.001           None	
    4    BTCEUR 8829.26 0.003398     market  sell       binance  2020-05-20 12:13:07        0.001           None
    5    BTCEUR 8828.77 0.004939     market  sell       binance  2020-05-20 12:13:07        0.001           None	
    6   BTC-EUR 8864.53    0.019     market   buy  coinbase_pro  2020-05-20 15:15:07        0.005           None	A
    7    BTCEUR 8955.15 0.001828     market  sell       binance  2020-05-20 15:15:07        0.001           None	A
    8    BTCEUR    8955 0.017172     market  sell       binance  2020-05-20 15:15:08        0.001           None	A
    9   BTC-EUR 8709.98    0.005     market   buy  coinbase_pro  2020-05-20 15:50:18        0.005           None	B
    10   BTCEUR 8800.02    0.005     market  sell       binance  2020-05-20 15:50:19        0.001           None	B
    11  BTC-EUR 8674.12    0.006     market   buy  coinbase_pro  2020-05-20 16:47:49        0.005           None	C
    12   BTCEUR 8774.34 0.003332     market  sell       binance  2020-05-20 16:47:49        0.001           None	C
    13   BTCEUR 8773.94 0.002668     market  sell       binance  2020-05-20 16:47:50        0.001           None	C
    14  BTC-EUR 8681.74    0.002     market   buy  coinbase_pro  2020-05-20 19:09:08        0.005           None	D
    15   BTCEUR 8791.68    0.002     market  sell       binance  2020-05-20 19:09:08        0.001           None	D
    16   BTCEUR 8791.68    0.002     market  sell       binance  2020-05-21 01:52:46        0.001           None
```

**Screenshots**
Already included in reproduction steps

**Release version**
Reproducible in 0.26.1 and 0.27.0 docker versions.
Google Compute Engine VM instance, Always Free Tier (f1-micro) with 2GB Swapfile added, running Ubuntu LTS and hummingbot using docker.

**Note**
Thought that it was the same bug as in https://github.com/CoinAlpha/hummingbot/issues/1358 , but given that it occurs in a different scenario and effect (including exchange and platform) the only thing in common seems to be the Clock relation, created a new one. Tried already to debug with @rennel-tabing unsuccessfully.

**Suggested labels**
arbitrage
bug
binance
docker

**Optional: your discord username:**
pacovi

**Comment by pacovi** [comment]
Extended the release version ticket section to include the machine type used to reproduce:
**Release version**
Reproducible in 0.26.1 and 0.27.0 docker versions.
Google Compute Engine VM instance, Always Free Tier (f1-micro) with 2GB Swapfile added, running Ubuntu LTS and hummingbot using docker.

**Comment by pacovi** [comment]
Apparently yesterday was a good day, some orders started to get through.
Looking at each order that got through looks like it does work when profitability > 1%  (estimation)
Updated the description to reflect so.
This is the history output from when orders started to go through, I added the column "MATCH" to reflect those that seem matched between the two exchanges. In the end, looking at the balances those "unmatched" created the error and hence, they didn't even go through in Binance, so the balance does not reflect those "history" lines.
```
         symbol   price   amount order_type  side        market            timestamp  fee_percent flat_fee / gas	MATCH
    0    BTCEUR 8829.26 0.005663     market  sell       binance  2020-05-20 09:10:14        0.001           None	
    1    BTCEUR 8829.26 0.003398     market  sell       binance  2020-05-20 09:10:14        0.001           None
    2    BTCEUR 8828.77 0.004939     market  sell       binance  2020-05-20 09:10:14        0.001           None	
    3    BTCEUR 8829.26 0.005663     market  sell       binance  2020-05-20 12:13:06        0.001           None	
    4    BTCEUR 8829.26 0.003398     market  sell       binance  2020-05-20 12:13:07        0.001           None
    5    BTCEUR 8828.77 0.004939     market  sell       binance  2020-05-20 12:13:07        0.001           None	
    6   BTC-EUR 8864.53    0.019     market   buy  coinbase_pro  2020-05-20 15:15:07        0.005           None	A
    7    BTCEUR 8955.15 0.001828     market  sell       binance  2020-05-20 15:15:07        0.001           None	A
    8    BTCEUR    8955 0.017172     market  sell       binance  2020-05-20 15:15:08        0.001           None	A
    9   BTC-EUR 8709.98    0.005     market   buy  coinbase_pro  2020-05-20 15:50:18        0.005           None	B
    10   BTCEUR 8800.02    0.005     market  sell       binance  2020-05-20 15:50:19        0.001           None	B
    11  BTC-EUR 8674.12    0.006     market   buy  coinbase_pro  2020-05-20 16:47:49        0.005           None	C
    12   BTCEUR 8774.34 0.003332     market  sell       binance  2020-05-20 16:47:49        0.001           None	C
    13   BTCEUR 8773.94 0.002668     market  sell       binance  2020-05-20 16:47:50        0.001           None	C
    14  BTC-EUR 8681.74    0.002     market   buy  coinbase_pro  2020-05-20 19:09:08        0.005           None	D
    15   BTCEUR 8791.68    0.002     market  sell       binance  2020-05-20 19:09:08        0.001           None	D
    16   BTCEUR 8791.68    0.002     market  sell       binance  2020-05-21 01:52:46        0.001           None
```

**Comment by vic-en** [comment]
@pacovi 
Could you upload your log file so I can possibly fix faster?

**Comment by pacovi** [comment]
Sorry for the late response @vic-en 
[logs_conf_arb_1.log.2020-05-27.zip](https://github.com/CoinAlpha/hummingbot/files/4724468/logs_conf_arb_1.log.2020-05-27.zip)
