### ISSUE TITLE
[BUG] Can't place orders on Kucoin after v0.27.0

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1796]
**Describe the bug**
```
Hi,

In the update of version 27 I can't make an order at KuCoin.

Best regards,
Peter
```

**Release version**
0.27.0

**Attachments**
[logs_conf_pure_mm_KU-21-5.log](https://github.com/CoinAlpha/hummingbot/files/4663910/logs_conf_pure_mm_KU-21-5.log)

**Comment by Clint-G13** [comment]
Base on the initial test we did, it appears that this error occurs if you have multiple orders and transaction cost is enabled (live and paper trade). Turning off or setting add_transaction to false prevents the error from occurring, so far the error didn't show on a single order with transaction cost enabled.

Multiple orders with add_transaction_cost set to true.
```
2020-05-22 07:25:08,028 - 16696 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Unknown error while generating order proposals.
Traceback (most recent call last):
  File "hummingbot\strategy\pure_market_making\pure_market_making_v2.pyx", line 472, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "hummingbot\strategy\pure_market_making\pure_market_making_v2.pyx", line 746, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_create_orders_proposals
  File "hummingbot\strategy\pure_market_making\pure_market_making_v2.pyx", line 631, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_check_and_add_transaction_costs_to_pricing_proposal
IndexError: list index out of range
```
![index error](https://user-images.githubusercontent.com/57189990/82616437-c1e1fc00-9bff-11ea-8213-b402da838708.PNG)

**Comment by dennisocana** [comment]
Asked for the strategy configuration file from the user. I am running on multiple order mode with `add_transaction_costs` enabled in KuCoin and not getting the same behavior.

<img width="947" alt="syPJwjVFa2" src="https://user-images.githubusercontent.com/50150287/82618344-6581db00-9c05-11ea-800f-9ca3733dd416.png">

**Comment by rennel-tabing** [comment]
I received a similar report today from a user running on Binance. The strategy was running perfectly for several days before then suddenly the bot stopped placing orders.
1. I imported the users strategy on my test environment and it was working just fine.
2. Doing a stop / start command or closing and reopening the hummingbot did not fix the issue on the users end.
3. User confirms that disabling the  `add_transaction_costs` parameter will make the strategy run again.

[conf_pmm_binanceRLC-ETH.txt](https://github.com/CoinAlpha/hummingbot/files/4678650/conf_pmm_binanceRLC-ETH.txt)
[logs_conf_pmm_0-binanceRLC-ETH.txt](https://github.com/CoinAlpha/hummingbot/files/4678651/logs_conf_pmm_0-binanceRLC-ETH.txt)

**Comment by mifeng** [comment]
Closing this issue since we made `add_transaction_costs` simpler in v0.28.0 - it should no longer block order placement.
