### ISSUE TITLE
[BUG] Unit test failed - test_config_templates.py

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1820]
Run nosetests for all tests in `hummingbot/test` directory - [test_all.log](https://github.com/CoinAlpha/hummingbot/files/4711517/test_all.log)

Getting an error when executing tests in `test_config_templates.py`.

```
======================================================================
ERROR: test_strategy_config_template_complete (test.test_config_templates.ConfigTemplatesUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dennis/hummingbot/test/test_config_templates.py", line 51, in test_strategy_config_template_complete
    with open(strategy_template_path, "r") as template_fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dennis/hummingbot/hummingbot/templates/conf_discovery_strategy_TEMPLATE.yml'
-------------------- >> begin captured logging << --------------------
root: ERROR: No module named 'hummingbot.strategy.discovery.discovery_config_map'
Traceback (most recent call last):
  File "/home/dennis/hummingbot/hummingbot/client/config/config_helpers.py", line 169, in get_strategy_config_map
    strategy_module = __import__(f"hummingbot.strategy.{strategy}.{cm_key}",
ModuleNotFoundError: No module named 'hummingbot.strategy.discovery.discovery_config_map'
--------------------- >> end captured logging << ---------------------
```

**Comment by rxlxrxsx** [comment]
Confirmed error doesn't occur anymore when running nosetest on ``test_config_templates.py``.

![image](https://user-images.githubusercontent.com/64377055/89620936-0c038100-d8c3-11ea-868c-0ee2171ae45c.png)
