### ISSUE TITLE
[BUG] Docker | Permission errors when updating to version 0.28.0 

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1886]
**Describe the bug**
// A clear and concise description of what the bug is.
Using the update script to install the latest 0.28.0 will causing the update to fail.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. You must have a previous version of hummingbot (e.i 0.27.0)
2. Stop all running instance 
  Use the update script script `./update.sh`
3. At the end of the update process, an error will occur

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.28.0
Installed using docker
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
```
Traceback (most recent call last):
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/logging/config.py", line 744, in configure_hand
ler
    result = factory(**kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/logging/handlers.py", line 200, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/hummingbot/logs/logs_hummingbot.log'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 139, in <module>
    main()
  File "bin/hummingbot_quickstart.py", line 135, in main
    asyncio.get_event_loop().run_until_complete(quick_start(args))
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until
_complete
    return future.result()
  File "bin/hummingbot_quickstart.py", line 72, in quick_start
    init_logging("hummingbot_logs.yml")
  File "/home/hummingbot/hummingbot/__init__.py", line 172, in init_logging
    logging.config.dictConfig(config_dict)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file_handler'

```

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rennel-tabing** [comment]
Workaround on my end (using ubuntu 18.04)
Delete the content of the `instance-name_files/hummingbot_logs folder`
do a `chmod 755 instance-name_files/hummingbot_logs`

**Comment by rennel-tabing** [comment]
Got a user who was using Centos and clearing the logs folder nor data folder is still giving out the error. He can access hummingbot but after you exit will show this error
![image](https://user-images.githubusercontent.com/53868268/85057429-ba663200-b16e-11ea-8ea4-bdcc7125820a.png)


Tried to do `docker rmi coinalpha/hummingbot:latest` and use the `create.sh` script but it's having the same issue.

**Comment by carlolm** [comment]
I tried the following:
`sudo chmod -R 777 instance-name_files/`
Not just to the logs folder, all folders.  The permissioning error may also affect the conf/ files also

**Comment by PtrckM** [comment]
Fix on the way https://github.com/CoinAlpha/hummingbot/pull/1892
