### ISSUE TITLE
[BUG] Error with celo_arb strategy on CELO pairs in Bittrex

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1895]
**Describe the bug**
 - error running celo_arb - bittrex

**Steps To Reproduce**
create arb_celo
select bittrex as secondary exchange

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/85200374-79fee380-b329-11ea-9ac4-c23b79ecf708.png)
![image](https://user-images.githubusercontent.com/54516858/85200379-808d5b00-b329-11ea-92dd-2a7d067aef8c.png)
![image](https://user-images.githubusercontent.com/54516858/85200382-83884b80-b329-11ea-8e3e-ea45fe2da1ec.png)
![image](https://user-images.githubusercontent.com/54516858/85200391-8be08680-b329-11ea-8256-25afb4d9f8c1.png)
![image](https://user-images.githubusercontent.com/54516858/85200393-900ca400-b329-11ea-834f-9d480eac0705.png)

**Release version**
0.28.0

**Attachments**
- logs
[logs_conf_celo_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/4807755/logs_conf_celo_arb_1.log)
[logs_conf_celo_arb_2.log](https://github.com/CoinAlpha/hummingbot/files/4807756/logs_conf_celo_arb_2.log)

- errors from logs
from conf_celo_arb_2
```
2020-06-20 10:58:41,606 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'CELO-USDT'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "hummingbot/strategy/celo_arb/celo_arb.pyx", line 278, in hummingbot.strategy.celo_arb.celo_arb.CeloArbStrategy.main_process
    self._trade_profits = get_trade_profits(self._market_info.market, self._market_info.trading_pair, self._order_amount)
  File "hummingbot/strategy/celo_arb/celo_arb.pyx", line 51, in hummingbot.strategy.celo_arb.celo_arb.get_trade_profits
    query_result = market.get_vwap_for_volume(trading_pair, True, float(order_amount))
  File "hummingbot/market/market_base.pyx", line 297, in hummingbot.market.market_base.MarketBase.get_vwap_for_volume
    return self.c_get_vwap_for_volume(trading_pair, is_buy, volume)
  File "hummingbot/market/market_base.pyx", line 221, in hummingbot.market.market_base.MarketBase.c_get_vwap_for_volume
    object query_volume = self.c_quantize_order_amount(trading_pair, Decimal(result.query_volume))
  File "hummingbot/market/bittrex/bittrex_market.pyx", line 668, in hummingbot.market.bittrex.bittrex_market.BittrexMarket.c_quantize_order_amount
    TradingRule trading_rule = self._trading_rules[trading_pair]
KeyError: 'CELO-USDT'
```
from conf_celo_arb_1
```
2020-06-20 11:02:54,234 - 1 - signalr_aio._connection - ERROR - Signalr connection error: There was an error invoking Hub method 'c2.queryExchangeState'.
2020-06-20 11:02:54,236 - 1 - signalr_aio._connection - ERROR - Signalr connection error: There was an error invoking Hub method 'c2.queryExchangeState'.
2020-06-20 11:02:54,238 - 1 - signalr_aio._connection - ERROR - Signalr connection error: There was an error invoking Hub method 'c2.queryExchangeState'.
2020-06-20 11:06:18,760 - 1 - hummingbot.market.bittrex.bittrex_api_order_book_data_source - NETWORK - Max retries met fetching snapshot for CGLD-USDT.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/market/bittrex/bittrex_api_order_book_data_source.py", line 227, in get_tracking_pairs
    snapshot: OrderBookMessage = await self.get_snapshot(temp_trading_pair)
  File "/home/hummingbot/hummingbot/market/bittrex/bittrex_api_order_book_data_source.py", line 211, in get_snapshot
    raise IOError
```

https://bittrex.zendesk.com/hc/en-us/articles/360045006211-Ticker-Name-and-Symbol-Change-CeloGold-cGLD-to-Celo-Native-Asset-CELO-

**Comment by rxlxrxsx** [comment]
One user reported the same behavior.
`##########################################
###   Celo Arbitrage strategy config   ###
##########################################

template_version: 1
strategy: celo_arb

# The following configuations are only required for the Celo arbitrage trading strategy

# Exchange and token parameters
secondary_exchange: bittrex
secondary_market: CELO-USDT
order_amount: 10.0

# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 0.05

# A buffer to add to the Celo price to account for slippage when buying/selling on celocli
# (Enter 1 for 1%)
celo_slippage_buffer: 0.01

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters`

[logs_conf_celo_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/4824691/logs_conf_celo_arb_1.log)
