### ISSUE TITLE
[BUG] Radar Relay fetching status update for previous orders eventually hitting request limit

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1923]
**Describe the bug**

Radar Relay keeps fetching status update for previous orders that were long cancelled/expired.

```
2020-06-24 04:32:45,103 - 1 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Error fetching status update for the order buy-WETH-DAI-1592967461002594: Error fetching data from https://api.radarrelay.com/v3/orders/0xba39f46864a10f470a5c788d488929c32806813892af3e3a87b0eb1c127264e2. HTTP status is 429 - Too many requests, please try again later...
2020-06-24 04:32:45,103 - 1 - hummingbot.market.radar_relay.radar_relay_market - WARNING - Failed to fetch status update for the order buy-WETH-DAI-1592967461002594. Check Ethereum wallet and network connection.
2020-06-24 04:32:45,103 - 1 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Error fetching status update for the order buy-WETH-DAI-1592967671002153: Error fetching data from https://api.radarrelay.com/v3/orders/0x45164e69597af3d03d9df4c5833424fb6b03a4c6519e9cf9a2dc15b5e4ec3755. HTTP status is 429 - Too many requests, please try again later...
2020-06-24 04:32:45,103 - 1 - hummingbot.market.radar_relay.radar_relay_market - WARNING - Failed to fetch status update for the order buy-WETH-DAI-1592967671002153. Check Ethereum wallet and network connection.
2020-06-24 04:32:45,104 - 1 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Error fetching status update for the order sell-WETH-DAI-1592967671002430: Error fetching data from https://api.radarrelay.com/v3/orders/0xf9e456ce484a92710f8168c6cc48f56e8d4fe4c16704e0acd6def231ca4f8423. HTTP status is 429 - Too many requests, please try again later...
2020-06-24 04:32:45,104 - 1 - hummingbot.market.radar_relay.radar_relay_market - WARNING - Failed to fetch status update for the order sell-WETH-DAI-1592967671002430. Check Ethereum wallet and network connection.
2020-06-24 04:32:45,104 - 1 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Error fetching status update for the order buy-WETH-DAI-1592968366001717: Error fetching data from https://api.radarrelay.com/v3/orders/0x9289f6dc9a5a9fbb415aaa0ee0f76541d725cfea773b16b713fc45699c548db8. HTTP status is 429 - Too many requests, please try again later...
2020-06-24 04:32:45,104 - 1 - hummingbot.market.radar_relay.radar_relay_market - WARNING - Failed to fetch status update for the order buy-WETH-DAI-1592968366001717. Check Ethereum wallet and network connection.
```

![](https://user-images.githubusercontent.com/50150287/85503222-b37e6a00-b61b-11ea-93c0-48377ba17f55.png)

One of the orders `buy-WETH-DAI-1592967461002594` was created 2 hours ago.

![](https://user-images.githubusercontent.com/50150287/85503216-b0837980-b61b-11ea-905d-08c0d524527c.png)

![image](https://user-images.githubusercontent.com/50150287/85503179-9b0e4f80-b61b-11ea-88da-8e8a15dbe104.png)

This will eventually result to errors when creating new orders.

```
2020-06-24 04:32:48,044 - 1 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Error submitting sell order to Radar Relay for 0.100000000 WETH-DAI.
Traceback (most recent call last):
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 618, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket._api_request
    raise IOError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 787, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket.execute_trade
    exchange_order_id, zero_ex_order = await self.submit_limit_order(trading_pair=trading_pair,
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 711, in submit_limit_order
    unsigned_limit_order = await self.request_unsigned_limit_order(trading_pair=trading_pair,
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 658, in request_unsigned_limit_order
    return await self._api_request(http_method="post", url=url, data=data)
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 599, in _api_request
    async with aiohttp.ClientSession() as client:
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 600, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket._api_request
    async with (
  File "hummingbot/market/radar_relay/radar_relay_market.pyx", line 625, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket._api_request
    raise IOError(f"Error fetching data from {url}. "
OSError: Error fetching data from https://api.radarrelay.com/v3/markets/WETH-DAI/order/limit. HTTP status is 429 - Too many requests, please try again later..
2020-06-24 04:32:48,045 - 1 - hummingbot.market.radar_relay.radar_relay_market - WARNING - Failed to submit sell order to Radar Relay. Check Ethereum wallet and network connection.
2020-06-24 04:32:48,048 - 1 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Error submitting buy order to Radar Relay for 0.048230330 WETH-DAI.
```

**Release version**
dev-0.29.0

**Attachments**
[test_radar_relay.log](https://github.com/CoinAlpha/hummingbot/files/4823292/test_radar_relay.log)
[config_test_radar_relay.txt](https://github.com/CoinAlpha/hummingbot/files/4823293/config_test_radar_relay.txt)
[hummingbot_trades.zip](https://github.com/CoinAlpha/hummingbot/files/4823294/hummingbot_trades.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1c8y) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Closing ticket, connector has been deprecated.
