### ISSUE TITLE
[BUG] Log errors after running `celo-arb` for a while

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1965]
**Describe the bug**
Running `celo-arb` seems to work initially, but after a few hours, I see log errors of the form:
```
2020-06-28 16:44:09,102 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

My memory usage was 61%, so I restarted the AWS instance which brought down to 30%.

Starting the strategy again, the log errors don't show, so I suspect there's a memory leak somewhere.

**Steps To Reproduce**
I used the [Celo Quickstart guide](https://docs.hummingbot.io/strategies/celo-arb/quickstart/)
- AWS t2.small instance
- Celo ultra-light node
- Docker build v0.28.1
- secondary market: CELO/USD on Bittrex

I also started and stopped the bot numerous times as I was configuring the strategy.

**Attachments**
[logs_conf_celo_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/4842698/logs_conf_celo_arb_1.log)

**Comment by haferman** [comment]
We are seeing the same error in our logs.

- AWS t3a.large instance
- Celo ultra-light node
- Docker build v0.28.1
- secondary market: CELO/USD on Bittrex

Memory usage is only 2.4 GB out of 3.7 available, and load on each of the 2 cores is only about 50%.

**Comment by mifeng** [comment]
I believe this error is due to elevated memory usage in smaller instances. I have run this on a `t2.medium` AWS instance over the past month and don't see this issue anymore.
