### ISSUE TITLE
[BUG] Arbitrage | Huobi - Parameter amount is invalid

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#2010]
**Describe the bug**

Huobi orders are failing when used as an exchange for running Arbitrage strategy.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up an arbitrage strategy using Huobi as one of the exchange
2. Start the strategy. Once the opportunity is available, the other exchange will execute/fill the other while the Huobi exchange will fail to fill the order

Here are the logs
```
2020-07-08 19:06:44,296 - 14032 - hummingbot.market.huobi.huobi_market - ERROR - Error received from https://api.huobi.pro/v1/order/orders/place. Response is {'status': 'error', 'err-code': 'invalid-amount', 'err-msg': 'Parameter `amount` is invalid.', 'data': None}.
2020-07-08 19:06:44,297 - 14032 - hummingbot.market.huobi.huobi_market - NETWORK - Error submitting buy MARKET order to Huobi for 0.0000 crousdt .
Traceback (most recent call last):
  File "hummingbot\market\huobi\huobi_market.pyx", line 651, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_buy
  File "hummingbot\market\huobi\huobi_market.pyx", line 616, in place_order
  File "hummingbot\market\huobi\huobi_market.pyx", line 302, in _api_request
  File "hummingbot\market\huobi\huobi_market.pyx", line 313, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
hummingbot.market.huobi.huobi_market.HuobiAPIError: {'error': {'status': 'error', 'err-code': 'invalid-amount', 'err-msg': 'Parameter `amount` is invalid.', 'data': None}}
2020-07-08 19:06:44,297 - 14032 - hummingbot.market.huobi.huobi_market - WARNING - Failed to submit buy order to Huobi. Check API key and network connection.
2020-07-08 19:06:44,299 - 14032 - hummingbot.strategy.arbitrage.arbitrage - INFO - Market order failed on huobi: buy-crousdt-1594228003992982 [clock=2020-07-08 17:06:44+00:00]
2020-07-08 19:06:44,303 - 14032 - hummingbot.market.kucoin.kucoin_market - INFO - Created OrderType.MARKET sell order sell-CRO-USDT-1594228003992983 for 221.5600 CRO-USDT.
2020-07-08 19:06:44,303 - 14032 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1594228004.0, "type": "OrderType.MARKET", "trading_pair": "CRO-USDT", "amount": 221.56, "price": 0.0, "order_id": "sell-CRO-USDT-1594228003992983", "event_name": "SellOrderCreatedEvent", "event_source": "kucoin"}

```
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.28.1

**Attachments**

[arb-CROUSDT.txt](https://github.com/CoinAlpha/hummingbot/files/4892708/arb-CROUSDT.txt)

[logs_arbtest.log](https://github.com/CoinAlpha/hummingbot/files/4892705/logs_arbtest.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:  Raegwyn

**Comment by dennisocana** [comment]
@rxlxrxsx @RC-13 please check if we're still getting this issue in the current release

**Comment by RC-13** [comment]
Run arbitrage strategy using Huobi and Binance exchange under version 0.21.0, error did not persist after getting a filled order on Huobi.
![Arbitrage trade](https://user-images.githubusercontent.com/57189990/97495064-2faa0500-19a2-11eb-9ad8-ebafb66d77c7.PNG)
