### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: 'scripts/'

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2014]
**Describe the bug**

In the latest Docker development brach, exits Hummingbot back to terminal after entering password and returns this error :

```
Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 154, in <module>
    main()
  File "bin/hummingbot_quickstart.py", line 150, in main
    asyncio.get_event_loop().run_until_complete(quick_start(args))
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bin/hummingbot_quickstart.py", line 90, in quick_start
    hb = HummingbotApplication.main_application()
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 87, in main_application
    cls._main_app = HummingbotApplication()
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 94, in __init__
    input_handler=self._handle_command, bindings=load_key_bindings(self), completer=load_completer(self)
  File "/home/hummingbot/hummingbot/client/ui/completer.py", line 190, in load_completer
    return HummingbotCompleter(hummingbot_application)
  File "/home/hummingbot/hummingbot/client/ui/completer.py", line 37, in __init__
    self._py_file_completer = WordCompleter(file_name_list(SCRIPTS_PATH, "py"))
  File "/home/hummingbot/hummingbot/client/ui/completer.py", line 24, in file_name_list
    return sorted([f for f in listdir(path) if isfile(join(path, f)) and f.endswith(file_extension)])
FileNotFoundError: [Errno 2] No such file or directory: 'scripts/'
```

**Release version** : dev-0.29.0

```
 "branch": "development",
 "commit": "64eb425ce8e3267820e348952574f28bf5b9f431",
 "date": "2020-07-10T01:00:06Z",
 "maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```

**Comment by carlolm** [comment]
I added a fix to this here:
https://github.com/CoinAlpha/hummingbot/pull/2013#issuecomment-656893720

**Comment by Clint-G13** [comment]
Test issue after PR#2020 got merged, error no longer shows.
![bug#2014](https://user-images.githubusercontent.com/57189990/87218669-5870a500-c387-11ea-842b-670ff85ea89c.gif)

```
"branch": "development",
"commit": "e07e2050ab8742e440e168b07f9562cae431fbac",
"date": "2020-07-11T05:04:26Z",
"maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```
