### ISSUE TITLE
[BUG] IndexError: list index out of range errors

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2042]
**Describe the bug**
Running a bot with order optimization enabled, the bot crashed with repeating log errors:
```
2020-07-14 02:25:10,002 - 27076 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 550, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    self.c_apply_order_price_modifiers(proposal)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 634, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_apply_order_price_modifiers
    self.c_apply_order_optimization(proposal)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 758, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_apply_order_optimization
    higher_sell_price = max(proposal.sells[0].price, price_below_ask)
IndexError: list index out of range
```
**Configuration**
- hanging orders enabled
- ping pong enabled
- order optimization enabled

**Release version**
`dev-0.29.0`

**Comment by mifeng** [comment]
Comment from @Nullably in Discord: 
```
There should be a check before accessing the buys and sells lists (to make sure they have at least an item in the list), should be a simple fix. I think this can happen when you use ping-pong and your sell orders  proposal is zero.
```

**Comment by dennisocana** [comment]
More steps to replicate the errors here: https://github.com/CoinAlpha/hummingbot/issues/1944
