### ISSUE TITLE
[BUG] Trading Fiat-Fiat on Kraken error

### ISSUE THREAD

**Issue by somethingaboutnothing** [CoinAlpha/hummingbot#2093]
**Describe the bug**
When starting the bot on kraken pair GBP-USD I get error "Unexpected error running clock tick. (See log file for stack trace dump)"
![image](https://user-images.githubusercontent.com/67629188/88183773-c9d31200-cc29-11ea-9e52-3f982f7aac31.png)

`2020-07-22 13:21:24,072 - 3152 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\core\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "hummingbot\strategy\pure_market_making\pure_market_making.pyx", line 583, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
  File "hummingbot\strategy\pure_market_making\pure_market_making.pyx", line 609, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
  File "hummingbot\strategy\pure_market_making\pure_market_making.pyx", line 338, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_get_mid_price
  File "hummingbot\strategy\market_trading_pair_tuple.py", line 33, in get_mid_price
  File "hummingbot\market\market_base.pyx", line 109, in hummingbot.market.market_base.MarketBase.get_mid_price
  File "hummingbot\market\market_base.pyx", line 316, in hummingbot.market.market_base.MarketBase.get_price
  File "hummingbot\market\market_base.pyx", line 215, in hummingbot.market.market_base.MarketBase.c_get_price
  File "hummingbot\market\market_base.pyx", line 190, in hummingbot.market.market_base.MarketBase.c_quantize_order_price
  File "hummingbot\market\kraken\kraken_market.pyx", line 1126, in hummingbot.market.kraken.kraken_market.KrakenMarket.c_get_order_price_quantum
KeyError: 'GBPUSD'`

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/67629188/88183542-811b5900-cc29-11ea-8502-7f41ad62ffa6.png)

**Screenshots**
See above

**Release version**
Version 0.29.0

**Optional: your discord username:**
5sdfg34

**Comment by PtrckM** [comment]
Able to replicate it, but it does work on paper trade and stable coin on live.

- live fiat
![image](https://user-images.githubusercontent.com/54516858/88185092-19cfca00-cc66-11ea-83b9-31de5c7dcf2b.png)

- paper trade fiat
![image](https://user-images.githubusercontent.com/54516858/88186019-3f110800-cc67-11ea-8441-857dfcae9032.png)

- live stable coin
![image](https://user-images.githubusercontent.com/54516858/88186072-4df7ba80-cc67-11ea-9115-2190e57121d5.png)
![image](https://user-images.githubusercontent.com/54516858/88186112-5cde6d00-cc67-11ea-94b2-c88f8de2e004.png)

- logs

**Comment by Clint-G13** [comment]
Made a test using USD-CAD pair and was able to replicate the issue:
![config](https://user-images.githubusercontent.com/57189990/88255498-13376600-cceb-11ea-9200-c7dc35027ac0.PNG)
![error](https://user-images.githubusercontent.com/57189990/88255499-15012980-cceb-11ea-84fd-634c37034165.PNG)

Confirmed that I can place order manually on Kraken exchange:
![kraken](https://user-images.githubusercontent.com/57189990/88255511-1df1fb00-cceb-11ea-9ab9-300ae2a00cad.PNG)

**Comment by RC-13** [comment]
No longer seeing this error on version 0.31.0 [master], running fiat to fiat or crypto to fiat pair. Test done using windows binary, WSL source, and docker build[docker toolbox].
![image](https://user-images.githubusercontent.com/57189990/92655729-6e1d2f00-f324-11ea-9b8e-8e881d146c87.png)

**Comment by dennisocana** [comment]
QA confirmed this is fixed in version 0.31 after standardizing trading pair names across all connectors.
