### ISSUE TITLE
[BUG] Bamboo_relay market object has no attribute '_withdraw_rules'

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2141]
**Describe the bug**
bamboo_relay unable to start using ARB, PMM and XEMM strategy. Similar to https://github.com/CoinAlpha/hummingbot/issues/2121

**Steps To Reproduce**
`connect ethereum`
`create`
`start`

- **ARB**
![image](https://user-images.githubusercontent.com/54516858/89171748-28967500-d5b4-11ea-8aad-e4bca2873e2f.png)

- **XEMM**
![image](https://user-images.githubusercontent.com/54516858/89171779-33e9a080-d5b4-11ea-9ee2-8a11d6beea71.png)

- **PMM**
![image](https://user-images.githubusercontent.com/54516858/89171803-3b10ae80-d5b4-11ea-8279-5c9314c21796.png)

- from logs
```
2020-07-30 11:24:28,239 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket' object has no attribute '_withdraw_rules'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 84, in start_check
    await self.start_market_making(self.strategy_name)
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 90, in start_market_making
    start_strategy(self)
  File "/home/hummingbot/hummingbot/strategy/arbitrage/start.py", line 34, in start
    self._initialize_markets(market_names)
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 275, in _initialize_markets
    market = BambooRelayMarket(
  File "hummingbot/market/bamboo_relay/bamboo_relay_market.pyx", line 187, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.__init__
    self._withdraw_rules = {}
AttributeError: 'hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket' object has no attribute '_withdraw_rules'
2020-07-30 11:27:21,656 - 1 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
```

- version dev-0.30.0

**Comment by PtrckM** [comment]
confirmed fix on development

![image](https://user-images.githubusercontent.com/54516858/89409031-f885d800-d753-11ea-8b3c-052bfffce4b2.png)
