### ISSUE TITLE
[BUG] Eterbase does not support paper trading mode

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2147]
**Describe the bug**

Eterbase does not support paper trading mode. When you get this error, you can't start the strategy even after running config exchange. You have to exit Hummingbot and restart the session.

```
2020-08-04 12:33:30,245 - 4664 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/Users/dennis/Desktop/GitHub/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 55, in start
    self._initialize_markets(market_names)
  File "/Users/dennis/Desktop/GitHub/hummingbot/hummingbot/client/hummingbot_application.py", line 244, in _initialize_markets
    market = create_paper_trade_market(market_name, trading_pairs)
  File "/Users/dennis/Desktop/GitHub/hummingbot/hummingbot/market/paper_trade/__init__.py", line 54, in create_paper_trade_market
    raise Exception(f"Market {exchange_name.upper()} is not supported with paper trading mode.")
Exception: Market ETERBASE is not supported with paper trading mode.
```

**Steps To Reproduce**

Run ``paper_trade`` mode with Eterbase as the exchange.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/89253448-495fd880-d64f-11ea-9675-eacb24619bd8.png)

**Release version**

version-0.29.0

**Comment by dennisocana** [comment]
@eterbase for your reference. We are formalizing connector guidelines, and this feature will be in the guidelines for connectors to stay certified.
