### ISSUE TITLE
Running arbitrage on DEX broken due to errors with flat fee

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2158]
**Describe the bug**
When starting an arbitrage strategy using a decentralized exchange, error `Unexpected error running clock tick. (See log file for stack trace dump)` immediately occur. It happens both during live trade and paper trading. I believe this error is causing Arbitrage to stop executing any trade even if there are opportunities.

```
2020-08-02 23:09:26,005 - 4748 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\core\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 179, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 312, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 332, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair_inner
  File "hummingbot\strategy\arbitrage\arbitrage.pyx", line 441, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_find_best_profitable_amount
  File "hummingbot\strategy\strategy_base.pyx", line 291, in hummingbot.strategy.strategy_base.StrategyBase.c_sum_flat_fees
Exception: Flat fee in other token than quote asset is not supported.
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Create an Arbitrage strategy.
1. Use decentralize exchange in both primary and secondary markets.
1. Start strategy and you will see a continuous `Unexpected error running clock tick` on the log pane.
1. Stop and start the strategy, this time, the error won't show however there won't be any trade that will be executed even if there are possible opportunities.
...

**Screenshots**
![arb](https://user-images.githubusercontent.com/57189990/89326424-db51fa80-d6bc-11ea-8dd2-b0d4be610e7a.png)
![unexpected error](https://user-images.githubusercontent.com/57189990/89326476-ef95f780-d6bc-11ea-82af-d6a30cb5d3af.JPG)
After restarting the strategy, error disappear however no orders are getting created or executed despite having a positive opportunity.
![arb-dex](https://user-images.githubusercontent.com/57189990/89326418-d725dd00-d6bc-11ea-8ce7-d03cb60d64f4.png)

**Release version**
0.29.0 and 0.30.0

**Attachments**
[logs_conf_arb_5 (1).log](https://github.com/CoinAlpha/hummingbot/files/5023649/logs_conf_arb_5.1.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak56h) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
No longer getting the error, tested using Loopring connector since connectors used in the ticket are already deprecated.
![image](https://user-images.githubusercontent.com/57189990/144792763-cd308de2-9d6d-4e3c-b446-ddc6c37b1ebe.png)
