### ISSUE TITLE
[BUG] Intermittent errors on Kraken fetching last trade price

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2205]
**Describe the bug**

Intermittent errors when executing ``get_last_traded_price`` but no major impact seen on orders. This also doesn't happen all the time but we're seeing this quite a lot in a day. Might be related to the issue seen in [#2204](https://github.com/CoinAlpha/hummingbot/issues/2204)

**Steps To Reproduce**

Run a pure market making strategy on Kraken.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/90003799-32605c80-dcc7-11ea-875c-c6e104ed0879.png)

```
"branch": "development",
"commit": "7659cfeee8ae7032647b466c335255eed417b084",
"date": "2020-08-11T02:22:37Z",
```

**Release version**

dev-0.30.0

**Attachments**

[logs_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/5061910/logs_kraken_btc-usdc.log)

**Comment by Clint-G13** [comment]
I saw similar error with KuCoin when I was checking an Arbitrage issue, found this error:
```
2020-08-17 00:51:33,196 - 4720 - hummingbot.market.kucoin.kucoin_order_book_tracker - NETWORK - Unexpected error while fetching last trade price.
Traceback (most recent call last):
  File "hummingbot\core\data_type\order_book_tracker.py", line 157, in _update_last_trade_prices_loop
  File "hummingbot\market\kucoin\kucoin_api_order_book_data_source.py", line 53, in get_last_traded_prices
  File "site-packages\aiohttp\client.py", line 582, in _request
  File "site-packages\aiohttp\helpers.py", line 596, in __exit__
asyncio.exceptions.TimeoutError
```
[logs_conf_arb_dgbusdt.txt](https://github.com/CoinAlpha/hummingbot/files/5087351/logs_conf_arb_dgbusdt.txt)
version: 0.30.0 (master)
