### ISSUE TITLE
[BUG] PermissionError: [Errno 13] Permission denied: 'conf/encrypted_default.json'

### ISSUE THREAD

**Issue by shayanb** [CoinAlpha/hummingbot#2249]
**Describe the bug**
On a clean install of Ubuntu and following the installation from [docs](https://docs.hummingbot.io/installation/docker/linux/), the setup fails.

**Steps To Reproduce**
Follow the documentation to install on digitalOcean instance, using Docker. This error happens as soon as I enter a password to encrypt keys in the wizard setup. 

**Screenshots**
```

Press [Enter] to continue
Unable to find image 'coinalpha/hummingbot:latest' locally
latest: Pulling from coinalpha/hummingbot
3ff22d22a855: Pull complete
e7cb79d19722: Pull complete
323d0d660b6a: Pull complete
b7f616834fd0: Pull complete
dfd5a91dbc21: Pull complete
f80a4b571b9e: Pull complete
6df8aaba3145: Pull complete
7494f02a9af9: Pull complete
5cd2362429ba: Pull complete
a785eda1f7f7: Pull complete
Digest: sha256:ecd5fe61260425472aedb2df7c5fdefafbaaad6c870731fcbbbde2fa238181f2
Status: Downloaded newer image for coinalpha/hummingbot:latest
Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 154, in <module>
    main()
  File "bin/hummingbot_quickstart.py", line 147, in main
    if not login_prompt():
  File "/home/hummingbot/hummingbot/client/ui/__init__.py", line 109, in login_prompt
    Security.update_secure_config("default", dummy)
  File "/home/hummingbot/hummingbot/client/config/security.py", line 100, in update_secure_config
    encrypt_n_save_config_value(key, new_value, cls.password)
  File "/home/hummingbot/hummingbot/client/config/config_crypt.py", line 53, in encrypt_n_save_config_value
    with open(file_path, 'w+') as f:
PermissionError: [Errno 13] Permission denied: 'conf/encrypted_default.json'
```

**Release version**
latest

**Comment by Clint-G13** [comment]
@shayanb Can you try the following steps:

 Change the permission on hummingbot folder
`sudo chmod a+rw <your_hummingbot_conf_folder>/*` or
`sudo chmod -R 777 instance-name_files/`

If the step above won't work, continue with these steps:
```
# Allow docker commands without requiring sudo prefix
sudo usermod -a -G docker $USER

# Restart by closing the terminal
exit

# Launch your instance and run create command again
./create.sh
```

**Comment by shayanb** [comment]
@Clint-G13 thanks, the permission on humminbot folder worked. I think this step should be added to `create.sh` script.
