### ISSUE TITLE
[BUG] Invalid_nonce error while running crypto.com on Windows binary

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2315]
**Describe the bug**

Discord user **MiBan** and **Dodecane** reported an invalid_nonce error while running crypto.com connector on Windows binary.  The error cause orders not to be created or cancelled.

Cross exchange error:
```
2020-09-11 15:47:24,503 - 796 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - ERROR - Error fetching data from https://api.crypto.com/v2/private/get-account-summary. HTTP status is 400. Message: {'id': 1599810444007536, 'method': 'private/get-account-summary', 'code': 10007, 'message': 'INVALID_NONCE'}
Traceback (most recent call last):
  File "hummingbot\connector\exchange\crypto_com\crypto_com_exchange.py", line 557, in _status_polling_loop
  File "hummingbot\core\utils\async_utils.py", line 22, in safe_gather
  File "hummingbot\connector\exchange\crypto_com\crypto_com_exchange.py", line 578, in _update_balances
  File "hummingbot\connector\exchange\crypto_com\crypto_com_exchange.py", line 341, in _api_request
OSError: Error fetching data from https://api.crypto.com/v2/private/get-account-summary. HTTP status is 400. Message: {'id': 1599810444007536, 'method': 'private/get-account-summary', 'code': 10007, 'message': 'INVALID_NONCE'}
```
Pure market making error:
```
2020-09-10 18:59:24,679 - 5788 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - NETWORK - Failed to cancel order sell-ETH-CRO-1599756775005362: Error fetching data from https://api.crypto.com/v2/private/cancel-order. HTTP status is 400. Message: {'id': 1599757075003696, 'method': 'private/cancel-order', 'code': 10007, 'message': 'INVALID_NONCE'}
Traceback (most recent call last):
  File "hummingbot\connector\exchange\crypto_com\crypto_com_exchange.py", line 526, in _execute_cancel
  File "hummingbot\connector\exchange\crypto_com\crypto_com_exchange.py", line 341, in _api_request
OSError: Error fetching data from https://api.crypto.com/v2/private/cancel-order. HTTP status is 400. Message: {'id': 1599757075003696, 'method': 'private/cancel-order', 'code': 10007, 'message': 'INVALID_NONCE'}
```
**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy or cross exchange strategy 
2. Use Crypto.com exchange as market, for cross exchange, set Crypto.com as the taker market.
3. Run the strategy

**Release version**

0.31.0

**Attachments**

[logs_conf_cro_eth.log](https://github.com/CoinAlpha/hummingbot/files/5211911/logs_conf_cro_eth.log)
[logs_cro-usdt-cross_test.log](https://github.com/CoinAlpha/hummingbot/files/5211912/logs_cro-usdt-cross_test.log)
[ETH-CRO.txt](https://github.com/CoinAlpha/hummingbot/files/5211918/ETH-CRO.txt)

**Comment by dennisocana** [comment]
Also ran into this on Hummingbot installed from source running on an AWS Linux cloud server.

[logs_crypto_cro-btc.log](https://github.com/CoinAlpha/hummingbot/files/5214058/logs_crypto_cro-btc.log)

**Comment by eerdik** [comment]
I have exactly the same error message.
Steps to reproduce:
1) Create Hummingbot instance (Docker, Windows 10)
2) Connect Crypto.com
3) Enter API 
4) it will ALWAYS show this error
![1f85ae2c-99cb-4c1d-9c63-a9a3a64dc62f](https://user-images.githubusercontent.com/42282706/115983354-e75e4f00-a5a0-11eb-9f5a-ba48efc0b577.gif)

**Comment by RC-13** [comment]
@eerdik Are you still experiencing this issue when connecting your crypto.com API key using the Hummingbot installed thru docker desktop or Hummingbot binary (exe)? This issue tends to occur if there is a [time discrepancy](https://exchange-docs.crypto.com/spot/index.html#response-and-reason-codes) between the crypto.com server and your device. Changing your device time to [internet time server](https://www.windowscentral.com/how-manage-time-servers-windows-10) might help if this issue still persists. I Will close this ticket for now and will re-open it if needed.
