### ISSUE TITLE
[BUG] Websocket connection issues on crypto.com connector

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2318]
**Describe the bug**

Websocket connection issues found in logs although no major impact on orders such as uncancelled orders in exchange, duplicate orders, etc. Logging a ticket in GitHub for tracking.

```
2020-09-11 14:27:44,363 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...
2020-09-11 14:27:52,002 - 22483 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Not cancelling active orders since difference between new order prices and current order prices is within 0.00% order_refresh_tolerance_pct
2020-09-11 14:27:54,708 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-09-11 14:28:05,223 - 22483 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error fetching OrderBook for CRO-BTC at crypto_com. HTTP status is 504.
Traceback (most recent call last):
  File "/home/ubuntu/crypto_cro-btc/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/crypto_cro-btc/hummingbot/core/data_type/order_book_tracker.py", line 174, in _init_order_books
    self._order_books[trading_pair] = await self._data_source.get_new_order_book(trading_pair)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 76, in get_new_order_book
    snapshot: Dict[str, Any] = await self.get_order_book_data(trading_pair)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 65, in get_order_book_data
    raise IOError(
OSError: Error fetching OrderBook for CRO-BTC at crypto_com. HTTP status is 504.
```

```
2020-09-11 18:45:20,501 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 177, in listen_for_order_book_snapshots
    snapshot: Dict[str, any] = await self.get_order_book_data(trading_pair)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 65, in get_order_book_data
    raise IOError(
OSError: Error fetching OrderBook for CRO-BTC at crypto_com. HTTP status is 504.

2020-09-11 18:45:20,501 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 5 seconds. Check network connection.
2020-09-11 18:45:20,541 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_websocket - ERROR - Websocket error: 'server rejected WebSocket connection: HTTP 504'
Traceback (most recent call last):
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 40, in connect
    self._client = await websockets.connect(self._WS_URL)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 504

2020-09-11 18:45:20,543 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 98, in listen_for_trades
    await ws.subscribe(list(map(
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 114, in subscribe
    return await self.request("subscribe", {
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 110, in request
    return await self._emit(method, data)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 104, in _emit
    await self._client.send(ujson.dumps(payload))
AttributeError: 'NoneType' object has no attribute 'send'

2020-09-11 18:45:20,544 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
```

```
2020-09-11 19:14:08,883 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_api_user_stream_data_source - ERROR - Unexpected error with CryptoCom WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_user_stream_data_source.py", line 68, in listen_for_user_stream
    async for msg in self._listen_to_orders_trades_balances():
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_user_stream_data_source.py", line 53, in _listen_to_orders_trades_balances
    raise e
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_user_stream_data_source.py", line 45, in _listen_to_orders_trades_balances
    await ws.subscribe(["user.order", "user.trade", "user.balance"])
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 114, in subscribe
    return await self.request("subscribe", {
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 110, in request
    return await self._emit(method, data)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 104, in _emit
    await self._client.send(ujson.dumps(payload))
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

Error when fetching last trade price.

```
2020-09-11 22:30:01,826 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_order_book_tracker - NETWORK - Unexpected error while fetching last trade price.
Traceback (most recent call last):
  File "/home/ubuntu/crypto_cro-btc/hummingbot/core/data_type/order_book_tracker.py", line 157, in _update_last_trade_prices_loop
    last_prices = await self._data_source.get_last_traded_prices(outdateds)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 45, in get_last_traded_prices
    resp_json = await resp.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.crypto.com/v2/public/get-ticker')
```

Error fetching OrderBook status.

```
2020-09-11 23:17:19,886 - 22483 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error fetching OrderBook for CRO-BTC at crypto_com. HTTP status is 504.
Traceback (most recent call last):
  File "/home/ubuntu/crypto_cro-btc/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/crypto_cro-btc/hummingbot/core/data_type/order_book_tracker.py", line 174, in _init_order_books
    self._order_books[trading_pair] = await self._data_source.get_new_order_book(trading_pair)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 76, in get_new_order_book
    snapshot: Dict[str, Any] = await self.get_order_book_data(trading_pair)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 65, in get_order_book_data
    raise IOError(
OSError: Error fetching OrderBook for CRO-BTC at crypto_com. HTTP status is 504.
2020-09-11 23:17:20,098 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 177, in listen_for_order_book_snapshots
    snapshot: Dict[str, any] = await self.get_order_book_data(trading_pair)
  File "/home/ubuntu/crypto_cro-btc/hummingbot/connector/exchange/crypto_com/crypto_com_api_order_book_data_source.py", line 65, in get_order_book_data
    raise IOError(
OSError: Error fetching OrderBook for CRO-BTC at crypto_com. HTTP status is 504.
2020-09-11 23:17:20,098 - 22483 - hummingbot.connector.exchange.crypto_com.crypto_com_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 5 seconds. Check network connection.
```

Installation type: Source
Version: 0.31.0
Machine: AWS EC2 instance
Operating system: Linux

Log file: [logs_crypto_cro-btc_1.log](https://github.com/CoinAlpha/hummingbot/files/5214274/logs_crypto_cro-btc_1.log)
Config file: [crypto_cro-btc.txt](https://github.com/CoinAlpha/hummingbot/files/5214279/crypto_cro-btc.txt)

**Comment by rxlxrxsx** [comment]
Logging a new Websocket connection issue that caused the bot to loop on cancelling the orders. After this error occurred the bot got stuck trying to cancel the order whenever it's time to create new orders.

```
2020-10-30 06:33:42,391 - 24659 - hummingbot.connector.exchange.crypto_com.crypto_com_websocket - ERROR - Websocket error: 'server rejected WebSocket connection: HTTP 502'
Traceback (most recent call last):
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 40, in connect
    self._client = await websockets.connect(self._WS_URL)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
2020-10-30 06:33:47,395 - 24659 - hummingbot.connector.exchange.crypto_com.crypto_com_api_user_stream_data_source - ERROR - Unexpected error with CryptoCom WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_api_user_stream_data_source.py", line 68, in listen_for_user_stream
    async for msg in self._listen_to_orders_trades_balances():
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_api_user_stream_data_source.py", line 53, in _listen_to_orders_trades_balances
    raise e
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_api_user_stream_data_source.py", line 45, in _listen_to_orders_trades_balances
    await ws.subscribe(["user.order", "user.trade", "user.balance"])
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 114, in subscribe
    return await self.request("subscribe", {
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 110, in request
    return await self._emit(method, data)
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_websocket.py", line 104, in _emit
    await self._client.send(ujson.dumps(payload))
AttributeError: 'NoneType' object has no attribute 'send'
```

Installation type: Source
Version: dev-0.33.0
Machine: AWS EC2 instance
Operating system: Linux


[cryptocom_cro-btc.txt](https://github.com/CoinAlpha/hummingbot/files/5464387/cryptocom_cro-btc.txt)
[logs_crypto_cro-btc.log](https://github.com/CoinAlpha/hummingbot/files/5464389/logs_crypto_cro-btc.log)

**Comment by bonez56** [comment]
I'm also having this problem. It was occurring on version 0.32 stable and also now on 0.33 stable. The bot won't trade for more than 15-30 minutes before it just stops communicating with the API.

It happens on both my home Debian 10 PC and also on a cloud based VPS running Debian 10.

I don't see anything appear unusual in the status pane, the bot simply stops communicating with the API and therefore stops trading. Any orders that were submitted to the API before this happens remain on the exchange, once they are filled, no new orders are submitted.

I've resorted to running a cron job to kill my hummingbot docker instances every 30 minutes and restart them, which is less than ideal.

Happy to submit logs but may need some guidance on exactly what to submit.
