### ISSUE TITLE
[BUG]Fail to submit order due to  HTTP status is 400, Message: "BAD_REQUEST"

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2326]
**Describe the bug**
Discord user **Raegwyn** reported a `HTTP status is 400, Message: "BAD_REQUEST"` while running cross exchange market making strategy and set crypto.com as taker market. When order maker order gets a fill, the taker side fails to submit with the following error message:
```
2020-09-10 22:19:34,286 - 7124 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - NETWORK - Error submitting SELL LIMIT order to Crypto.com for 0.10000 ETH-USDT NaN.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\crypto_com\crypto_com_exchange.py", line 449, in _create_order
  File "hummingbot\connector\exchange\crypto_com\crypto_com_exchange.py", line 341, in _api_request
OSError: Error fetching data from https://api.crypto.com/v2/private/create-order. HTTP status is 400. Message: {'id': 1599769172940180, 'method': 'private/create-order', 'code': 10004, 'message': 'BAD_REQUEST'}
2020-09-10 22:19:34,287 - 7124 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - WARNING - Error fetching data from https://api.crypto.com/v2/private/create-order. HTTP status is 400. Message: {'id': 1599769172940180, 'method': 'private/create-order', 'code': 10004, 'message': 'BAD_REQUEST'}
```

@rxlxrxsx was able to encounter the same issue while running cross exchange on Bittrex
```
2020-09-10 04:28:55,518 - 14933 - hummingbot.connector.exchange.bittrex.bittrex_market - NETWORK - Error submitting buy limit order to Bittrex for 0.02000000 ETH-USDT NaN.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/bittrex/bittrex_market.pyx", line 747, in hummingbot.connector.exchange.bittrex.bittrex_market.BittrexMarket.execute_buy
    order_result = await self.place_order(order_id,
  File "hummingbot/connector/exchange/bittrex/bittrex_market.pyx", line 708, in place_order
    api_response = await self._api_request("POST", path_url=path_url, body=body)
  File "hummingbot/connector/exchange/bittrex/bittrex_market.pyx", line 991, in _api_request
    async with client.request(http_method,
  File "hummingbot/connector/exchange/bittrex/bittrex_market.pyx", line 999, in hummingbot.connector.exchange.bittrex.bittrex_market.BittrexMarket._api_request
    raise IOError(f"Error fetching response from {http_method}-{url}. HTTP Status Code {response.status}: "
OSError: Error fetching response from POST-https://api.bittrex.com/v3/orders. HTTP Status Code 400: {'code': 'BAD_REQUEST', 'detail': 'Refer to the data field for specific field validation failures or extra fields in the body that were rejected.', 'data': {'newOrder.limit': ['Error converting value "NaN" to type \'System.Nullable`1[System.Decimal]\'. Path \'limit\', line 1, position 97.']}}
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a cross exchange market making strategy and set a Binance as maker and Crypto.com as taker.
2. Start strategy and wait for orders to get a fill.
3. Check logs and you will see a message saying that taker order fails to submit.
...

**Screenshots**
![unknown (1)](https://user-images.githubusercontent.com/57189990/93144476-a6ee4700-f71c-11ea-8f6a-55ba00e5518e.png)

**Release version**
0.31.0 - Windows Binary and Docker Toolbox

**Attachments**
[logs_xETH (1).log](https://github.com/CoinAlpha/hummingbot/files/5221399/logs_xETH.1.log)
[logs_xemm_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5221401/logs_xemm_eth-usdt.log)
[XEMM-crypto_com.txt](https://github.com/CoinAlpha/hummingbot/files/5221404/XEMM-crypto_com.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dennisocana** [comment]
May be related to this bug https://github.com/CoinAlpha/hummingbot/issues/2226 - @RC-13 @rxlxrxsx please check if this is still happening when a fix for the mentioned GitHub issue has been created.
