### ISSUE TITLE
[BUG]Orders stuck in Liquid due to timeout errors

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2342]
**Describe the bug**
Multiple timeouts resulted to losing track of order. Liquid testing bot encounter multiple timeouts, bot thought it failed to create a sell due to network issue however the order was pushed through on the exchange.
```
2020-09-15 12:33:34,018 - 30321 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.04 ETH, 373.03 USDT']
2020-09-15 12:33:34,019 - 30321 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.01 ETH, 380.57 USDT']
2020-09-15 12:33:35,368 - 30321 - hummingbot.connector.exchange.liquid.liquid_market - INFO - Successfully cancelled order buy-ETH-USDT-1600173092049721.
2020-09-15 12:33:35,376 - 30321 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1600173215.0, "order_id": "buy-ETH-USDT-1600173092049721", "event_name": "OrderCancelledEvent", "event_source": "liquid"}
2020-09-15 12:33:35,924 - 30321 - hummingbot.connector.exchange.liquid.liquid_market - INFO - Created OrderType.LIMIT_MAKER buy order buy-ETH-USDT-1600173214019073 for 0.04 ETH-USDT.
2020-09-15 12:33:35,933 - 30321 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1600173215.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "ETH-USDT", "amount": "0.04", "price": "373.03", "order_id": "buy-ETH-USDT-1600173214019073", "event_name": "BuyOrderCreatedEvent", "event_source": "liquid"}
2020-09-15 12:33:44,679 - 30321 - hummingbot.connector.exchange.liquid.liquid_market - NETWORK - Error submitting sell limit_maker order to Liquid for 0.01 ETH-USDT 380.57.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/liquid/liquid_market.pyx", line 985, in hummingbot.connector.exchange.liquid.liquid_market.LiquidMarket.execute_sell
    order_result = await self.place_order(order_id, trading_pair, decimal_amount, False, order_type, decimal_price)
  File "hummingbot/connector/exchange/liquid/liquid_market.pyx", line 865, in place_order
    order_result = await self._api_request("post", path_url=path_url, data=data)
  File "hummingbot/connector/exchange/liquid/liquid_market.pyx", line 312, in _api_request
    async with client.request(http_method,
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy and use Liquid as your exchange.
2. Run the strategy for long duration.
3. If errors keeps showing on the log pane, check the logs and exchange for stuck orders.
...

**Screenshots**
![Liquid stuck order](https://user-images.githubusercontent.com/57189990/93403453-21a09900-f8ba-11ea-8e0c-80498ff8af0d.PNG)

**Release version**
0.31.0

**Attachments**
[liquid.txt](https://github.com/CoinAlpha/hummingbot/files/5235449/liquid.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dennisocana** [comment]
We haven't ran into this error for 1 release or a month now. Feel free to re-open if this reoccurs.
