### ISSUE TITLE
[BUG] Unhandled error in background task when running with Telegram enabled

### ISSUE THREAD

**Issue by zappra** [CoinAlpha/hummingbot#2391]
Running with telegram enabled results in the following log output:

2020-09-27 14:49:55,560 - 576 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Unauthorized
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\start_command.py", line 74, in start_check
  File "hummingbot\client\hummingbot_application.py", line 361, in _initialize_notifiers
  File "hummingbot\notifier\telegram_notifier.py", line 99, in start
  File "site-packages\telegram\ext\updater.py", line 258, in start_polling
  File "site-packages\telegram\ext\jobqueue.py", line 311, in start
  File "site-packages\telegram\bot.py", line 54, in decorator
  File "<decorator-gen-1>", line 2, in get_me
  File "site-packages\telegram\bot.py", line 67, in decorator
  File "site-packages\telegram\bot.py", line 251, in get_me
  File "site-packages\telegram\utils\request.py", line 277, in get
  File "site-packages\telegram\utils\request.py", line 243, in _request_wrapper
telegram.error.Unauthorized: Unauthorized

This error occurs upon executing /start

Reproduced on both Windows and Mac binary installs, version 0.31.0

Telegram token and chat id have been successfully tested in another application and found to work ok. Token and ID entered via commands in Hummingbot UI.

**Comment by PtrckM** [comment]
I'm unable to reproduce this on my Windows 10 using Hummingbot binary installer version 0.31.0

![image](https://user-images.githubusercontent.com/54516858/94422930-68e03100-01ba-11eb-85f2-6dbd03297884.png)
![image](https://user-images.githubusercontent.com/54516858/94423000-8614ff80-01ba-11eb-9630-f6d2812e1950.png)
![image](https://user-images.githubusercontent.com/54516858/94423041-988f3900-01ba-11eb-8f1d-aba493873077.png)

viewing my `conf_global.yml` on a text editor
![image](https://user-images.githubusercontent.com/54516858/94423417-31be4f80-01bb-11eb-9428-cca4fd982d3d.png)

**Comment by zappra** [comment]
This is what I get
<img width="640" alt="screenshot" src="https://user-images.githubusercontent.com/35706360/94431214-e4c38480-018c-11eb-8f00-b07fb8a66c35.png">
[logs_conf_pure_mm_test.log](https://github.com/CoinAlpha/hummingbot/files/5292112/logs_conf_pure_mm_test.log)

**Comment by zappra** [comment]
Ah have found the cause. I was able to get it working by copying my bot token directly to the global.conf file. When using the 'config telegram_token' from within Hummingbot it incorrectly converts the token to all lower case
