### ISSUE TITLE
[BUG] Bot loop cancelling orders on Crypto.com connector

### ISSUE THREAD

**Issue by sigit2306** [CoinAlpha/hummingbot#2472]
**Describe the bug**
Some users reported issues running HB bot on Crypto.com connector:
- Bot failed to cancel orders on crypto.com but no open orders on the exchange platform 
- Bot loop canceling limit order where the real order is canceled, but the bot still thinks it is not canceled and keeps trying to cancel it.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Run a pure market making bot that connects to Crypto.com, setting order_levels to 4 is optional but users that reported this issue set it.
2. Let the bot run and made some trades, after some times, the bot loop canceling order(s).
3. When initiating stop/exit command, the bot shows message that it failed to cancel orders on crypto.com but no open orders on the exchange platform.
...

First user: 
**Screenshots**
Bot failed to cancel orders on crypto.com but user informed no open orders on exchange platform
![image](https://user-images.githubusercontent.com/12313129/95828500-4542ec00-0d5f-11eb-83af-7dc9950d8f0a.png)

Bot loop canceling limit order HBOT-B-BTC-USDT-1602236233001290 where the real order is canceled, but the bot still think is not canceled, and keeps trying to cancel it.
![image](https://user-images.githubusercontent.com/12313129/95835960-1598e180-0d69-11eb-9049-d53d6d988f44.png)

**Release version**
HB Windows binary version 0.32.0

**Attachments**
[first user.zip](https://github.com/CoinAlpha/hummingbot/files/5370030/first.user.zip)

Second user:
**Screenshots**
Bot loop canceling limit order HBOT-S-USDC-USDT-160246951900
![image](https://user-images.githubusercontent.com/12313129/95837451-d4093600-0d6a-11eb-820e-2e431a0b4c1c.png)

**Attachments**
[second user.zip](https://github.com/CoinAlpha/hummingbot/files/5370124/second.user.zip)

**Release version**
HB Docker build version 0.32.0 on a vps

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dennisocana** [comment]
Function `cancel_all` is intermittently failing.

```
2020-10-09 10:19:36,286 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - ERROR - Cancel all failed.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 711, in cancel_all
    results = await safe_gather(*tasks, return_exceptions=True)
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 715, in cancel_all
    successful_cancellations.append(CancellationResult(result, True))
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2020-10-09 10:19:36,287 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - NETWORK - Unexpected error cancelling orders.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 711, in cancel_all
    results = await safe_gather(*tasks, return_exceptions=True)
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 715, in cancel_all
    successful_cancellations.append(CancellationResult(result, True))
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2020-10-09 10:19:36,287 - 1 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - WARNING - Failed to cancel order on Crypto.com. Check API key and network connection.
```

**Comment by bonez56** [comment]
I assumed this behaviour was related to the websockets issue:
https://github.com/CoinAlpha/hummingbot/issues/2318

The reason for my assumption is because after some trades, the bot appears to lose connectivity with the crypto.com API, therefore it can't cancel existing or place new orders. The only way around this I have found is to set a cron job that kills the HB docker instance and restarts it. Often I only get 10-15 minutes of trading before the bot loses communication.
