### ISSUE TITLE
[BUG] raspberry: async utils - Unhandeld error in background task: Connector loopring class not found 

### ISSUE THREAD

**Issue by RobJah** [CoinAlpha/hummingbot#2528]
**Describe the bug**
When i run my freshly installed hummingbot on my raspi4B i cant seem to get past the point where i insert the api key for my loopring account. I get the error 'async utils - Unhandeld error in background task: Connector loopring class not found'
Also  I get another error on start up, but im not sure if it is related: hummingbot_cli - Unhandeld error in prompt_toolkit: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

**Steps To Reproduce**
I did every thing mentioned in this guid exept for the Multiple Nodes part: https://hummingbot.io/blog/2020-07-deploying-hummingbot-on-a-raspberry-pi/

Here are the steps to reproduce the issue (see attachments in the section below):
1. Try to connect a loopring account, get stranded at the api key
...

**Release version**
0.32.0

**Attachments**
didnt even get to the config

**Comment by PtrckM** [comment]
- the error first appears on version 0.31.0 this is due some new changes into the hummingbot
- this is not exchange specific 
- the error will show without doing anything. 
- the error doesn't show on docker build for raspberry pi only on source build
- still able to run a strategy but bot will throw some errors
- the raspberry pi hummingbot is still on beta.

```
2020-10-29 20:57:50,302 - 17921 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
```

```

2020-10-29 21:00:20,531 - 17921 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2020-10-29 21:00:21,597 - 17921 - hummingbot.connector.exchange.kraken.kraken_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-10-29 21:00:22,522 - 17921 - hummingbot.connector.exchange.kraken.kraken_order_book_tracker - INFO - Initialized order book for USDC-USDT. 1/1 completed.
2020-10-29 21:00:24,622 - 17921 - hummingbot.connector.exchange.kraken.kraken_exchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 455, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._user_stream_event_listener
    event_type: str = event_message[-1]
TypeError: Expected unicode, got dict
2020-10-29 21:00:29,632 - 17921 - hummingbot.connector.exchange.kraken.kraken_exchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 455, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._user_stream_event_listener
    event_type: str = event_message[-1]
TypeError: Expected unicode, got dict
```

**Comment by RobJah** [comment]
Hi Patrick,

Thanks for your respons. I think the main problem i'm experiencing is the other error i mentioned: async utils - Unhandeld error in background task: Connector loopring class not found

Do you have any suggestions about that error and what i possibly did wrong to get it? 
Because i just cant seem to get past the insertion of my api key. The strange thing is that when I exit the hummingbot and restart it to retry connecting the loopring account i do get the message 'do you want to delete your current api key?'
But when i try to start the humming bot all it says is "Preliminary checks:" but nothing follows, no orders get placed.

Thanks in advance!

**Comment by PtrckM** [comment]
I'm getting different output:

![image](https://user-images.githubusercontent.com/54516858/97596675-edcf9c00-1a3f-11eb-8a31-6666c079b293.png)

try installing dependencies from loopring: `bitstring pyblake2 pysha3`

`pip install pandas cython cachetools aiohttp ruamel.yaml eth_account aiokafka sqlalchemy binance python-binance ujson websockets signalr-client-aio web3 prompt_toolkit 0x-order-utils 0x-contract-wrappers eth_bloom pyperclip telegram python-telegram-bot pyjwt numpy mypy_extensions bitstring pyblake2 pysha3`

**Comment by RobJah** [comment]
![image](https://user-images.githubusercontent.com/43188591/97599499-5d299980-1a08-11eb-8d49-e9bb25c82a85.png)

Please add this part to the raspberry guide and your all set for post-beta :)
