### ISSUE TITLE
[BUG] error on binance using arb/xemm via papertrade ValueError: No order book exists for 'NEO-USD'

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2540]
**Describe the bug**
Unable to run arb or xemm strategy on bitfinex while using NEO-USD / NEO-USDT when paper trade is enabled.

```
2020-10-31 19:28:59,512 - 13564 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2020-10-31 19:28:59,646 - 13564 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-10-31 19:28:59,646 - 13564 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-10-31 19:29:01,312 - 13564 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\binance\binance_api_order_book_data_source.py", line 199, in listen_for_order_book_snapshots
  File "hummingbot\connector\exchange\binance\binance_api_order_book_data_source.py", line 109, in get_snapshot
OSError: Error fetching Binance market snapshot for NEO-USD. HTTP status is 400.
2020-10-31 19:29:01,334 - 13564 - hummingbot.connector.exchange.binance.binance_order_book_tracker - INFO - Initialized order book for NEO-USDT. 1/1 completed.
2020-10-31 19:29:06,413 - 13564 - hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making - ERROR - Error formatting market stats.
Traceback (most recent call last):
  File "hummingbot\strategy\strategy_base.pyx", line 155, in hummingbot.strategy.strategy_base.StrategyBase.market_status_data_frame
  File "hummingbot\connector\exchange\paper_trade\paper_trade_exchange.pyx", line 968, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.get_price
  File "hummingbot\connector\exchange_base.pyx", line 100, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
  File "hummingbot\connector\exchange\paper_trade\paper_trade_exchange.pyx", line 902, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.c_get_order_book
ValueError: No order book exists for 'NEO-USD'.
2020-10-31 19:29:59,991 - 13564 - hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making - WARNING - Markets are not ready. No market making trades are permitted.
2020-10-31 19:36:42,838 - 11148 - hummingbot.notifier.telegram_notifier - INFO - Telegram is listening...
2020-10-31 19:36:43,676 - 11148 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2020-10-31 19:36:44,046 - 11148 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-10-31 19:36:44,047 - 11148 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-10-31 19:36:47,908 - 11148 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\binance\binance_api_order_book_data_source.py", line 199, in listen_for_order_book_snapshots
  File "hummingbot\connector\exchange\binance\binance_api_order_book_data_source.py", line 109, in get_snapshot
OSError: Error fetching Binance market snapshot for NEO-USD. HTTP status is 400.
2020-10-31 19:36:47,940 - 11148 - hummingbot.connector.exchange.binance.binance_order_book_tracker - INFO - Initialized order book for NEO-USDT. 1/1 completed.
2020-10-31 19:37:00,361 - 11148 - hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making - ERROR - Error formatting market stats.
Traceback (most recent call last):
  File "hummingbot\strategy\strategy_base.pyx", line 155, in hummingbot.strategy.strategy_base.StrategyBase.market_status_data_frame
  File "hummingbot\connector\exchange\paper_trade\paper_trade_exchange.pyx", line 968, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.get_price
  File "hummingbot\connector\exchange_base.pyx", line 100, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
  File "hummingbot\connector\exchange\paper_trade\paper_trade_exchange.pyx", line 902, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.c_get_order_book
ValueError: No order book exists for 'NEO-USD'.

```

**Steps To Reproduce**
create strategy use arb or xemm
maker/taker: bitfinex
taker/maker: binance

**Screenshots**
- Using xemm with paper trade enabled
![image](https://user-images.githubusercontent.com/54516858/97779081-c8b16980-1bb6-11eb-8edb-21dcaa7d5485.png)

- live trading no error no issues
![image](https://user-images.githubusercontent.com/54516858/97779115-0910e780-1bb7-11eb-9ec7-2be9ccb04e22.png)

- `status` command issue https://github.com/CoinAlpha/hummingbot/issues/2412

**Release version**
0.32.0

**Attachments**
[logs_arb_neo.log](https://github.com/CoinAlpha/hummingbot/files/5469065/logs_arb_neo.log)
[logs_UmbertoM.log](https://github.com/CoinAlpha/hummingbot/files/5469066/logs_UmbertoM.log)
[umbertom_config.txt](https://github.com/CoinAlpha/hummingbot/files/5469068/umbertom_config.txt)

**Comment by PtrckM** [comment]
issue occurs because of the bug issue #2412
