### ISSUE TITLE
Unable to create order on Bitfinex

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2622]
**Describe the bug**
- bot unable to create orders

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

create strategy using pmm
select bitfinex
set spread and order refresh
connect bitfinex
start

```
2020-11-13 14:54:59,743 - 4284 - hummingbot.notifier.telegram_notifier - INFO - Telegram is listening...
2020-11-13 14:54:59,754 - 4284 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2020-11-13 14:55:00,692 - 4284 - hummingbot.connector.exchange.bitfinex.bitfinex_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-11-13 14:55:01,440 - 4284 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - INFO - Initialized order book for ETH-BTC. 1/1 completed.
2020-11-13 14:55:05,000 - 4284 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Not enough balance for buy order (Size: 0.04, Price: 0.02774), order_amount is adjusted to 0
2020-11-13 14:55:05,002 - 4284 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-BTC) Creating 1 ask orders at (Size, Price): ['0.04 ETH, 0.02888 BTC']
2020-11-13 14:55:05,514 - 4284 - hummingbot.connector.exchange.bitfinex.bitfinex_websocket - ERROR - _listen error Couldn't place order sell-ETH-BTC-1605250505003085
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 125, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 122, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_exchange.pyx", line 657, in hummingbot.connector.exchange.bitfinex.bitfinex_exchange.BitfinexExchange.place_order.waitFor
OSError: Couldn't place order sell-ETH-BTC-1605250505003085
2020-11-13 14:55:05,516 - 4284 - hummingbot.connector.exchange.bitfinex.bitfinex_exchange - NETWORK - Error submitting sell LIMIT order to Bitfinex for -0.04000 ETH-BTC 0.02888.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bitfinex\bitfinex_exchange.pyx", line 822, in hummingbot.connector.exchange.bitfinex.bitfinex_exchange.BitfinexExchange.execute_sell
  File "hummingbot\connector\exchange\bitfinex\bitfinex_exchange.pyx", line 664, in place_order
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 130, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 125, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 122, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_exchange.pyx", line 657, in hummingbot.connector.exchange.bitfinex.bitfinex_exchange.BitfinexExchange.place_order.waitFor
OSError: Couldn't place order sell-ETH-BTC-1605250505003085
2020-11-13 14:55:05,519 - 4284 - hummingbot.connector.exchange.bitfinex.bitfinex_exchange - WARNING - Failed to submit sell order to Bitfinex. Check API key and network connection.
2020-11-13 14:55:20,086 - 4284 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Not enough balance for buy order (Size: 0.04, Price: 0.02774), order_amount is adjusted to 0
2020-11-13 14:55:21,000 - 4284 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Not enough balance for buy order (Size: 0.04, Price: 0.02774), order_amount is adjusted to 0
2020-11-13 14:55:21,001 - 4284 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-BTC) Creating 1 ask orders at (Size, Price): ['0.04 ETH, 0.02888 BTC']
2020-11-13 14:55:22,082 - 4284 - hummingbot.connector.exchange.bitfinex.bitfinex_websocket - ERROR - _listen error Couldn't place order sell-ETH-BTC-1605250521002629
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 125, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 122, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_exchange.pyx", line 657, in hummingbot.connector.exchange.bitfinex.bitfinex_exchange.BitfinexExchange.place_order.waitFor
OSError: Couldn't place order sell-ETH-BTC-1605250521002629
2020-11-13 14:55:22,084 - 4284 - hummingbot.connector.exchange.bitfinex.bitfinex_exchange - NETWORK - Error submitting sell LIMIT order to Bitfinex for -0.04000 ETH-BTC 0.02888.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bitfinex\bitfinex_exchange.pyx", line 822, in hummingbot.connector.exchange.bitfinex.bitfinex_exchange.BitfinexExchange.execute_sell
  File "hummingbot\connector\exchange\bitfinex\bitfinex_exchange.pyx", line 664, in place_order
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 130, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 125, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_websocket.py", line 122, in messages
  File "hummingbot\connector\exchange\bitfinex\bitfinex_exchange.pyx", line 657, in hummingbot.connector.exchange.bitfinex.bitfinex_exchange.BitfinexExchange.place_order.waitFor
OSError: Couldn't place order sell-ETH-BTC-1605250521002629
2020-11-13 14:55:22,085 - 4284 - hummingbot.connector.exchange.bitfinex.bitfinex_exchange - WARNING - Failed to submit sell order to Bitfinex. Check API key and network connection.
2020-11-13 14:55:25,680 - 4284 - hummingbot.client.hummingbot_application - INFO - stop command initiated.

```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/99038554-a0ffcf80-25c0-11eb-879f-9b1c74d78e63.png)
![image](https://user-images.githubusercontent.com/54516858/99038669-ddcbc680-25c0-11eb-95ca-b5f0cf2c4329.png)

**Release version**
0.33.0

**Attachments**
[logs_test_bitfinex.log](https://github.com/CoinAlpha/hummingbot/files/5535233/logs_test_bitfinex.log)
[test_bitfinex_config.log](https://github.com/CoinAlpha/hummingbot/files/5535237/test_bitfinex_config.log)

**Comment by RC-13** [comment]
Re-test concern using source build, bot were able to create orders on the latest release:
![bittfinex](https://user-images.githubusercontent.com/57189990/99178572-64aea980-274f-11eb-8d77-cbabbb2ca8f7.PNG)

**Comment by PtrckM** [comment]
thank you for checking @RC-13 looks like its working now (exchange issue?)

![image](https://user-images.githubusercontent.com/54516858/99214831-2925e500-280c-11eb-8608-f9ec9bfa4831.png)
