### ISSUE TITLE
Bot loops on cancelling a non-existing order on OKEx

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2623]
**Describe the bug**

Bot loops on cancelling a non-existing order on OKEx. The behavior was possibly triggered because of error in timestamp ``00:44:10, 296``, the bot recognizes it as a successfully created order thus when it's time to cancel the order the bot couldn't find it and enters a loop trying to cancel it.

```
2020-11-12 00:44:07,001 - 9929 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.012575 ETH, 450.2 USDT']
2020-11-12 00:44:07,001 - 9929 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.047424 ETH, 459.29 USDT']
2020-11-12 00:44:10,296 - 9929 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: network() got multiple values for argument 'app_warning_msg'
Traceback (most recent call last):
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 804, in hummingbot.connector.exchange.okex.okex_exchange.OkexExchange.execute_sell
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, False, order_type, decimal_price)
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 700, in place_order
    exchange_order_id = await self._api_request(
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 292, in _api_request
    async with response_coro as response:
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/okex/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 831, in execute_sell
    self.logger().network(
TypeError: network() got multiple values for argument 'app_warning_msg'
```
In here you'll see that the buy order wasn't created successully thus only the non-existing sell order was created
```
2020-11-12 00:44:10,300 - 9929 - hummingbot.connector.exchange.okex.okex_exchange - NETWORK - Error submitting buy limit_maker order to OKEx for 0.012575 ETH-USDT .450.20.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 731, in hummingbot.connector.exchange.okex.okex_exchange.OkexExchange.execute_buy
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type, decimal_price)
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 700, in place_order
    exchange_order_id = await self._api_request(
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 292, in _api_request
    async with response_coro as response:
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

**Screenshots**

Based on the screenshot, it created a non-existing sell order that's not present on the exchange. Notice the available balance for ETH is still the same with the total balance.
![image](https://user-images.githubusercontent.com/64377055/99041225-7fedad80-25c5-11eb-912e-2b46c5f18a28.png)

Open order tab on the exchange not showing the order created above
![image](https://user-images.githubusercontent.com/64377055/99041483-f8ed0500-25c5-11eb-8268-38003af01ea5.png)

Installation type: Source
Version: dev-0.34.0
Machine: AWS EC2 instance
Operating system: Linux

**Attachments**

Logs: 
[logs_okex_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5535366/logs_okex_eth-usdt.log)
Config: 
[okex_eth-usdt.txt](https://github.com/CoinAlpha/hummingbot/files/5535374/okex_eth-usdt.txt)

**Comment by TradeClaw** [comment]
I have seen the same on Binance, it does not complete the 'stop' process and therefor can't 'start' again.
Only remedy was to restart the whole container.
Did not document it well, it happened when I was using Hanging Orders in my config, I don't do that anymore now and haven't seen this behavior.

**Comment by RC-13** [comment]
Closing this case, it's almost a month since this issue was seen on the long term testing bot. Will re-open if seen again.
