### ISSUE TITLE
Unable to pass trading pair on kucoin using windows binary v0.33.0

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2625]
**Describe the bug**
Unable to pass the trading pair section (even `ctrl +x`) and no auto pair when you press tab.

**Steps To Reproduce**
launch hummingbot windows binary version 0.33.0
create pmm strategy
use kucoin as exchange

```
2020-11-13 18:45:13,850 - 15668 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: object of type 'TimeoutError' has no len()
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\create_command.py", line 63, in prompt_for_configuration
  File "hummingbot\client\command\create_command.py", line 108, in prompt_a_config
  File "hummingbot\client\config\config_var.py", line 55, in validate
  File "hummingbot\strategy\pure_market_making\pure_market_making_config_map.py", line 36, in validate_exchange_trading_pair
  File "hummingbot\client\config\config_validators.py", line 60, in validate_market_trading_pair
TypeError: object of type 'TimeoutError' has no len()

```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/99064390-e16f4580-25e0-11eb-81b2-26a3d7ff1066.png)

**Release version**
0.33.0

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5536290/logs_hummingbot.log)

**Comment by PtrckM** [comment]
- For some cases like this, run the bot as administrator 
![image](https://user-images.githubusercontent.com/54516858/101613881-39b22f80-3a47-11eb-98a8-845c38b9daee.png)

- Result
![image](https://user-images.githubusercontent.com/54516858/101613687-02438300-3a47-11eb-8938-bb0129350778.png)
