### ISSUE TITLE
Unhandled error in background during stop or exit using kucoin 

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2627]
**Describe the bug**
hummingbot produce error `async_utils - ERROR - Unhandled error in background task: 0` when typing `stop` or `exit`

**Steps To Reproduce**
create pmm strategy
select kucoin as exchange
set spread and order refresh time
start the bot
after few mins stop or exit

```
2020-11-13 11:59:56,352 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 0
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 455, in _collect_and_decode_messages_loop
    async for raw_msg in kucoin_msg_iterator:
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 229, in __aiter__
    async for raw_msg in self._inner_messages(ws):
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 204, in _inner_messages
    yield await ws.recv()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/protocol.py", line 492, in recv
    await asyncio.wait(
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 426, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 523, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 485, in _collect_and_decode_messages_loop
    self._tasks[stream_type][task_index].message_iterator = None
KeyError: 0
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/99071088-71ff5300-25ec-11eb-8146-1723232dd562.png)

**Release version**
0.33.0

**Attachments**
[logs_kucoin.log](https://github.com/CoinAlpha/hummingbot/files/5536747/logs_kucoin.log)

**Comment by rapcmia** [comment]
Upon checking this again, the error is not showing on the bot.

Steps taken:
1. Ran PMM with default config
2. Start bot, exit after 5mins
3. No errors found

![image](https://user-images.githubusercontent.com/73840223/116972851-39644a80-acee-11eb-87ed-6b813da05e42.png)

Release version:
dev-0.39.0

[logs_pmm-2627.log](https://github.com/CoinAlpha/hummingbot/files/6419586/logs_pmm-2627.log)

**Comment by dennisocana** [comment]
Support confirmed this is already fixed.
