### ISSUE TITLE
Bittrex - Error parsing the trading pair rule

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2674]
**Describe the bug**
- Upon starting the bot it will output Error parsing the trading pair rule

**Steps To Reproduce**
1. `create` PMM strategy
2. select exchange bittrex
3. select your pair
4. input your spread
5. input your refrest time
6. input minimum order
7. `start` bot

```
2020-11-24 19:23:58,979 - 8588 - hummingbot.connector.exchange.bittrex.bittrex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'BAND-BTC', 'baseCurrencySymbol': 'BAND', 'quoteCurrencySymbol': 'BTC', 'minTradeSize': '0.51100000', 'precision': 8, 'status': 'ONLINE', 'createdAt': '2020-11-16T20:11:48.18Z', 'notice': '', 'prohibitedIn': ['US'], 'associatedTermsOfService': [], 'lastTradeRate': '0', 'bidRate': '0.00038140', 'askRate': '0'}. Skipping.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bittrex\bittrex_exchange.pyx", line 245, in hummingbot.connector.exchange.bittrex.bittrex_exchange.BittrexExchange._format_trading_rules
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
2020-11-24 19:23:58,981 - 8588 - hummingbot.connector.exchange.bittrex.bittrex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'BAND-ETH', 'baseCurrencySymbol': 'BAND', 'quoteCurrencySymbol': 'ETH', 'minTradeSize': '0.51100000', 'precision': 8, 'status': 'ONLINE', 'createdAt': '2020-11-16T20:11:52.793Z', 'notice': '', 'prohibitedIn': ['US'], 'associatedTermsOfService': [], 'lastTradeRate': '0', 'bidRate': '0.01090927', 'askRate': '0'}. Skipping.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bittrex\bittrex_exchange.pyx", line 246, in hummingbot.connector.exchange.bittrex.bittrex_exchange.BittrexExchange._format_trading_rules
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
2020-11-24 19:23:58,982 - 8588 - hummingbot.connector.exchange.bittrex.bittrex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'BAND-USD', 'baseCurrencySymbol': 'BAND', 'quoteCurrencySymbol': 'USD', 'minTradeSize': '0.51100000', 'precision': 3, 'status': 'ONLINE', 'createdAt': '2020-11-16T20:12:02.857Z', 'notice': '', 'prohibitedIn': ['US'], 'associatedTermsOfService': [], 'lastTradeRate': '0', 'bidRate': '0.11700000', 'askRate': '0'}. Skipping.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bittrex\bittrex_exchange.pyx", line 247, in hummingbot.connector.exchange.bittrex.bittrex_exchange.BittrexExchange._format_trading_rules
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
2020-11-24 19:23:58,983 - 8588 - hummingbot.connector.exchange.bittrex.bittrex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'BAND-USDT', 'baseCurrencySymbol': 'BAND', 'quoteCurrencySymbol': 'USDT', 'minTradeSize': '0.51100000', 'precision': 3, 'status': 'ONLINE', 'createdAt': '2020-11-16T20:12:07.777Z', 'notice': '', 'prohibitedIn': ['US'], 'associatedTermsOfService': [], 'lastTradeRate': '0', 'bidRate': '0.15200000', 'askRate': '0'}. Skipping.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bittrex\bittrex_exchange.pyx", line 248, in hummingbot.connector.exchange.bittrex.bittrex_exchange.BittrexExchange._format_trading_rules
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
2020-11-24 19:23:58,989 - 8588 - hummingbot.connector.exchange.bittrex.bittrex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'NVT-BTC', 'baseCurrencySymbol': 'NVT', 'quoteCurrencySymbol': 'BTC', 'minTradeSize': '22.00000000', 'precision': 8, 'status': 'ONLINE', 'createdAt': '2020-11-09T17:02:13.493Z', 'notice': '', 'prohibitedIn': ['US'], 'associatedTermsOfService': [], 'lastTradeRate': '0', 'bidRate': '0.00000117', 'askRate': '0.00159050'}. Skipping.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bittrex\bittrex_exchange.pyx", line 245, in hummingbot.connector.exchange.bittrex.bittrex_exchange.BittrexExchange._format_trading_rules
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
2020-11-24 19:23:58,991 - 8588 - hummingbot.connector.exchange.bittrex.bittrex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'RENBTC-BTC', 'baseCurrencySymbol': 'RENBTC', 'quoteCurrencySymbol': 'BTC', 'minTradeSize': '0.00018500', 'precision': 8, 'status': 'ONLINE', 'createdAt': '2020-11-16T20:08:10.287Z', 'notice': '', 'prohibitedIn': ['US'], 'associatedTermsOfService': [], 'lastTradeRate': '0', 'bidRate': '0.99253117', 'askRate': '0'}. Skipping.
Traceback (most recent call last):
  File "hummingbot\connector\exchange\bittrex\bittrex_exchange.pyx", line 245, in hummingbot.connector.exchange.bittrex.bittrex_exchange.BittrexExchange._format_trading_rules
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/100089138-2c644500-2e8c-11eb-90f3-1fc1a37583b2.png)

**Release version**
0.33.1

**Attachments**

[logs_conf_pure_mm_2.log](https://github.com/CoinAlpha/hummingbot/files/5589526/logs_conf_pure_mm_2.log)

**Comment by glenntomas** [comment]
* Tried replicating user issues and get the same error parsing the trading pair rule.

![image](https://user-images.githubusercontent.com/73885708/100140929-9997ca80-2ecc-11eb-84e7-58bbf4cc57af.png)

**Comment by PtrckM** [comment]
no more error, fix on PR https://github.com/CoinAlpha/hummingbot/pull/2701

![image](https://user-images.githubusercontent.com/54516858/101603163-1d5bc600-3a3a-11eb-9a5d-9d8d11280f5b.png)
