### ISSUE TITLE
Bot loops on cancelling a non-existing order on Huobi

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2679]
**Describe the bug**

Bot loops on cancelling a non-existing order on Huobi. It most likely got triggered when the bot tried to create an order that's below the minimum trade size allowed thus when it's time to refresh orders it couldn't find the specific order.

```
2020-11-25 20:41:51,004 - 20081 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Sell order amount 0 is lower than the minimum order size 0.1000000000000000055511151231257827021181583404541015625.
Traceback (most recent call last):
  File "/home/ubuntu/04-huobi/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/huobi/huobi_exchange.pyx", line 819, in execute_sell
    raise ValueError(f"Sell order amount {decimal_amount} is lower than the minimum order size "
ValueError: Sell order amount 0 is lower than the minimum order size 0.1000000000000000055511151231257827021181583404541015625.
```
```
2020-11-25 20:42:51,003 - 20081 - hummingbot.connector.exchange.huobi.huobi_exchange - NETWORK - Failed to cancel order sell-HT-USDT-1606336911002546: Failed to cancel order - sell-HT-USDT-1606336911002546. Order not found.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/huobi/huobi_exchange.pyx", line 875, in hummingbot.connector.exchange.huobi.huobi_exchange.HuobiExchange.execute_cancel
    raise ValueError(f"Failed to cancel order - {order_id}. Order not found.")
ValueError: Failed to cancel order - sell-HT-USDT-1606336911002546. Order not found.
```

**Steps To Reproduce**

1. Run a pure market making bot on Huobi.
2. Set ``inventory_skew_enabled`` to true.

**Screenshots**

Based on the screenshot, it created a non-existing sell order that's not present on the exchange. Notice the available balance for HT is still the same with the total balance.

![huobi stuck non existing order](https://user-images.githubusercontent.com/64377055/100315917-6ea89600-2ff4-11eb-8f7d-fab3dd0d333c.PNG)

**Release version**

Installation type: Source
Version: dev-0.34.0
Machine: AWS EC2 instance
Operating system: Linux

**Attachments**

[logs_huobi_ht-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5600913/logs_huobi_ht-usdt.log)
[huobi_ht-usdt.txt](https://github.com/CoinAlpha/hummingbot/files/5600920/huobi_ht-usdt.txt)

**Comment by RC-13** [comment]
Closing this case for now, will re-open if issue will re-occur or seen again on the long term test bot.

**Comment by rxlxrxsx** [comment]
Re-opening because it reoccured on the latest development version (0.35.0)

Logs: [logs_huobi_ht-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5724153/logs_huobi_ht-usdt.log)
Config: [huobi_ht-usdt.txt](https://github.com/CoinAlpha/hummingbot/files/5724160/huobi_ht-usdt.txt)
