### ISSUE TITLE
Errors running amm_arb strategy on USDC

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2682]
**Describe the bug**

After the error on `08:34:47` timestamp occurred the bot throws an `Unhandled error in background task` every second and wasn't able to recover.

```
2020-11-27 08:34:47,333 - 1 - hummingbot.connector.connector.balancer.balancer_connector - NETWORK - Error getting quote price for WETH-DAI  sell order for 0.03 amount.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/__init__.py", line 13, in memoize
    cache[key] = cache.pop(key)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/ttl.py", line 185, in pop
    return Cache.pop(self, *args, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/abc.py", line 33, in pop
    raise KeyError(key)
KeyError: "((<hummingbot.connector.connector.balancer.balancer_connector.BalancerConnector object at 0x7ff1f26e0310>, 'WETH-DAI', False, Decimal('0.03')), {})"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/connector/balancer/balancer_connector.py", line 156, in get_quote_price
    resp = await self._api_request("post",
  File "/home/hummingbot/hummingbot/connector/connector/balancer/balancer_connector.py", line 477, in _api_request
    raise IOError(f"Error fetching data from {url}. HTTP status is {response.status}.{err_msg}")
OSError: Error fetching data from https://localhost:5000/balancer/sell-price. HTTP status is 500. Message: Operation Error
2020-11-27 08:34:47,334 - 1 - hummingbot.connector.connector.balancer.balancer_connector - WARNING - Error fetching data from https://localhost:5000/balancer/sell-price. HTTP status is 500. Message: Operation Error

2020-11-27 08:34:47,335 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: unsupported operand type(s) for /: 'decimal.Decimal' and 'NoneType'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/strategy/amm_arb/amm_arb.py", line 119, in main
    arb_proposals = [t.copy() for t in self._arb_proposals
  File "/home/hummingbot/hummingbot/strategy/amm_arb/amm_arb.py", line 120, in <listcomp>
    if t.profit_pct(account_for_fee=True) >= self._min_profitability]
  File "/home/hummingbot/hummingbot/strategy/amm_arb/data_types.py", line 62, in profit_pct
    sell_fee_amount = sell_trade_fee.fee_amount_in_quote(sell.market_info.trading_pair, sell.quote_price,
  File "/home/hummingbot/hummingbot/core/event/events.py", line 268, in fee_amount_in_quote
    fee_amount += (flat_fee[1] / price)
TypeError: unsupported operand type(s) for /: 'decimal.Decimal' and 'NoneType'
```

**Release version**
Installation type: Docker
Version: dev-0.34.0
Machine: AWS EC2 instance
Operating system: Linux

**Attachments**
[logs_balancer_weth-dai_binance_eth-usdc.zip](https://github.com/CoinAlpha/hummingbot/files/5610109/logs_balancer_weth-dai_binance_eth-usdc.zip)
[balancer_weth-dai_binance_eth-usdc.txt](https://github.com/CoinAlpha/hummingbot/files/5610111/balancer_weth-dai_binance_eth-usdc.txt)

**Comment by mifeng** [comment]
This error is likely due to the `decimals` for USDC, which are 6 compared to other Ethereum tokens which have 18 decimals. WBTC is also different with 8 decimals. To use this correctly, we should divide any amounts retrieved from Gateway by the right number of decimals, which can be found in the Token List dictionary.

Incorrect decimals for USDC also affects the display of `status` and `history`:
<img width="772" alt="Screen Shot 2020-12-16 at 3 58 50 PM" src="https://user-images.githubusercontent.com/1795030/102421504-658a6380-3fb9-11eb-919c-9d4039785d03.png">
