### ISSUE TITLE
when I start hummingbot，it always tips timeout.

### ISSUE THREAD

**Issue by beyoar** [CoinAlpha/hummingbot#269]
2019-05-21 01:30:56,391 - hummingbot.management.console - INFO - Started debug console at localhost:8211.
2019-05-21 01:31:57,676 - wings.wallet.web3_wallet_backend - INFO - Approval already exists for Wrapped Ether from wallet address 0xC40D82cCa310b6267Bde7974E12efd19e1C63b37.
2019-05-21 01:31:57,678 - wings.wallet.web3_wallet_backend - INFO - Approval already exists for Tether USD from wallet address 0xC40D82cCa310b6267Bde7974E12efd19e1C63b37.
2019-05-21 01:31:57,679 - wings.wallet.web3_wallet_backend - INFO - Approval already exists for TrueUSD from wallet address 0xC40D82cCa310b6267Bde7974E12efd19e1C63b37.
2019-05-21 01:32:09,630 - wings.market.ddex_market - ERROR - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "wings/market/ddex_market.pyx", line 318, in wings.market.ddex_market.DDEXMarket._status_polling_loop
    await asyncio.gather(
  File "wings/market/ddex_market.pyx", line 336, in _update_trading_rules
    markets = await self.list_market()
  File "wings/market/ddex_market.pyx", line 618, in list_market
    response_data = await self._api_request('get', url=url)
  File "wings/market/ddex_market.pyx", line 488, in _api_request
    async with client.request(http_method, url=url, timeout=self.API_CALL_TIMEOUT, data=data, params=params,
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 575, in _request
    break
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
2019-05-21 01:32:19,826 - wings.data_source.binance_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/beyoar/Desktop/SHAKA/hummingbot-master/wings/data_source/binance_api_order_book_data_source.py", line 176, in listen_for_order_book_diffs
    async with websockets.connect(stream_url) as ws:
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/site-packages/websockets/py35/client.py", line 12, in __await_impl__
    transport, protocol = await self._creating_connection
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 783, in create_connection
    raise exceptions[0]
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 770, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/asyncio/selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('199.59.149.136', 9443)
2019-05-21 01:32:19,829 - wings.data_source.binance_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 783, in create_connection
    raise exceptions[0]
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 770, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/home/beyoar/anaconda3/envs/hummingbot/lib/python3.6/asyncio/selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('69.171.227.37', 443)

**Comment by mifeng** [comment]
@beyoar Thanks for submitting this bug. Please include more details about:
* your environment (OS, installed from Docker/source, Hummingbot version number)
* strategy config file
* full logs

You email the logs and config file to dev@coinalpha.com if you prefer.

**Comment by beyoar** [comment]
OS   ubuntu 18.04
installed from source   
version  2019.4.15


Thank you for your reply!

[LogAndConfig.zip](https://github.com/CoinAlpha/hummingbot/files/3205751/LogAndConfig.zip)

**Comment by beyoar** [comment]
> @beyoar Thanks for submitting this bug. Please include more details about:
> 
> your environment (OS, installed from Docker/source, Hummingbot version number)
> strategy config file
> full logs
> 
> You email the logs and config file to dev@coinalpha.com if you prefer.

I send email to dev@coinalpha.com.
thank you for your help.

**Comment by chowryan** [comment]
closing old bug report. this issue should be fixed in latest build; please reopen if it's still an issue.
