### ISSUE TITLE
PMM unable to use custom_api price source

### ISSUE THREAD

**Issue by leocape** [CoinAlpha/hummingbot#2707]
**Describe the bug**
When specifying a custom_api price source in the pmm config, the bot will fail to run.

**Steps To Reproduce**
In the PMM config, specify a custom_api url that returns only the last price, in Decimal format eg 18000.5 (setting the pair, or the price type, or returning a string instead of decimal does not change the bug happening)  

**Screenshots**
pmm config:
![image](https://user-images.githubusercontent.com/67806134/101740608-bb4e9f80-3ad1-11eb-9129-0ffc3635a33b.png)

bugs out at this line in pure_market_making.pyx:
![image](https://user-images.githubusercontent.com/67806134/101740586-b1c53780-3ad1-11eb-8a9f-c3faa1633c01.png)

**Release version**
0.33 source

**Attachments**

pmm Log:

```
2020-12-09 12:08:27,003 - 24633 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 644, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    proposal =self.c_create_base_proposal()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 692, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
    price = self.get_price() * (Decimal("1") - self._bid_spread - (level * self._order_level_spread))
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 354, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
    price = price_provider.get_price_by_type(self._price_type)
AttributeError: 'hummingbot.strategy.pure_market_making.api_asset_p' object has no attribute 'get_price_by_type'

```

**Optional: your discord username:**
leocape

**Comment by pulkitsharma** [comment]
Any update for this one?

**Comment by guibabtc** [comment]
Same issue here, any update?

`2021-06-22 13:39:21,001 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 672, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    proposal = self.c_create_base_proposal()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 702, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
    buy_reference_price = sell_reference_price = self.get_price()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 359, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
    price = price_provider.get_price_by_type(self._price_type)
AttributeError: 'hummingbot.strategy.pure_market_making.api_asset_p' object has no attribute 'get_price_by_type'`

**Comment by mahdi13** [comment]
Same problem

```
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 672, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    proposal = self.c_create_base_proposal()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 702, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
    buy_reference_price = sell_reference_price = self.get_price()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 359, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
    price = price_provider.get_price_by_type(self._price_type)
AttributeError: 'hummingbot.strategy.pure_market_making.api_asset_p' object has no attribute 'get_price_by_type'
```

**Comment by M-Mortaz** [comment]
Still, this bug exists, any update?

**Comment by M-Mortaz** [comment]
#3784
