### ISSUE TITLE
Intermittent connection errors on OKEx

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#2743]
**Describe the bug**
User reported that his Hummingbot client is having connection issues when using OKEx connector. Returning error every 5 secs,

`Could not fetch account updates from OKEx. Check API key and network connection`

```
OSError: Error fetching data from https://www.okex.com/api/spot/v3/orders/-1?instrument_id=WXT-BTC. Response: {'error_message': '{order_id}Parameter value filling error', 'code': 30024, 'error_code': '30024', 'message': '{order_id}Parameter value filling error'}.
2020-12-13 00:00:05,217 - 1 - hummingbot.connector.exchange.okex.okex_exchange - WARNING - Could not fetch account updates from OKEx. Check API key and network connection.
2020-12-13 00:00:10,213 - 1 - hummingbot.connector.exchange.okex.okex_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 513, in hummingbot.connector.exchange.okex.okex_exchange.OkexExchange._status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 408, in _update_order_status
    order_update = await self.get_order_status(exchange_order_id, tracked_order.trading_pair)
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 396, in get_order_status
    return await self._api_request("GET", path_url=path_url, is_auth_required=True)
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 292, in _api_request
    async with response_coro as response:
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 294, in hummingbot.connector.exchange.okex.okex_exchange.OkexExchange._api_request
    raise IOError(f"Error fetching data from {url}. Response: {await response.json()}.")
```
**Steps To Reproduce**
- Tried to relaunch VPS, same error
- Create new instance of bot, same error
- Create a different sent of API keys for OKEx, no go
- Tried to change to create a different cloud based on europa instead of US, same error

Tried to test our bots with OKEx:
- Bots are running ok on cloud, no error
- Tried Paper_trade, no found error as well

**Screenshots**
![image](https://user-images.githubusercontent.com/73840223/102484392-2fc0aa00-40a1-11eb-9b7b-10beb6102188.png)

**Release version**
0.33.1

**Attachments**
[logs_WXTBTC.log-2020-12-13.zip](https://github.com/CoinAlpha/hummingbot/files/5708226/logs_WXTBTC.log-2020-12-13.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
Closing this case for now, haven't been able to replicate the issue locally and through cloud. In case user reach back and get the same issue, we can re-open the case.
