### ISSUE TITLE
Issue with starting docker

### ISSUE THREAD

**Issue by devdems** [CoinAlpha/hummingbot#2747]
There is an issue with starting a hummingbot docker.

Traceback (most recent call last):
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/selector_events.py", line 259, in _add_reader
key = self._selector.get_key(fd)
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/selectors.py", line 192, in get_key
raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "bin/hummingbot_quickstart.py", line 144, in <module>
main()
File "bin/hummingbot_quickstart.py", line 137, in main
if not login_prompt():
File "/home/hummingbot/hummingbot/client/ui/__init__.py", line 86, in login_prompt
show_welcome()
File "/home/hummingbot/hummingbot/client/ui/__init__.py", line 20, in show_welcome
message_dialog(
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 810, in run
return loop.run_until_complete(self.run_async(pre_run=pre_run))
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 777, in run_async
return await _run_async2()
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 759, in _run_async2
result = await _run_async()
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 682, in _run_async
with self.input.attach(read_from_input):
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/contextlib.py", line 113, in __enter__
return next(self.gen)
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/prompt_toolkit/input/vt100.py", line 176, in _attached_input
loop.add_reader(fd, callback)
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/selector_events.py", line 332, in add_reader
return self._add_reader(fd, callback, *args)
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/selector_events.py", line 261, in _add_reader
self._selector.register(fd, selectors.EVENT_READ,
File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/selectors.py", line 359, in register
self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted

**Comment by jiangxch** [comment]
how to solve
