### ISSUE TITLE
binance perp testnet - Error parsing the trading pair rule

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2753]
**Describe the bug**
- Upon starting the bot it will output Error parsing the trading pair rule

**Steps To Reproduce**
- `create` perpetual_market_making
- for derivative name select `binance_perpetual_testnet`
- trading pair `BTC-USDT`
- enter leverage
- position mode: one-way
- enter your spread
- order refresh: 35
- input your order amount
- manage positions: Profit_taking
- input your entry price
- start bot

```
2020-12-18 07:22:05,588 - 1 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative - ERROR - Error parsing the trading pair rule {'symbol': 'BTCBUSD_201225', 'pair': 'BTCBUSD', 'contractType': 'CURRENT_QUARTER', 'deliveryDate': 1608883200000, 'onboardDate': 1605427200000, 'status': 'TRADING', 'maintMarginPercent': '2.5000', 'requiredMarginPercent': '5.0000', 'baseAsset': 'BTC', 'quoteAsset': 'BUSD', 'marginAsset': 'BUSD', 'pricePrecision': 2, 'quantityPrecision': 3, 'baseAssetPrecision': 8, 'quotePrecision': 8, 'underlyingType': 'COIN', 'underlyingSubType': [], 'settlePlan': 0, 'triggerProtect': '0.1500', 'filters': [{'minPrice': '0.01', 'maxPrice': '100000.01', 'filterType': 'PRICE_FILTER', 'tickSize': '0.01'}, {'stepSize': '0.001', 'filterType': 'LOT_SIZE', 'maxQty': '10000.001', 'minQty': '0.001'}, {'stepSize': '0', 'filterType': 'MARKET_LOT_SIZE', 'maxQty': '207609.100', 'minQty': '0.001'}, {'limit': 0, 'filterType': 'MAX_NUM_ORDERS'}, {'limit': 100, 'filterType': 'MAX_NUM_ALGO_ORDERS'}, {'multiplierDown': '0.8500', 'multiplierUp': '1.1500', 'multiplierDecimal': '4', 'filterType': 'PERCENT_PRICE'}], 'orderTypes': ['LIMIT', 'MARKET', 'STOP', 'STOP_MARKET', 'TAKE_PROFIT', 'TAKE_PROFIT_MARKET', 'TRAILING_STOP_MARKET'], 'timeInForce': ['GTC', 'IOC', 'FOK', 'GTX']}. Error: 'NoneType' object has no attribute 'group'. Skipping...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 633, in _format_trading_rules
    trading_pair = convert_from_exchange_trading_pair(rule["symbol"])
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_utils.py", line 33, in convert_from_exchange_trading_pair
    if split_trading_pair(exchange_trading_pair) is None:
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_utils.py", line 29, in split_trading_pair
    raise e
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_utils.py", line 27, in split_trading_pair
    return m.group(1), m.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
2020-12-18 07:22:05,589 - 1 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative - ERROR - Error parsing the trading pair rule {'symbol': 'BTCBUSD_210326', 'pair': 'BTCBUSD', 'contractType': '', 'deliveryDate': 1616745600000, 'onboardDate': 1605427200000, 'status': 'PENDING_TRADING', 'maintMarginPercent': '2.5000', 'requiredMarginPercent': '5.0000', 'baseAsset': 'BTC', 'quoteAsset': 'BUSD', 'marginAsset': 'BUSD', 'pricePrecision': 2, 'quantityPrecision': 3, 'baseAssetPrecision': 8, 'quotePrecision': 8, 'underlyingType': 'COIN', 'underlyingSubType': [], 'settlePlan': 0, 'triggerProtect': '0.1500', 'filters': [{'minPrice': '0.01', 'maxPrice': '100000.01', 'filterType': 'PRICE_FILTER', 'tickSize': '0.01'}, {'stepSize': '0.001', 'filterType': 'LOT_SIZE', 'maxQty': '10000.001', 'minQty': '0.001'}, {'stepSize': '0.001', 'filterType': 'MARKET_LOT_SIZE', 'maxQty': '207609.100', 'minQty': '0.001'}, {'limit': 0, 'filterType': 'MAX_NUM_ORDERS'}, {'limit': 100, 'filterType': 'MAX_NUM_ALGO_ORDERS'}, {'multiplierDown': '0.8500', 'multiplierUp': '1.1500', 'multiplierDecimal': '4', 'filterType': 'PERCENT_PRICE'}], 'orderTypes': ['LIMIT', 'MARKET', 'STOP', 'STOP_MARKET', 'TAKE_PROFIT', 'TAKE_PROFIT_MARKET', 'TRAILING_STOP_MARKET'], 'timeInForce': ['GTC', 'IOC', 'FOK', 'GTX']}. Error: 'NoneType' object has no attribute 'group'. Skipping...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 633, in _format_trading_rules
    trading_pair = convert_from_exchange_trading_pair(rule["symbol"])
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_utils.py", line 33, in convert_from_exchange_trading_pair
    if split_trading_pair(exchange_trading_pair) is None:
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_utils.py", line 29, in split_trading_pair
    raise e
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_utils.py", line 27, in split_trading_pair
    return m.group(1), m.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
```

- this doesn't affect performance of the strategy.

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/102588048-c34cb600-4147-11eb-8a0c-ced50d9b4325.png)

**Release version**
0.34.0

**Attachments**
[logs_conf_perpetual_market_making_1.log](https://github.com/CoinAlpha/hummingbot/files/5714318/logs_conf_perpetual_market_making_1.log)

**Comment by PtrckM** [comment]
currently fix on this [development branch](https://github.com/CoinAlpha/hummingbot/pull/2786#pullrequestreview-559505673)
