### ISSUE TITLE
Maker orderbook is empty on XEMM

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#2754]
**Describe the bug**
User getting the following error when running on XEMM on bamboo relay (matic/weth) and binance (matic/btc)
`bamboo_relay_market - Buy orderbook for MATIC-WETH is empty` 
`bamboo_relay_market - Ask orderbook for MATIC-WETH is empty`
`clock - Unexpected error running clock tick`

```
2020-12-02 22:51:33,029 - 1 - hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making - ERROR - Error formatting market stats.
Traceback (most recent call last):
  File "hummingbot/strategy/strategy_base.pyx", line 155, in hummingbot.strategy.strategy_base.StrategyBase.market_status_data_frame
    bid_price = market.get_price(trading_pair, False)
  File "hummingbot/market/bamboo_relay/bamboo_relay_market.pyx", line 1622, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.get_price
    return self.c_get_price(trading_pair, is_buy)
  File "hummingbot/market/market_base.pyx", line 207, in hummingbot.market.market_base.MarketBase.c_get_price
    OrderBook order_book = self.c_get_order_book(trading_pair)
  File "hummingbot/market/bamboo_relay/bamboo_relay_market.pyx", line 1647, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.c_get_order_book
    raise ValueError(f"No order book exists for '{trading_pair}'.")
ValueError: No order book exists for 'MATIC-WETH'.

```

![image](https://user-images.githubusercontent.com/73840223/102589187-9b5e5200-4149-11eb-9a6c-5fd3765243e2.png)

**Steps To Reproduce**

* Start the bot running on XEMM
* Connections are ok and when it tries to check order, error occurred. 

Tried different pairs but with same exchange

* Maker exchange (bamboo relay) WETH/DAI
* Taker exchange (binance) BTC/USDC
* Run the bot for more than 30mins, no trades and orders. 
![image](https://user-images.githubusercontent.com/73840223/102589161-8e416300-4149-11eb-9a50-6bc7ef7f00ea.png)

Tried bot CEX on XEMM

* Confirmed orders are placed and filled.

Team tried to run some test again

* Maker exchange (bamboo relay) MATIC/WETH
* Taker exchange (binance) VIB/ETH
* Getting same error that maker orderbook is empty.

**Release version**
v0.28.1

**Attachments**
[logs_conf_xemm_8.log](https://github.com/CoinAlpha/hummingbot/files/5714361/logs_conf_xemm_8.log)
[conf_xemm_8.txt](https://github.com/CoinAlpha/hummingbot/files/5714413/conf_xemm_8.txt)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakw7d) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Closing ticket, connector has been deprecated.
