### ISSUE TITLE
Outdated loopring version

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2817]
**Describe the bug**
- the current version of hummingbot still uses loopring v1
- no longer able to trade using v1 cause most of the order_book are empty.
- v1 to v2: https://medium.com/loopring-protocol/shutdown-of-loopring-exchange-v1-transition-to-v2-d06cdf462548

**Steps To Reproduce**
- create strategy
- select connect loopring
- finished strategy config
- `connect loopring`
- start bot

```
2021-01-09 05:51:37,753 - 1 - hummingbot.connector.exchange.loopring.loopring_order_book_tracker - NETWORK - Unexpected error while fetching last trade price.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 161, in _update_last_trade_prices_loop
    last_prices = await self._data_source.get_last_traded_prices(**args)
  File "/home/hummingbot/hummingbot/connector/exchange/loopring/loopring_api_order_book_data_source.py", line 70, in get_last_traded_prices
    return {x[0]: float(x[7]) for x in resp_json.get("data", [])}
  File "/home/hummingbot/hummingbot/connector/exchange/loopring/loopring_api_order_book_data_source.py", line 70, in <dictcomp>
    return {x[0]: float(x[7]) for x in resp_json.get("data", [])}
ValueError: could not convert string to float: ''
2021-01-09 05:51:43,050 - 1 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Ask orderbook for LINK-ETH is empty.
2021-01-09 05:51:43,051 - 1 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Buy orderbook for LINK-ETH is empty.
2021-01-09 05:51:43,051 - 1 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Ask orderbook for LINK-ETH is empty.
2021-01-09 05:51:43,051 - 1 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Buy orderbook for LINK-ETH is empty.
2021-01-09 05:51:43,051 - 1 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Ask orderbook for LINK-ETH is empty.
2021-01-09 05:51:43,051 - 1 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Buy orderbook for LINK-ETH is empty.
2021-01-09 05:51:43,052 - 1 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Ask orderbook for LINK-ETH is empty.
2021-01-09 05:51:43,170 - 1 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Buy orderbook for LINK-ETH is empty.
2021-01-09 05:51:43,171 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 659, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    self.c_apply_budget_constraint(proposal)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 819, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_apply_budget_const$
    if quote_balance < quote_size:
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/104084457-1d8df200-5282-11eb-98cb-f3a9eae44960.png)

**Release version**
0.34.0 / dev-0.35.0

**Comment by krisj** [comment]
would love to get up and running on Loopring V2 again... miss it 😢
