### ISSUE TITLE
Failed Test PR#2 - ERROR - Unexpected error in user stream listener loop

### ISSUE THREAD

**Issue by gerald-hb** [CoinAlpha/hummingbot#282]
## Summary and Screenshots
When running multiple bots using the same API key. We are randomly getting this error
![image](https://user-images.githubusercontent.com/84826167/193369605-ab92cf39-a09f-4455-b2dd-c85f511229f9.png)
```
2022-09-30 23:33:17,762 - 1 - hummingbot.connector.derivative.bitget_perpetual.bitget_perpetual_derivative.BitgetPerpetualDerivative - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/derivative/bitget_perpetual/bitget_perpetual_derivative.py", line 578, in _user_stream_event_listener
    await self._update_positions()  # Bitget doesn't send position update when position is completely closed
  File "/home/hummingbot/hummingbot/connector/derivative/bitget_perpetual/bitget_perpetual_derivative.py", line 292, in _update_positions
    raw_response: List[Dict[str, Any]] = await self._api_get(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 845, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 878, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.bitget.com/api/mix/v1/position/allPosition. HTTP status is 429. Error: 
```
Could this be a limitation from the exchange?

## Steps To Reproduce
Outline the steps to reproduce the buggy behavior.
1.Clone and install featured branch- commit (https://github.com/CoinAlpha/hummingbot-bitget/pull/2/commits/29aae43e086836e34b8712e76612438a89561708)
2.Connect Bitget perpetual API keys and create a perpetual market making. (You can use my config)
3.Run multiple bots (in this case, there are just 3 bots running)
4.Observe the logpane as this error would appear randomly

## Test Result Comparison
New connector

## Attachments

[bitget.zip](https://github.com/CoinAlpha/hummingbot/files/9688188/bitget.zip)

**Comment by gerald-hb** [comment]
Closing this bug report. It is corrected with proper rate limit sharing configured
