### ISSUE TITLE
Balance command defaults to binance

### ISSUE THREAD

**Issue by demesm** [CoinAlpha/hummingbot#2833]
**Describe the bug**
When connected to coinbase_pro, running balance looks like it checks binance by default ignoring connections

**Steps To Reproduce**
run balance when connected to coinbase_pro

**Release version**
0.34.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
|21:31:03 - async_utils - Unhandled error in background task: Cannot connect to host api.binance.com:443 ssl:default [The remote computer refused the network connection] (See log file for stack trace dump)

2021-01-11 21:31:03,148 - 13568 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Cannot connect to host api.binance.com:443 ssl:default [The remote computer refused the network connection]
Traceback (most recent call last):
  File "site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
  File "asyncio\base_events.py", line 1025, in create_connection
  File "asyncio\base_events.py", line 1010, in create_connection
  File "asyncio\base_events.py", line 924, in _connect_sock
  File "asyncio\proactor_events.py", line 702, in sock_connect
  File "asyncio\windows_events.py", line 808, in _poll
  File "asyncio\windows_events.py", line 595, in finish_connect
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\balance_command.py", line 87, in show_balances
  File "hummingbot\client\command\balance_command.py", line 141, in exchange_balances_usd_df
  File "hummingbot\core\utils\market_price.py", line 13, in usd_value
  File "hummingbot\core\utils\__init__.py", line 15, in memoize
  File "hummingbot\core\utils\market_price.py", line 25, in token_usd_values
  File "hummingbot\core\utils\__init__.py", line 15, in memoize
  File "hummingbot\connector\exchange\binance\binance_api_order_book_data_source.py", line 87, in get_all_mid_prices
  File "site-packages\aiohttp\client.py", line 480, in _request
  File "site-packages\aiohttp\connector.py", line 523, in connect
  File "site-packages\aiohttp\connector.py", line 858, in _create_connection
  File "site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
  File "site-packages\aiohttp\connector.py", line 980, in _create_direct_connection
  File "site-packages\aiohttp\connector.py", line 943, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.binance.com:443 ssl:default [The remote computer refused the network connection]

**Comment by RC-13** [comment]
@demesm Do you have any Binance API key connected on your bot when you did the balance check? I just did a test using windows binary and added only Coinbase pro API key and didn't get this error on the logs.
![image](https://user-images.githubusercontent.com/57189990/104265035-b1043480-54c7-11eb-9c9a-375585a59a25.png)

I do get that error if Binance API key is connected then sudden network interruption occur

**Comment by demesm** [comment]
@RC-13 Nope, only have coinbasepro

![image](https://user-images.githubusercontent.com/23346713/104265289-37366180-545b-11eb-8de2-c0abc3e3cb33.png)

**Comment by RC-13** [comment]
Thanks for the info, can you try reinstalling your Hummingbot and re-connect your coinbase pro API key, also make sure that your connection is stable. If the same behavior persist, kindly upload your hummingbot log file, you can follow the step on this link to find the log files: https://docs.hummingbot.io/intro/support/#where-are-my-config-and-log-files

**Comment by demesm** [comment]
@RC-13 Reinstalled, same issue, tried to get 0.35.0 but the link isnt working yet (https://dist.hummingbot.io/hummingbot_v0.35.0_setup.exe), log attached.
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5799684/logs_hummingbot.log)

**Comment by glenntomas** [comment]
Did you delete the hummingbot.io folder when reinstalling hummingbot? after you uninstall in control panel search %localappdata% then delete the hummingbot.io folder then proceed on installing new binary installer and try to connect again the coinbase_pro API key. It works fine on my end too.

![image](https://user-images.githubusercontent.com/73885708/104268317-97b2b680-54ce-11eb-81ce-058471fadef4.png)

**Comment by demesm** [comment]
I uninstalled and deleted a second time, same issue
![image](https://user-images.githubusercontent.com/23346713/104347198-57ebcf00-54ce-11eb-8a57-12622ee4d63e.png)

**Comment by demesm** [comment]
@RC-13 @glenntomas I installed via the docker scripts on a fresh linux VM and get the same error, what could be causing this?

![image](https://user-images.githubusercontent.com/23346713/104394456-a6bc5780-5514-11eb-9c21-88fc78b2c9f5.png)

**Comment by demesm** [comment]
fix: use VPN. 

I attempted to add an api key to binance.com but they're blocking US IPs I turned on VPN and ran the balance command again and it works (also added binanceUS key to test)

Need to add a check that will bypass checking binance.com for US users or simply only check the exchanges that currently have keys added.

![image](https://user-images.githubusercontent.com/23346713/104399104-00754f80-551e-11eb-805f-e4ab516c50d0.png)

**Comment by RC-13** [comment]
Closing this ticket now
