### ISSUE TITLE
Failed Test PR#286 - Fail to submit orders on mad-meerkat side 

### ISSUE THREAD

**Issue by Deepali6997** [CoinAlpha/hummingbot#287]
**Summary and Screenshots**
During the trade event on mad-meerkat, it failed to submit orders as seen below
![2022-10-21_20-21](https://user-images.githubusercontent.com/100112937/197225395-e3fa3431-b7b7-4e78-b0f4-e9e6d4a7ad7c.png)

upon further checking in the strategy log file 
![2022-10-21_20-21_1](https://user-images.githubusercontent.com/100112937/197225456-d1421bf7-2ea9-4eb4-a405-eb59476979d2.png)

<img width="789" alt="Screenshot 2022-10-21 at 8 26 27 PM" src="https://user-images.githubusercontent.com/100112937/197225936-af19332c-b95c-4bad-b698-7cf90b206e35.png">

```

2022-10-21 20:13:47,515 - 2976 - GatewayEVMAMM - ERROR - Error submitting BUY swap order to mad_meerkat on mainnet for 60.000000 WCRO-USDC 0.105383248500000.
Traceback (most recent call last):
  File "/Users/deepaligautam/PR286/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 532, in _create_order
    order_result: Dict[str, Any] = await self._get_gateway_instance().amm_trade(
  File "/Users/deepaligautam/PR286/hummingbot/core/gateway/gateway_http_client.py", line 463, in amm_trade
    return await self.api_request("post", "amm/trade", request_payload)
  File "/Users/deepaligautam/PR286/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/Users/deepaligautam/PR286/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/amm/trade Error: {'message': 'Network error. Please check your node URL, API key, and Internet connection.', 'httpErrorCode': 503, 'errorCode': 1001, 'stack': 'Error: processing response error (body="{\\"jsonrpc\\":\\"2.0\\",\\"id\\":84,\\"error\\":{\\"code\\":-32000,\\"message\\":\\"failed to deduct transaction costs from user balance: the tx gasfeecap is lower than the tx baseFee: 100000000000 (gasfeecap), 4893010833853 (basefee) : insufficient fee: insufficient fee\\"}}\\n", error={"code":-32000}, requestBody="{\\"method\\":\\"eth_sendRawTransaction\\",\\"params\\":[\\"0x02f9017419819e85174876e80085174876e800832dc6c094145677fc4d9b8f19b5d56d1820c48e0443049a3080b901048803dbee00000000000000000000000000000000000000000000000340aad21b3b70000000000000000000000000000000000000000000000000000000000000005f86a700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000060d1d15595e9ca555c4b0e901b3d4f1085e6f6b3000000000000000000000000000000000000000000000000000000006352b14b0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c21223249ca28397b4b6541dffaecc539bff0c590000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23c001a00a4f1c1fdcad79928b9226b014956058734520840ed0b7073f9fef2a061862b7a0467e523086b2d6490f26c0cd8fdd22783e9aaa2a91d0a0b5cdf9870e56ede0e7\\"],\\"id\\":84,\\"jsonrpc\\":\\"2.0\\"}", requestMethod="POST", url="https://evm.cronos.org/", code=SERVER_ERROR, version=web/5.6.1)\n    at Logger.makeError (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/logger/lib/index.js:233:21)\n    at Logger.throwError (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/logger/lib/index.js:242:20)\n    at /Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/web/lib/index.js:305:32\n    at step (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
```

**Steps To Reproduce**

pre - req : clone and install clean instance!

1. create a amm_arb strategy use mad-meerkat
2. set your trading pair for CEX and DEX sides
3. ensure have enough balance to place orders
4. set negative profitability to force trade event.
5. start strategy

NOTE : I am using my own wallet, made sure db folder is clean and also, there are no stuck order as of the moment.

**Test Result Comparison**
not available on the master and dev branches of the foundation yet

**Attachments**
files : 
[PR286_mmf.zip](https://github.com/CoinAlpha/hummingbot/files/9840215/PR286_mmf.zip)

**Comment by PtrckM** [comment]
this is confirmed fix using commit 343be8445f82ec94e20262439fbe0e8e95cb8954
