### ISSUE TITLE
Crypto.com - KeyError: trade_list error in update_result

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2899]
**Describe the bug**
Getting this error intermittently when running a bot on Crypto.com. Creating a github ticket for tracking.

```
2021-01-30 10:56:00,167 - 19892 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - ERROR - 'trade_list'
Traceback (most recent call last):
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 555, in _status_polling_loop
    await safe_gather(
  File "/home/ubuntu/10-crypto_com/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 612, in _update_order_status
    for trade_msg in update_result["result"]["trade_list"]:
KeyError: 'trade_list'
2021-01-30 10:56:00,168 - 19892 - hummingbot.connector.exchange.crypto_com.crypto_com_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 555, in _status_polling_loop
    await safe_gather(
  File "/home/ubuntu/10-crypto_com/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/10-crypto_com/hummingbot/connector/exchange/crypto_com/crypto_com_exchange.py", line 612, in _update_order_status
    for trade_msg in update_result["result"]["trade_list"]:
KeyError: 'trade_list'
```

**Steps To Reproduce**
1. Run a pure market making bot on Crypto.com
2. Notice that this error is intermittently showing on the logs

**Release version**
```
version: development 0.36.0
commit: ed6e337e0d4280abdf8d9be78e132f9399a59531
Date: Thu Jan 28 22:37:19 2021 -0300
```

**Attachments**
Logs: [logs_crypto_cro-btc.log](https://github.com/CoinAlpha/hummingbot/files/5899422/logs_crypto_cro-btc.log)
Config: [crypto_cro-btc.txt](https://github.com/CoinAlpha/hummingbot/files/5899423/crypto_cro-btc.txt)

**Comment by dennisocana** [comment]
Fixed in dev-0.37.0
