### ISSUE TITLE
Failed Test PR#286 - Getting issue on nonce when using concurrent orders submission between vvs and mmf

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#290]
## Summary and Screenshots
No success swap between mmf and vvs when using concurrent orders submission.

![image](https://user-images.githubusercontent.com/54516858/197717700-681ab32f-da39-42aa-8a9f-65ad6280ba79.png)

```
2022-10-25 16:01:25,673 - 84711 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:30861/amm/trade failed. See logs for more details.
2022-10-25 16:01:25,673 - 84711 - GatewayEVMAMM - ERROR - Error submitting SELL swap order to vvs on mainnet for 104.000000 WCRO-USDC 0.102320954400000.
Traceback (most recent call last):
  File "/Users/patrick/Documents/HB/add_cronos_chain_and_vvs_mmf_connector/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 532, in _create_order
    order_result: Dict[str, Any] = await self._get_gateway_instance().amm_trade(
  File "/Users/patrick/Documents/HB/add_cronos_chain_and_vvs_mmf_connector/hummingbot/core/gateway/gateway_http_client.py", line 463, in amm_trade
    return await self.api_request("post", "amm/trade", request_payload)
  File "/Users/patrick/Documents/HB/add_cronos_chain_and_vvs_mmf_connector/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/Users/patrick/Documents/HB/add_cronos_chain_and_vvs_mmf_connector/hummingbot/core/gateway/gateway_http_client.py", line 206, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:30861/amm/trade Error: {'message': 'Network error. Please check your node URL, API key, and Internet connection.', 'httpErrorCode': 503, 'errorCode': 1001, 'stack': 'Error: processing response error (body="{\\"jsonrpc\\":\\"2.0\\",\\"id\\":814,\\"error\\":{\\"code\\":-32000,\\"message\\":\\"invalid nonce; got 302, expected 233: invalid sequence: invalid sequence\\"}}\\n", error={"code":-32000}, requestBody="{\\"method\\":\\"eth_sendRawTransaction\\",\\"params\\":[\\"0x02f901771982012e860472a32b8c1b860472a32b8c1b832dc6c094145677fc4d9b8f19b5d56d1820c48e0443049a3080b9010438ed1739000000000000000000000000000000000000000000000005a34a38fc00a000000000000000000000000000000000000000000000000000000000000000a5bd3300000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000a86b66f4e7dc45a943d71a10c7dddde341246681000000000000000000000000000000000000000000000000000000006357990100000000000000000000000000000000000000000000000000000000000000020000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23000000000000000000000000c21223249ca28397b4b6541dffaecc539bff0c59c080a0c27f5b16488971819523c35b25d9447fde2442a7ef8574ff5727dfa1fdf5baf0a07244cfabee1c01e5c612d2912e44db239f2849cf96df6fd76ee6e22b541bce47\\"],\\"id\\":814,\\"jsonrpc\\":\\"2.0\\"}", requestMethod="POST", url="https://evm.cronos.org/", code=SERVER_ERROR, version=web/5.6.1)\n    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:233:21)\n    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:242:20)\n    at /usr/src/app/node_modules/@ethersproject/web/lib/index.js:305:32\n    at step (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)'}

```

## Steps To Reproduce
1. clone and install feature branch then launch client
2. build gateway thru source or docker
3. start gateway
4. gateway connect both vvs and mmf (same wallet or different) ensure you have balances
5. create amm between mmf and vvs 
6. set negative profitability to force trade
7. start strategy

## Test Result Comparison
New connector on oss

## Attachments
[subsequentorders.zip](https://github.com/CoinAlpha/hummingbot/files/9858359/subsequentorders.zip)

**Comment by Deepali6997** [comment]
seeing the same behaviour when arbitraging between mmf and crypto.com

![Screenshot 2022-10-25 at 6 50 16 PM](https://user-images.githubusercontent.com/100112937/197784253-8ae60f87-6e98-4521-b679-beadbd89dedf.png)

<img width="1564" alt="Screenshot 2022-10-25 at 6 51 25 PM" src="https://user-images.githubusercontent.com/100112937/197784433-12ad47de-1f9b-441b-88a6-342e670d2300.png">

<img width="790" alt="Screenshot 2022-10-25 at 6 53 23 PM" src="https://user-images.githubusercontent.com/100112937/197784881-099275dd-188b-44bc-8635-abd5bf7bb474.png">


```
2022-10-26 02:10:10 | info | 	Best trade for 0xc21223249CA28397B4B6541dfFaEcC539BfF0c59-0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23: [object Object] | undefined
2022-10-26 02:10:10 | info | 	Transaction Details: {"type":2,"chainId":25,"nonce":161,"maxPriorityFeePerGas":{"_hex":"0x04729aa8c03f","_isBigNumber":true},"maxFeePerGas":{"_hex":"0x04729aa8c03f","_isBigNumber":true},"gasPrice":null,"gasLimit":{"_hex":"0x2dc6c0","_isBigNumber":true},"to":"0x145677FC4d9b8F19B5D56d1820c48e0443049a30","value":{"_hex":"0x00","_isBigNumber":true},"data":"0x38ed173900000000000000000000000000000000000000000000000340aad21b3b70000000000000000000000000000000000000000000000000000000000000005fd49000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000060d1d15595e9ca555c4b0e901b3d4f1085e6f6b3000000000000000000000000000000000000000000000000000000006357dcae00000000000000000000000000000000000000000000000000000000000000020000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23000000000000000000000000c21223249ca28397b4b6541dffaecc539bff0c59","accessList":[],"hash":"0x104a4cbfeac7a9b7dff95b968d8c4be11d0a6f8cfac1ed1ccaec2247fe891941","v":1,"r":"0x51bd01b8fc5702d9731bdc2d87b06b224c03e3653287b3f13048fbf9ece31ffe","s":"0x7f1cb2b83acea10ac34c813ac0de4cb920e5087817f34522ffb8ebbf7b282305","from":"0x60d1d15595E9cA555C4b0e901B3d4F1085E6f6b3","confirmations":0} | undefined
2022-10-26 02:10:10 | info | 	Trade has been executed, txHash is 0x104a4cbfeac7a9b7dff95b968d8c4be11d0a6f8cfac1ed1ccaec2247fe891941, nonce is 161, gasPrice is 4890.267533375. | undefined
2022-10-26 02:10:11 | error | 	processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":224,\"error\":{\"code\":-32000,\"message\":\"invalid nonce; got 162, expected 161: invalid sequence: invalid sequence\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f901761981a28604729aa8c03f8604729aa8c03f832dc6c094145677fc4d9b8f19b5d56d1820c48e0443049a3080b901048803dbee00000000000000000000000000000000000000000000000340aad21b3b7000000000000000000000000000000000000000000000000000000000000000611e8500000000000000000000000000000000000000000000000000000000000000a000000000000000000000000060d1d15595e9ca555c4b0e901b3d4f1085e6f6b3000000000000000000000000000000000000000000000000000000006357dcae0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c21223249ca28397b4b6541dffaecc539bff0c590000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23c001a0ea3dec9e2b9c49ed97b9c08c83fc67bc20766740c8cc0b6b97dd24cc4e1b387ba01226910171e3c2a57d94efe82dc7d62cb575ef8020b5374f6a7581fe93d5e35d\"],\"id\":224,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://evm.cronos.org/", code=SERVER_ERROR, version=web/5.6.1) | Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":224,\"error\":{\"code\":-32000,\"message\":\"invalid nonce; got 162, expected 161: invalid sequence: invalid sequence\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f901761981a28604729aa8c03f8604729aa8c03f832dc6c094145677fc4d9b8f19b5d56d1820c48e0443049a3080b901048803dbee00000000000000000000000000000000000000000000000340aad21b3b7000000000000000000000000000000000000000000000000000000000000000611e8500000000000000000000000000000000000000000000000000000000000000a000000000000000000000000060d1d15595e9ca555c4b0e901b3d4f1085e6f6b3000000000000000000000000000000000000000000000000000000006357dcae0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c21223249ca28397b4b6541dffaecc539bff0c590000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23c001a0ea3dec9e2b9c49ed97b9c08c83fc67bc20766740c8cc0b6b97dd24cc4e1b387ba01226910171e3c2a57d94efe82dc7d62cb575ef8020b5374f6a7581fe93d5e35d\"],\"id\":224,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://evm.cronos.org/", code=SERVER_ERROR, version=web/5.6.1)
    at Logger.makeError (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at /Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/web/lib/index.js:305:32
    at step (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/Users/deepaligautam/PR286/gateway/node_modules/@ethersproject/web/lib/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Note : The log file of the strategy does not throw any error related to nonce. 

All the relevant files can be found here : 
[issue#290.zip](https://github.com/CoinAlpha/hummingbot/files/9860662/issue.290.zip)

**Comment by PtrckM** [comment]
nonce manager issue related will be tackle on a different tasks as per discuss.
