### ISSUE TITLE
Failed Test PR 292: Unexpected error running clock tick - error is seen in log pane after starting the strategy

### ISSUE THREAD

**Issue by Deepali6997** [CoinAlpha/hummingbot#293]
**Describe the bug**
When testing the PR on commit 2e39f31ca1b7cf0e33ea407c392c8dadb5218027 , log pane is getting flooded with error message 

> 18:25:52 - clock - Unexpected error running clock tick. (See log file for stack trace dump)

![image](https://user-images.githubusercontent.com/100112937/208676054-4efd313b-e222-4bd2-ab20-f5fbe39ccd20.png)

```python
2022-12-20 18:25:43,173 - 26583 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2022-12-20 18:25:43,176 - 26583 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-12-20 18:25:44,001 - 26583 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/connector/connector_base.pyx", line 218, in hummingbot.connector.connector_base.ConnectorBase.c_tick
    self.tick(timestamp)
  File "/Users/deepaligautam/PR292/hummingbot/connector/exchange_py_base.py", line 278, in tick
    last_recv_diff = timestamp - self._user_stream_tracker.last_recv_time
AttributeError: 'NoneType' object has no attribute 'last_recv_time'
```

**Steps To Reproduce**
1. Clean clone of branch 
2. Start the client
3. connect the API keys
4. create a Pure MM strategy

expected
5. Hit start and Pure MM should work as usual without any errors

actual
5. We're seeing error in log-pane

**Test Result Comparison**
Ci-ex not available on dev or master

**Attachments**
[pr292.zip](https://github.com/CoinAlpha/hummingbot/files/10268696/pr292.zip)

**Comment by RC-13** [comment]
Fixed in the latest commit: ba8ae216de93133a210a68cd2d489b85b9da9b94, closing ticket.
