### ISSUE TITLE
BitMax - Creates orders below the exchange minimum size in HB client

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2942]
**Describe the bug**
The bot doesn't omit order that is below exchange minimum and fails to cancel this order which prevents new orders to be created. This behavior occurs when inventory skew is enabled and using BitMax connector, the workaround is to stop the strategy and start again but the issue will persist once an order that doesn't meet the exchange requirement is created again.
```
2021-02-10 10:10:07,004 - 22561 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Notional amount 1.73954 is not withing the range of 5-400000.
Traceback (most recent call last):
  File "/home/ubuntu/bitmax/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/bitmax/hummingbot/connector/exchange/bitmax/bitmax_exchange.py", line 492, in _create_order
    raise ValueError(f"Notional amount {notional} is not withing the range of {bitmax_trading_rule.minNotional}-{bitmax_trading_rule.maxNotional}.")
ValueError: Notional amount 1.73954 is not withing the range of 5-400000.
2021-02-10 10:10:07,019 - 22561 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Notional amount 1.84714 is not withing the range of 5-400000.
Traceback (most recent call last):
  File "/home/ubuntu/bitmax/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/bitmax/hummingbot/connector/exchange/bitmax/bitmax_exchange.py", line 492, in _create_order
    raise ValueError(f"Notional amount {notional} is not withing the range of {bitmax_trading_rule.minNotional}-{bitmax_trading_rule.maxNotional}.")
ValueError: Notional amount 1.84714 is not withing the range of 5-400000.
```
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy
2. use Bitmax as the exchange
3. enable inventory skew
4.  set order level to 3 or more to easily replicate the behavior
5.  start strategy and run the status command
6. check log pane and order amounts, log will throw an `Unhandled error in background task` and there will be an order that is below the exchange minimum allowable trade size.
7.  Wait for order refresh time duration to end and monitor the log pane, run `status --live` as well. You will notice that this order amount below the exchange minimum will remain and fails to cancel.
...

**Screenshots**
highlighted orders are currently below exchange minimum:
![Bitmax](https://user-images.githubusercontent.com/57189990/107501391-492e3000-6bd2-11eb-9423-bb170121a786.PNG)

after order_refresh_time, the 2 order fails to get canceled preventing new orders to get created
![bitmax1](https://user-images.githubusercontent.com/57189990/107501502-6fec6680-6bd2-11eb-9328-026fa92b0a57.PNG)

**Release version**
0.36.0 

**Attachments**
[logs_bitmax_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5957650/logs_bitmax_eth-usdt.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
Confirmed PR fix the reported issue with Bitmax orders. No orders below exchange minimum trade size are created and no stuck orders occurred during testing.
