### ISSUE TITLE
Failed Test PR #294 - Getting listen_for_user_stream error after start strategy

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#296]
**Describe the bug**
- After starting a strategy an error observe showing on the right log pane. 

![image](https://user-images.githubusercontent.com/54516858/211998845-88d79cc4-7f93-4a4f-a4e1-cb21ac3fd6ef.png)

```
2023-01-12 14:58:23,495 - 44259 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'listen_for_user_stream'
Traceback (most recent call last):
  File "/Users/patrick/Documents/HB/injective/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/patrick/Documents/HB/injective/hummingbot/core/data_type/user_stream_tracker.py", line 34, in start
    self.data_source.listen_for_user_stream(self._user_stream)
AttributeError: 'NoneType' object has no attribute 'listen_for_user_stream'
2023-01-12 14:58:23,740 - 44259 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for INJ-USDT. 1/1 completed.
```

**Steps To Reproduce**
1. Clean clone of branch the install and compile it.
2. Start the client and gateway
3. create a pure_mm strategy using injective
4. start strategy then observe right pane 

**Test Result Comparison**
- does not happen on hb-pro injective

![image](https://user-images.githubusercontent.com/54516858/212000638-38dae0a7-c004-4a66-84ce-2afbf4c89985.png)

**Attachments**

[injective_oss.zip](https://github.com/CoinAlpha/hummingbot/files/10399032/injective_oss.zip)

**Comment by petioptrv** [comment]
This issue should be fixed by [this commit](https://github.com/CoinAlpha/hummingbot/pull/294/commits/617bad81b60c3fc1335f61a5800700d6d6abaede).

**Comment by PtrckM** [comment]
confirmed using the latest commit 617bad81b60c3fc1335f61a5800700d6d6abaede

![image](https://user-images.githubusercontent.com/54516858/212268439-4994dde3-c1d6-4d3c-8611-1cf5ac18be9e.png)
