### ISSUE TITLE
Beaxy - Getting stuck and timeout error after restarting straregy

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2991]
**Describe the bug**
- stopping the bot then restarting it will cause the bot to throw errors and get stuck.

**Steps To Reproduce**
- create PureMM strategy
- select beaxy as exchange connector
- set your token pair, spreads and order amount
- start the bot after few minutes stop the bot and re-start

```
2021-02-25 10:08:50,064 - 31094 - hummingbot.connector.exchange.beaxy.beaxy_exchange - WARNING - Exception while making api request.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/beaxy/beaxy_exchange.pyx", line 978, in hummingbot.connector.exchange.beaxy.beaxy_exchange.BeaxyExchange._api_request
    async with client.request(http_method.upper(), url=url, timeout=self.API_CALL_TIMEOUT, data=data_str, headers=headers) as response:
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/109154558-6ace1080-77a9-11eb-92df-9f365184760c.png)

**Release version**
https://github.com/CoinAlpha/hummingbot/pull/2913

**Attachments**
[logs_beaxy.log](https://github.com/CoinAlpha/hummingbot/files/6042965/logs_beaxy.log)

**Comment by novoxd** [comment]
Should be fixed by https://github.com/CoinAlpha/hummingbot/pull/2913/commits/9d61893ae064de0b458d079ed9db437a6a7ae645

**Comment by RC-13** [comment]
Closing ticket, the issue did not re-occur.
