### ISSUE TITLE
LM strategy - Markets prompt fails to validate trading pair format

### ISSUE THREAD

**Issue by glenntomas** [CoinAlpha/hummingbot#3006]
**Describe the bug**
A user reported liquidity mining strategy configuration push through even after entering the wrong format of market list, the expected behavior should be after entering the wrong format it'll throw an error right away and configuration won't continue.

**Steps To Reproduce**
1. Create a liquidity mining strategy
2. Enter a list of markets with spaces (e.g LTC-USDT, ETH-USDT)
3. Configuration continued after entering the wrong format instead of throwing an error right away 
4. `start` the bot
5. Logs will show `liquidity mining - binance is not ready. Please wait...`

**Screenshots**
![image](https://user-images.githubusercontent.com/73885708/109512625-3dea6800-7adf-11eb-8d5a-a94cc96315ed.png)

**Release version**
v0.36.0

**Attachments**
[conf_liquidity_mining_2.txt](https://github.com/CoinAlpha/hummingbot/files/6062431/conf_liquidity_mining_2.txt)
[logs_conf_liquidity_mining_2.log](https://github.com/CoinAlpha/hummingbot/files/6062432/logs_conf_liquidity_mining_2.log)

**Discord username:**
DeanoC#1610

**Comment by dennisocana** [comment]
As a result, the connector tries to fetch market snapshot with spaces for example " ETH-USDT".

```
2021-03-01 14:31:15,309 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error fetching market snapshot for  ETH-USDT. HTTP status is 400.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 178, in _init_order_books
    self._order_books[trading_pair] = await self._data_source.get_new_order_book(trading_pair)
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 140, in get_new_order_book
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair, 1000, self._domain)
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 128, in get_snapshot
    raise IOError(f"Error fetching market snapshot for {trading_pair}. "
OSError: Error fetching market snapshot for  ETH-USDT. HTTP status is 400.
```

```
2021-03-01 14:31:19,426 - 1 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 222, in listen_for_order_book_snapshots
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair,
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 128, in get_snapshot
    raise IOError(f"Error fetching market snapshot for {trading_pair}. "
OSError: Error fetching market snapshot for  ETH-USDT. HTTP status is 400.
```

**Comment by marcodepolo** [comment]
+1 for validating / trimming the spaces between the commas, I also encountered the issue.

I also met another issue that could be fixed together is that I had entered my settings as lower case but HB didn't handle it very well. 

Try to put 
markets rlc-usdt,xem-usdt,firo-usdt
token usdt

if starting the bot with this settings, you should get an error "invalid value usdt for config variable token"
if typing in "config token USDT" you will get another error "invalid token, USDT is not one of rlc,xem,firo,usdt

The only way is to exit the bot, open the config file, uppercase everything then restart the bot.

**Comment by RC-13** [comment]
This issue has been resolved on the latest version, closing ticket now.
