### ISSUE TITLE
Failed Test PR #294 - unable to create orders

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#301]
**Describe the bug**
- The bot is unable to create any order even with enough balance. 

![image](https://user-images.githubusercontent.com/54516858/213644153-6927d2e9-2398-41c2-a085-6d737f7a782f.png)
![image](https://user-images.githubusercontent.com/54516858/213644183-613a8335-154e-49ef-9b09-855d8ec759de.png)

```
2023-01-20 15:29:05,103 - 35043 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - NETWORK - Error submitting sell LIMIT_MAKER order to Injective_injective_mainnet for 2.000000000000000000 INJ-USDT 1.538.
Traceback (most recent call last):
  File "/Users/patrick/Documents/HB/injective/hummingbot/connector/exchange_py_base.py", line 482, in _create_order
    exchange_order_id = await self._place_order_and_process_update(order=order, **kwargs,)
  File "/Users/patrick/Documents/HB/injective/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 306, in _place_order_and_process_update
    exchange_order_id, misc_order_updates = await self._api_data_source.place_order(order=order, **kwargs)
  File "/Users/patrick/Documents/HB/injective/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 177, in place_order
    order_result: Dict[str, Any] = await self._get_gateway_instance().clob_place_order(
  File "/Users/patrick/Documents/HB/injective/hummingbot/core/gateway/gateway_http_client.py", line 1202, in clob_place_order
    return await self.api_request("post", "clob/orders", request_payload)
  File "/Users/patrick/Documents/HB/injective/hummingbot/core/gateway/gateway_http_client.py", line 217, in api_request
    raise e
  File "/Users/patrick/Documents/HB/injective/hummingbot/core/gateway/gateway_http_client.py", line 205, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:15888/clob/orders Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': "TypeError: Cannot read properties of undefined (reading 'baseToken')\n    at InjectiveCLOB.<anonymous> (/Users/patrick/Documents/HB/injective/gateway/dist/src/connectors/injective/injective.js:115:56)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/patrick/Documents/HB/injective/gateway/dist/src/connectors/injective/injective.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
```

- tried using the endpoint for `./requests/injective_post_order.json` still get the same issue
![image](https://user-images.githubusercontent.com/54516858/213644409-0b0fcbd4-d44e-4d3c-81d8-49c993d5108a.png)
![image](https://user-images.githubusercontent.com/54516858/213645047-123a47b4-6203-4fb4-a9bc-8e92c8b7f603.png)

- manually place order on exchange
![image](https://user-images.githubusercontent.com/54516858/213644215-cabe9eae-99c0-42bc-b9f5-03d6476d122d.png)

**Steps To Reproduce**
1. Clean clone of branch the install and compile it.
2. Start the client and gateway
3. create a pure_mm strategy using injective
4. start strategy then observe order creation keeps failing
5. check orders on exchange but none created
6. check gateway logs getting error

**Test Result Comparison**
- new connector to OSS

**Attachments**

[injective.zip](https://github.com/CoinAlpha/hummingbot/files/10464287/injective.zip)

**Comment by gerald-hb** [comment]
The order seems to appear now in the client. However, it is still not present in the exchange despite having enough balance to place them
![MPOmdU3fYX](https://user-images.githubusercontent.com/84826167/214708908-b196d167-1e25-493c-bc5b-7e2ac884e843.gif)
![image](https://user-images.githubusercontent.com/84826167/214708942-58e76eb0-e7f7-41c6-9ba3-40c26a69b3d9.png)
[injective.zip](https://github.com/CoinAlpha/hummingbot/files/10504370/injective.zip)

**Comment by PtrckM** [comment]
- fixed by adding more INJ asset for fee using the latest commit 4fd4fee5f5adc6b96de49c1ce5b6265733ec46c4
  - previous balance 0.1xxx current balance 2.1xxxx


![image](https://user-images.githubusercontent.com/54516858/214786272-0727d8b6-ebdf-4af0-96d8-7483a42e3745.png)

![image](https://user-images.githubusercontent.com/54516858/214786297-eeb51785-0ef3-41a4-93be-7b5f0d32979d.png)
