### ISSUE TITLE
Beaxy - Websocket connection errors

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3010]
**Describe the bug**
Websocket connection errors on Beaxy resulting to the bot not working as expected. For instance, there were no results on history, .sqlite and .csv file after an filled order event during the time when Websocket connection errors is happening.

```
2021-03-03 12:01:39,470 - 3309 - hummingbot.connector.exchange.beaxy.beaxy_exchange - WARNING - Exception while making api request.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/beaxy/beaxy_exchange.pyx", line 1010, in _api_request
    async with client.request(http_method.upper(), url=url, timeout=self.API_CALL_TIMEOUT, data=data_str, headers=headers) as response:
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Steps To Reproduce**

1. Run a pure market making bot on Beaxy
2. On the event that Websocket connection errors is happening and a trade was filled, the bot can't seem to capture the trade that happened resulting to history not showing any trades and .sqlite/.csv file left blank.

**Screenshots**
<img width="1423" alt="Screen Shot 2021-03-03 at 12 11 56 PM" src="https://user-images.githubusercontent.com/64377055/109770490-997b3980-7c36-11eb-943d-051d5b39cb88.png">
<img width="1161" alt="Screen Shot 2021-03-03 at 3 33 03 PM" src="https://user-images.githubusercontent.com/64377055/109770509-9f711a80-7c36-11eb-939e-df097435521a.png">

**Release version**
dev-0.37.0

**Attachments**
[logs_beaxy_test1.log](https://github.com/CoinAlpha/hummingbot/files/6074323/logs_beaxy_test1.log)

**Comment by RC-13** [comment]
Closing ticket, issue haven't re-occurred.
