### ISSUE TITLE
Hummingbot Client - Trading pair auto-complete not showing and won't accept any input resulting to TimeoutError when creating a strategy

### ISSUE THREAD

**Issue by whcfelix** [CoinAlpha/hummingbot#3055]
**Describe the bug**
// A clear and concise description of what the bug is.

I tried to create a pure market making strategy in KuCoin but the console didn't accept any trading pairs. There was an error reported in the running logs.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Just create a PMM, follow the guidelines then you can see the error.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

<img width="944" alt="Screen Shot 2021-03-09 at 11 41 03 AM" src="https://user-images.githubusercontent.com/80353609/110517734-d92ba080-80d0-11eb-9ffb-f5031127bd20.png">

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

0.37 

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rxlxrxsx** [comment]
Upon checking the TimeoutError appears when you entered the pair but auto-complete is still not showing. This is related to what @vic-en said about fetching trading pair requests from all exchanges and will depend on how fast your connection is. We recently applied a timeout of 3 seconds for the fetching trading pair request and currently investigating why it's giving a TimeoutError instead of an empty list. The team is aware of the issue and will release a fix ASAP.

Posting the traceback error as well

```2021-03-10 07:05:46,677 - 2411 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: object of type 'TimeoutError' has no len()
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hummingbot/hummingbot/client/command/create_command.py", line 63, in prompt_for_configuration
    await self.prompt_a_config(config)
  File "/Users/reiniersalazar/hummingbot/hummingbot/client/command/create_command.py", line 107, in prompt_a_config
    err_msg = config.validate(input_value)
  File "/Users/reiniersalazar/hummingbot/hummingbot/client/config/config_var.py", line 55, in validate
    err_msg = self._validator(value)
  File "/Users/reiniersalazar/hummingbot/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 35, in validate_exchange_trading_pair
    return validate_market_trading_pair(exchange, value)
  File "/Users/reiniersalazar/hummingbot/hummingbot/client/config/config_validators.py", line 60, in validate_market_trading_pair
    if len(trading_pairs) == 0:
TypeError: object of type 'TimeoutError' has no len()
```

This error also shows after exiting the client
<img width="1276" alt="Screen Shot 2021-03-10 at 6 52 47 AM" src="https://user-images.githubusercontent.com/64377055/110555747-16973900-8178-11eb-9709-380a213d4dd2.png">

**Comment by scope-li** [comment]
I have the same.

v0.37.0 / AWS t2.medium

But I have it only with "kucoin", on the same machine two other bots with "binance" without any problems.
I also have problem when I load an existing PMM on kucoin with ETH-USDT (see the log below).

I hope it helps to restrict the error.

```
2021-03-10 08:16:02,777 - 1 - root - ERROR - Error loading configs. Your config file may be corrupt. object of type 'TimeoutError' has no len()
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 304, in load_yml_into_cm
    err_msg = cvar.validate(str(cvar.value))
  File "/home/hummingbot/hummingbot/client/config/config_var.py", line 55, in validate
    err_msg = self._validator(value)
  File "/home/hummingbot/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 35, in validate_exchange_trading_pair
    return validate_market_trading_pair(exchange, value)
  File "/home/hummingbot/hummingbot/client/config/config_validators.py", line 60, in validate_market_trading_pair
    if len(trading_pairs) == 0:
TypeError: object of type 'TimeoutError' has no len()
2021-03-10 08:16:03,195 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/import_command.py", line 44, in import_config_file
    if await self.status_check_all():
  File "/home/hummingbot/hummingbot/client/command/status_command.py", line 156, in status_check_all
    missing_configs = self.missing_configurations()
  File "/home/hummingbot/hummingbot/client/command/status_command.py", line 112, in missing_configurations
    missing_configs = missing_required_configs(get_strategy_config_map(self.strategy_name))
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 453, in missing_required_configs
    return [c for c in config_map.values() if c.required and c.value is None and not c.is_connect_key]
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 453, in <listcomp>
    return [c for c in config_map.values() if c.required and c.value is None and not c.is_connect_key]
  File "/home/hummingbot/hummingbot/client/config/config_var.py", line 48, in required
    return self._required_if()
  File "/home/hummingbot/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 206, in <lambda>
    required_if=lambda: pure_market_making_config_map.get("order_levels").value > 1,
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
