### ISSUE TITLE
async_utils - ERROR - Unhandled error in background task

### ISSUE THREAD

**Issue by pusewicz** [CoinAlpha/hummingbot#3076]
**Describe the bug**
Starting a bot raises the error. This suddenly started happening. Not sure what's going on and not sure what other steps to take to debug.

```
2021-03-14 19:29:19,139 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: __init__() takes at least 2 positional arguments (0 given)
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/connect_command.py", line 76, in show_connections
    df, failed_msgs = await self.connection_df()
  File "/home/hummingbot/hummingbot/client/command/connect_command.py", line 88, in connection_df
    err_msgs = await UserBalances.instance().update_exchanges(reconnect=True)
  File "/home/hummingbot/hummingbot/user/user_balances.py", line 87, in update_exchanges
    results = await safe_gather(*tasks)
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/user/user_balances.py", line 70, in update_exchange_balance
    return await self.add_exchange(exchange, **api_keys)
  File "/home/hummingbot/hummingbot/user/user_balances.py", line 53, in add_exchange
    market = UserBalances.connect_market(exchange, **api_details)
  File "/home/hummingbot/hummingbot/user/user_balances.py", line 26, in connect_market
    connector = connector_class(**init_params)
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 126, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.__init__
    def __init__(self,
TypeError: __init__() takes at least 2 positional arguments (0 given)
```

**Steps To Reproduce**

Starting the bot with the `start` command.

**Release version**
0.37.1

**Comment by sidmontanez** [comment]
Hi @pusewicz, 
   May I have a screenshot of your `config` and  `status`? so I could take a closer look on what causes the error. Thanks

**Comment by pusewicz** [comment]
Thanks @sidmontanez!

Status command does not work as it raises the same exception.

Config is like this:

```
>>>  config                                          
                                                     
Global Configurations:                               
                            Key      Value           
             balancer_max_swaps          4           
            ethereum_chain_name   MAIN_NET           
            kill_switch_enabled      False           
               kill_switch_rate     -100.0           
               telegram_enabled      False           
                 telegram_token        abc           
               telegram_chat_id   30649752           
                send_error_logs       True           
              0x_active_cancels      False           
                 script_enabled      False           
               script_file_path       None           
               manual_gas_price       50.0           
      ethgasstation_gas_enabled      False           
          ethgasstation_api_key       None           
        ethgasstation_gas_level       None           
     ethgasstation_refresh_time        120           
               gateway_api_host  localhost           
               gateway_api_port       5000           
                                                     
Strategy Configurations:                             
                              Key               Value
                         strategy  pure_market_making
                         exchange             binance
                           market             EOS-EUR
                       bid_spread                0.28
                       ask_spread                0.32
                   minimum_spread              -100.0
               order_refresh_time                1200
                    max_order_age                7200
      order_refresh_tolerance_pct                0.02
                     order_amount                20.0
                    price_ceiling                -1.0
                      price_floor                -1.0
                ping_pong_enabled                True
                     order_levels                   5
               order_level_amount                20.0
               order_level_spread                 0.2
           inventory_skew_enabled               False
        inventory_target_base_pct                50.0
       inventory_range_multiplier                 1.0
                  inventory_price                 1.0
               filled_order_delay                   2
           hanging_orders_enabled                True
        hanging_orders_cancel_pct                 1.0
       order_optimization_enabled               False
     ask_order_optimization_depth             20000.0
     bid_order_optimization_depth             20000.0
            add_transaction_costs                True
                     price_source      current_market
                       price_type           mid_price
            price_source_exchange                None
              price_source_market                None
                  take_if_crossed                None
          price_source_custom_api                None
                   order_override                None
```

The weird thing is that it used to work just fine. Then I restarted the docker image and it stopped. I was running multiple images. I'm thinking that maybe there's an error being returned from Binance that's not being presented or handled correctly. Maybe the Binance Key got banned? Or went over some rate-limit?

**Comment by RC-13** [comment]
@pusewicz If this error occurs immediately after opening your bot, can you try updating all your docker instances or re-create your instances, see if that helps. However, if this issue only happens when you start your strategy, I recommend re-creating your strategy file.

**Comment by pusewicz** [comment]
I tried regenerating the the Docker images to no avail.

**Comment by R-K-H** [comment]
I had a similar issue:

1. Create a backup of your *.json in the config folder(s)
2. Remove the .json files which were created by the bot (make sure your backups are safe)
3. Run the bot again and setup a new password
4. Connect using the API keys and secret for the exchange connectors 

I was then able to run and import again. It seems something gets corrupted.

**Comment by pusewicz** [comment]
@R-K-H That definitely helped. The bot is working again.

**Comment by RC-13** [comment]
@R-K-H Thanks for sharing, @pusewicz I will be closing this concern now.

**Comment by pusewicz** [comment]
@R-K-H It would still be great to improve the error messages so that it's clearer what the actual error is.

**Comment by R-K-H** [comment]
> @R-K-H It would still be great to improve the error messages so that it's clearer what the actual error is.

I agree, but that's left up for the developers. :)

As much as I'd like to contribute to the code base, there's a lot of moving pieces here and I don't feel comfortable poking around.
