### ISSUE TITLE
(Pure MM) Inventory_price + external_market not working together

### ISSUE THREAD

**Issue by Fadiii** [CoinAlpha/hummingbot#3079]
Reproducing bug:
Use price_type = inventory_price and price_source = external_market.

This combination of settings causes a bug.

Log:

```
2021-03-15 01:51:35,002 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 678, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    self.c_apply_order_size_modifiers(proposal)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 805, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_apply_order_size_modifiers
    self.c_apply_inventory_skew(proposal)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 814, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_apply_inventory_skew
    base_balance, quote_balance = self.c_get_adjusted_available_balance(self.active_orders)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 759, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_get_adjusted_available_balance
    object base_balance = market.c_get_available_balance(self.base_asset)
  File "hummingbot/connector/connector_base.pyx", line 324, in hummingbot.connector.connector_base.ConnectorBase.c_get_available_balance
    return self.get_available_balance(currency)
  File "hummingbot/connector/connector_base.pyx", line 339, in hummingbot.connector.connector_base.ConnectorBase.get_available_balance
    available_balance = self.apply_balance_limit(currency, available_balance, balance_limit)
  File "hummingbot/connector/connector_base.pyx", line 303, in hummingbot.connector.connector_base.ConnectorBase.apply_balance_limit
    filled_balance = self.order_filled_balances().get(currency, s_decimal_0)
  File "hummingbot/connector/connector_base.pyx", line 143, in hummingbot.connector.connector_base.ConnectorBase.order_filled_balances
    base_value = Decimal("-1") * event.amount
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
```

**Comment by RC-13** [comment]
Confirming the defect, I was able to replicate the issue when running the `status` command. The bot was able to successfully create and submit orders with `inventoryCost` as `price_type` and `external_exchange` as `price_source` but can't display the status outcome. I believe the issue with status is triggered since the reference price (`inventory_price`) can't be converted from the external exchange:
![image](https://user-images.githubusercontent.com/57189990/111419591-b890c580-8724-11eb-83ca-061b62e4bcf3.png)
```ruby
2021-03-17 13:15:34,671 - 2653 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: float() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/home/clint_g/hbot-new/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/clint_g/hbot-new/hummingbot/client/command/status_command.py", line 135, in status_check_all
    self._notify(await self.strategy_status())
  File "/home/clint_g/hbot-new/hummingbot/client/command/status_command.py", line 79, in strategy_status
    st_status = self.strategy.format_status()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 596, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.format_status
    markets_df = self.market_status_data_frame([self._market_info])
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 583, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.market_status_data_frame
    float(ref_price)
TypeError: float() argument must be a string or a number, not 'NoneType'
```
@Fadiii I think your `inventory_price` is not set (which is defaulted to `1` ) which is why we have a different error trace dump but yeah the status command still won't work.
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/6153942/logs_conf_pure_mm_1.log)

**Comment by rapcmia** [comment]
Hi @MementoRC no it is not, We are planning to remove the `inventory_cost` price_type on future releases.

**Comment by sissnad** [comment]
Hi @rapcmia , what is the reason for future removal? I understand that it is failing right now; I have been trying to use without success. But I believe it makes total sense to have this mode, in particular if you want to serve pairs with low liquidity
