### ISSUE TITLE
Cannot start trade with par USDT-BVND on binance

### ISSUE THREAD

**Issue by hieuln1991** [CoinAlpha/hummingbot#3090]
**Describe the bug**
Cannnot start trade with trading pair USDT-BVND

**Steps To Reproduce**
1. Create new script with pure_market_making with trading pair USDT-BVND on binance connector
2. start script

**Screenshots**
![image](https://user-images.githubusercontent.com/7108232/111506700-77c49b00-877c-11eb-8a55-d0ebb03825b4.png)

**Release version**
0.37.1 on macOS

**Attachments**
Log:

  GNU nano 2.0.6                                                File: logs_conf_pure_usdt_bvnd_1.log                                                                                                        

  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 672, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 702, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 359, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
  File "hummingbot/strategy/market_trading_pair_tuple.py", line 40, in get_price_by_type
  File "hummingbot/connector/exchange_base.pyx", line 277, in hummingbot.connector.exchange_base.ExchangeBase.get_price_by_type
  File "hummingbot/connector/exchange_base.pyx", line 108, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
  File "hummingbot/connector/connector_base.pyx", line 376, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 1031, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.c_get_order_price_quantum
KeyError: 'USDT-BVND'
2021-03-17 23:41:32,005 - 13948 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 672, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 702, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 359, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
  File "hummingbot/strategy/market_trading_pair_tuple.py", line 40, in get_price_by_type
  File "hummingbot/connector/exchange_base.pyx", line 277, in hummingbot.connector.exchange_base.ExchangeBase.get_price_by_type
  File "hummingbot/connector/exchange_base.pyx", line 108, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
  File "hummingbot/connector/connector_base.pyx", line 376, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 1031, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.c_get_order_price_quantum
KeyError: 'USDT-BVND'
2021-03-17 23:41:33,003 - 13948 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 672, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 702, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 359, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
  File "hummingbot/strategy/market_trading_pair_tuple.py", line 40, in get_price_by_type
  File "hummingbot/connector/exchange_base.pyx", line 277, in hummingbot.connector.exchange_base.ExchangeBase.get_price_by_type
  File "hummingbot/connector/exchange_base.pyx", line 108, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
  File "hummingbot/connector/connector_base.pyx", line 376, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 1031, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.c_get_order_price_quantum
KeyError: 'USDT-BVND'
2021-03-17 23:41:33,996 - 13948 - hummingbot.client.hummingbot_application - INFO - stop command initiated.

**Comment by dendenski** [comment]
This is to confirm the issue, the pair USDT-BVND does not show in the drop down list.
![image](https://user-images.githubusercontent.com/78801399/111523601-6ab4a580-8796-11eb-9378-81be83f56ee3.png)

**Comment by dennisocana** [comment]
Fixed in version 0.38
