### ISSUE TITLE
Left Pane of Hummingbot Ceases to Work after Stopping during Live Status

### ISSUE THREAD

**Issue by dnlfrst** [CoinAlpha/hummingbot#3127]
# What is the problem?

Hummingbot (version 0.37.1) stops working after issuing the `stop` command during `status --live`. That is, Hummingbot still seems to process further commands (i.e., `config leverage 5`) but fails to display their output in the left pane until one issues `status --live` again.

# How to reproduce the problem?

1. Start Hummingbot on macOS or in Docker and authenticate yourself.
2. Issue the command `import bitcoin_future_trading.yml`.
3. Issue the command `start`.
4. Issue the command `status --live`.
5. Issue the command `stop`.

_**Note:**_ the above issue has appeared with _every_ strategy configuration that I used so far.

# Logs

After the fourth step, the log shows:

```
2021-03-29 16:10:35,181 - 3622 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-03-29 16:10:35,566 - 3622 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative - INFO - Successfully canceled order x-3QreWesy-SBCUT1617027011002879
2021-03-29 16:10:35,566 - 3622 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1617027035.0, "order_id": "x-3QreWesy-SBCUT1617027011002879", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance_perpetual"}
2021-03-29 16:10:36,369 - 3622 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'format_status'
Traceback (most recent call last):
  File "hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
  File "hummingbot/client/command/status_command.py", line 131, in status_check_all
  File "hummingbot/client/command/status_command.py", line 76, in strategy_status
AttributeError: 'NoneType' object has no attribute 'format_status
```

which points to:

https://github.com/CoinAlpha/hummingbot/blob/8ac56466b606f7780d448ab14b24cd0f9e40d94a/hummingbot/client/command/status_command.py#L71-L83

# Strategy Configuration

The following strategy configuration has been used to reproduce the issue:

<details>
<summary><code>bitcoin_futures_trading.yml</code></summary>

```
########################################################
###       Perpetual market making strategy config         ###
########################################################

template_version: 4
strategy: perpetual_market_making

# derivative and token parameters.
derivative: binance_perpetual

# Token trading pair for the exchange, e.g. BTC-USDT
market: BTC-USDT

# What leverage to used
leverage: 3

# Position mode to use, hedge mode or one-way position mode.
position_mode: Hedge

# How far away from mid price to place the bid order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_spread is 1.
# Your bid is placed at 99.
bid_spread: 0.05

# How far away from mid price to place the ask order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_spread is 1.
# Your bid is placed at 101.
ask_spread: 0.05

# Minimum Spread
# How far away from the mid price to cancel active orders
minimum_spread: -100.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 120.0

# The spread (from mid price) to defer order refresh process to the next cycle.
# (Enter 1 to indicate 1%), value below 0, e.g. -1, is to disable this feature - not recommended.
order_refresh_tolerance_pct: 0.0

# Size of your bid and ask order.
order_amount: 0.001

# Which position management feature to use. Trailing stop and take profit features are currently supported
position_management: Profit_taking

# long position take profit spread
long_profit_taking_spread: 0.25

# short position take profit spread
short_profit_taking_spread: 0.25

# Activation spread for trailing stop
ts_activation_spread: 0.0

# Callback rate for trailing stop
ts_callback_rate: 0.0

# Spread from position entry price to place a stop-loss order to close position
stop_loss_spread: 0.25

# OrderType to use for closing positions when using Trailing stop feature
close_position_order_type: MARKET

# Price band ceiling.
price_ceiling: -1.0

# Price band floor.
price_floor: -1.0

# Whether to alternate between buys and sells (true/false).
ping_pong_enabled: false

# Number of levels of orders to place on each side of the order book.
order_levels: 2

# Increase or decrease size of consecutive orders after the first order (if order_levels > 1).
order_level_amount: 0.0

# Order price space between orders (if order_levels > 1).
order_level_spread: 0.1

# How long to wait before placing the next order in case your order gets filled.
filled_order_delay: 60.0

# Whether to stop cancellations of orders on the other side (of the order book),
# when one side is filled (hanging orders feature) (true/false).
hanging_orders_enabled: false

# Spread (from mid price, in percentage) hanging orders will be canceled (Enter 1 to indicate 1%)
hanging_orders_cancel_pct: 10.0

# Whether to enable order optimization mode (true/false).
order_optimization_enabled: true

# The depth in base asset amount to be used for finding top ask (for order optimization mode).
ask_order_optimization_depth: 0.0

# The depth in base asset amount to be used for finding top bid (for order optimization mode).
bid_order_optimization_depth: 0.0

# Whether to enable adding transaction costs to order price calculation (true/false).
add_transaction_costs: true

# The price source (current_market/external_market/custom_api).
price_source: current_market

# The price type (mid_price/last_price/last_own_trade_price/best_bid/best_ask).
price_type: mid_price

# An external exchange name (for external exchange pricing source).
price_source_derivative:

# A trading pair for the external exchange, e.g. BTC-USDT (for external exchange pricing source).
price_source_market:

# An external api that returns price (for custom_api pricing source).
price_source_custom_api:

#Take order if they cross order book when external price source is enabled
take_if_crossed:

# Use user provided orders to directly override the orders placed by order_amount and order_level_parameter
# This is an advanced feature and user is expected to directly edit this field in config file
# Below is an sample input, the format is a dictionary, the key is user-defined order name, the value is a list which includes buy/sell, order spread, and order amount
# order_override:
#   order_1: [buy, 0.5, 100]
#   order_2: [buy, 0.75, 200]
#   order_3: [sell, 0.1, 500]
# Please make sure there is a space between : and [
order_override:

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters
```
</details>

**Comment by rxlxrxsx** [comment]
Closing as there's already a submitted ticket for this issue #3015. Please refer to the existing ticket moving forward.
