### ISSUE TITLE
Failed Test PR #315 - No orders are created using Injective

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#316]
## Summary and Screenshots
While there are open orders seen on the status output, there were actually no orders created upon checking on the exchange and logs. There are also errors being thrown which I think is related as to why no orders are created.

<img width="1421" alt="Screen Shot 2023-03-10 at 12 35 46 PM" src="https://user-images.githubusercontent.com/64377055/224424692-74e43c1c-0ed4-4f74-8212-caecbf1de333.png">

Error being thrown every tick:

```python
2023-03-10 12:27:22,609 - 12384 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - NETWORK - Unexpected error while fetching trading fees.
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/exchange_py_base.py", line 776, in _trading_fees_polling_loop
    await safe_gather(self._update_trading_fees())
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 591, in _update_trading_fees
    self._trading_fees = await self._api_data_source.get_trading_fees()
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 529, in get_trading_fees
    for trading_pair, market in self._trading_pair_to_active_spot_markets.items():
AttributeError: 'InjectiveAPIDataSource' object has no attribute '_trading_pair_to_active_spot_markets'
```

Error related to the supposed order that was created:

```python
2023-03-10 12:27:22,859 - 12384 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - NETWORK - Error fetching status update for the order BIJUT5f690bef5079f33f47d0eecf04ad56dcd63c5cae32c07: <AioRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "object not found"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:34.138.231.254:443 {grpc_message:"object not found", grpc_status:5, created_time:"2023-03-10T12:27:22.67539-07:00"}"
>.
```

## Steps To Reproduce
1. Clone and install branch
2. Setup and run gateway using the feature PR for Dexalot
3. Connect Injective wallet
4. Create and run a pure MM strategy using Injective

## Test Result Comparison
I tried replicating this on the foundation repository however I encountered an [issue](https://github.com/hummingbot/hummingbot/issues/6143) which further blocks testing.

## Attachments
Logs and config: 
[injective_issue.zip](https://github.com/CoinAlpha/hummingbot/files/10945983/injective_issue.zip)

**Comment by petioptrv** [comment]
This issue should be gone now.

**Comment by rxlxrxsx** [comment]
Tested on commit [7399225](https://github.com/CoinAlpha/hummingbot/pull/315/commits/7399225581ba3863943626367bc9f12f71639adb) and confirmed fixed.
