### ISSUE TITLE
Bittrex unhandled error using avellaneda USD as quote token

### ISSUE THREAD

**Issue by glenntomas** [CoinAlpha/hummingbot#3171]
**Describe the bug**
When using trading pair with USD quote with `avellaneda_market_making` shows unexpected error running clock tick and stucked after `volatility_buffer_size` and doesn't create orders

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create `avellaneda_market_making` strategy
2. Use Bittrex exchange and choose trading pair that has USD quote (BTC/USD - clock tick), (USDT-USD - Stucked after `volatility_buffer_size`) 
3. `start` the strategy

It only occurs when using USD as quote
```
2021-04-06 06:00:00,003 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 420, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_tick
    self.c_calculate_reserved_price_and_optimal_spread()
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 501, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_calculate_reserved_price_and_optimal_spread
    self._reserved_price = price - (q * self._gamma * mid_price_variance * time_left_fraction)
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'NoneType'
```

**Screenshots**
`2021-04-06 06:00:00,003 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.`
![image](https://user-images.githubusercontent.com/73885708/113679981-f87b1500-96f2-11eb-8e5b-dfe1a92e3fb2.png)

Stucked after `volatility_buffer_size` 
![image](https://user-images.githubusercontent.com/73885708/113682532-d8992080-96f5-11eb-8357-d670368e61ad.png)

**Release version**
dev-0.38.0

**Attachments**
[logs_conf_avellaneda_market_making_1.log](https://github.com/CoinAlpha/hummingbot/files/6263252/logs_conf_avellaneda_market_making_1.log)

**Comment by RC-13** [comment]
Closing ticket, after we did another test, we found out that this was due to a similar issue #2988
