### ISSUE TITLE
Failed Test PR #315 - Error requesting exchange info

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#318]
## Summary and Screenshots
Getting this error whenever gateway is not yet online.

<img width="1422" alt="Screen Shot 2023-03-13 at 9 23 39 AM" src="https://user-images.githubusercontent.com/64377055/224752955-4479bbd0-0784-4c2f-b213-68f00bfd0834.png">

```python
2023-03-13 09:01:34,050 - 9460 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/clob/markets failed. See logs for more details.
2023-03-13 09:01:34,050 - 9460 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 15888)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/exchange_py_base.py", line 1088, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/gateway_clob_spot.py", line 578, in _make_trading_pairs_request
    symbol_map = await self._api_data_source.get_symbol_map()
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/clob_api_data_source_base.py", line 221, in get_symbol_map
    self._check_markets_initialized() or await self._update_markets()
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/gateway_clob_api_data_source_base.py", line 407, in _update_markets
    for market_info in await self._get_markets_info():
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/gateway_clob_api_data_source_base.py", line 418, in _get_markets_info
    resp = await self._get_gateway_instance().get_clob_markets(
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/gateway/gateway_http_client.py", line 1176, in get_clob_markets
    resp = await self.api_request(method="get", path_url="clob/markets", params=request_payload)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/gateway/gateway_http_client.py", line 183, in api_request
    response = await client.get(url, params=params)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:15888 ssl:default [Connect call failed ('127.0.0.1', 15888)]
```

## Steps To Reproduce
1. Clone and install branch
2. Run the client

## Test Result Comparison
Not hitting this issue on development.

## Attachments
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/10959110/logs_hummingbot.log)

**Comment by petioptrv** [comment]
This is normal. The reason we're not observing this with Injective is that we fetch the trading pairs for injective using their python SDK, but we use Gateway with Dexalot. This means that if Gateway is not online, we can't fetch them. Same will happen if a CEX exchange servers are down.
