### ISSUE TITLE
amm_arb Strategy ERROR - [<class 'decimal.ConversionSyntax'>]

### ISSUE THREAD

**Issue by shahzadil** [CoinAlpha/hummingbot#3215]
**Describe the bug**

While testing the amm_arb strategy on konan_test, I got the following error:

```
hummingbot.connector.connector.uniswap.uniswap_connector - ERROR - [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/connector/uniswap/uniswap_connector.py", line 506, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/connector/uniswap/uniswap_connector.py", line 535, in _update_balances
    self._account_available_balances[token] = Decimal(str(bal))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
2021-04-15 19:03:37,323 - 1 - hummingbot.connector.connector.uniswap.uniswap_connector - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/connector/uniswap/uniswap_connector.py", line 506, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/connector/uniswap/uniswap_connector.py", line 535, in _update_balances
    self._account_available_balances[token] = Decimal(str(bal))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Steps To Reproduce**

- Create amm_arm strategy
- Enter all the details
- start the strategy

**Screenshots**
My Config:

![config](https://user-images.githubusercontent.com/81416132/114925291-8b7f2200-9e4c-11eb-840d-78f422f20ddb.PNG)

**Release version**

v0.38

**Attachments**

[logs_conf_amm_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/6320554/logs_conf_amm_arb_1.log)

**Comment by rapcmia** [comment]
Hi @shahzadil I tried to set up testbot for AMM-Arb using the same config on `Kovan testnet` and did not encounter the error. I think there was an update with our gateway so you might want to run the helper script `./update-gateway.sh` and try to check again. I can also check balances which seems to be ok.

![image](https://user-images.githubusercontent.com/73840223/114951624-6065f400-9e87-11eb-92e3-0842a27d18c8.png)

**Comment by shahzadil** [comment]
Everything is working as expected. Closing the issue.
