### ISSUE TITLE
Failed Test PR #324 - Errors after running the strategy

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#328]
## Summary and Screenshots
Getting flooded by errors immediately after start a perpetual market making strategy using Injective Perpetual. Here are the errors captured in the logs:

<img width="1422" alt="Screen Shot 2023-03-23 at 11 08 33 AM" src="https://user-images.githubusercontent.com/64377055/227305512-3673b324-922e-4641-996a-fcc6ff94f132.png">

```python
2023-03-23 11:08:23,265 - 6846 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'InjectivePerpetualAPIDataSource' object has no attribute '_sleep'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 287, in _update_market_info_loop
    await self._sleep(delay=CONSTANTS.MARKETS_UPDATE_INTERVAL)
AttributeError: 'InjectivePerpetualAPIDataSource' object has no attribute '_sleep'
```

```python
2023-03-23 11:08:23,268 - 6846 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'ETH-USDT'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/data_type/order_book_tracker.py", line 180, in _init_order_books
    self._order_books[trading_pair] = await self._initial_order_book_for_trading_pair(trading_pair)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/data_type/order_book_tracker.py", line 173, in _initial_order_book_for_trading_pair
    return await self._data_source.get_new_order_book(trading_pair)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/data_type/order_book_tracker_data_source.py", line 65, in get_new_order_book
    snapshot_msg: OrderBookMessage = await self._order_book_snapshot(trading_pair=trading_pair)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/gateway_clob_perp_api_order_book_data_source.py", line 84, in _order_book_snapshot
    snapshot = await self._api_data_source.get_order_book_snapshot(trading_pair=trading_pair)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 243, in get_order_book_snapshot
    market_info = self._trading_pair_to_active_perp_markets[trading_pair]
KeyError: 'ETH-USDT'
```

```python
2023-03-23 11:08:23,769 - 6846 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: next_funding_timestamp
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/perpetual_derivative_py_base.py", line 364, in _listen_for_funding_info
    await self._init_funding_info()
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/perpetual_derivative_py_base.py", line 371, in _init_funding_info
    funding_info = await self._orderbook_ds.get_funding_info(trading_pair)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/gateway_clob_perp_api_order_book_data_source.py", line 88, in get_funding_info
    return await self._api_data_source.get_funding_info(trading_pair=trading_pair)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 786, in get_funding_info
    return await self._request_funding_info(trading_pair=trading_pair)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 780, in _request_funding_info
    next_funding_utc_timestamp=market_info.next_funding_timestamp,
AttributeError: next_funding_timestamp
```

```python
2023-03-23 11:08:24,005 - 6846 - hummingbot.connector.gateway.clob_perp.gateway_clob_perp.GatewayCLOBPerp - ERROR - Error requesting time from Injective_perpetual_injective_mainnet server
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/exchange_py_base.py", line 832, in _update_time_synchronizer
    time_provider=self.web_utils.get_current_server_time(
AttributeError: 'NoneType' object has no attribute 'get_current_server_time'
```

```python
2023-03-23 11:08:24,010 - 6846 - hummingbot.connector.gateway.clob_perp.gateway_clob_perp.GatewayCLOBPerp - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/exchange_py_base.py", line 810, in _status_polling_loop
    await self._update_time_synchronizer()
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/exchange_py_base.py", line 832, in _update_time_synchronizer
    time_provider=self.web_utils.get_current_server_time(
AttributeError: 'NoneType' object has no attribute 'get_current_server_time'
```

```python
2023-03-23 11:08:37,321 - 6846 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'InjectivePerpetualAPIDataSource' object has no attribute '_bank_balances_stream_listener'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/gateway_clob_perp.py", line 214, in stop_network
    await self._api_data_source.stop()
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 153, in stop
    await self._stop_streams()
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 1290, in _stop_streams
    self._bank_balances_stream_listener and self._bank_balances_stream_listener.cancel()
AttributeError: 'InjectivePerpetualAPIDataSource' object has no attribute '_bank_balances_stream_listener'
```

## Steps To Reproduce
1. Run gateway (PR 7 - feat/injective_perpetual)
2. Run the client
3. Connect Injective Perpetual API key
4. Create and run a perpetual market making strategy using Injective Perpetual

## Test Result Comparison
N/A, new connector

## Attachments
Logs and config: [injperp_errors.zip](https://github.com/CoinAlpha/hummingbot/files/11054440/injperp_errors.zip)

**Comment by mrhzysbl** [comment]
Unable to start the strategy after pulling the commit [e770d73](https://github.com/CoinAlpha/hummingbot/pull/324/commits/e770d73f5c6cecb197030e382c79d2dbb0c0abfa) .

<img width="1594" alt="Screen Shot 2023-03-24 at 4 24 32 PM" src="https://user-images.githubusercontent.com/120451804/227464991-7a250747-54c9-47e1-b665-0c2734c6b7a2.png">

```ruby
2023-03-24 16:23:18,296 - 4417 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No module named 'pyinjective.proto.exchange.injective_portfolio_rpc_pb2'
Traceback (most recent call last):
  File "/Users/admin/pr324/clob/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/admin/pr324/clob/hummingbot/client/command/start_command.py", line 99, in start_check
    elif not await self.status_check_all(notify_success=False):
  File "/Users/admin/pr324/clob/hummingbot/client/command/status_command.py", line 172, in status_check_all
    invalid_conns = await asyncio.wait_for(self.validate_required_connections(), network_timeout)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/Users/admin/pr324/clob/hummingbot/client/command/status_command.py", line 95, in validate_required_connections
    connections = await UserBalances.instance().update_exchanges(self.client_config_map, exchanges=required_exchanges)
  File "/Users/admin/pr324/clob/hummingbot/user/user_balances.py", line 136, in update_exchanges
    results = await safe_gather(*tasks)
  File "/Users/admin/pr324/clob/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/admin/pr324/clob/hummingbot/user/user_balances.py", line 110, in update_exchange_balance
    return await self.add_exchange(exchange_name, client_config_map, **api_keys)
  File "/Users/admin/pr324/clob/hummingbot/user/user_balances.py", line 86, in add_exchange
    market = UserBalances.connect_market(exchange, client_config_map, **api_details)
  File "/Users/admin/pr324/clob/hummingbot/user/user_balances.py", line 25, in connect_market
    init_params = conn_setting.conn_init_parameters(
  File "/Users/admin/pr324/clob/hummingbot/client/settings.py", line 265, in conn_init_parameters
    params["api_data_source"] = self._load_clob_api_data_source(
  File "/Users/admin/pr324/clob/hummingbot/client/settings.py", line 338, in _load_clob_api_data_source
    module: ModuleType = importlib.import_module(module_path)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/admin/pr324/clob/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 31, in <module>
    from pyinjective.proto.exchange.injective_portfolio_rpc_pb2 import (
ModuleNotFoundError: No module named 'pyinjective.proto.exchange.injective_portfolio_rpc_pb2' ```

**Comment by rxlxrxsx** [comment]
@mrhzysbl I haven't encountered the same issue you got on commit [e770d73](https://github.com/CoinAlpha/hummingbot/pull/324/commits/e770d73f5c6cecb197030e382c79d2dbb0c0abfa). Can you try this again on a fresh clone of the repo?

I did re-try but I'm still getting errors after starting the strategy. These are the errors I'm getting when a position is currently open after starting the bot:

<img width="1425" alt="Screen Shot 2023-03-24 at 10 52 08 AM" src="https://user-images.githubusercontent.com/64377055/227593733-ee8647ce-a58c-4b24-aacd-55938802e546.png">

```python
2023-03-24 08:32:01,235 - 3318 - hummingbot.connector.gateway.clob_perp.data_sources.injective_perpetual.injective_perpetual_api_data_source.InjectivePerpetualAPIDataSource - ERROR - Unexpected error in position listener loop.
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 1211, in _listen_to_positions_stream
    async for message in stream:
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Received http2 header with status: 502"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:34.138.231.254:443 {grpc_message:"Received http2 header with status: 502", grpc_status:14, created_time:"2023-03-24T08:32:01.232242-06:00"}"
>
```

```python
2023-03-24 08:32:01,242 - 3318 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 1207, in _listen_to_positions_stream
    stream: UnaryStreamCall = await self._client.stream_derivative_positions(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/pyinjective/async_client.py", line 927, in stream_derivative_positions
    metadata = await self.load_cookie(type="exchange")
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/pyinjective/async_client.py", line 267, in load_cookie
    metadata = await self.renew_cookie(self.exchange_cookie, type)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/pyinjective/async_client.py", line 234, in renew_cookie
    expires_at = cookie.get(f"{self.cookie_type}").get("expires")
AttributeError: 'NoneType' object has no attribute 'get'
```

```python
2023-03-24 08:32:01,529 - 3318 - hummingbot.connector.gateway.clob_perp.gateway_clob_perp.GatewayCLOBPerp - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/exchange_py_base.py", line 813, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/perpetual_derivative_py_base.py", line 299, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/gateway_clob_perp.py", line 319, in _update_positions
    positions: List[Position] = await self._api_data_source.fetch_positions()
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 591, in fetch_positions
    market_info: DerivativeMarketInfo = self._market_id_to_active_perp_markets[position["marketId"]]
TypeError: 'Position' object is not subscriptable
```

These are the errors I'm getting when no positions are currently open, I also noticed that it fails to cancel the orders and is left stuck in the exchange.

```python
2023-03-24 11:11:50,985 - 3692 - hummingbot.connector.gateway.clob_perp.data_sources.injective_perpetual.injective_perpetual_api_data_source.InjectivePerpetualAPIDataSource - ERROR - Unexpected error in account balance listener loop.
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 976, in _listen_to_bank_balances_streams
    self._process_bank_balance_stream_event(message=bank_balance)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 966, in _process_bank_balance_stream_event
    balance_msg: BalanceUpdateEvent = self._parse_bank_balance_message(message=message)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 956, in _parse_bank_balance_message
    asset_name=denom_meta.symbol,
AttributeError: 'dict' object has no attribute 'symbol'
```

```python
2023-03-24 11:11:51,082 - 3692 - hummingbot.connector.gateway.clob_perp.data_sources.injective_perpetual.injective_perpetual_api_data_source.InjectivePerpetualAPIDataSource - ERROR - Unexpected error in transaction listener loop.
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 1094, in _listen_to_transactions_stream
    await self._process_transaction_event(transaction=transaction)
  File "/Users/reiniersalazar/hbot-ca-injectiveperp/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 1080, in _process_transaction_event
    messages = json.loads(s=transaction.message)
AttributeError: message
```

Logs and config: [injective_perp_e770d73.zip](https://github.com/CoinAlpha/hummingbot/files/11064842/injective_perp_e770d73.zip)

**Comment by mrhzysbl** [comment]
Pulled the latest commit [a15dc29](https://github.com/CoinAlpha/hummingbot/pull/324/commits/a15dc29ca9cd32b9ec1bbf647ed7b003c300d23c) and still unable to start a strategy. Getting this error:

<img width="1121" alt="Screen Shot 2023-03-28 at 5 06 51 PM" src="https://user-images.githubusercontent.com/120451804/228187079-a232c7ef-c28f-400e-b630-eada2915e115.png">

Tried to run the balance command and getting the same error.

``` ruby
2023-03-28 16:42:43,728 - 4305 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/Users/admin/pr324/clob/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/admin/pr324/clob/hummingbot/client/command/balance_command.py", line 84, in show_balances
    all_ex_bals = await asyncio.wait_for(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError 
```

Kindly try again if you'll be getting the same error @rxlxrxsx .
[Injective_Perp_a15dc29.zip](https://github.com/CoinAlpha/hummingbot/files/11087537/Injective_Perp_a15dc29.zip)

**Comment by rxlxrxsx** [comment]
@mrhzysbl still getting the same error as I commented above. I suggest trying it once more, based on the error you got it's related to your network connection, I haven't encountered this during my testing.

**Comment by petioptrv** [comment]
This issue will be addressed by #330

**Comment by petioptrv** [comment]
The issues listed here should now be addressed by #330
