### ISSUE TITLE
Failed Test PR #330 - Error fetching trading pairs for Injective Perpetual

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#332]
## Summary and Screenshots
Getting this error after running the client. This error is only thrown when the Injective Perpetual API key is already connected.

<img width="1278" alt="Screen Shot 2023-03-30 at 10 06 06 AM" src="https://user-images.githubusercontent.com/64377055/228902272-842f7ab9-2478-48eb-8925-2ca74fe7f9dd.png">

```python
2023-03-30 09:40:09,826 - 6331 - hummingbot.core.utils.trading_pair_fetcher - ERROR - An error occurred when fetching trading pairs for injective_perpetual_injective_mainnet.Please check the logs
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-injperp/hummingbot/core/utils/trading_pair_fetcher.py", line 53, in fetch_all
    self._fetch_pairs_from_connector_setting(connector_setting=conn_setting)
  File "/Users/reiniersalazar/hbot-ca-injperp/hummingbot/core/utils/trading_pair_fetcher.py", line 38, in _fetch_pairs_from_connector_setting
    connector = connector_setting.non_trading_connector_instance_with_default_configuration()
  File "/Users/reiniersalazar/hbot-ca-injperp/hummingbot/client/settings.py", line 321, in non_trading_connector_instance_with_default_configuration
    kwargs = self.conn_init_parameters(
  File "/Users/reiniersalazar/hbot-ca-injperp/hummingbot/client/settings.py", line 270, in conn_init_parameters
    params["api_data_source"] = self._load_clob_api_data_source(
  File "/Users/reiniersalazar/hbot-ca-injperp/hummingbot/client/settings.py", line 345, in _load_clob_api_data_source
    instance = api_data_source_class(
TypeError: Can't instantiate abstract class InjectivePerpetualAPIDataSource with abstract methods _get_exchange_base_quote_tokens_from_market_info, _get_exchange_trading_pair_from_market_info, _get_last_trade_price_from_ticker_data, _get_maker_taker_exchange_fee_rates_from_market_info, _get_trading_pair_from_market_info, _parse_trading_rule, connector_name, current_block_time, events_are_streamed
```

## Steps To Reproduce
1. Run gateway (PR 7 - feat/injective_perpetual)
2. Run the client
3. Connect Injective Perpetual API key
4. Restart the client

## Test Result Comparison
N/A, new connector

## Attachments
N/A

**Comment by petioptrv** [comment]
This issue should be now addressed

**Comment by mrhzysbl** [comment]
Tested and confirmed that the issue is no longer showing on commit [219225a](https://github.com/CoinAlpha/hummingbot/pull/330/commits/219225a74bce48ffc55840b2fc465141d7ab3cb3)
