### ISSUE TITLE
Loopring - Error calculating probability

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3338]
**Describe the bug**
Running the bot using Loopring keeps getting `Error calculating profitability`. It seems that this was triggered when the websocket connection error first appeared (see timestamp `2021-05-08 11:55:04,008` on the logs). Running history command also shows an error and will not show all the details as it should.

```
2021-05-08 11:55:21,461 - 29824 - hummingbot.core.utils.kill_switch - ERROR - Error calculating profitability: 'LRC-USDT'
Traceback (most recent call last):
  File "/home/ubuntu/loopring/hummingbot/core/utils/kill_switch.py", line 35, in check_profitability_loop
    self._profitability: Decimal = await self._hummingbot_application.calculate_profitability()
  File "/home/ubuntu/loopring/hummingbot/client/command/history_command.py", line 203, in calculate_profitability
    avg_return = await self.history_report(start_time, trades, display_report=False)
  File "/home/ubuntu/loopring/hummingbot/client/command/history_command.py", line 75, in history_report
    perf = await calculate_performance_metrics(market, symbol, cur_trades, cur_balances)
  File "/home/ubuntu/loopring/hummingbot/client/performance.py", line 168, in calculate_performance_metrics
    perf.cur_price = await get_last_price(exchange.replace("_PaperTrade", ""), trading_pair)
  File "/home/ubuntu/loopring/hummingbot/core/utils/market_price.py", line 29, in get_last_price
    return Decimal(str(last_prices[trading_pair]))
KeyError: 'LRC-USDT'
```

When running `history` command

```
2021-05-10 04:08:53,638 - 29824 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'LRC-USDT'
Traceback (most recent call last):
  File "/home/ubuntu/loopring/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/loopring/hummingbot/client/command/history_command.py", line 75, in history_report
    perf = await calculate_performance_metrics(market, symbol, cur_trades, cur_balances)
  File "/home/ubuntu/loopring/hummingbot/client/performance.py", line 168, in calculate_performance_metrics
    perf.cur_price = await get_last_price(exchange.replace("_PaperTrade", ""), trading_pair)
  File "/home/ubuntu/loopring/hummingbot/core/utils/market_price.py", line 29, in get_last_price
    return Decimal(str(last_prices[trading_pair]))
KeyError: 'LRC-USDT'
```

**Steps To Reproduce**
1. Run a pure_mm bot on Loopring
2. When the `Error calculating profitability` arises, run history command

**Screenshots**
<img width="1422" alt="Screen Shot 2021-05-10 at 12 08 45 PM" src="https://user-images.githubusercontent.com/64377055/117611040-576df700-b195-11eb-999e-70d6cfd5638c.png">

**Release version**
development-0.39.0

**Attachments**
[loopring.zip](https://github.com/CoinAlpha/hummingbot/files/6449739/loopring.zip)

**Comment by RC-13** [comment]
So far the issue hasn't occurred again, closing this ticket for now.
![image](https://user-images.githubusercontent.com/57189990/118749642-84569400-b890-11eb-819a-4226e943718d.png)
