### ISSUE TITLE
Fix AscendEx Unit Tests

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#3352]
**Describe the bug**
fail / error unit test on ascendex  

- test_ascend_ex_auth.py 1/1 = 1 error
```
(hummingbot) ubuntu@ip-172-31-37-182:~/hb-source-ascendex$ nosetests -v -s test/connector/exchange/ascend_ex/test_ascend_ex_auth.py
Failure: ModuleNotFoundError (No module named 'hummingbot.connector.exchange.ascend_ex.ascend_ex_util') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'hummingbot.connector.exchange.ascend_ex.ascend_ex_util')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/hb-source-ascendex/test/connector/exchange/ascend_ex/test_ascend_ex_auth.py", line 15, in <module>
    from hummingbot.connector.exchange.ascend_ex.ascend_ex_util import get_rest_url_private
ModuleNotFoundError: No module named 'hummingbot.connector.exchange.ascend_ex.ascend_ex_util'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
```

- test_ascend_ex_user_stream_tracker.py 1/1 =  error
```
(hummingbot) ubuntu@ip-172-31-37-182:~/hb-source-ascendex$ nosetests -v -s test/connector/exchange/ascend_ex/test_ascend_ex_test_ascend_ex_user_stream_tracker.py
Failure: ImportError (No module named 'test_ascend_ex_test_ascend_ex_user_stream_tracker') ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named 'test_ascend_ex_test_ascend_ex_user_stream_tracker')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'test_ascend_ex_test_ascend_ex_user_stream_tracker'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```
- test_ascend_ex_exchange.py = stuck for hours
![image](https://user-images.githubusercontent.com/54516858/117804521-713d3600-b28a-11eb-8202-25c0e049284e.png)

- config_local.py
![image](https://user-images.githubusercontent.com/54516858/117808198-2bcf3780-b28f-11eb-926e-de627d09328b.png)

**Comment by dendenski** [comment]
Run unit test using master branch.
- test_ascend_ex_auth.py: 1 OK, 1 ERROR
[test_ascend_ex_auth.log](https://github.com/CoinAlpha/hummingbot/files/6462505/test_ascend_ex_auth.log)
- test_ascend_ex_exchange.py: 2 OK, 4 ERROR, 2 FAIL
[test_ascend_ex_exchange.log](https://github.com/CoinAlpha/hummingbot/files/6462508/test_ascend_ex_exchange.log)
- test_ascend_ex_order_book_tracker.py: 3 OK
[test_ascend_ex_order_book_tracker.log](https://github.com/CoinAlpha/hummingbot/files/6462509/test_ascend_ex_order_book_tracker.log)
- test_ascend_ex_user_stream_tracker.py: 1 OK
[test_ascend_ex_user_stream_tracker.log](https://github.com/CoinAlpha/hummingbot/files/6462512/test_ascend_ex_user_stream_tracker.log)
