### ISSUE TITLE
Avellaneda Market Making -  Order_override on expert mode returns unexpected error running clock tick after calculating volatility 

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#3392]
**Describe the bug**
Getting `Unexpected error running clock tick` after calculating volatility on expert mode when over_override is set up on Avellaneda strategy. The bot creates orders if we don't override orders in config file (example test.yml)

```
2021-05-18 16:30:16,013 - 20460 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\core\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\strategy\avellaneda_market_making\avellaneda_market_making.pyx", line 430, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_tick
    self.c_calculate_reserved_price_and_optimal_spread()
  File "hummingbot\strategy\avellaneda_market_making\avellaneda_market_making.pyx", line 509, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_calculate_reserved_price_and_optimal_spread
    self._reserved_price = price - (q * self._gamma * mid_price_variance * time_left_fraction)
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'NoneType'
2021-05-18 16:30:17,010 - 20460 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\core\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\strategy\avellaneda_market_making\avellaneda_market_making.pyx", line 430, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_tick
    self.c_calculate_reserved_price_and_optimal_spread()
  File "hummingbot\strategy\avellaneda_market_making\avellaneda_market_making.pyx", line 509, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_calculate_reserved_price_and_optimal_spread
    self._reserved_price = price - (q * self._gamma * mid_price_variance * time_left_fraction)
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'NoneType'
```

**Steps To Reproduce**
1. Setup an Avellaneda market making strategy on Expert mode
2. Exit the bot then go to your hummingbot/conf or conf directory and modify your config file (example test.yml)

3. Setup order_override 
4. Relaunch the bot and import your config, start the bot

**Screenshots**
The bot returns `Unexpected error running clock tick`
![override-order](https://user-images.githubusercontent.com/73840223/118648776-5c761a80-b815-11eb-94f1-fe0a53770617.PNG)

The bot creates order when order_override is not setup on expert mode
![override-order off](https://user-images.githubusercontent.com/73840223/118649124-b971d080-b815-11eb-90d5-a8d92b3f8bdd.PNG)

**Release version**
dev-0.39.0

**Attachments**
[logs_ave-3379.log](https://github.com/CoinAlpha/hummingbot/files/6501149/logs_ave-3379.log)
[ave-3379-config.txt](https://github.com/CoinAlpha/hummingbot/files/6501162/ave-3379-config.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by dennisocana** [comment]
Fixed in version 0.40 release
