### ISSUE TITLE
Failed Test PR #330 - Funding payment not received

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#341]
## Summary and Screenshots
The funding payment is not being received by the bot, waited for at least 30 minutes but no message was seen regarding the funding payment received in the logs.

## Steps To Reproduce
1. Clone and install featured branch
2. Connect to gateway
3. Create a perpetual market making strategy using Injective Perpetual
4. Set tight spreads and wait for an order to get filled
5. With a position currently open, wait for funding period to pass by

## Test Result Comparison
N/A, new connector

## Attachments
Logs and config: [inj_funding.zip](https://github.com/CoinAlpha/hummingbot/files/11181681/inj_funding.zip)

**Comment by petioptrv** [comment]
Addressed in [this commit](https://github.com/CoinAlpha/hummingbot/pull/330/commits/a4f92e49e3ccf47f1a9b7e5340bc6ae8463a2f57).

**Comment by mrhzysbl** [comment]
There is an open position for more than 30 minutes then I got this message: 

<img width="1495" alt="Screen Shot 2023-04-10 at 5 42 57 PM" src="https://user-images.githubusercontent.com/120451804/230877384-3fae2b26-18cf-424f-a493-9290458a145d.png">

``` ruby
2023-04-10 17:43:41,346 - 3158914 - hummingbot.connector.gateway.clob_perp.gateway_clob_perp.GatewayCLOBPerp - WARNING - Could not fetch last fee payment for INJ-USDT. Check network connection.
2023-04-10 17:44:06,396 - 3158914 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/clob/perp/funding/payments failed. See logs for more details.
2023-04-10 17:44:06,397 - 3158914 - hummingbot.connector.gateway.clob_perp.gateway_clob_perp.GatewayCLOBPerp - NETWORK - Unexpected error while fetching last fee payment for INJ-USDT.
Traceback (most recent call last):
  File "/home/ubuntu/rhiza/inj_client/hummingbot/connector/perpetual_derivative_py_base.py", line 414, in _update_funding_payment
    timestamp, funding_rate, payment_amount = await self._fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/ubuntu/rhiza/inj_client/hummingbot/connector/gateway/clob_perp/gateway_clob_perp.py", line 418, in _fetch_last_fee_payment
    return await self._api_data_source.fetch_last_fee_payment(trading_pair=trading_pair)
  File "/home/ubuntu/rhiza/inj_client/hummingbot/connector/gateway/clob_perp/data_sources/injective_perpetual/injective_perpetual_api_data_source.py", line 520, in fetch_last_fee_payment
    response: Dict[str, Any] = await self._get_gateway_instance().clob_perp_funding_payments(
  File "/home/ubuntu/rhiza/inj_client/hummingbot/core/gateway/gateway_http_client.py", line 1312, in clob_perp_funding_payments
    return await self.api_request("post", "clob/perp/funding/payments", request_payload, use_body=True)
  File "/home/ubuntu/rhiza/inj_client/hummingbot/core/gateway/gateway_http_client.py", line 218, in api_request
    raise e
  File "/home/ubuntu/rhiza/inj_client/hummingbot/core/gateway/gateway_http_client.py", line 187, in api_request
    response = await client.post(url, json=params)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```
[Inj_funding.zip](https://github.com/CoinAlpha/hummingbot/files/11189619/Inj_funding.zip)

**Comment by mrhzysbl** [comment]
Tested on commit [dcea0fa](https://github.com/CoinAlpha/hummingbot/pull/330/commits/dcea0fa803d04cb34698b27e6973f138fdb486b5) and verified that the funding message is now showing on the log pane.
