### ISSUE TITLE
Avellaneda Strategy - clock tick error for long running bot

### ISSUE THREAD

**Issue by dendenski** [CoinAlpha/hummingbot#3424]
**Describe the bug**
// A clear and concise description of what the bug is.
Clock tick error happened after cancel order
```
2021-05-21 18:21:16,163 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - INFO - Successfully cancelled order sell-XEM-USDT-1621620976003855.
2021-05-21 18:21:16,173 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1621621276.0, "order_id": "sell-XEM-USDT-1621620976003855", "exchange_order_id": "60a7f8f07a22ce0006167409", "event_name": "OrderCancelledEvent", "event_source": "kucoin"}
2021-05-21 18:22:10,007 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 435, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_tick
    self.c_apply_budget_constraint(proposal)
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 646, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_apply_budget_constraint
    base_balance, quote_balance = self.c_get_adjusted_available_balance(self.active_orders)
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 622, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_get_adjusted_available_balance
    object quote_balance = market.c_get_available_balance(self.quote_asset)
  File "hummingbot/connector/connector_base.pyx", line 324, in hummingbot.connector.connector_base.ConnectorBase.c_get_available_balance
    return self.get_available_balance(currency)
  File "hummingbot/connector/connector_base.pyx", line 339, in hummingbot.connector.connector_base.ConnectorBase.get_available_balance
    available_balance = self.apply_balance_limit(currency, available_balance, balance_limit)
  File "hummingbot/connector/connector_base.pyx", line 303, in hummingbot.connector.connector_base.ConnectorBase.apply_balance_limit
    filled_balance = self.order_filled_balances().get(currency, s_decimal_0)
  File "hummingbot/connector/connector_base.pyx", line 139, in hummingbot.connector.connector_base.ConnectorBase.order_filled_balances
    quote_value = Decimal("-1") * event.price * event.amount
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
```
**Steps To Reproduce**
1. Set up your configuration file with these parameters:
![image](https://user-images.githubusercontent.com/65387749/119199961-961d7e80-babe-11eb-9bc1-163fb25be119.png)
2. Start the bot.
3. Run the bot for a few days.

**Screenshots**
![image](https://user-images.githubusercontent.com/65387749/119200280-31aeef00-babf-11eb-82c2-7355d82a0484.png)

**Release version**
0.39.0

**Attachments**
[avellaneda_kucoin.zip](https://github.com/CoinAlpha/hummingbot/files/6525153/avellaneda_kucoin.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by guiguid** [comment]
Hi, same issue,
when inventory_target_base_pct is set to 0 : Unexpected error running clock tick
when setting inventory_target_base_pct at 10 : no errors
cheers

**Comment by dennisocana** [comment]
Similar to https://github.com/CoinAlpha/hummingbot/issues/3361.

**Comment by smalltimepro** [comment]
I run PMM strategy and get get the error 1-5 times a day on each bot. It seems to be that the same bug exists on the PMM strategy as well. I will upgrade to 0.40 and monitor if it keeps happening, but worth checking on code level as well. I have looked into the code changes in #3361 and dont fully understand as yet how it addresses the bug
