### ISSUE TITLE
Failed Test PR#342 - Failed to cancel orders

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#344]
## Summary and Screenshots
After confirming issue #343 is due to an incorrect position mode, we are now facing an error when the bot attempts to cancel orders. Checked on the exchange and confirmed the setting are the same with the bot config.

<img width="1422" alt="Screen Shot 2023-04-14 at 9 38 03 PM" src="https://user-images.githubusercontent.com/64377055/232181296-937b908c-ccab-47b9-a943-5e7293706823.png">

```python
2023-04-15 11:38:36,382 - 3313173 - hummingbot.connector.derivative.phemex_perpetual.phemex_perpetual_derivative.PhemexPerpetualDerivative - ERROR - Failed to cancel order SDEUT5f9577e1f47039cc07bc38fbd7e9e201819
Traceback (most recent call last):
  File "/home/ubuntu/phemex/hummingbot/connector/exchange_py_base.py", line 553, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/home/ubuntu/phemex/hummingbot/connector/exchange_py_base.py", line 573, in _execute_order_cancel_and_process_update
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/ubuntu/phemex/hummingbot/connector/derivative/phemex_perpetual/phemex_perpetual_derivative.py", line 277, in _place_cancel
    raise IOError(f"{code} - {message}")
OSError: 20004 - TE_ERR_INCONSISTENT_POS_MODE
```

## Steps To Reproduce
1. Clone and install branch
2. Run the client
3. Connect Phemex API key
4. Create a perpetual market making strategy using Phemex
5. Start the strategy
6. Wait until the bot attempts to cancel the orders

## Test Result Comparison
N/A, new connector

## Attachments
Logs and config: [phemex_cancel_order.zip](https://github.com/CoinAlpha/hummingbot/files/11238207/phemex_cancel_order.zip)

**Comment by vic-en** [comment]
@rxlxrxsx Ensure that there are no positions and orders when starting a strategy that changes the position mode.

**Comment by mrhzysbl** [comment]
Tested and confirmed on commit [b3c3df3](https://github.com/CoinAlpha/hummingbot/pull/342/commits/b3c3df386d5db20cace2f85fa0f9ccde5ebf3897) that there were no stuck orders.
