### ISSUE TITLE
Failed Test PR# 342 - Not creating order to close position 

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/hummingbot#346]
## Summary and Screenshots
Getting this error whenever the bot is creating an order to close the position.

<img width="658" alt="Screen Shot 2023-04-17 at 3 08 24 PM" src="https://user-images.githubusercontent.com/120451804/232410422-dd8e3abd-12ee-4edf-9784-5d09e14c8f94.png">

https://user-images.githubusercontent.com/120451804/232410537-7fcb1163-8d97-4c03-a35f-a2e8580e1d23.mov

<br>

``` ruby
2023-04-17 14:12:49,066 - 2486 - hummingbot.connector.derivative.phemex_perpetual.phemex_perpetual_derivative.PhemexPerpetualDerivative - NETWORK - Error submitting buy LIMIT order to Phemex_perpetual for 60.0 DOGE-USDT 0.08995.
Traceback (most recent call last):
  File "/Users/admin/phemex/hummingbot/connector/exchange_py_base.py", line 484, in _create_order
    exchange_order_id = await self._place_order_and_process_update(order=order, **kwargs,)
  File "/Users/admin/phemex/hummingbot/connector/exchange_py_base.py", line 502, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/Users/admin/phemex/hummingbot/connector/derivative/phemex_perpetual/phemex_perpetual_derivative.py", line 331, in _place_order
    raise IOError(f"{code} - {order_result.get('msg')}")
OSError: 11011 - TE_REDUCE_ONLY_ABORT
```

## Steps To Reproduce
1. Clone and install the feat branch
2. Create a Perpetual Market Making Strategy. Set tight spreads to fill in orders quickly.
3. Start the strategy and wait for orders to be filled. Once filled, there should be an order in the open position.

## Expected Results
Once there is an open position, the bot should create another order to close the position

## Test Result Comparison
n/a, new connector

## Attachments

[Phemex.zip](https://github.com/CoinAlpha/hummingbot/files/11247291/Phemex.zip)

**Comment by mrhzysbl** [comment]
Tried to retest using commit [717a826](https://github.com/CoinAlpha/hummingbot/pull/342/commits/717a82692a4f067c328d38074b22485a0d5c03d8) and still getting the same error.

<img width="635" alt="Screen Shot 2023-04-18 at 2 08 57 PM" src="https://user-images.githubusercontent.com/120451804/232686695-8c3b833a-23a2-4100-b941-e190f9090402.png">

``` ruby
2023-04-18 14:04:16,080 - 1594 - hummingbot.connector.derivative.phemex_perpetual.phemex_perpetual_derivative.PhemexPerpetualDerivative - NETWORK - Error submitting buy LIMIT order to Phemex_perpetual for 250.0 DOGE-USDT 0.09261.
Traceback (most recent call last):
  File "/Users/admin/phemex/hummingbot/connector/exchange_py_base.py", line 484, in _create_order
    exchange_order_id = await self._place_order_and_process_update(order=order, **kwargs,)
  File "/Users/admin/phemex/hummingbot/connector/exchange_py_base.py", line 502, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/Users/admin/phemex/hummingbot/connector/derivative/phemex_perpetual/phemex_perpetual_derivative.py", line 329, in _place_order
    raise IOError(f"{code} - {order_result.get('msg')}")
OSError: 11011 - TE_REDUCE_ONLY_ABORT
```


[Phemex_order not created.zip](https://github.com/CoinAlpha/hummingbot/files/11258502/Phemex_order.not.created.zip)

**Comment by vic-en** [comment]
@mrhzysbl I pushed a commit that should resolve this.
Thanks.

**Comment by vic-en** [comment]
@mrhzysbl Can you run and also include a screenshot of the position you have on the exchange?

**Comment by rxlxrxsx** [comment]
Hi @vic-en, I think I've found the issue. As seen on the screenshot of the client you'll notice that a BUY order is filled however the position seen in the status output shows a SHORT position. This results to an incorrect order being placed to close the position.

<img width="1422" alt="Screen Shot 2023-04-25 at 8 24 25 PM" src="https://user-images.githubusercontent.com/64377055/234452760-1dde22bf-cf81-4be4-87f3-ae5f73a765dc.png">

<img width="962" alt="Screen Shot 2023-04-25 at 8 24 58 PM" src="https://user-images.githubusercontent.com/64377055/234452862-b9500532-d03b-4521-b88f-b06966629abb.png">

Logs, data and config: [issue_346.zip](https://github.com/CoinAlpha/hummingbot/files/11328443/issue_346.zip)

**Comment by vic-en** [comment]
@rxlxrxsx Thanks!
There is an inconsistency with the value of position sidebar various markets. That is reason I didn't catch it earlier cause I was testing on LTC-USDT market.
I pushed  a commit to resolve that.

**Comment by vic-en** [comment]
@rxlxrxsx I updated again.
pls do another test.

**Comment by rxlxrxsx** [comment]
Tested on commit [a8032b9](https://github.com/CoinAlpha/hummingbot/pull/342/commits/a8032b9c8a0b872129932ca9165f8d026a4f8d7d) and confirmed fixed.
