### ISSUE TITLE
Exception when stopping a strategy with the live status still active

### ISSUE THREAD

**Issue by aarmoa** [CoinAlpha/hummingbot#3467]
**Describe the bug**
When the bot is running and the live status functionality is activated, an exception happens when the strategy is stopped. This happens with any strategy.

**Steps To Reproduce**
Here are the steps to reproduce the issue:
1. Start the execution of any strategy (it could even be with paper trade)
2. Start the live status with the command **status --live**
3. Stop the execution of the strategy.

As a result in the "Running Logs" section there will be a line stating:
```
12:04:21 - async_utils - Unhandled error in background task: 'NoneType' object has no attribute 'format_status' (See log file for stack trace dump)
```

The log file includes the following error:

```
2021-05-31 12:04:22,611 - 3075 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'format_status'
Traceback (most recent call last):
  File "/Users/aarmoa/Projects/Hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/aarmoa/Projects/Hummingbot/hummingbot/client/command/status_command.py", line 131, in status_check_all
    await self.strategy_status() + script_status + "\n\n Press escape key to stop update.", 1
  File "/Users/aarmoa/Projects/Hummingbot/hummingbot/client/command/status_command.py", line 76, in strategy_status
    if inspect.iscoroutinefunction(self.strategy.format_status):
AttributeError: 'NoneType' object has no attribute 'format_status'
```

**Release version**
dev-0.40.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those!

**Comment by dennisocana** [comment]
Fixed in version 0.40 release
