### ISSUE TITLE
Failed Test PR#342 - Unexpected error while fetching account updates

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/hummingbot#347]
## Summary and Screenshots
While monitoring the logs, random network errors were displaying.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/120451804/232667633-e5c818e6-ff84-4914-a89d-06ac029b4b4e.png">

``` ruby
2023-04-18 11:24:00,508 - 1594 - hummingbot.connector.derivative.phemex_perpetual.phemex_perpetual_derivative.PhemexPerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/Users/admin/phemex/hummingbot/connector/exchange_py_base.py", line 813, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/Users/admin/phemex/hummingbot/connector/derivative/phemex_perpetual/phemex_perpetual_derivative.py", line 213, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/Users/admin/phemex/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/admin/phemex/hummingbot/connector/derivative/phemex_perpetual/phemex_perpetual_derivative.py", line 581, in _update_balances
    raise IOError(f"{code} - {message}")
OSError: 39999 - Error in query account position
```

``` ruby
2023-04-18 11:24:01,243 - 1594 - hummingbot.connector.derivative.phemex_perpetual.phemex_perpetual_derivative.PhemexPerpetualDerivative - WARNING - Could not fetch account updates from Phemex_perpetual. Check API key and network connection.
2023-04-18 11:24:02,020 - 1594 - hummingbot.connector.derivative.phemex_perpetual.phemex_perpetual_derivative.PhemexPerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/Users/admin/phemex/hummingbot/connector/exchange_py_base.py", line 813, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/Users/admin/phemex/hummingbot/connector/derivative/phemex_perpetual/phemex_perpetual_derivative.py", line 213, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/Users/admin/phemex/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/admin/phemex/hummingbot/connector/derivative/phemex_perpetual/phemex_perpetual_derivative.py", line 601, in _update_positions
    for position in positions.get("data", {}).get("positions", []):
AttributeError: 'NoneType' object has no attribute 'get'
```
## Steps to reproduce
1. Clone and install the feat branch
2. Create a Perpetual Market Making Strategy. Set tight spreads to fill in orders quickly.
3. Start the strategy and monitor the logs

## Test Result Comparison
n/a, new connector

## Attachments
[Network_error_Phemex.zip](https://github.com/CoinAlpha/hummingbot/files/11257722/Network_error_Phemex.zip)

**Comment by vic-en** [comment]
I pushed a commit that should prevent the second error.
The first of properly logged which is fine.

**Comment by mrhzysbl** [comment]
Tested on commit [496c253](https://github.com/CoinAlpha/hummingbot/pull/342/commits/496c2533e896f3f6aa4ba5400ff1664173fe0e5d) and verified that we are no longer getting the error.
