### ISSUE TITLE
Kucoin - Paper Trade mode not working

### ISSUE THREAD

**Issue by shahzadil** [CoinAlpha/hummingbot#3510]
**Describe the bug**
After the release of v0.39.1, the paper trade mode has stopped working with Kucoin Connector.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):

1. Turn ON paper trade mode.
2. Create a PMM strategy.
3. Start the strategy

**NOTE** - I was able to reproduce the issue on Windows Binary as well as Docker.

**Screenshots**
![Windows_Binary](https://user-images.githubusercontent.com/81416132/120847718-7cd20300-c591-11eb-8809-60d7195573f0.PNG)

**Release version**

0.39.1

**Attachments**

2021-06-04 23:44:20,049 - 9168 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "hummingbot\strategy\pure_market_making\start.py", line 59, in start
  File "hummingbot\client\hummingbot_application.py", line 231, in _initialize_markets
  File "hummingbot\connector\exchange\paper_trade\__init__.py", line 26, in create_paper_trade_market
TypeError: __init__() missing 1 required positional argument: 'auth'
2021-06-04 23:44:20,050 - 9168 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-06-04 23:44:39,851 - 9168 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-06-04 23:44:39,852 - 9168 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\stop_command.py", line 37, in stop_loop
  File "hummingbot\core\clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
ValueError: list.remove(x): x not in list

**Comment by shahzadil** [comment]
Additionally, after getting the error stop command does not work as it just gives the below message. I have to close the whole terminal down and open it again.

![stop](https://user-images.githubusercontent.com/81416132/120848075-f669f100-c591-11eb-962d-c79c1423cfa6.PNG)

**Comment by lt7** [comment]
I'm getting the same error, different strategy.

`2021-06-05 07:58:40,439 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: __init__() missing 1 required positional argument: 'auth'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 106, in start_check
    await self.start_market_making(self.strategy_name, restore)
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 113, in start_market_making
    start_strategy(self)
  File "/home/hummingbot/hummingbot/strategy/arbitrage/start.py", line 35, in start
    self._initialize_markets(market_names)
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 231, in _initialize_markets
    connector = create_paper_trade_market(connector_name, trading_pairs)
  File "/home/hummingbot/hummingbot/connector/exchange/paper_trade/__init__.py", line 26, in create_paper_trade_market
    return PaperTradeExchange(obt_class(**conn_setting.add_domain_parameter(obt_params)),
TypeError: __init__() missing 1 required positional argument: 'auth'
root@ip-172-31-22-94:/opt/arb_bnbbtc_files/hummingbot_logs#
`

**Comment by ruben-support** [comment]
Discord member Tukirito#1748 reported having the same issue. Attached are his conf/log files and screenshot. 


[Turkito.zip](https://github.com/CoinAlpha/hummingbot/files/6642226/Turkito.zip)

**Comment by CrimsonJacket** [comment]
This is a known issue after the `v0.39.1` hotfix. With this hotfix, KuCoin requires users to authenticate certain previously public endpoints. i.e. `GET /api/v3/market/orderbook/level2`
With that being said, paper trade mode does not consume any user auth and as such the aforementioned errors are observed.

We are looking into how to best resolve this issue.

**Comment by gerald-hb** [comment]
Discord member liljellyjam#6105
[logs_conf_liquidity_mining_1.log](https://github.com/CoinAlpha/hummingbot/files/6679790/logs_conf_liquidity_mining_1.log)
 reported having the same issue. Attached are his conf/log files and screenshot.
https://cdn.discordapp.com/attachments/563462222878212098/855618558582325298/unknown.png

**Comment by Sunny1192** [comment]
Discord member Jayb151#8170 is having the same issue. Attached config and log files.
[Files.zip](https://github.com/CoinAlpha/hummingbot/files/6704483/Files.zip)

**Comment by dennisocana** [comment]
Fixed in version 0.41 release
