### ISSUE TITLE
KUCoin API url change for get full order book

### ISSUE THREAD

**Issue by smalltimepro** [CoinAlpha/hummingbot#3512]
**Describe the bug**
Error when fetching full order book

```
2021-06-04 23:05:35,029 - 13328 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error fetching Kucoin market snapshot for ETH2-ETH. HTTP status is 404.
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\core\data_type\order_book_tracker.py", line 178, in _init_order_books
  File "hummingbot\connector\exchange\kucoin\kucoin_api_order_book_data_source.py", line 335, in get_new_order_book
  File "hummingbot\connector\exchange\kucoin\kucoin_api_order_book_data_source.py", line 328, in get_snapshot
OSError: Error fetching Kucoin market snapshot for ETH2-ETH. HTTP status is 404.
```

A change in required in the URL as function has been decprecated from v2 of api and shifted to v3
![image](https://user-images.githubusercontent.com/26482052/120868065-121dc900-c58b-11eb-9694-d09e78900ab7.png)

The constant `SNAPSHOT_REST_URL = "https://api.kucoin.com/api/v2/market/orderbook/level2"` in file `hummingbot\connector\exchange\kucoin\kucoin_api_order_book_data_source.py` needs to be updated

**Steps To Reproduce**
I get the error consistently at start in one bot and not another so not sure exact steps

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
![image](https://user-images.githubusercontent.com/26482052/120867889-c23f0200-c58a-11eb-9a10-316069287f51.png)

**Release version**
0.39.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:smalltimepro**

**Comment by R-K-H** [comment]
Checkout the recent hotfix 0.39.1 as it has resolved this for KuCoin.

**Comment by phbrgnomo** [comment]
Issue solved on previous versions. @smalltimepro, if you still run on similar problems, please create a new issue.
