### ISSUE TITLE
Failed Test PR #351 - Unexpected error while listening to user stream

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#352]
## Summary and Screenshots
Getting flooded by this error after starting a pure_mm bot using Dexalot.

<img width="1421" alt="Screen Shot 2023-05-01 at 9 33 04 AM" src="https://user-images.githubusercontent.com/64377055/235484371-ea1c899a-4a9b-44ab-b3c9-42fdd5e8d3ca.png">

```python
2023-05-01 08:39:23,229 - 2400 - hummingbot.connector.gateway.clob_spot.data_sources.dexalot.dexalot_api_data_source.DexalotAPIDataSource - ERROR - Unexpected error while listening to user stream. Reconnecting...
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 566, in _listen_to_streams
    ws_assistant = await self._connected_websocket_assistant()
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 576, in _connected_websocket_assistant
    auth_response = await self._api_get(
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 526, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/dexalot/dexalot_api_data_source.py", line 552, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.dexalot.com/privapi/auth/getwstoken. HTTP status is 401. Error: {"message":"Restricted api endpoint."}
```

## Steps To Reproduce
1. Clone and install branch
2. Run the client and generate gateway certs
3. Clone feature gateway PR
4. Finish setup and run gateway
5. Create and run a pure_mm strategy using Dexalot

## Expected Results
Error reported should be present in the log pane.

## Test Result Comparison
Not hitting this issue on foundation development.

Logs and config: [foundation_dev.zip](https://github.com/CoinAlpha/hummingbot/files/11366504/foundation_dev.zip)

## Attachments
Logs and config: [dexalot_issue.zip](https://github.com/CoinAlpha/hummingbot/files/11366506/dexalot_issue.zip)

**Comment by rxlxrxsx** [comment]
Re-tested the branch on commit [a938fdf](https://github.com/CoinAlpha/hummingbot/pull/351/commits/a938fdfb09ed061993880610543cb4db635aae7a) and was no longer able to encounter this issue anymore, both with and without API keys connected.
