### ISSUE TITLE
Kucoin - Failed to submit buy order when using DIVI-USDT token pair

### ISSUE THREAD

**Issue by sidmontanez** [CoinAlpha/hummingbot#3544]
**Describe the bug**
User LuisMota reported that he's experiencing a loop of "Failed to create buy" order error in Kucoin with trading pair DIVI-USDT. While the rest of the token pairs running on strategy is creating orders as expected. 

![image](https://user-images.githubusercontent.com/78310937/121272987-d02db380-c8f9-11eb-89d8-a9aca17f0bb0.png)

```
021-06-08 16:49:49,003 - 1 - hummingbot.strategy.liquidity_mining.liquidity_mining - INFO - (DIVI-USDT) Creating a bid order [ p: 0.04853 s: 7547.6710 ] value: 366.29 USDT spread: 1.11%
2021-06-08 16:49:49,003 - 1 - hummingbot.strategy.liquidity_mining.liquidity_mining - INFO - (DIVI-USDT) Spread is widened to 1.11% due to high market volatility
2021-06-08 16:49:49,315 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - NETWORK - Error submitting buy limit_maker order to Kucoin for 7547.6710 DIVI-USDT 0.04853.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 697, in hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange.execute_buy
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type,
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 674, in place_order
    return str(exchange_order_id["data"]["orderId"])
KeyError: 'data'
2021-06-08 16:49:49,316 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - WARNING - Failed to submit buy order to Kucoin. Check API key and network connection.
```
**Steps To Reproduce**
-Create a `Liquidity Mining` Strategy
-Enter the Token pair of `DIVI-USDT` 

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: 
```
########################################################
###        Liquidity Mining strategy config          ###
########################################################

template_version: 3
strategy: liquidity_mining

# The exchange to run this strategy.
exchange: kucoin

# The list of markets, comma separated, e.g. LTC-USDT,ETH-USDT
# Note: The actual markets will be determined by token below, only markets with the token specified below.
markets: DIVI-USDT

# The asset (base or quote) to use to provide liquidity
token: DIVI

# The size of each order in specified token amount
order_amount: 4223.0

# The spread from mid price to place bid and ask orders, enter 1 to indicate 1%
spread: 0.2

# Whether to enable Inventory skew feature (true/false).
inventory_skew_enabled: true

# The target base asset percentage for all markets, enter 50 to indicate 50% target
target_base_pct: 50.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 10.0

# The spread (from mid price) to defer order refresh process to the next cycle.
# (Enter 1 to indicate 1%), value below 0, e.g. -1, is to disable this feature - not recommended.
order_refresh_tolerance_pct: 0.0

# The range around the inventory target base percent to maintain, expressed in multiples of total order size (for
# inventory skew feature).
inventory_range_multiplier: 1.0

# The interval, in second, in which to pick historical mid price data from to calculate market volatility
# E.g 300 for 5 minutes interval
volatility_interval: 300

# The number of interval to calculate average market volatility.
avg_volatility_period: 10

# The multiplier used to convert average volatility to spread, enter 1 for 1 to 1 conversion
volatility_to_spread_multiplier: 1.0

# The maximum value for spread, enter 1 to indicate 1% or -1 to ignore this setting
max_spread: 2.0

# The maximum life time of your orders in seconds
max_order_age: 3600.0
```
...

**Screenshots**

![image](https://user-images.githubusercontent.com/78310937/121273078-fa7f7100-c8f9-11eb-8576-954cb6c6c57d.png)

**Release version**
0.39.1

**Attachments**
[logs_liquidity_divi-usdt.log](https://github.com/CoinAlpha/hummingbot/files/6620276/logs_liquidity_divi-usdt.log)

**Comment by glenntomas** [comment]
Tested this on my end and it works fine.

- Set token to USDT: OK

![image](https://user-images.githubusercontent.com/73885708/121278885-1ee14a80-c906-11eb-854d-2de96f69e0ed.png)

![image](https://user-images.githubusercontent.com/73885708/121278892-21dc3b00-c906-11eb-9b07-353f640d1293.png)

- I tried changing the token as well to DIVI: OK

![image](https://user-images.githubusercontent.com/73885708/121278929-33bdde00-c906-11eb-9913-9399f6c226e2.png)
