### ISSUE TITLE
Ascendex - fetching non existing PERP markets

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3546]
**Describe the bug**
Getting an unexpected websocket error and unhandled error after setting up `ETH-PERP` as a spot market.
```
2021-06-09 02:34:22,332 - 3260 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 5 seconds. Check network connection.
2021-06-09 02:34:22,334 - 3260 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'dict' object has no attribute 'message'
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/ascendex/hummingbot/core/data_type/order_book_tracker.py", line 178, in _init_order_books
    self._order_books[trading_pair] = await self._data_source.get_new_order_book(trading_pair)
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 106, in get_new_order_book
    snapshot: Dict[str, Any] = await self.get_order_book_data(trading_pair)
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 99, in get_order_book_data
    f"Error fetching OrderBook for {trading_pair} at {EXCHANGE_NAME}. "
AttributeError: 'dict' object has no attribute 'message'
```
Upon checking AscendEx exchange, the `ETH-PERP` or any `PERP` market doesn't exist however our bot recognizes these markets.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market-making strategy using AscendEx as a connector.
2. When the market is asked, check the autocomplete list and use any market associated with PERP, for example, ETH-PERP or BTC-PERP.
3. Start the strategy and notice that you will immediately get an error.
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/121284734-e8103200-c90f-11eb-8f7b-8dfd217b91d2.png)
![image](https://user-images.githubusercontent.com/57189990/121285073-58b74e80-c910-11eb-9379-ab3543e6ada1.png)

**Release version**
0.39.0

**Attachments**
[logs_maxorder.log](https://github.com/CoinAlpha/hummingbot/files/6620777/logs_maxorder.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Fix has been applied on the upcoming Hummingbot v1.3
