### ISSUE TITLE
liquidity_mining strategy - Unexpected error while requesting data from Hummingbot API

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3570]
**Describe the bug**
Getting this error everytime I run `status` command while running a bot on liquidity_mining strategy.

<img width="1422" alt="Screen Shot 2021-06-13 at 11 28 48 AM" src="https://user-images.githubusercontent.com/64377055/121794520-6be15b80-cc3b-11eb-89cf-f0dab185654a.png">

```
2021-06-13 03:27:24,270 - 1 - hummingbot.connector.parrot - ERROR - Unexpected error while requesting data from Hummingbot API.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/parrot.py", line 32, in get_campaign_summary
    campaigns = await get_active_campaigns(exchange, trading_pairs)
  File "/home/hummingbot/hummingbot/connector/parrot.py", line 67, in get_active_campaigns
    resp = await client.get(url)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```

**Steps To Reproduce**
1. Create and run a liquidity_mining strategy
2. Run status command and the error will appear on the log pane

**Release version**
v0.39.0

**Attachments**
Logs and config: [lm_strat.zip](https://github.com/CoinAlpha/hummingbot/files/6643231/lm_strat.zip)

**Comment by gerald-hb** [comment]
Customer who reported this issue: J0E#6190
User is using v0.39.1
[logs_conf_liquidity_mining_3.log](https://github.com/CoinAlpha/hummingbot/files/6643361/logs_conf_liquidity_mining_3.log)


[logs_conf_liquidity_mining_3.log](https://github.com/CoinAlpha/hummingbot/files/6643363/logs_conf_liquidity_mining_3.log)

**Comment by rxlxrxsx** [comment]
Issue seems to have self-resolved and wasn't able to encounter it anymore, will re-open the ticket once it happens again.
