### ISSUE TITLE
Binance Perpetual - Quarterly market are now in the market autocomplete list

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3576]
**Describe the bug**
When creating a perpetual market making strategy or spot-perpetual arbitrage using Binance_Perpetual as the connector, quarterly markets are now getting picked up and when they are used as markets, it caused an `unsupported operand error` or `clock tick error`. Since we currently don't support quarterly futures, I think it would be best to hide this market to avoid confusion.
Perpetual market making
```python
2021-06-14 14:12:01,006 - 23042 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "hummingbot/strategy/perpetual_market_making/perpetual_market_making.pyx", line 587, in hummingbot.strategy.perpetual_market_making.perpetual_market_making.PerpetualMarketMakingStrategy.c_tick
  File "hummingbot/strategy/perpetual_market_making/perpetual_market_making.pyx", line 823, in hummingbot.strategy.perpetual_market_making.perpetual_market_making.PerpetualMarketMakingStrategy.c_create_base_proposal
  File "hummingbot/strategy/perpetual_market_making/perpetual_market_making.pyx", line 328, in hummingbot.strategy.perpetual_market_making.perpetual_market_making.PerpetualMarketMakingStrategy.get_price
  File "hummingbot/strategy/market_trading_pair_tuple.py", line 40, in get_price_by_type
  File "hummingbot/connector/exchange_base.pyx", line 277, in hummingbot.connector.exchange_base.ExchangeBase.get_price_by_type
  File "hummingbot/connector/exchange_base.pyx", line 108, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
  File "hummingbot/connector/connector_base.pyx", line 381, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
  File "hummingbot/connector/connector_base.pyx", line 361, in hummingbot.connector.connector_base.ConnectorBase.c_get_order_price_quantum
  File "hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 435, in get_order_price_quantum
KeyError: 'ETHUSDT_210-625'
```
Spot-Perpetual Arbitrage:
```python
2021-06-14 14:04:25,006 - 23042 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: unsupported operand type(s) for +: 'int' and 'KeyError'
Traceback (most recent call last):
  File "hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
  File "hummingbot/strategy/spot_perpetual_arbitrage/spot_perpetual_arbitrage.py", line 159, in main
  File "hummingbot/strategy/spot_perpetual_arbitrage/arb_proposal.py", line 86, in proposed_spot_deriv_arb
TypeError: unsupported operand type(s) for +: 'int' and 'KeyError'
```

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a perpetual market-making strategy or spot-perpetual arbitrage strategy.
2. Use Binance_perpetual as the derivatives connector.
3. When asked to select the derivatives market, choose markets that have numbers as an extension, for example, ETHUSDT_210_625
4. Start the startegy.
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/121846869-45462200-cd1a-11eb-8ab0-3084abfa44a1.png)

**Release version**
0.39.1

**Attachments**
[logs_conf_perpetual_market_making_1.log](https://github.com/CoinAlpha/hummingbot/files/6646003/logs_conf_perpetual_market_making_1.log)
[logs_conf_spot_perpetual_arbitrage_1.log](https://github.com/CoinAlpha/hummingbot/files/6646005/logs_conf_spot_perpetual_arbitrage_1.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rxlxrxsx** [comment]
Closing the ticket as the issue no longer persist, quarterly markets doesn't appear anymore on market autocomplete list.
