### ISSUE TITLE
Failed Test PR #356 - Unhandled error in background task

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#358]
## Summary and Screenshots
Getting this error shortly after starting a strategy using Polkadex connector.

<img width="1422" alt="Screen Shot 2023-05-22 at 11 21 11 AM" src="https://github.com/CoinAlpha/hummingbot/assets/64377055/f925e259-06bd-4361-b021-b0772197dad2">

```python
2023-05-22 11:20:37,612 - 6881 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/connector/exchange_py_base.py", line 781, in _trading_fees_polling_loop
    await safe_gather(self._update_trading_fees())
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/connector/exchange/polkadex/polkadex_exchange.py", line 199, in _update_trading_fees
    raise NotImplementedError  # pragma: no cover
NotImplementedError
```

Logs and config: [polkadex_356.zip](https://github.com/CoinAlpha/hummingbot/files/11536931/polkadex_356.zip)

## Steps To Reproduce
1. Clone and install branch
2. Run the client
3. Connect Polkadex API key
4. Create a strategy using Polkadex
5. Start the strategy

## Expected Results
No errors should appear after starting the strategy.

## Test Result Comparison
Tested on armada development and didn't encounter the issue.

[polkadex_dev.zip](https://github.com/CoinAlpha/hummingbot/files/11536929/polkadex_dev.zip)

**Comment by petioptrv** [comment]
Addressed in the [latest commit](https://github.com/CoinAlpha/hummingbot/pull/356/commits/c7ba8eb1370e1cd6bdf2c8dd001cda1ffc031a97).

**Comment by mrhzysbl** [comment]
Verified on commit [f04d393](https://github.com/CoinAlpha/hummingbot/pull/356/commits/f04d393cf8e298e447d5559eeec79e14c2775727) that the error is no longer showing.
