### ISSUE TITLE
Failed Test #356 - Unable to start client

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/hummingbot#359]
## Summary and Screenshots
After the installing and compiling the branch, we are getting an error when running the command bin/hummingbot.py

``` ruby
(hummingbot) geneynopia@Loragenes-MacBook-Air polka % bin/hummingbot.py
Traceback (most recent call last):
  File "bin/hummingbot.py", line 10, in <module>
    from hummingbot.client.config.config_crypt import ETHKeyFileSecretManger
  File "/Users/geneynopia/polka/hummingbot/client/config/config_crypt.py", line 22, in <module>
    from hummingbot.client.settings import CONF_DIR_PATH
  File "/Users/geneynopia/polka/hummingbot/client/settings.py", line 13, in <module>
    from hummingbot.core.data_type.trade_fee import TradeFeeSchema
  File "/Users/geneynopia/polka/hummingbot/core/data_type/trade_fee.py", line 7, in <module>
    from hummingbot.connector.utils import combine_to_hb_trading_pair, split_hb_trading_pair
  File "/Users/geneynopia/polka/hummingbot/connector/utils.py", line 10, in <module>
    from zero_ex.order_utils import Order as ZeroExOrder
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/zero_ex/order_utils/__init__.py", line 31, in <module>
    from web3 import Web3
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/__init__.py", line 9, in <module>
    from web3.main import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/main.py", line 87, in <module>
    from web3.manager import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/manager.py", line 47, in <module>
    from web3.providers import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/providers/__init__.py", line 8, in <module>
    from .rpc import (  # noqa: F401,
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/providers/rpc.py", line 21, in <module>
    from web3._utils.request import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/request.py", line 13, in <module>
    from aiohttp import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 34, in <module>
    from yarl import URL
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/_url.py", line 80, in <module>
    class URL:
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/_url.py", line 152, in URL
    _QUOTER = _Quoter(requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

## Steps To Reproduce
1. Clone and install branch
2. Activate conda environment
3. Run bin/hummingbot.py

## Expected Results
The client should start without any errors.

## Test Result Comparison
HB dev branch was installed and started without any issues.

## Attachments

**Comment by mrhzysbl** [comment]
Updated the installed packages as per Petio's instructions and still getting the same error using a local machine: 

``` ruby
(hummingbot) geneynopia@Loragenes-MacBook-Air polkadex % bin/hummingbot.py
Traceback (most recent call last):
  File "bin/hummingbot.py", line 10, in <module>
    from hummingbot.client.config.config_crypt import ETHKeyFileSecretManger
  File "/Users/geneynopia/polkadex/hummingbot/client/config/config_crypt.py", line 22, in <module>
    from hummingbot.client.settings import CONF_DIR_PATH
  File "/Users/geneynopia/polkadex/hummingbot/client/settings.py", line 13, in <module>
    from hummingbot.core.data_type.trade_fee import TradeFeeSchema
  File "/Users/geneynopia/polkadex/hummingbot/core/data_type/trade_fee.py", line 7, in <module>
    from hummingbot.connector.utils import combine_to_hb_trading_pair, split_hb_trading_pair
  File "/Users/geneynopia/polkadex/hummingbot/connector/utils.py", line 10, in <module>
    from zero_ex.order_utils import Order as ZeroExOrder
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/zero_ex/order_utils/__init__.py", line 31, in <module>
    from web3 import Web3
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/__init__.py", line 9, in <module>
    from web3.main import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/main.py", line 87, in <module>
    from web3.manager import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/manager.py", line 47, in <module>
    from web3.providers import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/providers/__init__.py", line 8, in <module>
    from .rpc import (  # noqa: F401,
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/providers/rpc.py", line 21, in <module>
    from web3._utils.request import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/request.py", line 13, in <module>
    from aiohttp import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 34, in <module>
    from yarl import URL
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/_url.py", line 80, in <module>
    class URL:
  File "/Users/geneynopia/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/_url.py", line 152, in URL
    _QUOTER = _Quoter(requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

**Comment by mrhzysbl** [comment]
Tested on commit [f04d393](https://github.com/CoinAlpha/hummingbot/pull/356/commits/f04d393cf8e298e447d5559eeec79e14c2775727) and verified that the client is working on both local and remote machine.
