### ISSUE TITLE
Probit KR - Some unsupported markets are listed when choosing a market

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3596]
**Describe the bug**
Recently probit made some changes and made a dedicated order book for Probit global and Probit Korea (https://support.probit.com/hc/en-us/articles/900007419443). With this recent change, our bot still recognizes some pairs that are currently for Probit global, choosing this pair will result in failing to submit / or fail to cancel the order (existing order prior to the change).
![image](https://user-images.githubusercontent.com/57189990/122340829-59399000-cf75-11eb-94ed-6cd2065a75f1.png)
```python
  2021-06-17 00:23:19,042 - 8043 - hummingbot.connector.exchange.probit.probit_exchange - NETWORK - Error submitting BUY LIMIT_MAKER order to ProBit for 0.00450 ETH-USDT 2397.25.
  Traceback (most recent call last):
    File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 341, in _api_request
      headers = await self._probit_auth.get_auth_headers(client)
    File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_auth.py", line 71, in get_auth_headers
      raise e
    File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_auth.py", line 60, in get_auth_headers
      token_resp = await resp.json()
    File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1026, in json
      raise ContentTypeError(
  aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://accounts.probit.kr/token')

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 477, in _create_order
      order_result = await self._api_request(
    File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 357, in _api_request
      raise IOError(f"Error parsing data from {path_url}. Error: {str(e)}")
  OSError: Error parsing data from https://api.probit.kr/api/exchange/v1/new_order. Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://accounts.probit.kr/token')
```
```python
2021-06-17 03:14:38,123 - 8043 - hummingbot.connector.exchange.probit.probit_exchange - NETWORK - Error submitting BUY LIMIT_MAKER order to ProBit for 0.00450 ETH-USDT 2397.25.
Traceback (most recent call last):
  File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 477, in _create_order
    order_result = await self._api_request(
  File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 359, in _api_request
    raise IOError(f"Error fetching data from {path_url}. HTTP status is {response.status}. "
OSError: Error fetching data from https://api.probit.kr/api/exchange/v1/new_order. HTTP status is 400. Message: {'errorCode': 'INVALID_ARGUMENT', 'message': '', 'details': {'market_id': 'not_found'}} Params: None Data: {'market_id': 'ETH-USDT', 'type': 'limit', 'side': 'buy', 'time_in_force': 'gtc', 'limit_price': '2397.25', 'quantity': '0.00450', 'client_order_id': 'B-ETH-USDT-1623899678002753'}
```

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy and use Probit_kr as the connector
2. Press the tab button to show the autocomplete list and check that unsupported markets like BTC/ETH/USDT
3. Select a market such as ETH-USDT and start the strategy
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/122341350-f5fc2d80-cf75-11eb-950e-fd46ddd9ad4d.png)
![image](https://user-images.githubusercontent.com/57189990/122341456-10360b80-cf76-11eb-9c88-bbbbc65a469f.png)

**Release version**
0.40.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dennisocana** [comment]
Fixed in version 0.41 release
