### ISSUE TITLE
Kucoin - List index out of range error when using celo pair cUSD-USDT

### ISSUE THREAD

**Issue by smalltimepro** [CoinAlpha/hummingbot#3644]
**Describe the bug**
// A clear and concise description of what the bug is.
Trying to start a bot with any cUSD or cEUR pair on Kucoin results in an error. Program says invalid amount but this is probably due to not being able to get info on for min/max orders. This used to work uptil around a month ago.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
create new bot (any strategy) for cEUR-USDT pair and try to start it

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ... parameters do not matter
2. Start the bot using this command: ... start
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/26482052/123540462-0317da00-d737-11eb-83fb-e708e0e430cb.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.40

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by glenntomas** [comment]
Hi @smalltimepro, I've tested this on pure_market_making strategy using Kucoin and it works fine on my end.

- cEUR-USDT

![image](https://user-images.githubusercontent.com/73885708/123565044-26ea2700-d7ee-11eb-8701-e8870b42650d.png)

- cUSD-USDT

![image](https://user-images.githubusercontent.com/73885708/123565052-2e113500-d7ee-11eb-9bec-da8582538e04.png)

Can you please send here your `config` and `log file` so we can check. Thank you!

**Comment by smalltimepro** [comment]
Yes it seem to have started to work for CEUR for me too now, but still same for CUSD pair. Config and log below,
```
2021-06-27 10:56:05,906 - 31280 - hummingbot.client.hummingbot_application - ERROR - 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "hummingbot\client\command\config_command.py", line 147, in _config_single_key
  File "hummingbot\client\command\create_command.py", line 116, in prompt_a_config
  File "hummingbot\client\command\create_command.py", line 106, in prompt_a_config
  File "hummingbot\client\config\config_var.py", line 54, in get_prompt
  File "hummingbot\strategy\avellaneda_market_making\avellaneda_market_making_config_map.py", line 55, in order_amount_prompt
AttributeError: 'NoneType' object has no attribute 'split'
2021-06-28 03:25:41,935 - 12196 - root - ERROR - Invalid value 1000.0 for config variable order_amount
2021-06-28 03:26:00,915 - 12196 - hummingbot.client.hummingbot_application - ERROR - list index out of range
Traceback (most recent call last):
  File "hummingbot\client\command\config_command.py", line 147, in _config_single_key
  File "hummingbot\client\command\create_command.py", line 116, in prompt_a_config
  File "hummingbot\client\command\create_command.py", line 106, in prompt_a_config
  File "hummingbot\client\config\config_var.py", line 54, in get_prompt
  File "hummingbot\strategy\pure_market_making\pure_market_making_config_map.py", line 42, in order_amount_prompt
  File "hummingbot\client\config\config_helpers.py", line 382, in minimum_order_amount
  File "hummingbot\core\utils\market_price.py", line 27, in get_last_price
  File "hummingbot\connector\exchange\kucoin\kucoin_api_order_book_data_source.py", line 307, in get_last_traded_prices
IndexError: list index out of range
2021-06-28 03:28:27,784 - 12196 - hummingbot.client.hummingbot_application - ERROR - list index out of range
Traceback (most recent call last):
  File "hummingbot\client\command\config_command.py", line 147, in _config_single_key
  File "hummingbot\client\command\create_command.py", line 116, in prompt_a_config
  File "hummingbot\client\command\create_command.py", line 106, in prompt_a_config
  File "hummingbot\client\config\config_var.py", line 54, in get_prompt
  File "hummingbot\strategy\pure_market_making\pure_market_making_config_map.py", line 42, in order_amount_prompt
  File "hummingbot\client\config\config_helpers.py", line 382, in minimum_order_amount
  File "hummingbot\core\utils\market_price.py", line 27, in get_last_price
  File "hummingbot\connector\exchange\kucoin\kucoin_api_order_book_data_source.py", line 307, in get_last_traded_prices
IndexError: list index out of range
```

**Comment by glenntomas** [comment]
Hi! Yes, **cEUR-USDT** is working also on my end using Avellaneda MM strategy, however when using **cUSD-USDT** it throws an error upon creating the strategy.

![image](https://user-images.githubusercontent.com/73885708/123574468-78041600-d802-11eb-8a57-e3ab46fba470.png)
 
I've tried creating the strategy for **cEUR-USDT**, then after creating the strategy I changed the `market` to **cUSD-USDT** and it works.

![image](https://user-images.githubusercontent.com/73885708/123574321-33787a80-d802-11eb-8bf2-73465df80144.png)

Here's the traceback error when entering `cUSD-USDT` as you market
```
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 161, in _update_last_trade_prices_loop
    last_prices = await self._data_source.get_last_traded_prices(**args)
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_order_book_data_source.py", line 307, in get_last_traded_prices
    resp_record = [o for o in resp_json["data"]["ticker"] if o["symbolName"] == trading_pair][0]
IndexError: list index out of range
```

[logs_conf_avellaneda_market_making_1 - glenn.log](https://github.com/CoinAlpha/hummingbot/files/6723152/logs_conf_avellaneda_market_making_1.-.glenn.log)

**Comment by glenntomas** [comment]
Hi @smalltimepro, we've tried to use the `dev-0.41.0` version and enter `cUSD-USDT` as the market and it works with PMM and Avellaneda MM. You can try using our `development` branch on source or in docker. 

- Pure Market Making using `cUSD-USDT`

![image](https://user-images.githubusercontent.com/73885708/123577897-3e81d980-d807-11eb-9259-fc8b0715996e.png)

- Avellaneda MM using `cUSD-USDT`

![image](https://user-images.githubusercontent.com/73885708/123578132-be0fa880-d807-11eb-864b-72f54d2d2dc2.png)

**Comment by RC-13** [comment]
Re-tested the issue and I'm unable to get the error. Closing this ticket for now, feel free to re-open if the issue re-occurs.
![image](https://user-images.githubusercontent.com/57189990/125899557-7ac32cec-1930-44f6-bbb6-d215e9fb87a1.png)
![image](https://user-images.githubusercontent.com/57189990/125899584-c330a11b-0e82-4c76-ab0d-a2f915445154.png)
