### ISSUE TITLE
Failed Test PR #366 - Error fetching trading pairs for Polkadex

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#368]
### Describe the bug

Getting this error on the terminal after starting the client. Despite the error, the client runs as expected.

<img width="1069" alt="Screen Shot 2023-08-28 at 10 53 37 AM" src="https://github.com/CoinAlpha/hummingbot/assets/64377055/e27052d1-efea-4be4-88eb-1d51af4cd11d">

```python
2023-08-28 10:55:59,151 - 10468 - hummingbot.core.utils.trading_pair_fetcher - ERROR - An error occurred when fetching trading pairs for polkadex.Please check the logs
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/core/utils/trading_pair_fetcher.py", line 53, in fetch_all
    self._fetch_pairs_from_connector_setting(connector_setting=conn_setting)
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/core/utils/trading_pair_fetcher.py", line 38, in _fetch_pairs_from_connector_setting
    connector = connector_setting.non_trading_connector_instance_with_default_configuration()
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/client/settings.py", line 334, in non_trading_connector_instance_with_default_configuration
    connector = connector_class(**kwargs)
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/connector/exchange/polkadex/polkadex_exchange.py", line 45, in __init__
    self._data_source = PolkadexDataSource(
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/connector/exchange/polkadex/polkadex_data_source.py", line 68, in __init__
    self._substrate_interface = self._build_substrate_interface()
  File "/Users/reiniersalazar/hbot-ca-polkadex/hummingbot/connector/exchange/polkadex/polkadex_data_source.py", line 462, in _build_substrate_interface
    substrate_interface = SubstrateInterface(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.10/site-packages/substrateinterface/base.py", line 132, in __init__
    self.connect_websocket()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.10/site-packages/substrateinterface/base.py", line 177, in connect_websocket
    self.websocket = create_connection(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.10/site-packages/websocket/_core.py", line 608, in create_connection
    websock.connect(url, **options)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.10/site-packages/websocket/_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.10/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.10/site-packages/websocket/_handshake.py", line 150, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status {status} {message} -+-+- {headers} -+-+- {body}".format(status=status, message=status_message, headers=resp_headers, body=response_body), status, status_message, resp_headers, response_body)
websocket._exceptions.WebSocketBadStatusException: Handshake status 429 Too Many Requests -+-+- {'content-type': 'text/plain', 'content-length': '45', 'date': 'Mon, 28 Aug 2023 16:55:58 GMT'} -+-+- b'Too many connections. Please try again later.'
```

### Steps to reproduce

1. Clone and install the branch
2. Run the client
3. After client start up, observe that the error appears in the terminal

### Release version

1.19.0

### Type of installation

Source

### Attach required files

N/A

**Comment by petioptrv** [comment]
Polkadex has provided a new url, and I have updated the code. Please re-test. It should prevent the issue observed here.

**Comment by rxlxrxsx** [comment]
Tested on commit [b092456](https://github.com/CoinAlpha/hummingbot/pull/366/commits/b0924562e6a9c471e96d847e56b466730d273ba0) and confirmed fixed.
