### ISSUE TITLE
DyDx Perpetual - Timeout when fetching for funding fee

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3688]
**Describe the bug**
When two bots are run (different instances) using the same market and `dydx_perpetual`as the derivatives exchange, one of the bots will randomly get an issue fetching funding fee. Upon checking the logs, it seems that the bot encounters timeout whenever it checks for a funding fee.
```python
Traceback (most recent call last):
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 739, in _update_funding_rates
    await self._get_funding_info(trading_pair)
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 727, in _get_funding_info
    markets_info = (await self.dydx_client.get_markets())['markets']
  File "/Users/clint_g/Documents/Github-Repo/hb-general/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_client_wrapper.py", line 83, in get_markets
    return await f
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/modules/public.py", line 70, in get_markets
    return self._get(uri, {'market': market})
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/modules/public.py", line 16, in _get
    return request(
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/helpers/requests.py", line 18, in request
    response = send_request(
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/dydx3/helpers/requests.py", line 32, in send_request
    return getattr(session, method)(uri, headers=headers, **kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/clint_g/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(60, 'ETIMEDOUT')"))
2021-07-06 08:47:15,594 - 2416 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative - WARNING - Could not fetch funding_rate for ETH-USD. Check API key and network connection.
```

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a perpetual market-making strategy and use  dydx_perpetual as the derivatives exchange.
2. Use the ETH-USD market or depending on your preference, you can use other markets and start.
3. Create another bot with the same strategy, exchange and market then start.
4. Monitor each bot side by side, the error may sometimes come up immediately or after positions are open in each bot.

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/124527807-1ca4da00-de39-11eb-9945-918cf595268d.png)

**Release version**
0.40.0, the test is done in the current development branch [0.41.0]

**Attachments**
[logs_dydx-perp-test-funding-time.log](https://github.com/CoinAlpha/hummingbot/files/6766638/logs_dydx-perp-test-funding-time.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by vic-en** [comment]
Unfortunately, I couldn't reproduce this error. From your log, it appears there's a problem with your internet connection at that moment.
Pls update with new logs if issue persists.

**Comment by RC-13** [comment]
After running for more than 24 hours, both test bots encountered the error one time each but it was due to a network issue (remote disconnection).  We can close this issue and open a new one if a new error comes up regarding the the funding payment.

**Comment by RC-13** [comment]
Re-opening the issue, the DyDx perpetual connector encounter the issue again :
![image](https://user-images.githubusercontent.com/57189990/135183950-8b7e2ed0-0f4b-4844-beda-ffadafd3ac17.png)

**Comment by petioptrv** [comment]
@vic-en, @RC-13, It sounds like fixing this calls for `AsyncThrottler` integration into dydx perpetual. For now, I propose we catch `status_code=429` and output a better error message. Thoughts?

**Comment by vic-en** [comment]
@petioptrv I agree
