### ISSUE TITLE
Avellaneda MM - Unexpected error while processing event 106 when hanging order is cancelled

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3700]
**Describe the bug**
Getting an `Unexpected error while processing event 106` everytime a hanging order is cancelled on avellaneda_market_making strategy

<img width="1423" alt="Screen Shot 2021-07-08 at 11 52 59 AM" src="https://user-images.githubusercontent.com/64377055/124861797-d0979800-dfe6-11eb-8fb1-176f8a99be54.png">

```python
2021-07-08 11:52:21,174 - 11175 - hummingbot.connector.exchange.binance.binance_exchange - ERROR - Unexpected error while processing event 106.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/strategy/strategy_base.pyx", line 68, in hummingbot.strategy.strategy_base.OrderCancelledListener.c_call
    self._owner.c_did_cancel_order(arg)
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 1079, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_did_cancel_order
    self._hanging_orders_tracker.did_cancel_hanging_order(order_id)
  File "/Users/reiniersalazar/development/hummingbot/strategy/hanging_orders_tracker.py", line 327, in did_cancel_hanging_order
    limit_order_to_be_removed = next(o for o in self.original_orders if o.client_order_id == order_id)
StopIteration
```

**Steps To Reproduce**
1. Run a avellaneda_market_making strategy with hanging orders enabled
2. Set the hanging_order_cancel_pct to a low value for a higher chance of hanging orders to get cancelled

**Release version**
dev-0.41.0

**Attachments**
[ave.zip](https://github.com/CoinAlpha/hummingbot/files/6781401/ave.zip)

**Comment by dennisocana** [comment]
@rxlxrxsx just to confirm, does this happen to all hanging orders that are cancelled? Even with the error, the order gets cancelled successfully in the exchange?

**Comment by rxlxrxsx** [comment]
@dennisocana yes that's correct, the error appears everytime a hanging order is cancelled and can confirm that those orders gets cancelled successfully in the exchange.

**Comment by RC-13** [comment]
It appears that this issue doesn't happen in all environments, the error did not occur on the binary build for windows and mac.

**Comment by rapcmia** [comment]
Tested on Windows docker dev-0.44 build, I did not encounter the error when the hanging order reaches the set percentage. Here is a screenshot for reference:

hanging_orders_cancel_pct is set to 0.08
![image](https://user-images.githubusercontent.com/73840223/131835566-776ec802-7530-4772-a2cf-d58d7afb305b.png)

Attached:
[issue-3700.zip](https://github.com/CoinAlpha/hummingbot/files/7098475/issue-3700.zip)

**Comment by RC-13** [comment]
Closing ticket, issue no longer occuring
