### ISSUE TITLE
Probit KR - Unable to start connector  due to failing to fetch the orderbook

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3716]
**Describe the bug**
Probit KR fails to start due to these error:
```python
2021-07-13 05:20:43,085 - 16835 - hummingbot.connector.exchange.probit.probit_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_api_order_book_data_source.py", line 221, in listen_for_order_book_snapshots
    snapshot: Dict[str, any] = await self.get_order_book_data(trading_pair)
  File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_api_order_book_data_source.py", line 80, in get_order_book_data
    f"Error fetching OrderBook for {trading_pair} at {CONSTANTS.ORDER_BOOK_PATH_URL.format(domain)}. "
AttributeError: module 'hummingbot.connector.exchange.probit.probit_constants' has no attribute 'ORDER_BOOK_PATH_URL'
```

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy and use Probit_kr as a connector
2. Choose USDT-KRW as market and start the strategy 
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/125396255-e211e300-e3de-11eb-91cc-0b09987b31ba.png)
![image](https://user-images.githubusercontent.com/57189990/125397379-6fa20280-e3e0-11eb-8b53-175a99737595.png)

**Release version**
0.40.0

**Attachments**
[logs_usdt-krw-log.txt](https://github.com/CoinAlpha/hummingbot/files/6806180/logs_usdt-krw-log.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dennisocana** [comment]
Fixed in version 0.41 release
