### ISSUE TITLE
Ascendex - Error parsing data due to rate limit

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3754]
**Describe the bug**
After running AscendEx test bots for several days (2-3days), all test bots suddenly stop placing new orders and start getting ` Unexpected error with WebSocket connection. Retrying after 30 seconds... (See log file for stack trace dump)` and ` Failed to cancel the order, Check API key and network connection.` In some cases, there is an order on one instance that fails to cancel, once this occurs, it will affect all other running instances. After checking the logs, it appears that it is now hitting the rate limit `websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429`
```python
2021-07-20 00:28:51,059 - 2589 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - WARNING - Failed to cancel the order HMBot-B-XDAI-USDT-1626658945012973 on AscendEx. Check API key and network connection.
2021-07-20 00:29:07,043 - 2589 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 130, in listen_for_trades
    async with websockets.connect(WS_URL) as ws:
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 517, in __aenter__
    return await self
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429
2021-07-20 00:29:25,464 - 2589 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-07-20 00:29:25,525 - 2589 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - NETWORK - Failed to cancel all orders.
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 407, in _api_request
    parsed_response = json.loads(await response.text())
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 747, in cancel_all
    await self._api_request(
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 409, in _api_request
    raise IOError(f"Error parsing data from {url}. Error: {str(e)}")
OSError: Error parsing data from https://ascendex.com/5/api/pro/v1/cash/order/batch. Error: Expecting value: line 1 column 1 (char 0)

```

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create multiple test bots using any market-making strategy and set AscendEx as the connector.
2. Start the strategy and leave it running for long period.
3. Regularly monitor the instances to check if one of them starts to get an error.
4. If you see one instance getting the WebSocket connection, monitor other instances and soon they will start getting the same error.

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/126245252-1d132557-6749-405e-a459-c4d59830f5cc.png)

**Release version**
0.41.0

**Attachments**
[logs_usdt-lm-ascendex2-rate-limit.txt](https://github.com/CoinAlpha/hummingbot/files/6844655/logs_usdt-lm-ascendex2-rate-limit.txt)
[logs_usdt-lm-ascendex2.log.2021-07-18.zip](https://github.com/CoinAlpha/hummingbot/files/6848740/logs_usdt-lm-ascendex2.log.2021-07-18.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
@Nullably I have attached the older logs, the snippet below shows the initial traced dump prior to the start of the websocket error. There is a failure to cancel orders as well which I believe is a factor that causes the rate limit since the bot keeps trying to look into this uncancelled order.
```python
2021-07-19 06:02:00,991 - 2589 - hummingbot.connector.exchange.ascend_ex.ascend_ex_order_book_tracker - NETWORK - Unexpected error while fetching last trade price.
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/core/data_type/order_book_tracker.py", line 161, in _update_last_trade_prices_loop
    last_prices = await self._data_source.get_last_traded_prices(**args)
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 49, in get_last_traded_prices
    raise IOError(
OSError: Error fetching last traded prices at ascend_ex. HTTP status is 429.
2021-07-19 06:02:03,917 - 2589 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - NETWORK - Unexpected error while fetching trading rules. Error: Error parsing data from https://ascendex.com/api/pro/v1/products. Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 407, in _api_request
    parsed_response = json.loads(await response.text())
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 270, in _trading_rules_polling_loop
    await self._update_trading_rules()
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 282, in _update_trading_rules
    instruments_info = await self._api_request(
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 409, in _api_request
    raise IOError(f"Error parsing data from {url}. Error: {str(e)}")
OSError: Error parsing data from https://ascendex.com/api/pro/v1/products. Error: Expecting value: line 1 column 1 (char 0)
2021-07-19 06:02:03,917 - 2589 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - WARNING - Could not fetch new trading rules from AscendEx. Check network connection.
2021-07-19 06:02:04,277 - 2589 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 130, in listen_for_trades
    async with websockets.connect(WS_URL) as ws:
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 517, in __aenter__
    return await self
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429
```

**Comment by RC-13** [comment]
Adding Jason's log files
- PMM: Bot fails to fully cancel all the orders. This will result in the bot continuously send requests to cancel the order if kept running.
![image](https://user-images.githubusercontent.com/57189990/126404742-cd269362-158a-4d1c-9760-ae7c266f69b6.png)
![no_order_on_exchange](https://user-images.githubusercontent.com/57189990/126403488-0e236bed-c12e-42f8-ac33-859638a596a1.png)
[logs_CLOUT-USDT_pmm.log](https://github.com/CoinAlpha/hummingbot/files/6851556/logs_CLOUT-USDT_pmm.log)
- Avellaneda MM: Inconsistent order creation due to the balance error that appears after every other cycle.
[logs_avellaneda_lqm_market_making.log](https://github.com/CoinAlpha/hummingbot/files/6851575/logs_avellaneda_lqm_market_making.log)
