### ISSUE TITLE
[BUG] `Unexpected error while processing event 102` error after each filled order on Binacce

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#379]
**Describe the bug**
When running the pure market making strategy on Binance, the following error appears in the log file after a buy or sell order is filled. It doesn't seem to have a visible effect on the bot.

After a buy order fill:
```
2019-06-11 14:51:03,284 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (FTMBTC) Maker buy order of 1001.0 FTM filled. [clock=2019-06-11 21:51:03+00:00]
2019-06-11 14:51:03,284 - hummingbot.market.binance.binance_market - INFO - The market buy order buy-FTMBTC-1560289731000511 has completed according to user stream.
2019-06-11 14:51:03,284 - hummingbot.market.binance.binance_market - ERROR - Unexpected error while processing event 102.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 164, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 62, in hummingbot.strategy.pure_market_making.pure_market_making_v2.BuyOrderCompletedListener.c_call
    self._owner.c_did_complete_buy_order(arg)
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 568, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_buy_order
    f"({market_info.maker_symbol}) Maker buy order {order_id} "
AttributeError: 'MarketInfo' object has no attribute 'maker_symbol'
2019-06-11 14:51:06,004 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (FTMBTC) Creating limit ask order for 1000.0 FTM at 4.256175e-06 BTC. [clock=2019-06-11 21:51:06+00:00]
```

After a sell order fill:
```
2019-06-11 15:05:49,787 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (FTMBTC) Maker sell order of 1000.0 FTM filled. [clock=2019-06-11 22:05:49+00:00]
2019-06-11 15:05:49,788 - hummingbot.market.binance.binance_market - INFO - The market sell order sell-FTMBTC-1560289866005142 has completed according to user stream.
2019-06-11 15:05:49,788 - hummingbot.market.binance.binance_market - ERROR - Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 164, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 67, in hummingbot.strategy.pure_market_making.pure_market_making_v2.SellOrderCompletedListener.c_call
    self._owner.c_did_complete_sell_order(arg)
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 584, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
    f"({market_info.maker_symbol}) Maker sell order {order_id} "
AttributeError: 'MarketInfo' object has no attribute 'maker_symbol'
```
**Release version**
`dev-0.9.0`

**Attachments**
Logs:
[hummingbot_logs_2019-06-11-14-45-46.log](https://github.com/CoinAlpha/hummingbot/files/3278869/hummingbot_logs_2019-06-11-14-45-46.log)

Configs:
```
maker_market: binance
maker_market_symbol: FTMBTC

# size of each order
order_amount: 1000.0

# Time in seconds before cancelling and rerunning strategy
# If tick size is 60, the bot cancels active orders and reruns after a minute
cancel_order_wait_time: 3600

# How far away from mid price to place the bid order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and bid_place threshold is 0.01
# Your bid is placed at 99
bid_place_threshold: 0.005

# How far away from mid price to place the ask order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and ask_place threshold is 0.01
# Your bid is placed at 101
ask_place_threshold: 0.005
```

**Comment by veecos2** [comment]
This should be fixed now
