### ISSUE TITLE
Problem when using arbitrage in binance - Unexpected error running clock tick

### ISSUE THREAD

**Issue by Kathard** [CoinAlpha/hummingbot#401]
I am trying to use the arbitration strategy between two pairs in binance:

primary_market_symbol: ZECUSDT
secondary_market_symbol: ZECUSDC

When I launch the bot, I have these errors:

```

2019-06-19 01:24:34,973 - hummingbot.market.binance.binance_market - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-06-19 01:24:35,049 - hummingbot.strategy.arbitrage.arbitrage - WARNING - Markets are not ready. No arbitrage trading is permitted.
2019-06-19 01:24:35,479 - hummingbot.market.binance.binance_api_user_stream_data_source - INFO - Obtained listen key ztiUObBdmPMykh2kDZia1IGYSABNEtprfJGJk0aHx0CU5khwq00q1Ggwzg7U.
2019-06-19 01:24:35,482 - hummingbot.market.binance.binance_api_user_stream_data_source - INFO - Reconnecting to wss://stream.binance.com:9443/ws/ztiUObBdmPMykh2kDZia1IGYSABNEtprfJGJk0aHx0CU5khwq00q1Ggwzg7U.
2019-06-19 01:24:35,484 - hummingbot.market.binance.binance_api_order_book_data_source - INFO - Initialized order book for ZECUSDC. 1/1 completed.
2019-06-19 01:24:35,886 - hummingbot.market.binance.binance_order_book_tracker - INFO - Started order book tracking for ZECUSDC.
2019-06-19 01:24:37,001 - hummingbot.strategy.arbitrage.arbitrage - INFO - Markets are ready. Trading started.
2019-06-19 01:24:37,001 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "arbitrage.pyx", line 247, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
  File "arbitrage.pyx", line 352, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
  File "arbitrage.pyx", line 297, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_calculate_arbitrage_top_order_profitability
  File "market_base.pyx", line 100, in hummingbot.market.market_base.MarketBase.get_order_book
  File "binance_market.pyx", line 1110, in hummingbot.market.binance.binance_market.BinanceMarket.c_get_order_book
ValueError: No order book exists for 'ZECUSDT'.

```

The configuration file:

 

```

 #####################################
 ###   Arbitrage strategy config   ###
 #####################################
 
 # The following configuations are only required for the
 # arbitrage strategy
 
 # Exchange and token parameters
 primary_market: binance
 secondary_market: binance
 primary_market_symbol: ZECUSDT
 secondary_market_symbol: ZECUSDC
 
 # Minimum profitability target required to place an order
 # Expressed in decimals: 0.01 = 1% target profit
 min_profitability: 0.01
 
 trade_size_override: 14.0
 top_depth_tolerance:
 - - ^.+(USDT|USDC|USDS|DAI|PAX|TUSD)$
   - 1000
 - - ^.+ETH$
   - 10
 - - ^.+BTC$
   - 0.5
 # For more detailed information, see:
 # https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters
 

```

In the portfolio of binance I have 45 usdt and 0.68639000 ZEC.

I configured something wrong? or can't arbitrage be used in the same exchange? it's a bug?

I use hummingbot in GCP with ubuntu server.

**Comment by nkona** [comment]
It appears that this is a bug related to using any arbitrage or cross-market making strategy on two pairs within the same exchange. It occurs regardless of operating system (checked on cloud docker, windows docker, and macOS source). We haven't done much testing or provided support for using two coin pairs in a single exchange, so this is something we'll look into more in future updates.

**Comment by Kathard** [comment]
Thanks nkona, little by little it will be the best bot

**Comment by chowryan** [comment]
@Kathard fixed in "development" branch https://github.com/CoinAlpha/hummingbot/pull/405

**Comment by chowryan** [comment]
@Kathard a fix was merged to the development branch. either clone that branch or wait for v0.9.0. Thanks!

**Comment by Kathard** [comment]
Thank you! I'll wait for the new version because I don't know update this file in docker, I'm still a noob

**Comment by moraliang** [comment]
@Kathard This bug reported is qualified for our bug bounty. Please provide us with your ETH address. We'll send over 0.1 ETH.

**Comment by Kathard** [comment]
> @Kathard This bug reported is qualified for our bug bounty. Please provide us with your ETH address. We'll send over 0.1 ETH.

Thanks moraliang, my wallet is 0xEEDf2209A55034C63B1EdFE959744EAd2f74e556, I hope to continue contributing.
