### ISSUE TITLE
Cancellation issue:  'HummingbotApplication' has no attribute 'is_testing_mode'`

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#4100]
**Describe the bug**
While inspecting our test bots, the probit test bot encounter an issue where it fails to cancel an order and continuously get `Unhandled error in background task: type object 'HummingbotApplication' has no attribute 'is_testing_mode'`
```python
2021-09-05 04:52:17,005 - 13999 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
Traceback (most recent call last):
  File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 551, in _execute_cancel
    raise ValueError(f"Failed to cancel order - {order_id}. Order not found.")
ValueError: Failed to cancel order - B-BTC-USDT-1630675926003018. Order not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/probit/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 571, in _execute_cancel
    self.logger().network(
  File "/home/ubuntu/probit/hummingbot/logger/logger.py", line 53, in network
    if app_warning_msg is not None and not HummingbotApplication.is_testing_mode():
AttributeError: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
```
It seems that this issue is not specific for the connector and strategy, other test bots running on different strategy encounter the same error. Some bots recovers from the cancel loop while some requires the strategy to be restarted to recover.

It appears that this hap
Here are the steps to reproduce the issue (see attachments in the section below):
1.  Create a PMM strategy using any connector
2. Start the bot 
3. After orders are created, disconnect from the internet for about 1 to 2 min
4.  You can also run the bot for long period prior disconnecting from the internet.
...

**Screenshots**
![probit-global-is-testing-mode](https://user-images.githubusercontent.com/57189990/132281124-b448fdf6-98f4-41a1-aba1-0c64250b48f5.png)

![image](https://user-images.githubusercontent.com/57189990/132281094-5596624b-6239-4bfa-bc2c-33bf4d4ee237.png)

**Release version**
0.44.0

**Attachments**
[logs_probit_btc-usdt.log](https://github.com/CoinAlpha/hummingbot/files/7118789/logs_probit_btc-usdt.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rxlxrxsx** [comment]
The testing bots on Bitfinex and Kraken encountered this issue as well.

Bitfinex
```python
2021-09-07 14:05:39,002 - 5821 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
Traceback (most recent call last):
  File "hummingbot/connector/in_flight_order_base.pyx", line 84, in hummingbot.connector.in_flight_order_base.InFlightOrderBase.get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx", line 860, in hummingbot.connector.exchange.bitfinex.bitfinex_exchange.BitfinexExchange.execute_cancel
    exchange_order_id = await self._in_flight_orders.get(order_id).get_exchange_order_id()
  File "hummingbot/connector/in_flight_order_base.pyx", line 83, in get_exchange_order_id
    async with timeout(10):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/bitfinex/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/bitfinex/bitfinex_exchange.pyx", line 902, in execute_cancel
    self.logger().network(
  File "/home/ubuntu/bitfinex/hummingbot/logger/logger.py", line 53, in network
    if app_warning_msg is not None and not HummingbotApplication.is_testing_mode():
AttributeError: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
```

Kraken
```python
2021-09-07 14:59:59,662 - 24425 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 850, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange.execute_buy
    order_result = await self.place_order(userref=userref,
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 812, in place_order
    return await self._api_request_with_retry("post",
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 722, in _api_request_with_retry
    raise e
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 708, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request_with_retry
    result= await self._api_request(method, path_url, params, data, is_auth_required, request_weight)
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 734, in _api_request
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 754, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    async with response_coro as response:
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 779, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._api_request
    raise IOError({"error": response_json})
OSError: {'error': {'error': ['EGeneral:Internal error']}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/kraken/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 881, in execute_buy
    self.logger().network(
  File "/home/ubuntu/kraken/hummingbot/logger/logger.py", line 53, in network
    if app_warning_msg is not None and not HummingbotApplication.is_testing_mode():
```

Logs: 
[logs_bitfinex_btg-usd.log](https://github.com/CoinAlpha/hummingbot/files/7125447/logs_bitfinex_btg-usd.log)
[logs_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/7125448/logs_kraken_btc-usdc.log)

**Comment by rxlxrxsx** [comment]
Getting this issue on the Coinbase Pro, Kucoin and Liquid test bots as well.

Coinbase Pro

```python
2021-09-08 22:52:55,411 - 9817 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
Traceback (most recent call last):
  File "hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx", line 728, in hummingbot.connector.exchange.coinbase_pro.coinbase_pro_exchange.CoinbaseProExchange.execute_buy
    order_result = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type, decimal_price)
  File "hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx", line 704, in place_order
    order_result = await self._api_request("post", path_url=path_url, data=data)
  File "hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx", line 314, in _api_request
    async with client.request(http_method,
  File "hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx", line 318, in hummingbot.connector.exchange.coinbase_pro.coinbase_pro_exchange.CoinbaseProExchange._api_request
    raise IOError(f"Error fetching data from {url}. HTTP status is {response.status}. {data}")
OSError: Error fetching data from https://api.pro.coinbase.com/orders. HTTP status is 400. {'message': 'Insufficient funds'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/coinbase_pro/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/coinbase_pro/coinbase_pro_exchange.pyx", line 748, in execute_buy
    self.logger().network(
  File "/home/ubuntu/coinbase_pro/hummingbot/logger/logger.py", line 53, in network
    if app_warning_msg is not None and not HummingbotApplication.is_testing_mode():
AttributeError: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
```

Kucoin

```python
2021-09-08 05:59:05,300 - 9892 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 766, in hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange.execute_sell
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, False, order_type,
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 671, in place_order
    return str(exchange_order_id["data"]["orderId"])
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/kucoin/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 795, in execute_sell
    self.logger().network(
  File "/home/ubuntu/kucoin/hummingbot/logger/logger.py", line 53, in network
    if app_warning_msg is not None and not HummingbotApplication.is_testing_mode():
AttributeError: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
```

Liquid

```python
2021-09-08 09:21:19,347 - 24387 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
Traceback (most recent call last):
  File "hummingbot/connector/exchange/liquid/liquid_exchange.pyx", line 922, in hummingbot.connector.exchange.liquid.liquid_exchange.LiquidExchange.execute_buy
    order_result = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type, decimal_price)
  File "hummingbot/connector/exchange/liquid/liquid_exchange.pyx", line 865, in place_order
    order_result = await self._api_request("post", path_url=path_url, data=data)
  File "hummingbot/connector/exchange/liquid/liquid_exchange.pyx", line 312, in _api_request
    async with client.request(http_method,
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/liquid/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/liquid/liquid_exchange.pyx", line 941, in execute_buy
    self.logger().network(
  File "/home/ubuntu/liquid/hummingbot/logger/logger.py", line 53, in network
    if app_warning_msg is not None and not HummingbotApplication.is_testing_mode():
AttributeError: type object 'HummingbotApplication' has no attribute 'is_testing_mode'
```

Logs: [logs.zip](https://github.com/CoinAlpha/hummingbot/files/7133391/logs.zip)

**Comment by CrimsonJacket** [comment]
Just a quick observation here, the connectors above are all built using Cython and I was wondering if you have re-compiled the Hummingbot client?
