### ISSUE TITLE
dYdX (Spot exchange): Failed to create strategy using DAI-USDC market

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#4169]
**Describe the bug**
When creating a pure market making strategy or Avellaneda market making strategy and choosing DAI-USDC market, strategy fails to get created due to Unhandled error in background task: [<class 'decimal.DivisionByZero'>]
```python
2021-09-13 10:47:08,592 - 7294 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [<class 'decimal.DivisionByZero'>]
Traceback (most recent call last):
  File "/Users/clintgogoc/Desktop/github/websocket-update/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/clintgogoc/Desktop/github/websocket-update/hummingbot/client/command/create_command.py", line 63, in prompt_for_configuration
    await self.prompt_a_config(config)
  File "/Users/clintgogoc/Desktop/github/websocket-update/hummingbot/client/command/create_command.py", line 106, in prompt_a_config
    prompt = await config.get_prompt()
  File "/Users/clintgogoc/Desktop/github/websocket-update/hummingbot/client/config/config_var.py", line 54, in get_prompt
    return await self.prompt()
  File "/Users/clintgogoc/Desktop/github/websocket-update/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 42, in order_amount_prompt
    min_amount = await minimum_order_amount(exchange, trading_pair)
  File "/Users/clintgogoc/Desktop/github/websocket-update/hummingbot/client/config/config_helpers.py", line 384, in minimum_order_amount
    quote_amount = default_amount / mid_price
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```
It seems that the bot is unable to compute for the suggested minimum order size. The other 2 supported market (WETH-DAI and WETH-USDC) doesn't have an issue.
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy or Avellaneda market making strategy using dYdX spot exchange.
2. Set DAI-USDC as market [Error will occur immediately for Avellaneda MM]
3.  Add spreads parameter and refresh time [PMM only]
**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/133019230-c378a620-8f76-46ee-bf8c-321b9925557a.png)

**Release version**
0.42.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
Checked strategy creation using dYdX connector and it appears that the issue no longer happening in the latest development. Closing the ticket
