### ISSUE TITLE
Pure market making - failed to submit order when setting higher order_amount than available balance

### ISSUE THREAD

**Issue by glenntomas** [CoinAlpha/hummingbot#4220]
**Describe the bug**
When running Pure Market Making strategy using KuCoin it throws an error when you set higher `order_amount` compare to your available balance. The bot only creates sell orders.

**Steps To Reproduce**
1. Create a `pure_market_making` strategy
2. Select one from these token pairs, I've tested all these and get the same error
      - DAO/USDT
      - FEAR/USDT
      - DIVI/USDT
      - PDEX/USDT
      - HAI/USDT
      - DYP/USDT
3. Set your `order_amount` higher than your available balance
4. `start` the bot

**Screenshots**
- `config`

![image](https://user-images.githubusercontent.com/73885708/133959151-d6f23e53-fe84-45c6-8b88-73b718e12d38.png)

- `balance`

![image](https://user-images.githubusercontent.com/73885708/133959230-10dccb3e-da69-4fed-9dcd-289f58118689.png)

- `status`

![image](https://user-images.githubusercontent.com/73885708/133959408-1a110c0d-bc0d-47f7-9437-b1d0964be28e.png)

- Error on `log file`

```
2021-09-20 05:16:10,167 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - NETWORK - Error submitting buy limit_maker order to Kucoin for 139.7544 DYP-USDT 0.5276.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 694, in hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange.execute_buy
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type,
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 671, in place_order
    return str(exchange_order_id["data"]["orderId"])
KeyError: 'data'
2021-09-20 05:16:10,167 - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - WARNING - Failed to submit buy order to Kucoin. Check API key and network connection.
```

**Release version**
version 0.43.1

**Attachments**
[logs_conf_pure_mm_1 - glenn.log](https://github.com/CoinAlpha/hummingbot/files/7193701/logs_conf_pure_mm_1.-.glenn.log)

**Comment by RC-13** [comment]
Adding notes:
1. The issue occurs if the total of both token combined is less than the order amount specified, however the order amount are adjusted if the specified size set is within the range of total asset.
2. The bot shows an incorrect available balance when the issue occur, the balance is reduce or shows 0 however there are no open order in the exchange (shows fails to submit on the bot).
3. If you check the affected token using the `balance` command, the allocation is 100 even if no order was created.

**Comment by RC-13** [comment]
Adding additional notes for this concern:
The adjusted order amount is directly affected by the price of the order. If the calculated price is closer to the mid-price, the adjusted amount is lower compared to the size with a price set away from the mid price. Since the bot calculates the adjusted amount by dividing the quote balance over to the current price with fee, the result size may still be more than the current balance can handle and this are the orders that are failed to be submitted.

**Comment by codewc** [comment]
> Updating notes: I tried replicating the issue and found out that the order size which fails to be submitted is rejected as well if you manually try to place the order in the exchange. For example: The bid order @ 31.6068 DAO for 2.03347 USDT got rejected or failed to submit ![image](https://user-images.githubusercontent.com/57189990/134292648-b8ba7fe4-09a5-4b36-ac02-34579d15a1fc.png) By manually placing the same size in the exchange, it was rejected and prompted with the max amount that can be place ![image](https://user-images.githubusercontent.com/57189990/134292774-ba15261e-d886-4786-a9df-31c80b545e8a.png) It seems that the exchange is imposing some trade rule that prevents the entire quote asset to be use.

Hi, 
The `spot` and `futures` of KuCoin exchange have restrictions on placing orders 
spot: https://docs.kucoin.center/#get-symbols-list
futures: https://docs.kucoin.center/futures/#get-order-info-of-the-contract

For example, for placing a spot order：
The baseMinSize and baseMaxSize fields define the min and max order size. The priceIncrement field specifies the min order price as well as the price increment.This also applies to quote currency.
The order price must be a positive integer multiple of this priceIncrement (i.e. if the increment is 0.01, the 0.001 and 0.021 order prices would be rejected).
