### ISSUE TITLE
handling rate limited commands

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#4282]
**Describe the bug**
New parameter `other_commands_timeout` and `create_command_timeout` accepting decimal values or zero as value causing the bot not able to start.

**Steps To Reproduce**
config `create_command_timeout 0.0001` or config `create_command_timeout 0`
config `other_commands_timeout 0.01` or config `other_commands_timeout 0`
create strategy then start

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/134759067-39f6d948-e4d3-4ca5-9609-75a12a756a0f.png)
![image](https://user-images.githubusercontent.com/54516858/134759090-78772252-372a-4166-a74a-1e6e738c0576.png)
![image](https://user-images.githubusercontent.com/54516858/134759092-5e7a23fc-aa6e-4cf5-89b5-8a2d1b110415.png)

```
2021-09-25 05:07:08,579 - 71987 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task:
Traceback (most recent call last):
  File "/home/ubuntu/handling_rate_limited_commands/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/handling_rate_limited_commands/hummingbot/client/command/start_command.py", line 72, in start_check
    is_valid = await self.status_check_all(notify_success=False)
  File "/home/ubuntu/handling_rate_limited_commands/hummingbot/client/command/status_command.py", line 152, in status_check_all
    invalid_conns = await asyncio.wait_for(self.validate_required_connections(), network_timeout)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 464, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
2021-09-25 05:07:08,580 - 71987 - hummingbot.logger.reporting_proxy_handler - ERROR - Error sending logs.
Traceback (most recent call last):
  File "/home/ubuntu/handling_rate_limited_commands/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/handling_rate_limited_commands/hummingbot/client/command/start_command.py", line 72, in start_check
    is_valid = await self.status_check_all(notify_success=False)
  File "/home/ubuntu/handling_rate_limited_commands/hummingbot/client/command/status_command.py", line 152, in status_check_all
    invalid_conns = await asyncio.wait_for(self.validate_required_connections(), network_timeout)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 464, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/handling_rate_limited_commands/hummingbot/logger/reporting_proxy_handler.py", line 157, in flush
    self.send_logs(self._log_queue)
  File "/home/ubuntu/handling_rate_limited_commands/hummingbot/logger/reporting_proxy_handler.py", line 116, in send_logs
    if not self._enable_order_event_logging:
AttributeError: 'ReportingProxyHandler' object has no attribute '_enable_order_event_logging'
```

**Release version**
dev-0.44.4

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/7229190/logs_hummingbot.log)

**Comment by PtrckM** [comment]
Issue addressed and fix. merge on development
