### ISSUE TITLE
Bybit Perpetual - Error fetching funding fee

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#4290]
**Describe the bug**
Updating description:
First issue: When running the perpetual_mm using bybit_perpetual with position/s currently open, there are no funding payment notification on the logs upon funding period. (Fix on the latest commit of the Bybit PR)
New issue:
When it's time for funding period, the bot receive the funding payment however it encounters an error fetching the funding fee with the following error:
```python
2021-09-29 00:05:33,852 - 9312 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative - INFO - Funding payment of 0.0060 received on DOGE-USDT market.
2021-09-29 00:05:33,853 - 9312 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative - ERROR - Unexpected error occurred fetching funding fee for DOGE-USDT. Error: 'exec_timestamp'
Traceback (most recent call last):
  File "/home/ubuntu/bybit_connector_4308/hummingbot/connector/derivative/bybit_perpetual/bybit_perpetual_derivative.py", line 1035, in _fetch_funding_fee
    FundingPaymentCompletedEvent(timestamp=int(data["exec_timestamp"] * 1e3),
KeyError: 'exec_timestamp'
2021-09-29 00:05:38,923 - 9312 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on private/linear/funding/prev-funding-DOGE-USDT (120 calls per 60s) has almost reached. Limits used is 120 in the last 60 seconds
```
With this error, it result to not recording the funding payment in the FundingPayment table on the sqlite file

**Steps To Reproduce**
1. Run a perpetual_mm strategy using bybit_perpetual
2. Make sure that there's an open position during funding period

**Screenshots**

![image](https://user-images.githubusercontent.com/57189990/135183640-ff3ec022-9992-4384-8383-dba69a255942.png)
![image](https://user-images.githubusercontent.com/57189990/135183735-43df7531-5529-4092-89ae-e5f3d0efcd6c.png)

**Release version**
development-0.44.0 under the `epic/bybit_connector` branch

**Attachments**
[logs_bybit_perp.log](https://github.com/CoinAlpha/hummingbot/files/7248042/logs_bybit_perp.log)

**Comment by RC-13** [comment]
Re-tested the Bybit PR and the funding payment is now displayed in the logs, however the bot encounter an error getting the funding fee:
![image](https://user-images.githubusercontent.com/57189990/135181860-7ea32960-f5e6-4e32-9942-b784d4ec739c.png)

```python
2021-09-29 00:05:33,852 - 9312 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative - INFO - Funding payment of 0.0060 received on DOGE-USDT market.
2021-09-29 00:05:33,853 - 9312 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative - ERROR - Unexpected error occurred fetching funding fee for DOGE-USDT. Error: 'exec_timestamp'
Traceback (most recent call last):
  File "/home/ubuntu/bybit_connector_4308/hummingbot/connector/derivative/bybit_perpetual/bybit_perpetual_derivative.py", line 1035, in _fetch_funding_fee
    FundingPaymentCompletedEvent(timestamp=int(data["exec_timestamp"] * 1e3),
KeyError: 'exec_timestamp'
2021-09-29 00:05:38,923 - 9312 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on private/linear/funding/prev-funding-DOGE-USDT (120 calls per 60s) has almost reached. Limits used is 120 in the last 60 seconds
```
With this error, it result to not recording the funding payment in the FundingPayment table on the sqlite file
![image](https://user-images.githubusercontent.com/57189990/135181827-1ad62dc0-1c8d-4b7d-8f2d-881a1b1987e2.png)
[logs_bybit_perp.log](https://github.com/CoinAlpha/hummingbot/files/7247968/logs_bybit_perp.log)
