### ISSUE TITLE
Paper trade broken on recently refactored connectors using the new asyncio throttler (gate.io, binance, kucoin)

### ISSUE THREAD

**Issue by TheHolyRoger** [CoinAlpha/hummingbot#4300]
**Describe the bug**
Paper trade is broken on all the recently refactored exchanges using the new asyncio throttler as it adds a new required arg to the classes

**Steps To Reproduce**
Run any of these refactored connectors in paper trade mode (gate.io, binance, kucoin, ascend_ex, crypto.com, ndax, kraken)

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
development

**Attachments**
```
2021-09-27 15:47:15,546 - 1 - hummingbot.core.remote_control.remote_command_executor - INFO - Starting Remote Command Executor.
2021-09-27 15:47:15,548 - 1 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 60, in start
    self._initialize_markets(market_names)
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 265, in _initialize_markets
    connector = create_paper_trade_market(connector_name, trading_pairs)
  File "/home/hummingbot/hummingbot/connector/exchange/paper_trade/init.py", line 27, in create_paper_trade_market
    obt_obj = obt_class(**obt_kwargs)
TypeError: init() missing 1 required positional argument: 'throttler'
2021-09-27 15:47:15,548 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2021-09-27 15:47:15,618 - 1 - hummingbot.core.remote_control.remote_command_executor - INFO - Remote Command Executor is listening.
2021-09-27 15:47:20,867 - 1 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2021-09-27 15:47:20,867 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/stop_command.py", line 37, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list
```

**Comment by TheHolyRoger** [comment]
Boom https://github.com/CoinAlpha/hummingbot/pull/4301 :)

**Comment by dennisocana** [comment]
Thanks @TheHolyRoger for this fix! We'll review today before we close the version 0.44 development phase.
