### ISSUE TITLE
Paper_trade: Strategy fails to start when using Binance connector

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#4315]
**Describe the bug**
When running a strategy using Binance connector in paper trade mode, a clock tick error occur. 
```python
2021-09-29 03:23:23,039 - 19778 - hummingbot.connector.exchange.binance.binance_order_book_tracker - INFO - Initialized order book for DOGE-USDT. 1/1 completed.
2021-09-29 03:23:24,212 - 19778 - hummingbot.client.hummingbot_application - ERROR - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/ubuntu/hb/hummingbot/client/command/start_command.py", line 160, in start_market_making
    await self.wait_till_ready(self.kill_switch.start)
  File "/home/ubuntu/hb/hummingbot/client/command/start_command.py", line 45, in wait_till_ready
    all_ready = all([market.ready for market in self.markets.values()])
  File "/home/ubuntu/hb/hummingbot/client/command/start_command.py", line 45, in <listcomp>
    all_ready = all([market.ready for market in self.markets.values()])
  File "hummingbot/connector/exchange/paper_trade/paper_trade_exchange.pyx", line 238, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.ready.__get__
    self.init_paper_trade_market()
  File "hummingbot/connector/exchange/paper_trade/paper_trade_exchange.pyx", line 199, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.init_paper_trade_market
    base_asset, quote_asset = self.split_trading_pair(trading_pair_str)
TypeError: 'NoneType' object is not iterable
```

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Enable paper trade
2. Create a pure market making strategy or Avellaneda market making strategy using Binance as connector.
3. Start the strategy
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/135198961-a0471559-6ef0-4c99-a8b2-9ed37100e659.png)

**Release version**
0.44.0

**Attachments**
 
[ave-logs.log](https://github.com/CoinAlpha/hummingbot/files/7248682/ave-logs.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
Fix in the development and staging branch (0.44)
