### ISSUE TITLE
[BUG] XEMM "balance insufficient" bug due to Binance size adjustment for fees

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#434]
**Describe the bug**
Because the Binance market class adjusts the size of buy transactions to account for fees, it may fail and raise an error if the size adjustment results in a trade size that exceeds inventory balance.

This happens when users running XEMM have their trade size capped at their total balance. Trade size is determined before a buy order is adjusted by the Market class, so it is capped at inventory balance. When the Market class adjusts order by increasing size slightly, it exceeds the inventory balance and the order fails.

Before making any changes, we should discuss whether it makes sense to adjust Binance buy order sizes. The small differences in size may not matter that much to users, and size adjustment necessitates handling of edge cases like this.

Parsing the logs:
1. The bot places a buy order for 30.853 ALGO at 1.642 price. I only have 50.66 TUSD in my account, so this is correctly capped.
2. The actual trade size submitted to Binance is for 30.883 ALGO, reflecting the size adjustment for fees. This triggers an error, since it exceeds my TUSD inventory balance.

```
2019-06-25 14:38:23,000 - hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - (ALGOTUSD) Creating limit bid order for 30.85300000 ALGO at 1.64200000 TUSD. Current hedging price: 1.658 USDT (Rate adjusted: 1.65 USDT). [clock=2019-06-25 21:38:23+00:00]
2019-06-25 14:38:23,415 - hummingbot.core.utils.async_call_scheduler - NETWORK - API call error.
Traceback (most recent call last):
  File "/Users/feng/Code/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 1222, in order_limit_buy
    return self.order_limit(timeInForce=timeInForce, **params)
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 1186, in order_limit
    return self.create_order(**params)
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 1149, in create_order
    return self._post('order', True, data=params)
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 210, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 181, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 176, in _request
    return self._handle_response(response)
  File "/Users/feng/anaconda3/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 200, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.
2019-06-25 14:38:23,416 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-06-25 14:38:23,418 - hummingbot.market.binance.binance_market - NETWORK - Error submitting buy LIMIT order to Binance for 30.88300000 ALGOTUSD 1.64200000.
```

### Version
`0.9.0-dev`

### Config
```
# Exchange and token parameters
maker_market: binance
taker_market: binance
maker_market_symbol: ALGOTUSD
taker_market_symbol: ALGOUSDT

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.005

# Maximum order size in terms of quote currency
trade_size_override: 50
```
### Logs
[insufficient binance balance.log](https://github.com/CoinAlpha/hummingbot/files/3327656/insufficient.binance.balance.log)

**Comment by chowryan** [comment]
this is probably fixed? reopen if it still an issue.
