### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

### ISSUE THREAD

**Issue by netada** [CoinAlpha/hummingbot#4365]
**Describe the bug**
Getting intermittent errors when balance limit is set with pure market making strategy
"ERROR - Unexpected error running clock tick."

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up your configuration file with these parameters: ...
1. Start the bot using this command: ...
Running in a container on Amazon Linux. Bot is started using the start.sh script. From the trace, it appears the parameter that is triggering this bug is "balance limit". Specifically I have "balance limit kucoin USDT 500"

**Screenshots**
2021-10-02 17:51:51,000 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 722, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    self.c_apply_budget_constraint(proposal)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 897, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_apply_budget_constraint
    base_balance, quote_balance = self.adjusted_available_balance_for_orders_budget_constrain()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 888, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.adjusted_available_balance_for_orders_budget_constrain
    return self.c_get_adjusted_available_balance(all_non_hanging_orders)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 803, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_get_adjusted_available_balance
    object quote_balance = market.c_get_available_balance(self.quote_asset)
  File "hummingbot/connector/connector_base.pyx", line 331, in hummingbot.connector.connector_base.ConnectorBase.c_get_available_balance
    return self.get_available_balance(currency)
  File "hummingbot/connector/connector_base.pyx", line 346, in hummingbot.connector.connector_base.ConnectorBase.get_available_balance
    available_balance = self.apply_balance_limit(currency, available_balance, balance_limit)
  File "hummingbot/connector/connector_base.pyx", line 310, in hummingbot.connector.connector_base.ConnectorBase.apply_balance_limit
    filled_balance = self.order_filled_balances().get(currency, s_decimal_0)
  File "hummingbot/connector/connector_base.pyx", line 150, in hummingbot.connector.connector_base.ConnectorBase.order_filled_balances
    base_value = Decimal("-1") * event.amount
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.44.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**
[config.txt](https://github.com/CoinAlpha/hummingbot/files/7273185/config.txt)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran8kh) by [Unito](https://www.unito.io)

**Comment by Carl0423** [comment]
Hello @netada, I tried running the bot while almost exactly copying your config (except the order amount), and have not encountered the issue after an hour of testing. 

![KuCoin test](https://user-images.githubusercontent.com/90753976/135756761-988a1f55-4afb-43c7-b1f0-82acba02f20e.jpg)

**Comment by nikspz** [comment]
@netada Could please you confirm, are you using Docker build on ec2 instance (amazon Linux)?

**Comment by netada** [comment]
yes, Docker build on ec2 (amazon Linux)

**Comment by netada** [comment]
the error is intermittent and seems to occur during relatively higher trading activity

**Comment by nikspz** [comment]
@netada Upon checking we have a ticket with a similar error message on KuCoin for Avellaneda strategy
https://github.com/CoinAlpha/hummingbot/issues/4124

Tried to replicate with your config, bot working fine, couldn't replicate it now.
![image](https://user-images.githubusercontent.com/83953535/135765529-852a414e-3d03-4752-9df5-d299dc1d8da7.png)

**Comment by netada** [comment]
I will wait for it to happen again and take a screen shot and attach it here.

**Comment by netada** [comment]
Issue is fixed in v0.45.0
