### ISSUE TITLE
Avellaneda - volatility_buffer_size accepts decimal value

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#4368]
**Describe the bug**
When updating parameters, the bot would normally prompt the user to enter the correct values if it is entered incorrectly however for Avellaneda market-making's `volatility_buffer_size` it accepts decimal values which results `unexpected error running clock tick`

```
2021-10-04 17:10:18,000 - 19328 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot\\core\\clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot\\strategy\\avellaneda_market_making\\avellaneda_market_making.pyx", line 589, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_tick
    self.c_collect_market_variables(timestamp)
  File "hummingbot\\strategy\\avellaneda_market_making\\avellaneda_market_making.pyx", line 631, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_collect_market_variables
    self._time_left = max(self._time_left - Decimal(timestamp - self._last_timestamp) * 1000, 0)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'decimal.Decimal'
```

**Steps To Reproduce**

1. Create a simple Avellaneda market-making strategy
1. Change `volatility_buffer_size` to decimal value 
1. You will notice that it accept it with some errors on the logs
1. Start the bot, getting `unexpected clock ticket error`

**Screenshots**
On the screenshot below, I tried to enter an alphanumeric value and it prompt again to enter it correctly since getting logs that the `20a` is not an integer. Then entered a decimal which the bot accepts but a same error on the logs
![image](https://user-images.githubusercontent.com/73840223/135829205-88d751a4-d2f3-426a-825a-b9f635c75c89.png)

**Release version**
dev-0.45.0

**Attachments**
[ave-test.zip](https://github.com/CoinAlpha/hummingbot/files/7277104/ave-test.zip)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran8rn) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Fix on version 0.46.0, closing ticket.
