### ISSUE TITLE
undefined symbol: _ZSt28__throw_bad_array_new_lengthv

### ISSUE THREAD

**Issue by mablue** [CoinAlpha/hummingbot#4606]
**Describe the bug**

```
(hummingbot) [mab@mab hummingbot]$ bin/hummingbot.py
Traceback (most recent call last):
  File "bin/hummingbot.py", line 12, in <module>
    from hummingbot.client.hummingbot_application import HummingbotApplication
  File "/home/mab/Documents/DEV/hummingbot/hummingbot/hummingbot/client/hummingbot_application.py", line 9, in <module>
    from hummingbot.client.command import __all__ as commands
  File "/home/mab/Documents/DEV/hummingbot/hummingbot/hummingbot/client/command/__init__.py", line 1, in <module>
    from .config_command import ConfigCommand
  File "/home/mab/Documents/DEV/hummingbot/hummingbot/hummingbot/client/command/config_command.py", line 16, in <module>
    from hummingbot.client.config.config_helpers import (
  File "/home/mab/Documents/DEV/hummingbot/hummingbot/hummingbot/client/config/config_helpers.py", line 37, in <module>
    from hummingbot.core.utils.market_price import get_last_price
  File "/home/mab/Documents/DEV/hummingbot/hummingbot/hummingbot/core/utils/market_price.py", line 5, in <module>
    from hummingbot.connector.exchange.binance.binance_api_order_book_data_source import BinanceAPIOrderBookDataSource
  File "/home/mab/Documents/DEV/hummingbot/hummingbot/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 25, in <module>
    from hummingbot.core.data_type.order_book_tracker_data_source import OrderBookTrackerDataSource
  File "/home/mab/Documents/DEV/hummingbot/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 13, in <module>
    from hummingbot.core.data_type.order_book import OrderBook
ImportError: /home/mab/Documents/DEV/hummingbot/hummingbot/hummingbot/core/data_type/order_book.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```

**Steps To Reproduce**

```
conda activate hummingbot && ./compile
bin/hummingbot.py
```

**Release version**
cant run it

discord mablue

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1tctjnm) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Hello @mablue are you still having an issue starting the client using source build?

**Comment by RC-13** [comment]
Closing ticket since it has been idle for a while now.
