### ISSUE TITLE
Paper trade: Unhandled error when running history command

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#4634]
**Describe the bug**
When running a bot in paper trade, the following error occur when `history` command is run after getting a fill. This error occur only when one of the token used as market has not beed added yet in the `balance paper`.

```python
2021-11-02 02:34:36,457 - 10685 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'int' object has no attribute 'is_nan'
Traceback (most recent call last):
  File "/home/ubuntu/paper/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/paper/hummingbot/client/command/history_command.py", line 85, in history_report
    self.report_performance_by_market(market, symbol, perf, precision)
  File "/home/ubuntu/paper/hummingbot/client/command/history_command.py", line 158, in report_performance_by_market
    PerformanceMetrics.smart_round(perf.cur_base_bal, precision),
  File "/home/ubuntu/paper/hummingbot/client/performance.py", line 140, in smart_round
    if value is None or value.is_nan():
AttributeError: 'int' object has no attribute 'is_nan'
```

This issue can be worked around by adding the token symbol in the paper balance, if you want to start with a 0 asset, then value needs to be specified, example `balance paper DOGE 0`

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Create any market making strategy
1. Use any market as long as one of the token doesn't have existing paper balance
1. Start the strategy and wait for a fill.
1. Run `history` or `history --verbose` command after getting a fill
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/139779043-28a937c5-f994-4bb0-bd77-f3023b851ff4.png)

**Release version**
0.44.0

**Attachments**

[paper-logs.log](https://github.com/CoinAlpha/hummingbot/files/7457464/paper-logs.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1u9d606) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Closing ticket, I no longer see the issue in the latest version (0.46.0)
