### ISSUE TITLE
Gateway v2 - Unable to start gateway properly

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#4686]
**Describe the bug**
- Unable to connect to port 5000 due to configuration cause by permission
- Duplicate entry of telemetry on configuration

**Steps To Reproduce**
1. clone and install `git clone -b feat/gateway-v2 https://github.com/CoinAlpha/hummingbot gateway-v2`
2. `cd gateway-v2/gateway`
3. `yarn`
4. `yarn build`
5. `yarn start`

- starting gateway shows api is listening on port 5000 but port is not open when check
![image](https://user-images.githubusercontent.com/54516858/141049572-3b24dc35-b7f2-4478-a117-2f713c9273d2.png)

- upon checking logs
```
2021-11-10 05:42:04 | error |   unhandledRejection: ENOENT: no such file or directory, lstat './conf/gateway-passphrase.yml'
Error: ENOENT: no such file or directory, lstat './conf/gateway-passphrase.yml'
    at Object.lstatSync (fs.js:1119:3)
    at Object.readPassphrase (/home/ubuntu/gateway-v2/gateway/dist/src/services/config-manager.js:13:35)
    at addHttps (/home/ubuntu/gateway-v2/gateway/dist/src/https.js:27:52)
    at /home/ubuntu/gateway-v2/gateway/dist/src/app.js:76:45
    at Generator.next (<anonymous>)
    at /home/ubuntu/gateway-v2/gateway/dist/src/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/gateway-v2/gateway/dist/src/app.js:4:12)
    at startGateway (/home/ubuntu/gateway-v2/gateway/dist/src/app.js:67:28)
    at Object.<anonymous> (/home/ubuntu/gateway-v2/gateway/dist/src/index.js:4:24) | Error: ENOENT: no such file or directory, lstat './conf/gateway-passphrase.yml'
    at Object.lstatSync (fs.js:1119:3)
    at Object.readPassphrase (/home/ubuntu/gateway-v2/gateway/dist/src/services/config-manager.js:13:35)
    at addHttps (/home/ubuntu/gateway-v2/gateway/dist/src/https.js:27:52)
    at /home/ubuntu/gateway-v2/gateway/dist/src/app.js:76:45
    at Generator.next (<anonymous>)
    at /home/ubuntu/gateway-v2/gateway/dist/src/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/gateway-v2/gateway/dist/src/app.js:4:12)
    at startGateway (/home/ubuntu/gateway-v2/gateway/dist/src/app.js:67:28)
    at Object.<anonymous> (/home/ubuntu/gateway-v2/gateway/dist/src/index.js:4:24)
2021-11-10 05:42:04 | info |    eth stored nonces | undefined
2021-11-10 05:42:04 | info |    eth stored nonces | undefined
2021-11-10 05:47:02 | info |    1 request(s) sent in last 300 seconds. | undefined
```

5. Using `sh setup/config.sh` to generate gateway-passphrase. It created `gateway-passphrase.yml` file with correct permissions (also shows the typed password during setup.)
![image](https://user-images.githubusercontent.com/54516858/141051704-ed70d0a4-1fda-498f-ad40-d036a96bbfe9.png)

6. try to start gateway `yarn start` gateway crashed

![image](https://user-images.githubusercontent.com/54516858/141051845-1643f936-a7ca-4912-95ef-282399ce23d1.png)

- upon checking the `conf/gateway-config.yml` file it has duplicated `ENABLE_TELEMETRY: 'false'`
![image](https://user-images.githubusercontent.com/54516858/141052337-4edc2d75-7c26-4937-aaeb-0ff53dda1e03.png)

7. Workaround: Delete duplicate entry then `yarn start`
![image](https://user-images.githubusercontent.com/54516858/141052547-62ebd94e-8599-4853-8f5a-4be52a596028.png)

- note the passphrase also available on `conf/gateway-config.yml` file
![image](https://user-images.githubusercontent.com/54516858/141052131-7d4140b8-57bf-4671-8099-fe6bb6734a18.png)

- node version
![image](https://user-images.githubusercontent.com/54516858/141050226-a8258bc8-0559-4225-8994-c9473b49ef83.png)

**Attachments**

[gwv2.zip](https://github.com/CoinAlpha/hummingbot/files/7509973/gwv2.zip)

**Comment by PtrckM** [comment]
FIXED - duplicate telemetry during setup

still need to remove https://github.com/CoinAlpha/hummingbot/blob/feat/gateway-v2/gateway/conf/gateway-config-example.yml#L14 cause its no longer in-use.
