### ISSUE TITLE
DYDX - Spot (Layer 1) now deprecated

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#4689]
**Describe the bug**
DYDX recently announced that they will close down their spot and margin (layer 1) trading. In line with this, the connector (spot) is no longer usable in the client. More info here:
https://dydx.exchange/blog/layer-1-wind-down

<img width="1422" alt="Screen Shot 2021-11-11 at 9 10 03 AM" src="https://user-images.githubusercontent.com/64377055/141219782-f56a5a8a-1aad-4d33-8dc0-8f8e5607b47d.png">

```python
2021-11-11 09:09:47,224 - 1980 - hummingbot.connector.exchange.dydx.dydx_exchange - ERROR - Could not set balance OSError('Error fetching active dydx token configurations. HTTP status is 404.')
Traceback (most recent call last):
  File "hummingbot/connector/exchange/dydx/dydx_exchange.pyx", line 717, in hummingbot.connector.exchange.dydx.dydx_exchange.DydxExchange._set_balances
    await self.token_configuration._configure()
  File "/Users/reiniersalazar/development/hummingbot/connector/exchange/dydx/dydx_api_token_configuration_data_source.py", line 45, in _configure
    raise IOError(f"Error fetching active dydx token configurations. HTTP status is {response.status}.")
OSError: Error fetching active dydx token configurations. HTTP status is 404.
```

**Release version**
development-0.46.0

**Comment by dennisocana** [comment]
A user story has been created to remove this connector : https://github.com/CoinAlpha/hummingbot/issues/4734
