### ISSUE TITLE
Binance connector issue

### ISSUE THREAD

**Issue by glarkou** [CoinAlpha/hummingbot#4780]
**Describe the bug**
While running the cross exchange strategy I get the following from Binance exchange.

2021-11-20 15:06:09,228 - 1 - hummingbot.connector.exchange.binance.binance_api_user_stream_data_source - ERROR - Unexpected error while listening to user stream. Retrying after 5 seconds... Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_api_user_stream_data_source.py", line 152, in listen_for_user_stream
    output.put_nowait(msg.json())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rxlxrxsx** [comment]
Hi @glarkou, we have an [open ticket](https://github.com/CoinAlpha/hummingbot/issues/4627) for this issue. Moving forward please refer to this ticket for updates. Closing this one now.
