### ISSUE TITLE
Avellaneda - "Unexpected error running clock tick" when cancelling orders

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#4837]
**Describe the bug**
While testing the Avellaneda strategy, we noticed that there are instances of the bot getting `Unexpected error running clock tick` on cancelling orders when it reached the set order_refresh_time. There are also instances of the bot recovering from the error which can be found on the attached log file. 

```
2021-11-30 07:08:23,818 - 10143 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER SELL order hummingbot-S-BTC-USDT-1638256101401605 for 0.00030 BTC-USDT.
2021-11-30 07:08:23,944 - 10143 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1638256102.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-USDT", "amount": "0.00030", "price": "56875.51", "order_id": "hummingbot-S-BTC-USDT-1638256101401605", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "bitmart"}
2021-11-30 07:08:23,945 - 10143 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER BUY order hummingbot-B-BTC-USDT-1638256101401374 for 0.00030 BTC-USDT.
2021-11-30 07:08:24,063 - 10143 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1638256102.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-USDT", "amount": "0.00030", "price": "56309.58", "order_id": "hummingbot-B-BTC-USDT-1638256101401374", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "bitmart"}
2021-11-30 07:09:21,210 - 10143 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (BTC-USDT) Cancelling the limit order hummingbot-B-BTC-USDT-1638256101401374. [clock=2021-11-30 07:09:21+00:00]
2021-11-30 07:09:21,211 - 10143 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (BTC-USDT) Cancelling the limit order hummingbot-S-BTC-USDT-1638256101401605. [clock=2021-11-30 07:09:21+00:00]
2021-11-30 07:09:31,158 - 10143 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Successfully cancelled order hummingbot-B-BTC-USDT-1638256101401374.
2021-11-30 07:09:31,352 - 10143 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1638256171.0, "order_id": "hummingbot-B-BTC-USDT-1638256101401374", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "bitmart"}
2021-11-30 07:09:31,352 - 10143 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Successfully cancelled order hummingbot-S-BTC-USDT-1638256101401605.
2021-11-30 07:09:31,536 - 10143 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1638256171.0, "order_id": "hummingbot-S-BTC-USDT-1638256101401605", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "bitmart"}
2021-11-30 07:09:32,610 - 10143 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (BTC-USDT) Creating 1 bid orders at (Size, Price): ['0.0003 BTC, 56309.58 USDT']
2021-11-30 07:09:32,610 - 10143 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (BTC-USDT) Creating 1 ask orders at (Size, Price): ['0.0003 BTC, 56875.51 USDT']
2021-11-30 07:09:34,629 - 10143 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER SELL order hummingbot-S-BTC-USDT-1638256172610715 for 0.00030 BTC-USDT.
2021-11-30 07:09:34,685 - 10143 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1638256172.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-USDT", "amount": "0.00030", "price": "56875.51", "order_id": "hummingbot-S-BTC-USDT-1638256172610715", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "bitmart"}
2021-11-30 07:09:34,685 - 10143 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER BUY order hummingbot-B-BTC-USDT-1638256172610454 for 0.00030 BTC-USDT.
2021-11-30 07:09:34,810 - 10143 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1638256172.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-USDT", "amount": "0.00030", "price": "56309.58", "order_id": "hummingbot-B-BTC-USDT-1638256172610454", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "bitmart"}

# After 1minute, refresh time triggered
 
2021-11-30 07:10:32,009 - 10143 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 602, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_tick
    self.c_calculate_reserved_price_and_optimal_spread()
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 710, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_calculate_reserved_price_and_optimal_spread
    self._optimal_spread += 2 * Decimal(1 + self._gamma / self._kappa).ln() / self._gamma
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Steps To Reproduce**
1. Set your assets to 50/50 (tested on Bitmart BTC/USDT)
2. Setup Avellaneda strategy
3. Set inventory_target_base_pct to 20
4. Monitor your bot when trying to cancel orders at the set refresh time

**Screenshots**
![image](https://user-images.githubusercontent.com/73840223/144027880-821304a9-30a4-46a4-8d77-a65c1f43c372.png)

**Release version**
dev 0.46.0 / staging 

**Attachments**
[ave-test.zip](https://github.com/CoinAlpha/hummingbot/files/7624877/ave-test.zip)

**Comment by mhrvth** [comment]
@rapcmia 
Can you please check with the brach refactor/avellaneda_time ? This issue should be fixed there.
