### ISSUE TITLE
[BUG] Error when stop loss is triggered

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#484]
**Describe the bug**
When stop loss is triggered, the bot seems to cancel all orders as expected.

However, this error message is logged:

```
2019-07-02 06:12:51,469 - hummingbot.core.utils.stop_loss_tracker - INFO - Stop loss threshold reached. Stopping the bot...
2019-07-02 06:12:51,469 - hummingbot.core.utils.stop_loss_tracker - ERROR - Error calculating stop loss percentage: An asyncio.Future, a coroutine or an awaitable is required
Traceback (most recent call last):
  File "/hummingbot/core/utils/stop_loss_tracker.py", line 66, in stop_loss_loop
    self._stop_handler()
  File "/hummingbot/client/hummingbot_application.py", line 1006, in <lambda>
    self.stop(*args, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/tasks.py", line 526, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

---

```
2019-07-02 09:55:49,097 - hummingbot.client.hummingbot_application - ERROR - '[**SYMBOL**]'
Traceback (most recent call last):
  File "/hummingbot/client/hummingbot_application.py", line 215, in _handle_command
    f(**kwargs)
  File "/hummingbot/client/hummingbot_application.py", line 1119, in history
    self.analyze_performance()
  File "/hummingbot/client/hummingbot_application.py", line 1176, in analyze_performance
    else self.balance_snapshot()[asset_name][market_name]
KeyError: '[**SYMBOL**]'
```

**Steps To Reproduce**
1. Run pure-mm and set a stop loss
...

**Screenshots**

**Release version**
0.9.1

**Comment by yzhang1994** [comment]
The second bug still needs to be triaged and fixed
