### ISSUE TITLE
Order notional value is less than the minimum allowable notional value

### ISSUE THREAD

**Issue by dkreeg** [CoinAlpha/hummingbot#4848]
Receiving the following errors after upgrading to v0.46.0 running avellaneda strategy. Created the strategy from scratch...using values that worked fine in v0.45.0

```2021-12-01 13:09:56,006 - 16337 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 602, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_tick
    self.c_calculate_reserved_price_and_optimal_spread()
  File "hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx", line 710, in hummingbot.strategy.avellaneda_market_making.avellaneda_market_making.AvellanedaMarketMakingStrategy.c_calculate_reserved_price_and_optimal_spread
    self._optimal_spread += 2 * Decimal(1 + self._gamma / self._kappa).ln() / self._gamma
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]```

Also this error. Again all values entered in the config worked fine in 0.45.0

```2021-12-01 13:04:33,056 - 16337 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Order notional value(0E-11) is less than the minimum allowable notional value for an order (0.0050000000000000000)
Traceback (most recent call last):
  File "/home/name/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "hummingbot/connector/exchange/loopring/loopring_exchange.pyx", line 417, in execute_buy
    if await self.execute_order(TradeType.BUY, order_id, trading_pair, amount, order_type, price):
  File "hummingbot/connector/exchange/loopring/loopring_exchange.pyx", line 362, in execute_order
    raise ValueError(f"Order notional value({str(amount*price)}) is less than the minimum allowable notional value for an order ({str(trading_rule.min_notional_size)})")
ValueError: Order notional value(0E-11) is less than the minimum allowable notional value for an order (0.0050000000000000000)```

**Comment by dkreeg** [comment]
Thank you for the reply. 

As for the second error about minimum order size. I do not believe that the size of the order is reason for the error. I can set the pure_market_maket with the same order size without any errors or issues. The exchange will accept the order size.

**Comment by RC-13** [comment]
Can you attach you logs and strategy configuration file? @dkreeg

**Comment by mhrvth** [comment]
Hi, what's your risk_factor?

**Comment by dkreeg** [comment]
> Hi, what's your risk_factor?

I've tried three:
1.0 (default)
.75
.50

**Comment by mhrvth** [comment]
In that case this should be already fixed in the branch refactor/avellaneda_time

**Comment by dkreeg** [comment]
Here it is...can't figure out why is it's creating a bid like this: 1 bid orders at (Size, Price): ['85 LRC, 0 ETH']

``` 2021-12-01 22:2021-12-01 22:27:04,018 - 3945 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (LRC-ETH) Creating 1 bid orders at (Size, Price): ['85 LRC, 0 ETH']27:04,019 - 3945 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (LRC-ETH) Creating 1 ask orders at (Size, Price): ['85 LRC, 0.00064498 ETH']
2021-12-01 22:27:04,019 - 3945 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Order notional value(0E-11) is less than the minimum allowable notional value for an order (0.0050000000000000000) ```

**Comment by dkreeg** [comment]
[logs_conf_avellaneda_loop_2.log](https://github.com/CoinAlpha/hummingbot/files/7641761/logs_conf_avellaneda_loop_2.log)

**Comment by mhrvth** [comment]
That's also fixed in the new branch.

**Comment by mhrvth** [comment]
Moving back to backlog because all Avellaneda specific issues have been addressed. The bug should be either renamed or recreated as a bug specific to the order sizes.

**Comment by mhrvth** [comment]
> ValueError: Order notional value(0E-11) is less than ...

Since the amount is fixed, the price had to be 0. This should be already fixed in the development branch. Therefore I'm closing this bug. If it's still happening for you, please feel free to let me know.
