### ISSUE TITLE
[BUG] sqlite3.ProgrammingError when running `history` from telegram (dev-0.11.0)

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#571]
**Describe the bug**

When running `history` on telegram, the follow error occurs.

```
|2019-07-22 17:06:05,956 - hummingbot.client.hummingbot_application - ERROR - (sqlite3.ProgrammingError) SQLit
|e objects created in a thread can only be used in that same thread. The object was created in thread id 14008
|8285422976 and this is thread id 140086708520704.
|[SQL: SELECT "TradeFill".id AS "TradeFill_id", "TradeFill".config_file_path AS "TradeFill_config_file_path",
|"TradeFill".strategy AS "TradeFill_strategy", "TradeFill".market AS "TradeFill_market", "TradeFill".symbol AS
| "TradeFill_symbol", "TradeFill".base_asset AS "TradeFill_base_asset", "TradeFill".quote_asset AS "TradeFill_
|quote_asset", "TradeFill".timestamp AS "TradeFill_timestamp", "TradeFill".order_id AS "TradeFill_order_id", "
|TradeFill".trade_type AS "TradeFill_trade_type", "TradeFill".order_type AS "TradeFill_order_type", "TradeFill
|".price AS "TradeFill_price", "TradeFill".amount AS "TradeFill_amount", "TradeFill".trade_fee AS "TradeFill_t
|rade_fee", "TradeFill".exchange_trade_id AS "TradeFill_exchange_trade_id"
|FROM "TradeFill"
|WHERE "TradeFill".config_file_path = ? ORDER BY "TradeFill".timestamp DESC
| LIMIT ? OFFSET ?]
|[parameters: [{}]]
|
|(Background on this error at: http://sqlalche.me/e/f405) (See log file for stack trace dump)
```

On telegram, nothing is returned.  But the error above appears in Telegram.

However, running `history` from terminal is fine.

**Steps To Reproduce**

1. setup a bot with telegram
2. run `history` from telegram

**Screenshots**

**Release version**

`dev-0.11.0`

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by carlolm** [comment]
This also happens now when running `history` in the terminal.  This may be related or separate:

```
Traceback (most recent call last):
  File "pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
  File "/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/hummingbot/market/markets_recorder.py", line 181, in _did_create_order
    self.save_market_states(self._config_file_path, market, no_commit=True)
  File "/hummingbot/market/markets_recorder.py", line 123, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market)
  File "/hummingbot/market/markets_recorder.py", line 151, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3250, in one_or_none
    ret = list(self)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3322, in __iter__
    self.session._autoflush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1576, in _autoflush
    self.flush()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2458, in flush
    self._flush(objects)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2551, in _flush
    subtransactions=True
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 937, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 315, in _begin
    self._assert_active()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 294, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139874325751552 and this is thread id 139875980748160.
[SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, price, last_status, last_update_timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'amount': 160.0, 'price': 0.001176401276489903, 'strategy': 'pure_market_making', 'last_update_timestamp': 1563931318786, 'market': 'idex', 'id': 'buy-**QUOTE_BASE**-1563931318223381', 'last_status': 'BuyOrderCreated', 'symbol': '**QUOTE_BASE**', 'creation_timestamp': 1563931318786, 'order_type': 'LIMIT', 'base_asset': 'VIDT', 'config_file_path': 'conf_pure_market_making_strategy_0.yml', 'quote_asset': 'ETH'}]]
(Background on this error at: http://sqlalche.me/e/f405)
2019-07-24 22:22:41,631 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1564006961.0, "type": "OrderType.LIMIT", "symbol": "**QUOTE_BASE**", "amount": 240.0, "price": 0.001172476130770807, "order_id": "sell-**QUOTE_BASE**-1564006960199084", "event_name": "SellOrderCreatedEvent", "event_source": "idex"}
```

**Comment by yzhang1994** [comment]
Fixed.
