### ISSUE TITLE
[BUG] Errors while trying to connect Binance Api

### ISSUE THREAD

**Issue by vipasane** [CoinAlpha/hummingbot#575]
**Describe the bug**
Lines from the log:

binance.exceptions.BinanceWithdrawException: BinanceWithdrawException: API key does not exist
2019-07-22 17:32:39,166 - hummingbot.market.binance.binance_market - WARNING - Could not fetch new trading rules from Binance. Check network connection.
2019-07-22 17:32:39,534 - hummingbot.market.binance.binance_api_user_stream_data_source - ERROR - Unexpected error while maintaining the user event listen key. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/hummingbot/market/binance/binance_api_user_stream_data_source.py", line 90, in listen_for_user_stream
    self._current_listen_key = await self.get_listen_key()
  File "/hummingbot/market/binance/binance_api_user_stream_data_source.py", line 46, in get_listen_key
    raise IOError(f"Error fetching Binance user stream listen key. HTTP status is {response.status}.")
OSError: Error fetching Binance user stream listen key. HTTP status is 401.
2019-07-22 17:32:39,818 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.

**Configuration**
Strategy: pure_market_marking
Exchange: Binance
Correct API Key and Secret Key

**Release version**
Humminbot: 0.10.1
OS:  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Attachments**

[conf_pure_market_making_strategy_0.yml.txt](https://github.com/CoinAlpha/hummingbot/files/3418970/conf_pure_market_making_strategy_0.yml.txt)
[hummingbot_logs_2019-07-22-17-09-50.log](https://github.com/CoinAlpha/hummingbot/files/3418973/hummingbot_logs_2019-07-22-17-09-50.log)

discord username: vipasane
ETH address: 0x08d30F21c2d3dbEFA87634f14bFEE9F2c46ad53c

**Comment by vipasane** [comment]
Enabled Withdrawals in API settings as advised in Discord channel.
As a security feature Currently have two-factor authentication and whitelisted etherium wallet which is configured in hummingbot.
New log file attached.
[2019-07-23_after_enabling_withdraw.log](https://github.com/CoinAlpha/hummingbot/files/3421647/2019-07-23_after_enabling_withdraw.log)

**Comment by vipasane** [comment]
Those were from VM located in Azure made a another VM in AWS and with same configuration and getting same issues.
Logs and screenshots below
[hummingbot_logs_2019-07-25-20-23-02.log](https://github.com/CoinAlpha/hummingbot/files/3433190/hummingbot_logs_2019-07-25-20-23-02.log)
![status](https://user-images.githubusercontent.com/8975997/61906990-32af7d80-af35-11e9-8572-d3be1f371f1e.png)

**Comment by vipasane** [comment]
Re created Binance Api key & secret everything is now working like charm
