### ISSUE TITLE
[BUG] Incorrect "failed to cancel the following orders on binance" (orders were canceled)

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#576]
**Describe the bug**

When hitting `stop` or `exit`, bot says "Failed to cancel the following orders on binance".

When attempting to stop/exit, it shows this error:

```
2019-07-22 22:15:56,644 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
```

However, the orders were actually canceled and don't exist, so this error should not be coming up.  It also makes "exit -f" required.

After waiting for a while and trying `exit` again, it actually does so.

**Steps To Reproduce**

1. Was stress testing pure-mm, `multiple`: 10 orders on each side

**Screenshots**

**Release version**
`dev-0.11.0-

**Attachments**

Additional logs:

```
Traceback (most recent call last):
  File "binance_market.pyx", line 1065, in hummingbot.market.binance.binance_market.BinanceMarket.cancel_all
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "binance_market.pyx", line 1064, in hummingbot.market.binance.binance_market.BinanceMarket.cancel_all
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
2019-07-22 22:15:06,481 - hummingbot.market.binance.binance_market - WARNING - Failed to cancel order with Binance. Check API key and network connection.
2019-07-22 22:15:06,610 - hummingbot.data_feed.coin_gecko_data_feed - WARNING - Coin Gecko API request failed. Unable to get prices.
2019-07-22 22:15:56,143 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:15:56,144 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672001890", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2019-07-22 22:15:56,518 - hummingbot.market.binance.binance_market - NETWORK - Unexpected error cancelling orders.
Traceback (most recent call last):
  File "binance_market.pyx", line 1065, in hummingbot.market.binance.binance_market.BinanceMarket.cancel_all
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "binance_market.pyx", line 1064, in hummingbot.market.binance.binance_market.BinanceMarket.cancel_all
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
2019-07-22 22:15:56,518 - hummingbot.market.binance.binance_market - WARNING - Failed to cancel order with Binance. Check API key and network connection.
2019-07-22 22:15:56,644 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:15:57,146 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:15:57,649 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:15:58,150 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:15:58,653 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:15:59,154 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:15:59,656 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:16:00,158 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:42,565 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:42,566 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672002008", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2019-07-22 22:18:43,066 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:43,067 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672001986", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2019-07-22 22:18:43,568 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:43,569 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672002030", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2019-07-22 22:18:44,070 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:44,070 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672001746", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2019-07-22 22:18:44,571 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:44,572 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672001934", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2019-07-22 22:18:45,073 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:45,074 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672001843", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2019-07-22 22:18:45,574 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:45,575 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672001962", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2019-07-22 22:18:46,077 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error.
2019-07-22 22:18:46,078 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": NaN, "order_id": "buy-**BASEQUOTE**-1563833672001867", "event_name": "OrderCancelledEvent", "event_source": "binance"}
```

**Comment by hongson1981** [comment]
I got same error in version 0.11.1
[hummingbot_logs_2019-07-31-13-26-16.log](https://github.com/CoinAlpha/hummingbot/files/3452100/hummingbot_logs_2019-07-31-13-26-16.log)

**Comment by spmuppar** [comment]
I also got same error when running pure market making in XRPETH in binance

**Comment by yzhang1994** [comment]
Closing this as it is likely stale.

**Comment by globeone** [comment]
This is still an issue today. Pretty sure just adding a sleep(1) to each cancel would solve the problem as I suspect that the Binance API rate limit disconnects the bot for sending too many requests at once.
