### ISSUE TITLE
[BUG] Discovery fails when processing market pair

### ISSUE THREAD

**Issue by piotr-roslaniec** [CoinAlpha/hummingbot#721]
**Describe the bug**
Discovery strategy fails to produce results. It crashes with error:
`hummingbot.strategy.discovery.discovery - ERROR - Error processing market pair DiscoveryMarketPair(binance, coinbasepro)`

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Run Hummingbot from Docker image.
2. Set up your configuration using the file provided in attachments.
3. Start the bot using this command: `start`

**Screenshots**
1. Error visible in logs:
![image](https://user-images.githubusercontent.com/39299780/64066433-c4d43100-cc19-11e9-85bd-a954011b10db.png)
(repeats)
2. The output of `status` command:
![image](https://user-images.githubusercontent.com/39299780/64066327-77a38f80-cc18-11e9-8562-d7c9ab71ec7c.png)
(redacted)
![image](https://user-images.githubusercontent.com/39299780/64066319-65295600-cc18-11e9-952b-a53bfd8ab4bf.png)

**Release version**
0.13.0

**Attachments**
Strategy configuration:
```yml
primary_market: binance
secondary_market: coinbase_pro

target_profitability: 0.0
target_amount: .inf

target_symbol_1: []
target_symbol_2: []
equivalent_tokens:
- - USDT
  - USDC
  - USDS
  - DAI
  - PAX
  - TUSD
  - USD
- - ETH
  - WETH
- - BTC
  - WBTC
```
Relevant logs:
```
// redacted
2019-08-31 15:27:08,330 - hummingbot.market.binance.binance_order_book_tracker - INFO - Started order book tracking for BLZBTC.
2019-08-31 15:27:09,013 - hummingbot.strategy.discovery.discovery - ERROR - Error processing market pair DiscoveryMarketPair(binance, coinbase_pro).
Traceback (most recent call last):
  File "discovery.pyx", line 219, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.c_tick
  File "discovery.pyx", line 427, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.c_process_market_pair
  File "discovery.pyx", line 372, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.c_calculate_arbitrage_discovery
TypeError: Expected dict, got DataFrame
2019-08-31 15:27:10,020 - hummingbot.strategy.discovery.discovery - ERROR - Error processing market pair DiscoveryMarketPair(binance, coinbase_pro).
Traceback (most recent call last):
  File "discovery.pyx", line 219, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.c_tick
  File "discovery.pyx", line 427, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.c_process_market_pair
  File "discovery.pyx", line 372, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.c_calculate_arbitrage_discovery
// repeats
```
Please let me know what other information I should provide, if any.

**Comment by rennel-tabing** [comment]
I am able to reproduce the error using 0.13.0 and dev-0.14.0
[hummingbot_logs_2019-08-30-14-55-07.log](https://github.com/CoinAlpha/hummingbot/files/3562669/hummingbot_logs_2019-08-30-14-55-07.log)

**Comment by chowryan** [comment]
Fixed. https://github.com/CoinAlpha/hummingbot/pull/734

**Comment by piotr-roslaniec** [comment]
Thanks for looking into this.
My Ethereum Address: `0x1309B1AC45e76b9AD69CF80011919E15564C277F`
