### ISSUE TITLE
[BUG] Binance market connector loses orderbook object

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#730]
**Describe the bug**

Bot is currently running fine as expected, reporting errors found in the logs.

```
2019-08-31 08:18:12,001 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 270, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 375, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_execute_orders_proposal
AttributeError: 'NoneType' object has no attribute 'actions'
```

**Steps To Reproduce**

Run a normal pure-mm bot.

**Screenshots**

![image](https://user-images.githubusercontent.com/50150287/64198294-8f01a780-ceba-11e9-8e0b-47e7b46f892b.png)

**Release version**

version: dev-0.14.0
commit: "126d5f0c4058bbf0d9fadea117f2d5c9e5648ac3"
date: "2019-08-27T00:47:47Z"

**Attachments**

[hummingbot_logs_2019-08-31-02-17-29.zip](https://github.com/CoinAlpha/hummingbot/files/3570877/hummingbot_logs_2019-08-31-02-17-29.zip)

**Comment by veecos2** [comment]
From what we can initially observe, this happens very infrequently.

**Comment by chowryan** [comment]
ive seen this occasionally too. think its a race condition bug with kill switch @yzhang1994

**Comment by chowryan** [comment]
fixed https://github.com/CoinAlpha/hummingbot/pull/744
