### ISSUE TITLE
[BUG] Connection issues in Binance market

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#739]
**Describe the bug**

Bot is running fine as expected, reporting errors found in logs.

```
2019-09-04 12:26:00,039 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
2019-09-04 12:26:00,039 - hummingbot.market.binance.binance_market - NETWORK - Error fetching trades update for the order ONEUSDT: .
2019-09-04 12:26:00,039 - hummingbot.market.binance.binance_market - WARNING - Failed to fetch trade update for ONEUSDT.
2019-09-04 12:26:00,116 - hummingbot.market.binance.binance_market - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "binance_market.pyx", line 700, in hummingbot.market.binance.binance_market.BinanceMarket._status_polling_loop
  File "binance_market.pyx", line 488, in _update_order_status
AttributeError: 'TimeoutError' object has no attribute 'code'
2019-09-04 12:26:00,117 - hummingbot.market.binance.binance_market - WARNING - Could not fetch account updates from Binance. Check API key and network connection.

2019-09-04 14:02:09,114 - hummingbot.core.event.event_reporter - EVENT_LOG - {"type": "OrderType.LIMIT", "symbol": "ONEUSDT", "amount": 1462.0, "price": 0.00856, "order_id": "buy-ONEUSDT-1567605728001723", "event_name": "BuyOrderCreatedEvent", "event_source": "binance", "ts": 1567605729.0}
2019-09-04 14:02:21,104 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
2019-09-04 14:02:22,107 - hummingbot.market.binance.binance_market - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "binance_market.pyx", line 700, in hummingbot.market.binance.binance_market.BinanceMarket._status_polling_loop
  File "binance_market.pyx", line 488, in _update_order_status
AttributeError: 'ConnectionError' object has no attribute 'code'
2019-09-04 14:02:22,107 - hummingbot.market.binance.binance_market - WARNING - Could not fetch account updates from Binance. Check API key and network connection.
```

```
2019-09-04 13:39:50,030 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
2019-09-04 13:39:50,073 - hummingbot.market.binance.binance_market - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/conda/envs/hummingbot/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/conda/envs/hummingbot/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/envs/hummingbot/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/conda/envs/hummingbot/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 309, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/conda/envs/hummingbot/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/conda/envs/hummingbot/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/envs/hummingbot/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/conda/envs/hummingbot/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 309, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "binance_market.pyx", line 700, in hummingbot.market.binance.binance_market.BinanceMarket._status_polling_loop
  File "binance_market.pyx", line 284, in _update_balances
  File "binance_market.pyx", line 263, in query_api
  File "binance_market.pyx", line 265, in hummingbot.market.binance.binance_market.BinanceMarket.query_api
  File "binance_market.pyx", line 255, in schedule_async_call
  File "/hummingbot/core/utils/async_call_scheduler.py", line 115, in schedule_async_call
    return await fut
  File "/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/opt/conda/envs/hummingbot/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 1563, in get_account
    return self._get('account', True, data=params)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 207, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 181, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/binance/client.py", line 175, in _request
    response = getattr(self.session, method)(uri, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
2019-09-04 13:39:50,075 - hummingbot.market.binance.binance_market - WARNING - Could not fetch account updates from Binance. Check API key and network connection.
2019-09-04 13:39:51,535 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
```

**Steps To Reproduce**

Run a normal pure-mm bot.

**Release version**

version: dev-0.14.0
commit: "126d5f0c4058bbf0d9fadea117f2d5c9e5648ac3"
date: "2019-08-27T00:47:47Z"

**Attachments**

[hummingbot_logs_2019-09-03_19-00-00.log](https://github.com/CoinAlpha/hummingbot/files/3575857/hummingbot_logs_2019-09-03_19-00-00.log)

**Comment by veecos2** [comment]
Following issues were found: API call error: HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10). API call error: ('Connection aborted.', OSError("(104, 'ECONNRESET')",)). Market has recovered from it and we did not find major issues after connection was re-established.

**Comment by michaelc9** [comment]
@dennisocana This is an issue from the Binance API. 
Closing the ticket. Since Hummingbot reconnected after API issues, it is working as expected.
