### ISSUE TITLE
[BUG] Nonce issues in idex market

### ISSUE THREAD

**Issue by veecos2** [CoinAlpha/hummingbot#749]
**Describe the bug**
// A clear and concise description of what the bug is.
Getting errors that 'Nonce is too low. Please refresh and try again.'

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by dennisocana** [comment]
Bot is currently running fine. Errors were found in previous logs.

```
2019-09-05 19:57:26,001 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ETH_[BASE]) Creating limit bid orders for   Bids (Size,Price) to be placed at: ['10.000000000000000000 [BASE] @  0.032475449999995076 ETH', '15.000000000000000000 [BASE] @  0.032150695499995129 ETH'] [clock=2019-09-05 19:57:26+00:00]
2019-09-05 19:57:26,210 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error: Error fetching data from https://api.idex.market/order. HTTP status is 400 - {'error': 'Nonce too low. Please refresh and try again.'}
2019-09-05 19:57:26,211 - hummingbot.market.idex.idex_market - NETWORK - Error submitting buy order to IDEX for 10.0 ETH_[BASE].
Traceback (most recent call last):
  File "idex_market.pyx", line 726, in hummingbot.market.idex.idex_market.IDEXMarket.execute_buy
  File "idex_market.pyx", line 670, in post_limit_order
  File "idex_market.pyx", line 444, in _sequential_api_request
  File "idex_market.pyx", line 454, in hummingbot.market.idex.idex_market.IDEXMarket._sequential_api_request
  File "/hummingbot/core/utils/async_call_scheduler.py", line 115, in schedule_async_call
    return await fut
  File "/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "idex_market.pyx", line 418, in _api_request
  File "idex_market.pyx", line 427, in hummingbot.market.idex.idex_market.IDEXMarket._api_request
OSError: Error fetching data from https://api.idex.market/order. HTTP status is 400 - {'error': 'Nonce too low. Please refresh and try again.'}
2019-09-05 19:57:26,211 - hummingbot.market.idex.idex_market - WARNING - Failed to submit buy order to IDEX: Error fetching data from https://api.idex.market/order. HTTP status is 400 - {'error': 'Nonce too low. Please refresh and try again.'}
2019-09-05 19:57:26,414 - hummingbot.core.utils.async_call_scheduler - WARNING - API call error: Error fetching data from https://api.idex.market/order. HTTP status is 400 - {'error': 'Nonce too low. Please refresh and try again.'}
2019-09-05 19:57:26,415 - hummingbot.market.idex.idex_market - NETWORK - Error submitting buy order to IDEX for 15.0 ETH_[BASE].
Traceback (most recent call last):
  File "idex_market.pyx", line 726, in hummingbot.market.idex.idex_market.IDEXMarket.execute_buy
  File "idex_market.pyx", line 670, in post_limit_order
  File "idex_market.pyx", line 444, in _sequential_api_request
  File "idex_market.pyx", line 454, in hummingbot.market.idex.idex_market.IDEXMarket._sequential_api_request
  File "/hummingbot/core/utils/async_call_scheduler.py", line 115, in schedule_async_call
    return await fut
  File "/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "idex_market.pyx", line 418, in _api_request
  File "idex_market.pyx", line 427, in hummingbot.market.idex.idex_market.IDEXMarket._api_request
OSError: Error fetching data from https://api.idex.market/order. HTTP status is 400 - {'error': 'Nonce too low. Please refresh and try again.'}
2019-09-05 19:57:26,415 - hummingbot.market.idex.idex_market - WARNING - Failed to submit buy order to IDEX: Error fetching data from https://api.idex.market/order. HTTP status is 400 - {'error': 'Nonce too low. Please refresh and try again.'}
```

Test bot is set up in `test-release.hummingbot.io`.
```
maker_market: idex
maker_market_symbol: ETH_[BASE]
order_amount: 10
cancel_order_wait_time: 45.0
bid_place_threshold: 0.015
ask_place_threshold: 0.015
mode: multiple
number_of_orders: 2
order_start_size: 10
order_step_size: 5.0
order_interval_percent: 0.01
inventory_skew_enabled: false
inventory_target_base_percent: 0.01
```

version: `0.13.0`

"branch": "master",
"commit": "7ae2c7cc04f0bfdb2838371450b838872db314c9",
"date": "2019-08-28T18:30:46Z",

[id_qnt-eth.log](https://github.com/CoinAlpha/hummingbot/files/3585646/id_qnt-eth.log)

**Comment by chowryan** [comment]
this is an issue on their end. its also relatively infrequent (twice in 24 hours) and refreshing orders every minute.
