### ISSUE TITLE
[BUG] Failed to submit cancel orders in Huobi

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#750]
**Describe the bug**

Previous logs show multiple instances of two different OSErrors. There were orders stuck that failed to cancel.

```
2019-09-05 18:04:31,258 - hummingbot.market.huobi.huobi_market - NETWORK - Error submitting sell LIMIT order to Huobi for 19.2862 [BASE][QUOTE] 0.5582.
Traceback (most recent call last):
  File "huobi_market.pyx", line 643, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_sell
  File "huobi_market.pyx", line 534, in place_order
  File "huobi_market.pyx", line 247, in _api_request
  File "huobi_market.pyx", line 254, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
OSError: Error fetching data from https://api.huobi.pro/v1/order/orders/place. HTTP status is 429.
2019-09-05 18:04:31,258 - hummingbot.market.huobi.huobi_market - WARNING - Failed to submit sell order to Huobi. Check API key and network connection.
```
```
2019-09-06 03:20:12,258 - hummingbot.market.huobi.huobi_market - NETWORK - Failed to cancel order buy-[BASE][QUOTE]-1567739911001697: Error reading data from https://api.huobi.pro/v1/order/orders/47109441452/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None}.
Traceback (most recent call last):
  File "huobi_market.pyx", line 699, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_cancel
  File "huobi_market.pyx", line 247, in _api_request
  File "huobi_market.pyx", line 262, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
OSError: Error reading data from https://api.huobi.pro/v1/order/orders/47109441452/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None}.
2019-09-06 03:20:12,258 - hummingbot.market.huobi.huobi_market - WARNING - Failed to cancel the order buy-[BASE][QUOTE]-1567739911001697 on Huobi. Check API key and network connection.
```

**Steps To Reproduce**

Test bot is set up in test-development.hummingbot.io.

The bot is being updated to the latest development branch daily. Prior to today's update, previously created orders were stuck. I shut down the bot using `exit` command, did an update -> restart and the bot seem to work normally again. Although the logs (second attached) shows few of the same intermittent OSErrors.

```
maker_market: huobi
maker_market_symbol: [basequote]
order_amount: 1.0
cancel_order_wait_time: 40.0
bid_place_threshold: 0.0025
ask_place_threshold: 0.0025
mode: multiple
number_of_orders: 2
order_start_size: 20.0
order_step_size: 10.0
order_interval_percent: 0.005
inventory_skew_enabled: true
inventory_target_base_percent: 0.5
```

**Release version**

"version": "dev-0.14.0",
"commit": "7ac989dc132fee287c1f9da9c31704a833ae8bef",
"date": "2019-09-05T23:06:18Z"

**Attachments**

[hummingbot_logs_2019-09-05-17-54-24.log](https://github.com/CoinAlpha/hummingbot/files/3585561/hummingbot_logs_2019-09-05-17-54-24.log)
[hummingbot_logs_2019-09-06-18-51-49.log](https://github.com/CoinAlpha/hummingbot/files/3585564/hummingbot_logs_2019-09-06-18-51-49.log)

**Comment by dennisocana** [comment]
```
2019-09-06 18:57:31,002 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base][quote]) Cancelling the limit order sell-[base][quote]-1567796211002823. [clock=2019-09-06 18:57:31+00:00]
2019-09-06 18:57:31,276 - hummingbot.market.huobi.huobi_market - NETWORK - Failed to cancel order sell-[base][quote]-1567796211002823: Error fetching data from https://api.huobi.pro/v1/order/orders/47187247670/submitcancel. HTTP status is 429.
Traceback (most recent call last):
  File "huobi_market.pyx", line 699, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_cancel
  File "huobi_market.pyx", line 247, in _api_request
  File "huobi_market.pyx", line 254, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
OSError: Error fetching data from https://api.huobi.pro/v1/order/orders/47187247670/submitcancel. HTTP status is 429.
2019-09-06 18:57:31,277 - hummingbot.market.huobi.huobi_market - WARNING - Failed to cancel the order sell-[base][quote]-1567796211002823 on Huobi. Check API key and network connection.
```

After another attempt the order was succesfully cancelled:

```
2019-09-06 18:58:32,001 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base][quote]) Cancelling the limit order sell-[base][quote]-1567796211002823. [clock=2019-09-06 18:58:32+00:00]
2019-09-06 18:58:40,173 - hummingbot.market.huobi.huobi_market - INFO - The market order sell-[base][quote]-1567796211002823 has been cancelled according to order status API.
```

**Comment by dennisocana** [comment]
Sell order ID 1567800771002153 failed to cancel at [2019-09-06 20:14]:

```
2019-09-06 20:12:51,307 - hummingbot.core.event.event_reporter - EVENT_LOG - {"type": "OrderType.LIMIT", "symbol": "[base][quote]", "amount": 32.2762, "price": 0.5488, "order_id": "sell-[base][quote]-1567800771002277", "event_name": "SellOrderCreatedEvent", "event_source": "huobi", "ts": 1567800771.0}
2019-09-06 20:12:51,373 - hummingbot.market.huobi.huobi_market - INFO - Created OrderType.LIMIT sell order sell-[base][quote]-1567800771002153 for 21.5173 [base][quote].

2019-09-06 20:14:32,001 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base][quote]) Cancelling the limit order sell-[base][quote]-1567800771002153. [clock=2019-09-06 20:14:32+00:00]
2019-09-06 20:14:32,263 - hummingbot.market.huobi.huobi_market - NETWORK - Failed to cancel order sell-[base][quote]-1567800771002153: Error reading data from https://api.huobi.pro/v1/order/orders/47194492154/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None}.
Traceback (most recent call last):
  File "huobi_market.pyx", line 699, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_cancel
  File "huobi_market.pyx", line 247, in _api_request
  File "huobi_market.pyx", line 262, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
OSError: Error reading data from https://api.huobi.pro/v1/order/orders/47194492154/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None}.
2019-09-06 20:14:32,263 - hummingbot.market.huobi.huobi_market - WARNING - Failed to cancel the order sell-[base][quote]-1567800771002153 on Huobi. Check API key and network connection.

2019-09-06 20:15:33,001 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base][quote]) Cancelling the limit order sell-[base][quote]-1567800771002153. [clock=2019-09-06 20:15:33+00:00]
2019-09-06 20:15:33,241 - hummingbot.market.huobi.huobi_market - NETWORK - Failed to cancel order sell-[base][quote]-1567800771002153: Error reading data from https://api.huobi.pro/v1/order/orders/47194492154/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None}.
Traceback (most recent call last):
  File "huobi_market.pyx", line 699, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_cancel
  File "huobi_market.pyx", line 247, in _api_request
  File "huobi_market.pyx", line 262, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
OSError: Error reading data from https://api.huobi.pro/v1/order/orders/47194492154/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None}.
2019-09-06 20:15:33,242 - hummingbot.market.huobi.huobi_market - WARNING - Failed to cancel the order sell-[base][quote]-1567800771002153 on Huobi. Check API key and network connection.
```

Hummingbot attempting to cancel the order multiple times and as of [2019-09-07 22:30] the order is still stuck. Probably because of this, the bot has stopped creating new sell orders.

<img width="947" alt="putty_W90NR514O2" src="https://user-images.githubusercontent.com/50150287/64480901-ed54c000-d203-11e9-9bea-4bdc740b91cc.png">

<img width="960" alt="chrome_ifZRdcPH9K" src="https://user-images.githubusercontent.com/50150287/64480902-f6459180-d203-11e9-845c-bfe0be2c2879.png">

In Huobi, the order that failed to cancel is not appearing under open orders.

<img width="534" alt="chrome_mosIOJkEHx" src="https://user-images.githubusercontent.com/50150287/64480948-feea9780-d204-11e9-9cc5-efc3e55fd81e.png">

Latest log file: [hummingbot_logs_2019-09-06-18-51-49.log](https://github.com/CoinAlpha/hummingbot/files/3587113/hummingbot_logs_2019-09-06-18-51-49.log)

**Comment by chowryan** [comment]
> ```
> 2019-09-06 18:57:31,002 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base][quote]) Cancelling the limit order sell-[base][quote]-1567796211002823. [clock=2019-09-06 18:57:31+00:00]
> 2019-09-06 18:57:31,276 - hummingbot.market.huobi.huobi_market - NETWORK - Failed to cancel order sell-[base][quote]-1567796211002823: Error fetching data from https://api.huobi.pro/v1/order/orders/47187247670/submitcancel. HTTP status is 429.
> Traceback (most recent call last):
>   File "huobi_market.pyx", line 699, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_cancel
>   File "huobi_market.pyx", line 247, in _api_request
>   File "huobi_market.pyx", line 254, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
> OSError: Error fetching data from https://api.huobi.pro/v1/order/orders/47187247670/submitcancel. HTTP status is 429.
> 2019-09-06 18:57:31,277 - hummingbot.market.huobi.huobi_market - WARNING - Failed to cancel the order sell-[base][quote]-1567796211002823 on Huobi. Check API key and network connection.
> ```
> 
> After another attempt the order was succesfully cancelled:
> 
> ```
> 2019-09-06 18:58:32,001 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base][quote]) Cancelling the limit order sell-[base][quote]-1567796211002823. [clock=2019-09-06 18:58:32+00:00]
> 2019-09-06 18:58:40,173 - hummingbot.market.huobi.huobi_market - INFO - The market order sell-[base][quote]-1567796211002823 has been cancelled according to order status API.
> ```

this is expected behavior

**Comment by dennisocana** [comment]
Version: dev-0.15.0
Image timestamp: 2019-09-11T00:52:56Z

[hummingbot_logs_2019-09-11-02-56-13.log](https://github.com/CoinAlpha/hummingbot/files/3603116/hummingbot_logs_2019-09-11-02-56-13.log)

```
2019-09-11 06:53:42,000 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base][quote]) Cancelling the limit order buy-[base][quote]-1568184721002555. [clock=2019-09-11 06:53:42+00:00]
2019-09-11 06:53:42,248 - hummingbot.market.huobi.huobi_market - NETWORK - Failed to cancel order buy-[base][quote]-1568184721002555: Error reading data from https://api.huobi.pro/v1/order/orders/47727716762/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None}.
Traceback (most recent call last):
  File "huobi_market.pyx", line 698, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_cancel
  File "huobi_market.pyx", line 247, in _api_request
  File "huobi_market.pyx", line 262, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
OSError: Error reading data from https://api.huobi.pro/v1/order/orders/47727716762/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None}.
2019-09-11 06:53:42,249 - hummingbot.market.huobi.huobi_market - WARNING - Failed to cancel the order buy-[base][quote]-1568184721002555 on Huobi. Check API key and network connection.
```

**Comment by chowryan** [comment]
an order got stuck again?

**Comment by dennisocana** [comment]
@chowryan yes it did. The buy order is stuck in Hummingbot but not in Huobi, which prevents the bot from creating new buy orders.

<img width="476" alt="n96IrwDWKH" src="https://user-images.githubusercontent.com/50150287/64745252-b94a0980-d539-11e9-9f36-35fdcb9284b3.png">
<img width="683" alt="putty_ZUcdcjEtOo" src="https://user-images.githubusercontent.com/50150287/64745257-bc44fa00-d539-11e9-97c6-f12a8e592243.png">
<img width="683" alt="q14OjTilQs" src="https://user-images.githubusercontent.com/50150287/64745258-bd762700-d539-11e9-993c-4201db9be135.png">

**Comment by dennisocana** [comment]
@chowryan same issue on dev-0.16.0

New log file: 
[hummingbot_logs_2019-09-24-01-16-35.log](https://github.com/CoinAlpha/hummingbot/files/3650358/hummingbot_logs_2019-09-24-01-16-35.log)

```
"branch": "development",
"commit": "69d71a42e1ad42c72320360d1fd4dc78f8aeae4a",
"date": "2019-09-23T17:57:25Z",
```

**Comment by dennisocana** [comment]
Cross-exchange strategy log file
[hummingbot_logs_2019-09-27-16-20-43.log](https://github.com/CoinAlpha/hummingbot/files/3664976/hummingbot_logs_2019-09-27-16-20-43.log)

**Comment by dennisocana** [comment]
After further observing the issue, it happens when an order is partially filled.

![1_a](https://user-images.githubusercontent.com/50150287/66160272-5b05d780-e65c-11e9-8fce-964f60dd8a0e.jpg)

Sell orders were being canceled or replaced when completely filled until this sell order was filled partially.
```
2019-10-01 12:34:31,283 - hummingbot.market.huobi.huobi_market - INFO - Created OrderType.LIMIT sell order sell-[base]usdt-1569933271002762 for 25.4639 [base]usdt.
2019-10-01 12:34:31,295 - hummingbot.core.event.event_reporter - EVENT_LOG - {"type": "OrderType.LIMIT", "symbol": "[base]usdt", "amount": 25.4639, "price": 0.4723, "order_id": "sell-[base]usdt-1569933271002762", "event_name": "SellOrderCreatedEvent", "event_source": "huobi", "ts": 1569933271.0}
2019-10-01 12:34:40,192 - hummingbot.market.huobi.huobi_market - INFO - Filled 4.820000000000000000 out of 25.4639 of the order sell-[base]usdt-1569933271002762.
2019-10-01 12:34:40,193 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base]usdt) Maker sell order of 4.82 [base] filled. [clock=2019-10-01 12:34:40+00:00]
2019-10-01 12:34:40,229 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "sell-[base]usdt-1569933271002762", "symbol": "[base]usdt", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT", "price": 0.4723, "amount": 4.82, "trade_fee": [0.002, []], "exchange_trade_id": "", "event_name": "OrderFilledEvent", "event_source": "huobi", "ts": 1569933280.0}
2019-10-01 12:35:11,002 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base]usdt) Cancelling the limit order sell-[base]usdt-1569933271002762. [clock=2019-10-01 12:35:11+00:00]
2019-10-01 12:36:12,001 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base]usdt) Cancelling the limit order sell-[base]usdt-1569933271002762. [clock=2019-10-01 12:36:12+00:00]
2019-10-01 12:36:12,241 - hummingbot.market.huobi.huobi_market - ERROR - Error received from https://api.huobi.pro/v1/order/orders/50251325509/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None, 'order-state': 5}.
```

![2](https://user-images.githubusercontent.com/50150287/66160281-635e1280-e65c-11e9-9797-5483b5ae87f2.jpg)
![3](https://user-images.githubusercontent.com/50150287/66160290-678a3000-e65c-11e9-8b41-f2c9b9a9289f.jpg)

Same with this buy order.
```
2019-10-01 12:42:51,002 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base]usdt) Creating limit bid orders at (Size, Price): ['14.3799 [base], 0.4692 usdt', '21.5699 [base], 0.4669 usdt'] [clock=2019-10-01 12:42:51+00:00]
2019-10-01 12:42:51,284 - hummingbot.market.huobi.huobi_market - INFO - Created OrderType.LIMIT buy order buy-[base]usdt-1569933771003100 for 14.3799 [base]usdt.
2019-10-01 12:42:51,295 - hummingbot.core.event.event_reporter - EVENT_LOG - {"type": "OrderType.LIMIT", "symbol": "[base]usdt", "amount": 14.3799, "price": 0.4692, "order_id": "buy-[base]usdt-1569933771003100", "event_name": "BuyOrderCreatedEvent", "event_source": "huobi", "ts": 1569933771.0}
2019-10-01 12:43:00,349 - hummingbot.market.huobi.huobi_market - INFO - Filled 13.718800000000000000 out of 14.3799 of the order buy-[base]usdt-1569933771003100.
2019-10-01 12:43:00,350 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base]usdt) Maker buy order of 13.7188 [base] filled. [clock=2019-10-01 12:43:00+00:00]
2019-10-01 12:43:00,387 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "buy-[base]usdt-1569933771003100", "symbol": "[base]usdt", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": 0.4692, "amount": 13.7188, "trade_fee": [0.002, []], "exchange_trade_id": "", "event_name": "OrderFilledEvent", "event_source": "huobi", "ts": 1569933780.0}
2019-10-01 12:44:32,002 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - ([base]usdt) Cancelling the limit order buy-[base]usdt-1569933771003100. [clock=2019-10-01 12:44:32+00:00]
2019-10-01 12:44:32,245 - hummingbot.market.huobi.huobi_market - ERROR - Error received from https://api.huobi.pro/v1/order/orders/50252206946/submitcancel. Response is {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None, 'order-state': 5}.
```

![4](https://user-images.githubusercontent.com/50150287/66160298-6c4ee400-e65c-11e9-9b85-b43db878a31d.jpg)

Log file: 
[hummingbot_logs_2019-10-01-04-31-39.log](https://github.com/CoinAlpha/hummingbot/files/3687766/hummingbot_logs_2019-10-01-04-31-39.log)

**Comment by dennisocana** [comment]
Issue still ongoing

![image](https://user-images.githubusercontent.com/50150287/66822793-88655600-ef77-11e9-8d6d-b736a8e6e7c3.png)
