### ISSUE TITLE
[BUG] Bamboo Relay unexpected error with WebSocket connection

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#751]
**Describe the bug**

Bot is currently running fine. Opening a GitHub issue for the errors found in previous logs. This happened twice on two different timestamps.

```
2019-09-06 00:15:01,528 - hummingbot.market.bamboo_relay.bamboo_relay_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/hummingbot/market/bamboo_relay/bamboo_relay_api_order_book_data_source.py", line 214, in listen_for_order_book_diffs
    async with websockets.connect(WS_URL) as ws:
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/py35/client.py", line 12, in __await_impl__
    transport, protocol = await self._creating_connection
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 783, in create_connection
    raise exceptions[0]
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 770, in create_connection
    yield from self.sock_connect(sock, address)
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('188.166.94.193', 443)
```

```
2019-09-06 06:15:02,446 - hummingbot.market.bamboo_relay.bamboo_relay_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/hummingbot/market/bamboo_relay/bamboo_relay_api_order_book_data_source.py", line 214, in listen_for_order_book_diffs
    async with websockets.connect(WS_URL) as ws:
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/py35/client.py", line 12, in __await_impl__
    transport, protocol = await self._creating_connection
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 783, in create_connection
    raise exceptions[0]
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 770, in create_connection
    yield from self.sock_connect(sock, address)
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('188.166.94.193', 443)
```

**Steps To Reproduce**

Test bot is set up in `test-development.hummingbot.io`.

```
maker_market: bamboo_relay
taker_market: binance
maker_market_symbol: [BASE]-[QUOTE]
taker_market_symbol: [BASEQUOTE]
min_profitability: 0.002
trade_size_override: 0.0
top_depth_tolerance:

- -
    ^.+(USDT|USDC|USDS|DAI|PAX|TUSD)$
  - 0
- - ^.+ETH$
  - 0
- - ^.+BTC$
  - 0

active_order_canceling: true
cancel_order_threshold: -0.025
limit_order_min_expiration: 60.0
```

**Release version**

"version": "dev-0.14.0",
"commit": "7ac989dc132fee287c1f9da9c31704a833ae8bef",
"date": "2019-09-05T23:06:18Z"

**Attachments**

[hummingbot_logs_2019-09-05-17-54-25.log](https://github.com/CoinAlpha/hummingbot/files/3585605/hummingbot_logs_2019-09-05-17-54-25.log)

**Comment by dennisocana** [comment]
Confirmed with Joshua that these errors result to the server restarting at least twice a day which will drop WebSocket connections. This shows up in the logs a few times in a day transiently before Hummingbot just reconnects. Specifically its nginx that restarts and takes ~1 second when it happens.

If it ends up being minutes, then there may be a problem. If it's just for a few seconds then it's almost 100% the restarts.
