### ISSUE TITLE
[BUG] Bounty Status server error

### ISSUE THREAD

**Issue by SasaValencia** [CoinAlpha/hummingbot#754]
**Describe the bug**
// A clear and concise description of what the bug is.
Error: Bounty reset aborted

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
open hummingbot and run bounty --status

Here are the steps to reproduce the issue (see attachments in the section below):
open hummingbot and run bounty --status
...

**Screenshots**
![image](https://user-images.githubusercontent.com/55037772/64481737-9a055200-d1b0-11e9-81e7-077bf36102e6.png)

// If applicable, add screenshots to help explain your problem.

**Release version**
// 13

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty) 0xd8fbeb0f4d919e7091fafd9a432a3ad4cb63743b

**Comment by rennel-tabing** [comment]
The error occurs when running the `bounty --restore-id` and after entering the verification code.

**Comment by rennel-tabing** [comment]
Logs is as follows
```2019-09-08 01:21:29,699 - hummingbot.client.liquidity_bounty.bounty_utils - ERROR - Error fetching filled volume metrics: 
Traceback (most recent call last):
  File "/hummingbot/client/liquidity_bounty/bounty_utils.py", line 340, in fetch_filled_volume_metrics
    results: Dict[str, Any] = await self.authenticated_request("GET", url, json=data)
  File "/hummingbot/client/liquidity_bounty/bounty_utils.py", line 285, in authenticated_request
    assert client_id is not None
AssertionError
```

**Comment by dennisocana** [comment]
Same with https://github.com/CoinAlpha/hummingbot/issues/689, probably related to the server being down during that time. Are you still experiencing this issue?

**Comment by rennel-tabing** [comment]
I just tested the command and the output error remains the same as of this writing.

**Comment by chowryan** [comment]
@rennel-tabing I'm not sure how your issue is related to @SasaValencia 's error. Seems like @SasaValencia  is just having issues running `bounty --status`?

**Comment by rennel-tabing** [comment]
I am assuming there was a mistake when the subject was submitted as I can only reproduce the error that was described using the `bounty --restore-id` command

**Comment by dennisocana** [comment]
@chowryan the error happens on all bounty-related commands.

**Comment by dennisocana** [comment]
@chowryan I think the error happens on both `status` and `restore-id`. Sometimes it's either one or the other.

**Comment by znerol19619** [comment]
I tried running the command ``bounty --restore-id`` and got the same error after typing in the verification code. 
```diff
---"Bounty reset aboted:Liquidity bounty server error. Server responded with status 500"
```

**Comment by moraliang** [comment]
Sent you 0.1 ETH bounty reward. @SasaValencia
