### ISSUE TITLE
[BUG] Discovery -  Error parsing symbol BTTTRX: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#755]
**Describe the bug**
// A clear and concise description of what the bug is.
 Error parsing symbol BTTTRX: 'NoneType' object has no attribute 'group'

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
test bots in support-patrick.hummingbot.io

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...

```
#####################################
###   Discovery strategy config   ###
#####################################

# The following configuations are only required for the
# discovery strategy

# Exchange and token parameters
primary_market: binance
secondary_market: coinbase_pro

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
target_profitability: 0.0
target_amount: .inf

target_symbol_1: []
target_symbol_2: []
equivalent_tokens:
- - USDT
  - USDC
  - USDS
  - DAI
  - PAX
  - TUSD
  - USD
- - ETH
  - WETH
- - BTC
  - WBTC
# For more detailed information, see:
# https://docs.hummingbot.io/strategies/discovery/
```

**Screenshots**
// If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/54516858/64498005-d934bf80-d2e4-11e9-873b-53704aa0193e.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
tested on both 0.13.0 and dev-0.14.0

```
                "branch": "master",
                "commit": "15be81297619da700c505bbb8e503ebdb38abd6d",
                "date": "2019-08-26T19:04:12Z",

                "branch": "development",
                "commit": "c27ee9a80454afc8354eab7e9c18a9112245b98d",
                "date": "2019-08-29T00:05:48Z",
```
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
```
2019-09-09 01:01:59,939 - hummingbot.notifier.telegram_notifier - INFO - Telegram is listening...
2019-09-09 01:02:01,081 - hummingbot.data_feed.coin_gecko_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-09-09 01:02:01,978 - hummingbot.data_feed.coin_cap_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-09-09 01:02:15,047 - hummingbot.client.hummingbot_application - ERROR - Error initializing strategy.
Traceback (most recent call last):
  File "binance_market.pyx", line 194, in hummingbot.market.binance.binance_market.BinanceMarket.split_symbol
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 31, in start
    target_base_quote_1: List[Tuple[str, str]] = self._initialize_market_assets(market_1, target_symbol_1)
  File "/hummingbot/client/hummingbot_application.py", line 206, in _initialize_market_assets
    market_symbols: List[Tuple[str, str]] = [market.split_symbol(symbol) for symbol in symbols]
  File "/hummingbot/client/hummingbot_application.py", line 206, in <listcomp>
    market_symbols: List[Tuple[str, str]] = [market.split_symbol(symbol) for symbol in symbols]
  File "binance_market.pyx", line 196, in hummingbot.market.binance.binance_market.BinanceMarket.split_symbol
ValueError: Error parsing symbol BTTTRX: 'NoneType' object has no attribute 'group'
```

**Comment by PtrckM** [comment]
test in dev-0.15.0 support-patrick.hummingbot.io

```
                "branch": "development",
                "commit": "c7086e480b4ffec52b95b948571d8ba9b4b76b7a",
                "date": "2019-09-09T18:29:48Z",
```
logs

```
2019-09-10 01:10:31,179 - hummingbot.data_feed.coin_gecko_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-09-10 01:10:31,793 - hummingbot.data_feed.coin_cap_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-09-10 01:10:35,889 - hummingbot.client.hummingbot_application - ERROR - Error initializing strategy.
Traceback (most recent call last):
  File "binance_market.pyx", line 194, in hummingbot.market.binance.binance_market.BinanceMarket.split_symbol
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 25, in start
    target_base_quote_1: List[Tuple[str, str]] = self._initialize_market_assets(market_1, target_symbol_1)
  File "/hummingbot/client/hummingbot_application.py", line 208, in _initialize_market_assets
    market_symbols: List[Tuple[str, str]] = [market.split_symbol(symbol) for symbol in symbols]
  File "/hummingbot/client/hummingbot_application.py", line 208, in <listcomp>
    market_symbols: List[Tuple[str, str]] = [market.split_symbol(symbol) for symbol in symbols]
  File "binance_market.pyx", line 196, in hummingbot.market.binance.binance_market.BinanceMarket.split_symbol
ValueError: Error parsing symbol BTTTRX: 'NoneType' object has no attribute 'group'
```

**Comment by PtrckM** [comment]
this exchange/token conf facing similar problem 
``
Error parsing symbol BTTTRX: 'NoneType' object has no attribute 'group' 
``

```
# Exchange and token parameters
primary_market: huobi
secondary_market: binance
```

``
Version: 0.14.0 
``

**Comment by chowryan** [comment]
this issue is fixed in the latest dev branch (was missing TRX quote symbol in binance)
