### ISSUE TITLE
[BUG] Quantization issues in Radar relay market

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#775]
**Describe the bug**

Bot is currently running fine as expected, reporting errors found in logs and tracking.

Start: `2019-09-11 15:56:01,001`
End: `2019-09-11 16:22:00,002`

```
2019-09-11 15:56:01,001 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Unknown error while generating order proposals.
Traceback (most recent call last):
  File "pure_market_making_v2.pyx", line 262, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 288, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_get_orders_proposal_for_market_info
  File "constant_multiple_spread_pricing_delegate.pyx", line 48, in hummingbot.strategy.pure_market_making.constant_multiple_spread_pricing_delegate.ConstantMultipleSpreadPricingDelegate.c_get_order_price_proposal
  File "market_base.pyx", line 192, in hummingbot.market.market_base.MarketBase.c_quantize_order_price
  File "radar_relay_market.pyx", line 990, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket.c_get_order_price_quantum
KeyError: '[BASE]-WETH'
2019-09-11 15:56:01,002 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 270, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 375, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_execute_orders_proposal
AttributeError: 'NoneType' object has no attribute 'actions'
```

**Steps To Reproduce**

Run a normal pure market making bot.

**Release version**

Version: `latest 0.14.0`
Image timestamp: `2019-09-09T17:57:15Z`

**Attachments**

[hummingbot_logs_2019-09-09-19-20-21.log](https://github.com/CoinAlpha/hummingbot/files/3603420/hummingbot_logs_2019-09-09-19-20-21.log)

**Comment by mlafon** [comment]
I have the same issue with WBTC-WETH.

Looking at hummingbot/market/radar_relay/radar_relay_market.pyx, this seems to be related to how RadarRelay's markets are fetched.

The API /v2/markets/ can have several pages and list_market() only fetch the first one. In my case, WBTC-WETH is on the second page.

If you do not want to fetch all pages, you can use the 'ids' API parameters to get specific market pairs.

**Comment by dennisocana** [comment]
I'm no longer seeing this in the current version 0.26.0 using Radar Relay connector.
