### ISSUE TITLE
[BUG] Kill switch not getting data feed while running Xemm

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#776]
**Describe the bug**

Found these errors in logs.

```
2019-09-11 02:56:50,475 - hummingbot.core.utils.exchange_rate_conversion - ERROR - None is not in one of the data feeds: dict_keys(['coincap_api', 'coin_gecko_api']).
2019-09-11 02:56:50,475 - hummingbot.core.utils.kill_switch - ERROR - Error calculating profitability: Data feed name not valid.
Traceback (most recent call last):
  File "/hummingbot/core/utils/kill_switch.py", line 35, in check_profitability_loop
    self._profitability = self._hummingbot_application.calculate_profitability() / 1e2
  File "/hummingbot/client/command/history_command.py", line 128, in calculate_profitability
    performance_analysis: PerformanceAnalysis = self.get_performance_analysis_with_updated_balance()
  File "/hummingbot/client/command/history_command.py", line 82, in get_performance_analysis_with_updated_balance
    performance_analysis.add_balances(asset_name, amount, is_base, is_starting)
  File "/hummingbot/client/performance_analysis.py", line 53, in add_balances
    temp_amount = erc.convert_token_value(amount, asset_name, currency_amount.token, source="default")
  File "/hummingbot/core/utils/exchange_rate_conversion.py", line 179, in convert_token_value
    exchange_rate = self.get_exchange_rate(source)
  File "/hummingbot/core/utils/exchange_rate_conversion.py", line 128, in get_exchange_rate
    raise Exception("Data feed name not valid.")
Exception: Data feed name not valid.
```

**Steps To Reproduce**

Strategy configuration:

```
maker_market: bamboo_relay
taker_market: binance
maker_market_symbol: [BASE]-WETH
taker_market_symbol: [BASE]ETH
min_profitability: 0.002
trade_size_override: 0.0
top_depth_tolerance:

- -
    ^.+(USDT|USDC|USDS|DAI|PAX|TUSD)$
  - 0
- - ^.+ETH$
  - 0
- - ^.+BTC$
  - 0

active_order_canceling: true
cancel_order_threshold: -0.025
limit_order_min_expiration: 60.0
```

**Release version**

Version: `dev-0.15.0`
Image timestamp: `2019-09-11T00:52:56Z`

**Attachments**

[hummingbot_logs_2019-09-11-02-56-14.log](https://github.com/CoinAlpha/hummingbot/files/3603593/hummingbot_logs_2019-09-11-02-56-14.log)

**Comment by dennisocana** [comment]
@veecos2 so far I'm no longer getting the same error in the logs with the new cross-exchange config file.
