### ISSUE TITLE
[BUG] Failed to submit orders in Radar Relay

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#793]
**Describe the bug**

Getting errors submitting buy and sell orders in Radar Relay:

<img width="947" alt="18mSWjfZGx" src="https://user-images.githubusercontent.com/50150287/65008275-6908e800-d93b-11e9-86b0-6d17543b65f9.png">

```
2019-09-16 06:28:10,122 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "radar_relay_market.pyx", line 558, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket._api_request
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "radar_relay_market.pyx", line 230, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket._status_polling_loop
  File "radar_relay_market.pyx", line 275, in _update_trading_rules
  File "radar_relay_market.pyx", line 268, in list_market
  File "radar_relay_market.pyx", line 545, in _api_request
  File "radar_relay_market.pyx", line 546, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket._api_request
  File "radar_relay_market.pyx", line 565, in hummingbot.market.radar_relay.radar_relay_market.RadarRelayMarket._api_request
OSError: Error fetching data from https://api.radarrelay.com/v2/markets?include=base. HTTP status is 429 - Too many requests, please try again later..
```

**Release version**

version: 0.14.0
branch: master
commit: "a1bce79aae846b396b591b12208a75103ab2e361"
date: 2019-09-09T17:57:15Z

**Attachments**

[conf_pmm_base-weth.txt](https://github.com/CoinAlpha/hummingbot/files/3619081/conf_pmm_base-weth.txt)
[hummingbot_logs_2019-09-16-06-12-40.zip](https://github.com/CoinAlpha/hummingbot/files/3619083/hummingbot_logs_2019-09-16-06-12-40.zip)

**Comment by chowryan** [comment]
ill investigate this rate limiting issue

**Comment by dennisocana** [comment]
Bug no longer exists after updating to latest version 0.16.0

**Comment by dennisocana** [comment]
Reported issue is no longer happening on latest release version 0.18.1
```
"branch": "master",
"commit": "f8d1c19dfd0875bd12717f9c46ddbe20cc7b9a0d",
"date": "2019-11-04T22:16:16Z",
```
