### ISSUE TITLE
[BUG] TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#842]
**Describe the bug**

No orders made with pure-mm due to an error. The xemm test bot on the same development image is not having this issue.

```
2019-09-28 01:48:03,000 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Unknown error while generating order proposals.
Traceback (most recent call last):
  File "pure_market_making_v2.pyx", line 284, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 384, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_get_orders_proposal_for_market_info
  File "inventory_skew_multiple_size_sizing_delegate.pyx", line 165, in hummingbot.strategy.pure_market_making.inventory_skew_multiple_size_sizing_delegate.InventorySkewMultipleSizeSizingDelegate.c_get_order_size_proposal
  File "huobi_market.pyx", line 828, in hummingbot.market.huobi.huobi_market.HuobiMarket.c_quantize_order_amount
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
2019-09-28 01:48:03,002 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 292, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pass_through_filter_delegate.pyx", line 22, in hummingbot.strategy.pure_market_making.pass_through_filter_delegate.PassThroughFilterDelegate.c_filter_orders_proposal
AttributeError: 'NoneType' object has no attribute 'actions'
```

**Steps To Reproduce**

1. Update `development` branch to the latest image (see release version)
2. Run a pure-mm bot with below configs

```
maker_market: huobi
maker_market_symbol: [BASE]usdt
order_amount: 1.0
cancel_order_wait_time: 40.0
bid_place_threshold: 0.0025
ask_place_threshold: 0.0025
mode: multiple
number_of_orders: 2
order_start_size: 20.0
order_step_size: 10.0
order_interval_percent: 0.005
inventory_skew_enabled: true
inventory_target_base_percent: 0.5
filled_order_replenish_wait_time: 10.0
enable_order_filled_stop_cancellation: false
jump_orders_enabled: false
jump_orders_depth: 0.0
```

**Screenshots**

<img width="947" alt="putty_KT5NZ2UiOG" src="https://user-images.githubusercontent.com/50150287/65809984-b0626480-e1d6-11e9-96e7-9101760c5375.png">

**Release version**

version: dev-0.16.0
branch: "development",
commit: "efe15e750547cb528789083e9de6d5cd934c8533",
date: "2019-09-27T20:31:49Z",

**Attachments**

[hummingbot_logs_2019-09-28-01-47-58.log](https://github.com/CoinAlpha/hummingbot/files/3664992/hummingbot_logs_2019-09-28-01-47-58.log)

**Comment by chowryan** [comment]
ill take a look thanks

**Comment by chowryan** [comment]
fixed thanks
