### ISSUE TITLE
[wings.market.binance_market] Unexpected error while fetching account updates

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#85]
**Describe the bug**
Error message as follows:

```
wings.market.binance_market - ERROR - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "wings/market/binance_market.pyx", line 429, in wings.market.binance_market.BinanceMarket.query_api
    return await self.schedule_async_call(coro, self.API_CALL_TIMEOUT)
  File "wings/market/binance_market.pyx", line 424, in schedule_async_call
    return await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wings/market/binance_market.pyx", line 704, in wings.market.binance_market.BinanceMarket._status_polling_loop
    await asyncio.gather(
  File "wings/market/binance_market.pyx", line 448, in _update_balances
    account_info = await self.query_api(self._binance_client.get_account)
  File "wings/market/binance_market.pyx", line 427, in query_api
    async with timeout(self.API_CALL_TIMEOUT):
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```
**Steps To Reproduce**
- Arbitrage strategy for BAT-ETH between Binance and DDEX

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with the attached parameters.
2. Start the bot using this command: config, start
...

**Screenshots**
N/A

**Release version**
0.4.0

**Attachments**
1) configuration files
2) log file

[config.zip](https://github.com/CoinAlpha/hummingbot/files/3096465/config.zip)
[hummingbot_logs_2019-04-18-12-05-50 2.log](https://github.com/CoinAlpha/hummingbot/files/3096467/hummingbot_logs_2019-04-18-12-05-50.2.log)

**Comment by mifeng** [comment]
This is caused by inconsistent connection to Binance. We have made a fix to improve network connection stability in 0.6.0 that should reduce how often users see this error.

**Comment by beyoar** [comment]
I tested the v0.6.0 version and the problem persists.

Version 0.6.0
OS: ubuntu 18.04

**Comment by beyoar** [comment]
https://github.com/CoinAlpha/hummingbot/issues/279

**Comment by beyoar** [comment]
I installed from source.
