### ISSUE TITLE
[BUG] XEMM not placing orders in empty maker market

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#854]
**Describe the bug**

The objective is to make a buy order in Bamboo Relay for ETHPLO-WETH pair and hedge in DDEX. When the bot tries to make an order in an empty order book it returns an error:
```
OSError: Order book is empty - no price quote is possible.
```

**Steps To Reproduce**

1. Set up a cross-exchange bot with the following configs:

```
maker_market: bamboo_relay
taker_market: ddex
maker_market_symbol: ETHPLO-WETH
taker_market_symbol: ETHPLO-WETH
min_profitability: 0.01
order_amount: 1000.0
adjust_order_enabled: true
active_order_canceling: true
cancel_order_threshold: 0.05
limit_order_min_expiration: 130.0
top_depth_tolerance: 0.0
anti_hysteresis_duration: 60.0
order_size_taker_volume_factor: 0.25
order_size_taker_balance_factor: 0.995
order_size_taker_balance_factor: 0.1667
```

**Screenshots**

![image](https://user-images.githubusercontent.com/50150287/65940481-31ca2900-e45b-11e9-908c-64f54d7be03c.png)

![image](https://user-images.githubusercontent.com/50150287/65940501-40184500-e45b-11e9-894a-bc5193829307.png)

**Release version**

version: dev-0.16.0

**Attachments**

[hummingbot_logs_2019-09-27-23-25-55.log](https://github.com/CoinAlpha/hummingbot/files/3674802/hummingbot_logs_2019-09-27-23-25-55.log)
[hummingbot_logs_2019-09-27-23-39-22.log](https://github.com/CoinAlpha/hummingbot/files/3674803/hummingbot_logs_2019-09-27-23-39-22.log)

**Discord username:** Markus ETHPLO
**ETH address:** 0xe363b6c03a8b20e75447ca34bf514aaaf1bf1499

**Comment by veecos2** [comment]
@dennisocana : Can you reproduce this ?. Currently its saying Markets are not ready and no market making trades are permitted and there also seem to be some errors with Bamboo relay api.

**Comment by PtrckM** [comment]
**Tested on:**
```
                "branch": "development",
                "commit": "2b77661c5a07ded3d84cc808d065372bd42c8c37",
                "date": "2019-10-01T21:19:39Z",
```
**Error:**
```
2019-10-02 01:17:50,002 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "cross_exchange_market_making.pyx", line 302, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_tick
  File "cross_exchange_market_making.pyx", line 387, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_process_market_pair
  File "cross_exchange_market_making.pyx", line 1088, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_check_and_create_new_orders
  File "cross_exchange_market_making.pyx", line 763, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_get_market_making_price
  File "cross_exchange_market_making.pyx", line 964, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_get_top_bid_ask_from_price_samples
  File "cross_exchange_market_making.pyx", line 915, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_get_top_bid_ask
  File "composite_order_book.pyx", line 187, in hummingbot.core.data_type.composite_order_book.CompositeOrderBook.c_get_price
OSError: Order book is empty - no price quote is possible.
```

**Comment by veecos2** [comment]
Maybe its due to geofencing, as I am unable to get token approvals for this particular token. I will ask Dennis to check.

**Comment by veecos2** [comment]
I have tested that this is fixed. Please reopen if not.

**Comment by moraliang** [comment]
Bounty has been sent.
