### ISSUE TITLE
[wings.market.binance_market] - ERROR - API call error

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#86]
**Describe the bug**
Error message as follows:

```
2019-04-18 15:24:50,115 - wings.market.binance_market - ERROR - API call error.
Traceback (most recent call last):
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/anaconda3/envs/hummingbot/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/anaconda3/envs/hummingbot/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/anaconda3/envs/hummingbot/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/anaconda3/envs/hummingbot/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 309, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
OSError: (54, 'ECONNRESET')

During handling of the above exception, another exception occurred:
```
**Steps To Reproduce**
- Arbitrage strategy for BAT-ETH between Binance and DDEX

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with the attached configuration parameters.
2. Start the bot using this command: config and then start.

**Screenshots**
N/A

**Release version**
0.4.0

**Attachments**
1) configuration files
2) log file

[config.zip](https://github.com/CoinAlpha/hummingbot/files/3096465/config.zip)
[hummingbot_logs_2019-04-18-15-13-14.log](https://github.com/CoinAlpha/hummingbot/files/3096476/hummingbot_logs_2019-04-18-15-13-14.log)

**Comment by moraliang** [comment]
I got this error too.

**Comment by mifeng** [comment]
This is caused by inconsistent connection to Binance. We have made a fix to improve network connection stability in 0.6.0 that should reduce how often users see this error.
