### ISSUE TITLE
[wings.watcher.new_blocks_watcher] Timed out fetching new block from node

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#87]
**Describe the bug**
Error message as follows:

```
2019-04-18 16:04:12,002 - wings.watcher.new_blocks_watcher - ERROR - Timed out fetching new block from node.
Traceback (most recent call last):
  File "/Users/carlol/tutorial/hummingbot/wings/watcher/new_blocks_watcher.py", line 97, in fetch_new_blocks_loop
    full_transactions=True))
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlol/tutorial/hummingbot/wings/watcher/new_blocks_watcher.py", line 119, in fetch_new_blocks_loop
    del self._blocks_window[block_hash]
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/anaconda3/envs/hummingbot/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
2019-04-18 16:04:43,004 - wings.watcher.new_blocks_watcher - ERROR - Timed out fetching new block from node.
Traceback (most recent call last):
  File "/Users/carlol/tutorial/hummingbot/wings/watcher/new_blocks_watcher.py", line 97, in fetch_new_blocks_loop
    full_transactions=True))
concurrent.futures._base.CancelledError
```

**Steps To Reproduce**
- Arbitrage strategy for BAT-ETH between Binance and DDEX

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with the attached parameters.
2. Start the bot using this command: config, start

**Screenshots**
N/A

**Release version**
0.4.0

**Attachments**
1) configuration files
2) log file

[config.zip](https://github.com/CoinAlpha/hummingbot/files/3096465/config.zip)
[hummingbot_logs_2019-04-18-15-49-30.log](https://github.com/CoinAlpha/hummingbot/files/3096478/hummingbot_logs_2019-04-18-15-49-30.log)

**Comment by chowryan** [comment]
seems like there are binance network errors too so more than likely this was a network issue. we need a better way to display network issues.

**Comment by mifeng** [comment]
This is caused by an inconsistent network connection. We have made a fix to improve network connection stability in 0.6.0 that should reduce how often users see this error.
