### ISSUE TITLE
[BUG] Discovery fails to show profitability coinbase_pro - idex

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#899]
**Describe the bug**
Discovery fails to show the profitability between two markets

tested 2 different VM's with different API's from both coinbase_pro and idex
VM1: wait 30 mins for profitability result
VM2: wait 35 mins for profitability result

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/66539177-c74f7200-eb59-11e9-987a-11c867f96863.png)

**Release version**
```
                "branch": "dev-0.17.0",
                "commit": "10297d49722451b0382e940044829222dda77422",
                "date": "2019-10-09T19:25:59Z",
```
**Config**
```
#####################################
###   Discovery strategy config   ###
#####################################

# The following configuations are only required for the
# discovery strategy

# Exchange and token parameters
primary_market: coinbase_pro
secondary_market: idex

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
target_profitability: 0.0
target_amount: .inf

target_symbol_1: []
target_symbol_2: []
equivalent_tokens:
- - USDT
  - USDC
  - USDS
  - DAI
  - PAX
  - TUSD
  - USD
- - ETH
  - WETH
- - BTC
  - WBTC
# For more detailed information, see:
# https://docs.hummingbot.io/strategies/discovery/
```
**LOGS**
```
2019-10-10 04:24:27,292 - hummingbot.client.hummingbot_application - INFO - Saving discovery output...
2019-10-10 04:24:27,299 - hummingbot.client.hummingbot_application - ERROR - Error in check_discovery_strategy_ready_loop: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 53, in check_discovery_strategy_ready_loop
    await save_discovery_output(self)
  File "/hummingbot/strategy/discovery/start.py", line 29, in save_discovery_output
    df_list: List[pd.DataFrame] = self.strategy.get_status_dataframes()
  File "discovery.pyx", line 436, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.get_status_dataframes
  File "discovery.pyx", line 487, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.get_conversion_rate_df
  File "/hummingbot/core/utils/exchange_rate_conversion.py", line 169, in adjust_token_rate
    return Decimal(repr(exchange_rate[asset_name])) * price
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
2019-10-10 04:24:31,439 - hummingbot.market.idex.idex_market - ERROR - Error fetching data from https://api.idex.market/returnCompleteBalances. HTTP status is 200 - {}
2019-10-10 04:24:32,153 - hummingbot.market.idex.idex_market - ERROR - Error fetching data from https://api.idex.market/returnContractAddress. HTTP status is 200 - {'address': '0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208'}
2019-10-10 04:24:32,494 - hummingbot.client.hummingbot_application - INFO - Saving discovery output...
2019-10-10 04:24:32,502 - hummingbot.client.hummingbot_application - ERROR - Error in check_discovery_strategy_ready_loop: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 53, in check_discovery_strategy_ready_loop
    await save_discovery_output(self)
  File "/hummingbot/strategy/discovery/start.py", line 29, in save_discovery_output
    df_list: List[pd.DataFrame] = self.strategy.get_status_dataframes()
  File "discovery.pyx", line 436, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.get_status_dataframes
  File "discovery.pyx", line 487, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.get_conversion_rate_df
  File "/hummingbot/core/utils/exchange_rate_conversion.py", line 169, in adjust_token_rate
    return Decimal(repr(exchange_rate[asset_name])) * price
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
2019-10-10 04:25:11,539 - hummingbot.notifier.telegram_notifier - ERROR -
2019-10-10 04:25:12,033 - hummingbot.client.hummingbot_application - INFO - Saving discovery output...
2019-10-10 04:25:12,042 - hummingbot.client.hummingbot_application - ERROR - Error in check_discovery_strategy_ready_loop: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 53, in check_discovery_strategy_ready_loop
    await save_discovery_output(self)
  File "/hummingbot/strategy/discovery/start.py", line 29, in save_discovery_output
    df_list: List[pd.DataFrame] = self.strategy.get_status_dataframes()
  File "discovery.pyx", line 436, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.get_status_dataframes
  File "discovery.pyx", line 487, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.get_conversion_rate_df
  File "/hummingbot/core/utils/exchange_rate_conversion.py", line 169, in adjust_token_rate
    return Decimal(repr(exchange_rate[asset_name])) * price
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float
```

**Comment by znerol19619** [comment]
Tested the same configuration, and got the same result. 

**Error**
```
Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 53, in check_discovery_strategy_ready_loop
    await save_discovery_output(self)
  File "/hummingbot/strategy/discovery/start.py", line 29, in save_discovery_output
    df_list: List[pd.DataFrame] = self.strategy.get_status_dataframes()
  File "discovery.pyx", line 436, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.get_status_dataframes
  File "discovery.pyx", line 487, in hummingbot.strategy.discovery.discovery.DiscoveryStrategy.get_conversion_rate_df
  File "/hummingbot/core/utils/exchange_rate_conversion.py", line 169, in adjust_token_rate
    return Decimal(repr(exchange_rate[asset_name])) * price
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
2019-10-10 10:10:55,393 - hummingbot.market.idex.idex_market - ERROR - Error fetching data from https://api.idex.market/returnCompleteBalances. HTTP status is 200 - {'ETH': {'available': '0.0138402247', 'onOrders': '0'}}
2019-10-10 10:10:59,501 - hummingbot.client.hummingbot_application - INFO - Saving discovery output...
2019-10-10 10:10:59,503 - hummingbot.client.hummingbot_application - ERROR - Error in check_discovery_strategy_ready_loop: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

```
**Release version**
```
                "branch": "development",
                "commit": "10297d49722451b0382e940044829222dda77422",
                "date": "2019-10-09T19:25:59Z",
```

**Comment by rennel-tabing** [comment]
It seems that this version had issues with the discovery as the config posted was working fine with the version that was released three days ago.

![image](https://user-images.githubusercontent.com/53868268/66583547-8ce1d700-eb51-11e9-87de-fd75733ac475.png)

**Comment by BUDDHA-TONY** [comment]
As expected ,Tested with the same configuration and had the same result.
![discovery](https://user-images.githubusercontent.com/55869559/66614882-45b12000-ebfd-11e9-92da-38238db784e0.png)
"Labels": {
                "branch": "development",
                "commit": "10297d49722451b0382e940044829222dda77422",
                "date": "2019-10-09T19:25:59Z",

**Comment by PtrckM** [comment]
confirmed fix

![image](https://user-images.githubusercontent.com/54516858/66881143-6bbd3280-eff8-11e9-849f-31b98b51a870.png)
```
                "branch": "dev-0.17.0",
                "commit": "c501b403f81ae5e34a1fcaa1ad7b9c18556a9220",
                "date": "2019-10-15T23:59:12Z",
```
