### ISSUE TITLE
[BUG] Order filled event is not emitted when order is immediately filled after placement in Binance Market 

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#905]
**Describe the bug**

Pure market making bot will behave as expected but will eventually get this error.

![image](https://user-images.githubusercontent.com/50150287/66662186-f27db280-ec7a-11e9-90fb-1c51e024415d.png)

There are no more open buy orders in Binance because it was already filled but Hummingbot still thinks it's as an active order.

![image](https://user-images.githubusercontent.com/50150287/66662236-04f7ec00-ec7b-11e9-97e3-45f748ca939d.png)

Because it's "stuck", Hummingbot no longer generates new buy orders.

```
2019-10-11 14:23:27,000 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Unknown error while generating order proposals.
Traceback (most recent call last):
  File "pure_market_making_v2.pyx", line 287, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 530, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_get_orders_proposal_for_market_info
KeyError: 'buy-ONEUSDT-1570803798002151'

2019-10-11 14:23:27,001 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 295, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pass_through_filter_delegate.pyx", line 22, in hummingbot.strategy.pure_market_making.pass_through_filter_delegate.PassThroughFilterDelegate.c_filter_orders_proposal
AttributeError: 'NoneType' object has no attribute 'actions'
```

**Release version**

"branch": "development",
"commit": "99f45919e141296ea0e059cf933068dc34b83fca",
"date": "2019-10-11T03:01:46Z",

**Attachments**

Log file: 
[logfile_one-usdt.log](https://github.com/CoinAlpha/hummingbot/files/3718271/logfile_one-usdt.log)

**Comment by veecos2** [comment]
Hi Dennis, does the bot recover automatically after this and start placing orders again ?. The order status polling task should get the new status of the order shortly.

**Comment by veecos2** [comment]
Based on initial investigation of logs, the order seems to have filled immediately after it was placed. Binance market did not seem to have sent out out the OrderFilled event via the websocket immediately. The order was still marked as active in our order tracker though it was filled. Needs further investigation.

**Comment by dennisocana** [comment]
Hi @veecos2 , no the bot does not recover at all. I left it with the error last night and after 6 hours it's still the same.

**Comment by veecos2** [comment]
Okays, Can you attach more of the log here (the current log only shows till 10 minutes from when the error first occured, 1 hour would be ideal) (or) send me the complete log file ?.

**Comment by dennisocana** [comment]
@veecos2 looks like the bug occurs when `enable_order_filled_stop_cancellation` is set to `true` and it happens only with buy orders.
