### ISSUE TITLE
[BUG] Paper Trading | Error Unknown while generating order proposal

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#914]
**Describe the bug**
// A clear and concise description of what the bug is.

Running Paper Trading mode under version 0.16.0 generates a `Error Unknown while generating order proposal` after running the bot for some time.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Enable  Paper Trading mode and run the sample configuration below

```
########################################################
###       Pure market making strategy config         ###
########################################################

# The following configuations are only required for the
# pure market making strategy

# Exchange and token parameters
maker_market: binance
maker_market_symbol: LINKUSDT

# size of each order
order_amount: 14.0

# Time in seconds before cancelling and rerunning strategy
# If tick size is 60, the bot cancels active orders and reruns after a minute
cancel_order_wait_time: 30.0

# How far away from mid price to place the bid order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and bid_place threshold is 0.01
# Your bid is placed at 99
bid_place_threshold: 0.0006

# How far away from mid price to place the ask order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and ask_place threshold is 0.01
# Your bid is placed at 101
ask_place_threshold: 0.0007

# If you want to have single or multiple bids and asks on each side
mode: single

# If you have multiple orders number of orders you want to place on one side of the orderbook
number_of_orders: 1

# Size of the first bid and ask order for multiple order mode
order_start_size: 1.0

# Increment size of consecutive orders after the first order in multiple order mode
order_step_size: 0.0

# Spacing between orders in multiple order mode
order_interval_percent: 0.01

# Toggle enabling of Inventory skew
inventory_skew_enabled: true

# Target base asset inventory percentage target to be maintained
inventory_target_base_percent: 0.5

# How long to wait before placing the next order in case your order gets filled for single order mode
filled_order_replenish_wait_time: 10.0

# Do you want to stop cancellations of orders on the other side when one side is filled
enable_order_filled_stop_cancellation: true

# Do you want to enable penny jumping mode
jump_orders_enabled: true

# If jump_orders_enabled is True, what is the depth in base currency to be used for finding top bid and ask
jump_orders_depth: 0.0

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters


```

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
   (Please see the config above)
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
Here are the error logs
![image](https://user-images.githubusercontent.com/53868268/66747948-dda84700-ee53-11e9-950a-fa75982b9efb.png)

![image](https://user-images.githubusercontent.com/53868268/66748010-0cbeb880-ee54-11e9-85be-744a3962cd07.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).

```
                "commit": "c71bc06cbcd7c346c09ac8868e802558f114bbf1",
                "date": "2019-10-07T18:07:21Z",
```

**Optional: your discord username: EA
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by rennel-tabing** [comment]
This issue might be related to https://github.com/CoinAlpha/hummingbot/issues/905 . 
So far, no errors were generated after setting the `enable_order_filled_stop_cancellation` to `False`.

**Comment by veecos2** [comment]
Could you send me the entire log file ?.

**Comment by znerol19619** [comment]
@veecos2 I tested yesterday and it took 56 mins (almost an hour) for the error to occur, and as what @rennel-tabing said, errors are not generated when ``enable_order_filled_stop_cancellation`` is set to ``false``. 

**Start at:**
```2019-10-14 07:51:23,340 - hummingbot.market.binance.binance_order_book_tracker - INFO - Started order book tracking for ZRXETH.
2019-10-14 07:51:24,003 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ZRXETH) Creating limit bid orders at (Size, Price): ['1E+1 ZRX, 0.0016001 ETH'] [clock=2019-10-14 07:51:24+00:00]
```
**Error occurs at:**
```
2019-10-14 08:47:17,283 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Unknown error while generating order proposals.
Traceback (most recent call last):
  File "pure_market_making_v2.pyx", line 287, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 530, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_get_orders_proposal_for_market_info
KeyError: 'buy://ZRXETH/2cc632e2fc0763cdc090b32313'
2019-10-14 08:47:17,285 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
```

**Release version**
```
                "branch": "development",
                "commit": "99f45919e141296ea0e059cf933068dc34b83fca",
                "date": "2019-10-11T03:01:46Z",
```
**Logs**
[hummingbot_logs_2019-10-14-07-44-16.log](https://github.com/CoinAlpha/hummingbot/files/3727797/hummingbot_logs_2019-10-14-07-44-16.log)

**Comment by rennel-tabing** [comment]
@veecos2 Here are my log file as requested. 
[PaperTradingUnknownError.log](https://github.com/CoinAlpha/hummingbot/files/3729067/PaperTradingUnknownError.log)

**Comment by moraliang** [comment]
@rennel-tabing Is it possible to get the reporter's ETH address? Thanks.
