### ISSUE TITLE
[BUG] Hummingbot does not launch without autostart

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#935]
**Describe the bug**

Creating or updating Hummingbot container to the latest Docker development image fails to launch if not configured with trading strategy autostart.

```
Bot config incomplete: argument --strategy/-s: expected one argument. Starting normally...
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/conda/envs/hummingbot/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/conda/envs/hummingbot/lib/python3.6/argparse.py", line 1902, in consume_optional
    arg_count = match_argument(action, selected_patterns)
  File "/opt/conda/envs/hummingbot/lib/python3.6/argparse.py", line 2066, in _match_argument
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument --strategy/-s: expected one argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 59, in quick_start
    args = CmdlineParser().parse_args()
  File "/opt/conda/envs/hummingbot/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/conda/envs/hummingbot/lib/python3.6/argparse.py", line 1773, in parse_known_args
    self.error(str(err))
  File "/hummingbot/client/ui/parser.py", line 13, in error
    raise ArgumentParserError(message)
hummingbot.client.errors.ArgumentParserError: argument --strategy/-s: expected one argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 111, in <module>
    asyncio.get_event_loop().run_until_complete(quick_start())
  File "/opt/conda/envs/hummingbot/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "bin/hummingbot_quickstart.py", line 107, in quick_start
    await normal_start()
  File "/bin/hummingbot.py", line 42, in main
    chdir_to_data_directory()
  File "/hummingbot/__init__.py", line 109, in chdir_to_data_directory
    import appdirs
ModuleNotFoundError: No module named 'appdirs'
```

**Steps To Reproduce**

1. Update to the latest Docker development image

```
"commit": "c689cf61fc137e7a3736a1d0d437e7f26a200a6a"
"date": "2019-10-17T22:38:38Z"
```

2. Start Hummingbot with trading strategy autostart to work
3. Start Hummingbot without trading strategy autostart to receive the error

**Comment by PtrckM** [comment]
confirmed running only on strategy autostart

**Comment by yzhang1994** [comment]
@martinkou this looks like a missing package issue after adding pyinstaller. Could you take a look?
