### ISSUE TITLE
[BUG] Error with inventory skew enabled in Radar Relay

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#943]
**Describe the bug**

I get this error in the logs with `inventory_skew_enabled` set to `true` running on Radar Relay. Tested and confirmed error doesn't happen in other exchanges like Bamboo Relay or Huobi.

```
2019-10-19 02:43:26,001 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - ERROR - Unknown error while generating order proposals.
Traceback (most recent call last):
  File "pure_market_making_v2.pyx", line 287, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pure_market_making_v2.pyx", line 506, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_get_orders_proposal_for_market_info
  File "inventory_skew_multiple_size_sizing_delegate.pyx", line 101, in hummingbot.strategy.pure_market_making.inventory_skew_multiple_size_sizing_delegate.InventorySkewMultipleSizeSizingDelegate.c_get_order_size_proposal
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]
2019-10-19 02:43:26,002 - 10 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
  File "pure_market_making_v2.pyx", line 295, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick
  File "pass_through_filter_delegate.pyx", line 22, in hummingbot.strategy.pure_market_making.pass_through_filter_delegate.PassThroughFilterDelegate.c_filter_orders_proposal
AttributeError: 'NoneType' object has no attribute 'actions'
```

**Steps To Reproduce**

This is the same bot in 942 but in multiple mode.

```
maker_market: radar_relay
maker_market_symbol: ZRX-WETH
order_amount: 10.0
cancel_order_wait_time: 60.0
bid_place_threshold: 0.01
ask_place_threshold: 0.01
mode: multiple
number_of_orders: 2
order_start_size: 10.0
order_step_size: 5.0
order_interval_percent: 0.01
inventory_skew_enabled: true
inventory_target_base_percent: 0.5
filled_order_replenish_wait_time: 10.0
enable_order_filled_stop_cancellation: false
jump_orders_enabled: false
jump_orders_depth: 0.0
```

**Screenshots**

<img width="947" alt="putty_TI9rvOsd6y" src="https://user-images.githubusercontent.com/50150287/67136897-07041100-f260-11e9-9263-255b15781d76.png">

**Release version**

```
"branch": "development",
"commit": "9b5662bb5dcbf0ef674b9542964ae17ea188fe80",
"date": "2019-10-18T19:25:47Z",
```

**Attachments**

Log file: 
[radar_zrx-weth_multiple.log](https://github.com/CoinAlpha/hummingbot/files/3746157/radar_zrx-weth_multiple.log)

**Comment by stevenwally** [comment]
Hey @dennisocana, I can take this bug!

**Comment by veecos2** [comment]
Related to https://github.com/CoinAlpha/hummingbot/issues/942

**Comment by veecos2** [comment]
This should be fixed now. Feel free to reopen if not.
